//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.28 at 01:58:23 PM CST 
//


package contabilidad.servicio;

import javax.xml.bind.annotation.XmlRegistry;

import contabilidad.bean.ContaElecPolizasBean;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.polizas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryPolizas {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.polizas
     * 
     */
    public ObjectFactoryPolizas() {
    }

    /**
     * Create an instance of {@link Polizas.Poliza }
     * 
     */
    public ContaElecPolizasBean.Poliza createPolizasPoliza() {
        return new ContaElecPolizasBean.Poliza();
    }

    /**
     * Create an instance of {@link Polizas.Poliza.Transaccion.Comprobantes }
     * 
     */
    public ContaElecPolizasBean.Poliza.Transaccion.Comprobantes createPolizasPolizaTransaccionComprobantes() {
        return new ContaElecPolizasBean.Poliza.Transaccion.Comprobantes();
    }

    /**
     * Create an instance of {@link Polizas.Poliza.Transaccion.Cheque }
     * 
     */
    public ContaElecPolizasBean.Poliza.Transaccion.Cheque createPolizasPolizaTransaccionCheque() {
        return new ContaElecPolizasBean.Poliza.Transaccion.Cheque();
    }

    /**
     * Create an instance of {@link Polizas.Poliza.Transaccion.Transferencia }
     * 
     */
    public ContaElecPolizasBean.Poliza.Transaccion.Transferencia createPolizasPolizaTransaccionTransferencia() {
        return new ContaElecPolizasBean.Poliza.Transaccion.Transferencia();
    }

    /**
     * Create an instance of {@link Polizas.Poliza.Transaccion }
     * 
     */
    public ContaElecPolizasBean.Poliza.Transaccion createPolizasPolizaTransaccion() {
        return new ContaElecPolizasBean.Poliza.Transaccion();
    }

    /**
     * Create an instance of {@link Polizas }
     * 
     */
    public ContaElecPolizasBean createPolizas() {
        return new ContaElecPolizasBean();
    }

}
