//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 05:42:45 PM CST 
//


package contabilidad.servicio;
import javax.xml.bind.annotation.XmlRegistry;

import contabilidad.bean.CatalogoBean;

@XmlRegistry
public class ObjectFactoryCatalogo {


   
    public ObjectFactoryCatalogo() {
    }


    public CatalogoBean createCatalogo() {
        return new CatalogoBean();
    }


    public CatalogoBean.Ctas createCatalogoCtas() {
        return new CatalogoBean.Ctas();
    }



}
