DELIMITER ;
DROP TABLE IF EXISTS AMORTICREDITOPOSTDIFER;

DELIMITER ;
CREATE TABLE `AMORTICREDITOPOSTDIFER` (
  `AmortizacionID` INT(4) NOT NULL COMMENT 'No\nAmortizacion',
  `CreditoID` BIGINT(12) NOT NULL COMMENT 'Credito',
  `NumeroDiferimientos` INT(11) NOT NULL COMMENT 'Numero de Diferimientos',
  `ClienteID` INT(11) DEFAULT NULL COMMENT 'Cliente',
  `CuentaID` BIGINT(12) DEFAULT NULL,
  `FechaInicio` DATE DEFAULT NULL COMMENT 'Fecha de Inicio\n',
  `FechaVencim` DATE DEFAULT NULL COMMENT 'Fecha de\nVencimiento',
  `FechaExigible` DATE DEFAULT NULL COMMENT 'Fecha Exigible\nde Pago\n',
  `Estatus` VARCHAR(1) DEFAULT NULL COMMENT 'Estatus del Credito, no se pide en el alta. Nace inactivo\nI .- Inactivo\nV.- Vigente\nP .- Pagado\nC .- Cancelado\nB.- Vencido\nA.- Atrasado\n',
  `FechaLiquida` DATE DEFAULT NULL COMMENT 'Fecha de \nLiquidacion o\nTerminacion\n',
  `Capital` DECIMAL(14,2) DEFAULT NULL COMMENT 'Monto del Capital',
  `Interes` DECIMAL(14,2) DEFAULT NULL COMMENT 'Interes',
  `IVAInteres` DECIMAL(10,2) DEFAULT NULL COMMENT 'IVA Interes',
  `SaldoCapVigente` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vigente, en el alta nace con ceros',
  `SaldoCapAtrasa` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Atrasado, en el alta nace con ceros',
  `SaldoCapVencido` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido, en el alta nace con ceros',
  `SaldoCapVenNExi` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido no Exigible, en al alta nace con ceros',
  `SaldoInteresOrd` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Ordinario, en el alta nace con ceros',
  `SaldoInteresAtr` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Atrasado, en el alta nace con ceros',
  `SaldoInteresVen` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldos de Interes Vencido, en el alta nace con ceros',
  `SaldoInteresPro` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Provision, en el alta nace con ceros',
  `SaldoIntNoConta` DECIMAL(12,4) DEFAULT NULL COMMENT 'Saldo de Interes\nNo Contabilizado',
  `SaldoIVAInteres` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo IVA Interes, en el alta nace con ceros',
  `SaldoMoratorios` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo Moratorios, en el alta nace con ceros',
  `SaldoIVAMorato` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo IVA Mora, en el alta nace con ceros',
  `SaldoComFaltaPa` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo Comision Falta Pago, en el alta nace con ceros',
  `SaldoIVAComFalP` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo IVA Com Falta Pago, en el alta nace con ceros',
  `SaldoComServGar` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Comision por Servicio de Garantia Agro',
  `SaldoIVAComSerGar` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Iva Comision por Servicio de Garantia Agro',
  `MontoOtrasComisiones` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Monto a Cobrar de Otras Comisiones',
  `MontoIVAOtrasComisiones` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Monto a Cobrar del IVA de Otras Comisiones',
  `SaldoOtrasComis` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo Otras Comisiones, en el alta nace con ceros',
  `SaldoIVAComisi` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo IVA Otras Com, en el alta nace con ceros',
  `ProvisionAcum` DECIMAL(14,4) DEFAULT NULL COMMENT 'Provision\nAcumulada ',
  `SaldoCapital` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo Capital',
  `NumProyInteres` INT(11) DEFAULT NULL COMMENT 'Numero de Veces que se ha Realizado la Proyeccion de Intereses\nen un Pago Anticipado',
  `SaldoMoraVencido` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Interes Moratorio en atraso o vencido',
  `SaldoMoraCarVen` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Moratorios deirvado de cartera vencida, en ctas de orden',
  `MontoSeguroCuota` DECIMAL(12,2) DEFAULT '0.00' COMMENT 'Monto del seguro por cuota',
  `IVASeguroCuota` DECIMAL(12,2) DEFAULT '0.00' COMMENT 'Monto de Iva para el seguro por cuota',
  `SaldoSeguroCuota` DECIMAL(12,2) DEFAULT '0.00' COMMENT 'Saldo Monto Seguro Cuota',
  `SaldoIVASeguroCuota` DECIMAL(12,2) DEFAULT '0.00' COMMENT 'Saldo IVA Seguro Cuota',
  `SaldoComisionAnual` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Comision Anual',
  `SaldoComisionAnualIVA` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'IVA por comision por anualidad',
  `SaldoIntPref` DECIMAL(16,2) DEFAULT NULL COMMENT 'Saldo de Interes Preferencial Calculado para el tipo de diferimeinto P',
  `EmpresaID` INT(11) DEFAULT NULL,
  `Usuario` INT(11) DEFAULT NULL,
  `FechaActual` DATETIME DEFAULT NULL,
  `DireccionIP` VARCHAR(20) DEFAULT NULL,
  `ProgramaID` VARCHAR(50) DEFAULT NULL,
  `Sucursal` INT(11) DEFAULT NULL,
  `NumTransaccion` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`AmortizacionID`,`CreditoID`,`NumeroDiferimientos`),
  KEY `fk_AMORTICREDITO_2` (`ClienteID`),
  KEY `fk_AMORTICREDITO_3` (`CuentaID`),
  KEY `fk_AMORTICREDITO_1` (`CreditoID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 COMMENT='Tabla de Amortizaciones de los Creditos';
