-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- ARRENDAMIENTOS
DELIMITER ;
DROP TABLE IF EXISTS `ARRENDAMIENTOS`;DELIMITER $$

CREATE TABLE `ARRENDAMIENTOS` (
  `ArrendaID` bigint(12) NOT NULL COMMENT 'Numero ID identificador del Arrendamiento',
  `LineaArrendaID` bigint(12) NOT NULL DEFAULT '0' COMMENT 'Numero ID de la linea de Arrendamiento solo en caso de existir',
  `ClienteID` int(11) NOT NULL DEFAULT '0' COMMENT 'Numero de Cliente al que se le da de alta el arrendamiento',
  `NumTransacSim` bigint(20) NOT NULL DEFAULT '0' COMMENT 'Numero de Transaccion con la que se genero la simulacion del plan de pagos',
  `TipoArrenda` char(1) NOT NULL DEFAULT '0' COMMENT 'F = Financiero  P = Puro',
  `MonedaID` int(11) NOT NULL DEFAULT '1' COMMENT 'Id de la moneda del Arrendamiento 01 = Pesos Mexicano',
  `ProductoArrendaID` int(4) NOT NULL DEFAULT '0' COMMENT 'ID del Producto de Arrendamiento',
  `MontoArrenda` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Es el monto del Arrendamiento antes de Enganche o anticipo y sin IVA',
  `IVAMontoArrenda` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Es el IVA del monto correspondiente al valor del Bien',
  `MontoEnganche` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto que se da de enganche o anticipo',
  `IVAEnganche` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'IVA del Enganche en caso de que aplique',
  `PorcEnganche` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor porcentual que representa el monto del enganche respecto al valor del Bien Ejemplo: Si valor del Bien es 100,000  y valor de Enganche es 10,000 el Valor Porcentual debera ser 10',
  `MontoFinanciado` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Es el Valor a Financiar para el arrendamiento Reprsenta el Valor del Bien menos el Enganche',
  `SeguroArrendaID` int(11) NOT NULL DEFAULT '0' COMMENT 'Numero de ID de la aseguradora',
  `TipoPagoSeguro` int(11) NOT NULL DEFAULT '0' COMMENT '1 = Contado   2 = Financiado',
  `MontoSeguroAnual` decimal(14,2) NOT NULL COMMENT 'Es el monto del seguro Anual de contado',
  `SeguroVidaArrendaID` int(11) NOT NULL COMMENT 'Numero de ID de la aseguradora',
  `TipoPagoSeguroVida` int(11) NOT NULL COMMENT ' 1 = Contado  2 = Financiado',
  `MontoSeguroVidaAnual` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Es el monto del seguro de Vida Anual de contado',
  `MontoResidual` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Es el valor residual en caso que aplique',
  `FechaRegistro` date NOT NULL COMMENT 'Fecha en la que se da de alta el arrendamiento',
  `FechaApertura` date NOT NULL COMMENT 'Fecha en la que se inicia el Arrendamiento',
  `FechaPrimerVen` date NOT NULL COMMENT 'Fecha del Primer Pago del Arrendamiento',
  `FechaUltimoVen` date NOT NULL COMMENT 'Fecha del ultimo Pago del Arrendamiento',
  `FechaLiquida` date NOT NULL COMMENT 'Fecha real en la que el cliente liquida o realiza el ultimo pago del arrendamiento. Si el arrendamiento sigue Vigente debe ser 1900-01-01',
  `Plazo` int(11) NOT NULL COMMENT 'Numero correspondiente al plazo Ejemplo:   36, 48, 60',
  `FrecuenciaPlazo` char(1) NOT NULL COMMENT 'Frecuencia en la cual esta expresado el plazo M.- Mensual',
  `TasaFijaAnual` decimal(5,2) NOT NULL COMMENT 'Valor porcentual anual para la tasa de interes',
  `MontoRenta` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'monto calculado del valor de la renta antes de IVA con la formula de Pago de Excel',
  `MontoSeguro` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'monto calculado del valor del seguro con la formula de Pago de Excel',
  `MontoSeguroVida` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'monto calculado del valor del seguro de vida con la formula de Pago de Excel',
  `CantRentaDepo` int(11) NOT NULL DEFAULT '0' COMMENT 'Cantidad de Rentas en Deposito',
  `MontoDeposito` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto total del Deposito',
  `IVADeposito` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'IVA del monto en Deposito',
  `MontoComApe` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Comision por Apertura',
  `IVAComApe` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto Comision por Apertura',
  `OtroGastos` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Son otros gastos o Pagos que se pueden considerar como: Pueden ser Placas y Tenencia para el caso de arrendamiento de Auto pero podria representar otra cosa en otro tipo de arrendamientos',
  `IVAOtrosGastos` decimal(14,2) NOT NULL COMMENT 'En caso de aplique IVA para Otros Pagos',
  `TotalPagoInicial` decimal(14,2) NOT NULL COMMENT 'Monto total a pagar, como pago inical, el cual incluye  el enganche, las comisiones por apertura, el deposito, oytros gastos  y los seguros en caso de ser de contado',
  `TipCobComMorato` char(1) NOT NULL DEFAULT 'N' COMMENT 'Tipo de Comision del Moratorio  N .- N Veces la Tasa Ordinaria  T .- Tasa Fija Anualizada',
  `FactorMora` decimal(14,2) NOT NULL COMMENT 'Es el porcentaje o la cantidad de N veces el valor de la tasa ordinaria',
  `CantCuota` int(11) NOT NULL COMMENT 'Cantidad de Cuotas o amortizaciones que tiene el plan de pagos del Arrendamiento',
  `MontoCuota` decimal(12,2) NOT NULL COMMENT 'Valor final de cada cuota que el cliente debera pagar ',
  `Estatus` char(1) NOT NULL COMMENT 'G = Generado  A = Autorizado  C = Cancelado  V = Vigente  B = Vencido  P = Pagado',
  `SucursalID` int(11) NOT NULL COMMENT 'Sucursal donde se dio de alta el Arrendamiento',
  `UsuarioAlta` int(11) NOT NULL COMMENT 'Usuario que da de alta el Arrendamiento',
  `UsuarioAutoriza` int(11) NOT NULL COMMENT 'Usuario que realiza la autorizacion del Arrendamiento',
  `FechaAutoriza` date NOT NULL COMMENT 'Fecha en la que se realiza la autorizacion del Arrendamiento',
  `FechaTraspasaVen` date NOT NULL COMMENT 'Fecha en la que pasa a Vencido en caso que aplique',
  `FechaRegulariza` date NOT NULL COMMENT 'Fecha en la que se regulariza el arrendamiento, cuando pasa de Vencido a Vigente',
  `UsuarioCancela` int(11) NOT NULL COMMENT 'Usuario que realiza la cancelacion del Arrendamiento',
  `FechaCancela` date NOT NULL COMMENT 'Fecha en la que se realiza la cancelacion',
  `MotivoCancela` varchar(100) NOT NULL COMMENT 'Comentarios del porque se realizo la cancelacion',
  `SaldoCapVigente` decimal(14,2) NOT NULL COMMENT 'Es la suma de Saldo de Capital vigente de la renta',
  `SaldoCapAtrasad` decimal(14,2) NOT NULL COMMENT 'es la suma de Saldo de Capital Atrasado de la Renta ',
  `SaldoCapVencido` decimal(14,4) NOT NULL COMMENT 'es es la suma de Saldo de Capital Vencido exigible, Sucede cuando el arrendamiento tiene 90 dias o mas de atraso (sumariza las cuotas con estatus de B = Vencido)',
  `MontoIVACapital` decimal(14,2) NOT NULL COMMENT 'Es la suma de  IVA de capital que se ha pagado (no es saldo, es lo realmente pagado) en todo el arrendamiento',
  `SaldoInteresVigent` decimal(14,2) NOT NULL COMMENT 'Es la suma de Saldo vigente de Interes de la Renta',
  `SaldoInteresAtras` decimal(14,2) NOT NULL COMMENT 'Es la suma de Saldo Atrasado del interes de la renta, (suma los saldos de las cuotas atrasadas)',
  `SaldoInteresVen` decimal(14,2) NOT NULL COMMENT 'Es la suma de Saldo de Interes Vencido exigible, Sucede cuando el arrendamiento esta vencido porque tiene 90 dias de atraso o mas (sumariza las cuotas con estatus de B = Vencido)',
  `MontoIVAInteres` decimal(14,2) NOT NULL COMMENT 'Es el IVA que se ha pagado de Interes en cada cuota',
  `SaldoSeguro` decimal(14,2) NOT NULL COMMENT 'Saldo del Seguro inmobiliario Solo aplica si el seguro es financiado',
  `MontoIVASeguro` decimal(14,2) NOT NULL COMMENT 'Monto de IVA del seguro inmobiliario pagado',
  `SaldoSeguroVida` decimal(14,2) NOT NULL COMMENT 'Saldo del Seguro de vida Solo aplica si el seguro es financiado',
  `MontoIVASeguroVida` decimal(14,2) NOT NULL COMMENT 'Monto de IVA del seguro de vida pagado',
  `SaldoMoratorios` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Saldo de los intereses moratorios en caso de tener atraso',
  `MontoIVAMora` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'IVA pagado de los intereses moratorios',
  `SaldComFaltPago` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Es la suma de Saldo de la comision falta de pago generada por un atraso',
  `MontoIVAComFalPag` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'IVA pagado de la comision falta de pago',
  `SaldoOtrasComis` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'es la suma de Saldo de alguna otra comision que se maneje',
  `MontoIVAComisi` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'IVA pagado de otras comisiones',
  `DiaPagoProd` char(1) NOT NULL COMMENT 'Dias de Pago:  F = Fin de mes  A = Aniversario',
  `PagareImpreso` char(1) NOT NULL DEFAULT 'N' COMMENT 'Indica si el pagare o plan de pagos de amortizaciones ya se imprimio  S =  Si  N = No',
  `FechaInhabil` char(1) NOT NULL DEFAULT 'S' COMMENT 'Calculo de Fecha para cuando el vencimiento cae en día Inhabil:  S.- Siguiente dia habil   A.- día habil Anterior',
  `TipoPrepago` char(1) NOT NULL DEFAULT 'U' COMMENT 'Tipo de prepago a aplicar U = Pago a ultimas cuotas I   = A las cuotas siguientes inmediatas',
  `EsRenAnticipada` char(1) NOT NULL DEFAULT 'N' COMMENT 'Indica si se realizara pago anticipado del arrendamiento, S=SI N=NO.',
  `TipRenAdelanta` char(1) NOT NULL DEFAULT 'P' COMMENT 'Indica la forma de adelanto que se aplicara al arrendamiento, P=Primeras rentas U=Ultimas rentas.',
  `NumRenAdelantada` int(11) NOT NULL DEFAULT '0' COMMENT 'Indica el numero de cuotas que se adelantaran.',
  `RentasAdelantadas` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Indica el monto a pagar para la primera cuota',
  `IVARenAdelanta` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Indica el IVA a pagar para la primera cuota',
  `RentaAnticipada` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Indica el monto a pagar para las cuotas adelantadas',
  `IVARentaAnticipa` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Indica el IVA a pagar para las cuotas adelantadas',
  `EsPagoInicial` char(1) NOT NULL DEFAULT 'N' COMMENT 'Estatus de pago inicial',
  `EmpresaID` int(11) NOT NULL COMMENT 'Empresa ID',
  `Usuario` int(11) NOT NULL COMMENT 'Usuario',
  `FechaActual` datetime NOT NULL COMMENT 'Fecha Actual',
  `DireccionIP` varchar(15) NOT NULL COMMENT 'Direccion IP',
  `ProgramaID` varchar(50) NOT NULL COMMENT 'Programa de Auditoria',
  `Sucursal` int(11) NOT NULL COMMENT 'Sucursal',
  `NumTransaccion` bigint(20) NOT NULL COMMENT 'Numero de Transacción',
  PRIMARY KEY (`ArrendaID`),
  KEY `FK_ARRENDAMIENTOS_1_idx` (`ProductoArrendaID`),
  KEY `FK_ARRENDAMIENTOS_2_idx` (`ClienteID`),
  KEY `FK_ARRENDAMIENTOS_3_idx` (`MonedaID`),
  CONSTRAINT `FK_ARRENDAMIENTOS_1` FOREIGN KEY (`ProductoArrendaID`) REFERENCES `PRODUCTOARRENDA` (`ProductoArrendaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ARRENDAMIENTOS_2` FOREIGN KEY (`ClienteID`) REFERENCES `CLIENTES` (`ClienteID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ARRENDAMIENTOS_3` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Almacena los Arrendamientos'$$