DELIMITER ;
DROP TABLE IF EXISTS CARTALIQUIDACIONDET;

DELIMITER $$
CREATE TABLE CARTALIQUIDACIONDET (
CartaLiquidaID		INT(20)			NOT NULL	COMMENT	'Id de la carta de liquidacion',
SaldoCapital		DECIMAL(14,2)	NOT NULL	COMMENT	'Saldo de Capital',
UltAbono			DECIMAL(14,2)	NOT NULL	COMMENT	'Ultimo Abono',
PorcenCuoPag		DECIMAL(14,4)	NOT NULL	COMMENT	'Porcentaje Cuotas que se han pagado',
ProcenCuoNoPag		DECIMAL(14,4)	NOT NULL	COMMENT	'Porcentaje Cuotas que NO se han pagado',
MontoPagado			DECIMAL(14,2)	NOT NULL	COMMENT	'Monto Pagado',
SaldoAtrasado		DECIMAL(14,2)	NOT NULL	COMMENT	'Saldo Atrasado, Capital + Int',
CuotasGeneradas		INT(11)			NOT NULL	COMMENT	'Cuotas Generadas hasta la fecha',
MontoTotalAdeu		DECIMAL(14,2)	NOT NULL	COMMENT	'Monto Total Adeudo a la fecha  Cap+Int',
MontoPendiente		DECIMAL(14,2)	NOT NULL	COMMENT	'Monto Pendiente de Pago Cap+Int',
CuotasPagadas		DECIMAL(14,2)	NOT NULL	COMMENT	'Cuotas pagadas puede ser decimal',
MontoPagaFec		DECIMAL(14,2)	NOT NULL	COMMENT	'Monto Pagado a la Fecha',
CuotasPendientes	INT(11)			NOT NULL	COMMENT	'Numero de cuotas pendientes',
MontoLiquidar		DECIMAL(14,2)	NOT NULL	COMMENT	'Monto Para Liquidar a fecha Proyectada',
DescuentoPen		DECIMAL(14,4)	NOT NULL	COMMENT	'Descuentos pendientes',
FechaUltDescuento 	DATE 			NOT NULL DEFAULT 19000101 COMMENT 'Fecha de Ultimo Descuento',
CodigoQR			MEDIUMBLOB		NOT NULL	COMMENT	'Código QR con contenido delimitado por pipes No.Crédito  |ImporteDePago | ClaveUsuarioGeneraCarta|FechaGeneración',
CreditoID			BIGINT(12)		NOT NULL DEFAULT 0 COMMENT 'ID del Credito Consolidado',
FechaRegistro		DATE 			NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha de Registro.',
EstatusCredito		CHAR(1)			NOT NULL DEFAULT ''	COMMENT 'Estatus del Credito anterior al momento de hacer la Consolidacion',
EstatusCreacion		CHAR(1)			NOT NULL DEFAULT '' COMMENT 'Estatus contable con que nace el Crédito. \nV.-Vigente \nB.-Vencido',
NumDiasAtraso		INT(11)			NOT NULL DEFAULT 0 COMMENT 'Numero de Dias de Atraso del Credito a Consolidar',
NumPagoSoste		INT(11)			NOT NULL DEFAULT 0 COMMENT 'Numero de Pagos Sostenidos para Regularizacion',
NumPagoActual		INT(11)			NOT NULL DEFAULT 0 COMMENT 'Numero de Pagos Sostenidos Realizados Actualmente',
Regularizado		CHAR(1)			NOT NULL DEFAULT '' COMMENT 'Indica si ya se Regularizo o No de acuerdo a los pagos Sostenidos. ,\nN.- NO \n\SI',
FechaRegularizacion	DATE 			NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha de Regularizacion de acuerdo a los pagos sostenidos',
ReservaInteres		DECIMAL(14,2) 	NOT NULL DEFAULT 0.0 COMMENT 'Monto de la Estimaciones Preventivas por el Saldo del Interés en Cuentas de Orden',
FechaLimiteReporte	DATE 			NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha de Repor te de Dias de Atraso',
EmpresaID			INT(11) 		NOT NULL 	COMMENT 'Campo de Auditoria',
Usuario				INT(11) 		NOT NULL 	COMMENT 'Campo de Auditoria',
FechaActual			DATETIME 		NOT NULL 	COMMENT 'Campo de Auditoria',
DireccionIP			VARCHAR(15) 	NOT NULL 	COMMENT 'Campo de Auditoria',
ProgramaID			VARCHAR(50)		NOT NULL 	COMMENT 'Campo de Auditoria',
Sucursal			INT(11)			NOT NULL 	COMMENT 'Campo de Auditoria',
NumTransaccion		BIGINT(20) 		NOT NULL 	COMMENT 'Campo de Auditoria',
PRIMARY KEY (CartaLiquidaID)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 COMMENT='Tabla para el detalle de las cartas de liquidacion'$$