-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- CLIENTES
DELIMITER ;
DROP TABLE IF EXISTS `CLIENTES`;
DELIMITER $$

CREATE TABLE `CLIENTES` (
  `ClienteID` int(11) NOT NULL COMMENT 'LLave Primaria para Identificar los Clientes\n',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Llave Foranea Hacia Paquete Empresa si existe pero no es necesaria.\n',
  `SucursalOrigen` int(5) DEFAULT NULL COMMENT 'No de Sucursal a la que pertenece el cliente, Llave Foranea Hacia Tabla SUCURSALES\n',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de Personalidad del Cliente M.- Persona Moral A.- Persona Fisica Con Actividad Empresarial F.- Persona Fisica Sin Actividad Empresarial\n',
  `Titulo` varchar(10) DEFAULT NULL COMMENT 'Titulo del Cliente\nTitulo del Cliente, Ej. Sr., Sra, Srita, Lic, Dr. Ing, Prof.,CP, etc',
  `PrimerNombre` varchar(50) DEFAULT NULL COMMENT 'Primer Nombre del Cliente',
  `SegundoNombre` varchar(50) DEFAULT NULL COMMENT 'Segundo Nombre del Cliente\n',
  `TercerNombre` varchar(50) DEFAULT NULL COMMENT 'Tercer Nombre Del Cliente\n',
  `ApellidoPaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Paterno del Cliente\n',
  `ApellidoMaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Materno del Cliente\n',
  `FechaNacimiento` date DEFAULT NULL COMMENT 'Fecha Nacimiento del Cliente o Rep Legal\n',
  `CURP` char(18) DEFAULT NULL COMMENT 'Clave Unica de Registro Poblacional\n',
  `Nacion` char(1) DEFAULT NULL COMMENT 'Nacionalidad del cliente\n''N'' = Nacional\n''E'' = Extranjero\n',
  `PaisResidencia` int(5) DEFAULT NULL COMMENT 'Pais de Residencian, Llave Foranea Hacia tabla PAISES',
  `GrupoEmpresarial` int(11) DEFAULT NULL COMMENT 'Llave Foranea Hacia tabla GRUPOSEMP si existe peor no es necesaria.\n',
  `RazonSocial` varchar(150) DEFAULT NULL COMMENT 'Razon Social\n',
  `TipoSociedadID` int(11) DEFAULT NULL COMMENT 'Tipo de Sociedad, tiene llave foranea a la tabla  TIPOSOCIEDAD si existe pero no es necesaria',
  `Fax` varchar(30) DEFAULT NULL COMMENT 'Fax o Faxes del Cliente\n',
  `Correo` varchar(50) DEFAULT NULL COMMENT 'Fax o Faxes del Cliente\n',
  `RFC` char(13) DEFAULT NULL COMMENT 'Registro Federal de Contribuyentes del Cliente\n',
  `RFCpm` char(13) DEFAULT NULL COMMENT 'RFC de persona moral',
  `RFCOficial` char(13) DEFAULT NULL COMMENT 'RFC del cliente ya sea RFC que es asignado como persona fisica o el RFC como persona moral',
  `SectorGeneral` int(3) DEFAULT NULL COMMENT 'Sector General del Cliente,Llave Foranea Hacia tabla SECTORES\n',
  `ActividadBancoMX` varchar(15) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun Banco de Mexico,Llave Foranea Hacia tabla ACTIVIDADESBMX\n',
  `ActividadINEGI` int(11) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun INEGI,Llave Foranea Hacia tabla ACTIVIDADESINEGI\n',
  `ActividadFR` bigint(20) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun la ACTIVIDADESFR',
  `ActividadFOMURID` int(11) DEFAULT NULL COMMENT 'Actividad Fomur del Cte, segun la ACTIVIDADESFOMUR',
  `SectorEconomico` int(11) DEFAULT NULL COMMENT 'Sector Economico Segun INEGI,Llave Foranea Hacia tabla SECTORESECONOM\n',
  `Sexo` char(1) DEFAULT NULL COMMENT 'Codigo de sexo del cliente\nClave Sexo:\n''M'' = Masculino\n''F''  = Femenino',
  `EstadoCivil` char(2) DEFAULT NULL COMMENT 'Clave Estado Civil:\\n\\''S\\'' = Soltero\\n\\''CS\\''  = Casado Bienes Separados\\n\\''CM\\''  = Casado Bienes Mancomunados\\n\\''CC\\''  = Casado Bienes Mancomunados Con Capitulacion\\n\\''V\\'' = Viudo\\n\\''D\\'' = Divorciado\\n\\''SE\\''  = Separado\\n\\''U\\'' = Union Libre',
  `LugarNacimiento` int(11) DEFAULT NULL COMMENT 'Pais de Nacimiento, llave foranea a PAISES\n',
  `EstadoID` int(11) DEFAULT NULL COMMENT 'Identificador de Estado que Se Encuentra en la tabla ESTADOSREPUB',
  `OcupacionID` int(5) DEFAULT NULL COMMENT 'Profesión del cliente,Llave Foranea Hacia tabla OCUPACIONES si existe pero no es necesario.\n',
  `LugardeTrabajo` varchar(100) DEFAULT NULL COMMENT 'Lugar donde Trabaja\n',
  `Puesto` varchar(100) DEFAULT NULL COMMENT 'Puesto en el Trabajo\n',
  `DomicilioTrabajo` varchar(500) NOT NULL COMMENT 'Domicilio de trabajo del cliente',
  `TelTrabajo` varchar(20) DEFAULT NULL COMMENT 'Telefono del Trabajo\n',
  `AntiguedadTra` decimal(12,2) DEFAULT NULL COMMENT 'Antiguedad usado como decimal como años\nejemplo: 10.5\n10 años y 6 meses.',
  `TelefonoCelular` varchar(20) DEFAULT NULL COMMENT 'TelefonoCelular\n',
  `Telefono` varchar(20) DEFAULT NULL COMMENT 'Telefonos del Cliente\n',
  `Clasificacion` char(1) DEFAULT NULL COMMENT 'Clasificación del cliente, valores esperados:\nI .- Cliente independiente\nN.- Cliente Empresa de Nomina \nE.- Cliente Empleado.\nC.- Cliente Corportativo\nR .- Relacionado a Corporativo, \nF .- Negocio Afiliado\nM.- Empleado de Nomina\nO.- Cliente Funcionario',
  `MotivoApertura` char(1) DEFAULT NULL COMMENT 'Motivo de Apertura Razon del alta del cliente, valores esperados:\n1.- Credito \n2.- Recomendado \n3.- Publicidad  Campaña Promocion \n4.- Necesidad/ Proveedor \n5.- Cercania de Sucursal\n6.- Cuenta de Captacion.',
  `PagaISR` char(1) DEFAULT NULL COMMENT 'Paga ISR en Inversiones\nEspecifica si el cliente paga o no ISR por los \nIntereses de Inversión\n	''S''.- Si Paga\n	''N''.- No Paga',
  `PagaIVA` char(1) DEFAULT NULL COMMENT 'Paga IVA\nEspecifica si el cliente paga o no IVA\n	''S''.- Si Paga\n	''N''.- No Paga',
  `PagaIDE` char(1) DEFAULT NULL COMMENT 'Especifica si Cobra Impuesto de Depositos En Efectivo\nEspecifica si Cobra Impuesto de Depositos en Efectivo\n''N'' = No \n''S'' = Si',
  `NivelRiesgo` char(1) DEFAULT NULL COMMENT '\nNivel de riesgo del cliente:\nA .-  Alto\nM .- Medio\nB .-  Bajo',
  `PromotorInicial` int(6) DEFAULT NULL COMMENT 'Promotor original asignado al cliente,Llave Foranea Hacia tabla PROMOTORES\n',
  `PromotorActual` int(6) DEFAULT NULL COMMENT 'Promotor actual del cliente  ,Llave Foranea Hacia tabla PROMOTORES\n',
  `FechaAlta` date DEFAULT NULL COMMENT 'Fecha de Alta o Registro. Mostra Fec. Hoy\n',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus del cliente. Inicialmente nace Activo \n''A''.- Activo\n''I'' .- Inactivo',
  `NombreCompleto` varchar(200) DEFAULT NULL COMMENT 'Este campo no se captura, se forma en base a los nombres y apellidos\n',
  `TipoInactiva` int(11) DEFAULT NULL COMMENT 'Tipo de movimiento 1.-Activación, 2.-Inactivacion\n',
  `MotivoInactiva` varchar(150) DEFAULT NULL COMMENT 'Motivo de la Activación/Inactivacion\n',
  `EsMenorEdad` char(1) DEFAULT NULL COMMENT 'Campo que identifica si un cliente es menor de edad S.- Si  N.-NO',
  `CorpRelacionado` varchar(45) DEFAULT NULL COMMENT 'Es el dato de corporativo \nrelacionado a el \ncliente (el \ncorporativo es otro \ncliente moral)\nademás solo debe \nde tener datos si \nel en el campo \nclasificación tiene\nel valor de "R"',
  `CalificaCredito` char(1) DEFAULT NULL COMMENT 'Calificacion del cliente\\n\\nN : NO ASIGNADA\\nA: EXCELENTE\\nB : BUENA\\nC: REGULAR',
  `RegistroHacienda` char(1) DEFAULT NULL,
  `FechaBaja` date DEFAULT NULL COMMENT 'Indica la fecha en la que se da de baja el cliente',
  `Observaciones` varchar(500) DEFAULT NULL COMMENT 'Observaciones Sobre el cliente. Opcional',
  `NoEmpleado` varchar(20) DEFAULT NULL COMMENT 'Numero de empleado en la institucion de nomina',
  `TipoEmpleado` char(1) DEFAULT NULL COMMENT 'Tipo de Empleado en la Institucion de Nomina',
  `ExtTelefonoPart` varchar(6) DEFAULT NULL COMMENT 'Contiene en número de extensión del teléfono de trabajo',
  `ExtTelefonoTrab` varchar(6) DEFAULT NULL,
  `EjecutivoCap` int(11) DEFAULT NULL COMMENT 'Ejecutivo de captación\n0.- No Asignado',
  `PromotorExtInv` int(11) DEFAULT NULL COMMENT 'Promotor Extreno de inversion\n0.- No Asignado',
  `TipoPuesto` int(11) DEFAULT NULL COMMENT 'Tipo de Puesto de Empleados Nomina',
  `FechaIniTrabajo` date DEFAULT '1900-01-01' COMMENT 'Fecha de inicio en el trabajo actual',
  `UbicaNegocioID` int(11) DEFAULT '0' COMMENT 'ID de la ubicacion del negocio, relacion con CATUBICANEGOCIO',
  `FechaConstitucion` date DEFAULT NULL COMMENT 'Fecha de Constitucion ante el Registro Federal de Contribuyentes.',
  `FEA` varchar(250) DEFAULT NULL COMMENT 'Firma Electrónica Avanzada, en caso de contar con ella.',
  `PaisFEA` int(11) DEFAULT NULL,
  `PaisConstitucionID` int(11) DEFAULT NULL COMMENT 'Pais de Constitucion de la empresa',
  `CorreoAlterPM` varchar(50) DEFAULT NULL COMMENT 'Correo Alternativo Persona Moral',
  `NombreNotario` varchar(150) DEFAULT NULL COMMENT 'Nombre Notario campo para Persona Moral',
  `NumNotario` int(11) DEFAULT NULL COMMENT 'Numero de Notario campo para Persona Moral',
  `InscripcionReg` varchar(50) DEFAULT NULL COMMENT 'Inscripcion en el registro publico campo para Persona Moral',
  `EscrituraPubPM` varchar(20) DEFAULT NULL COMMENT 'Escritura Publica Persona Moral',
  `SoloNombres` varchar(500) NOT NULL COMMENT 'Primer Nombre, Segundo Nombre y Tercer Nombre',
  `SoloApellidos` varchar(500) NOT NULL COMMENT 'Apellido Paterno y Apellido Materno',
  `RazonSocialPLD` varchar(150) DEFAULT '' COMMENT 'Nombre de la persona moral limpio de caracteres especiales\nusado para la detección de personas morales.',
  `FechaSigEvalPLD` date DEFAULT NULL COMMENT 'Fecha de la siguiente evaluación para el Nivel de Riesgo',
  `PaisNacionalidad` int(11) DEFAULT NULL COMMENT 'Pais de nacionalidad del cliente',
  `TamanioAcreditado` int(11) DEFAULT NULL COMMENT 'Clave que indica el Tamanio del Acreditado WS (0,1,2,3,4)',
  `FechaReactivacion` date DEFAULT '1900-01-01' COMMENT 'Fecha de Reactivación del Cliente.',
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ClienteID`),
  KEY `fk_CLIENTES_1` (`SucursalOrigen`),
  KEY `fk_CLIENTES_2` (`PaisResidencia`),
  KEY `fk_CLIENTES_3` (`EstadoID`),
  KEY `fk_CLIENTES_4` (`PromotorInicial`),
  KEY `fk_CLIENTES_5` (`PromotorActual`),
  KEY `Index_RFCOficial` (`RFCOficial`),
  KEY `index8` (`ActividadBancoMX`),
  KEY `index9` (`ActividadINEGI`),
  KEY `index10` (`ActividadFR`),
  KEY `clientes_TelCel` (`TelefonoCelular`),
  KEY `fk_CLIENTES_6` (`SectorEconomico`),
  KEY `fk_CLIENTES_7` (`SucursalOrigen`),
  KEY `fk_CLIENTES_8` (`SectorGeneral`),
  KEY `fk_CLIENTES_9` (`ActividadINEGI`),
  KEY `fk_CLIENTES_10` (`ActividadFR`),
  KEY `fk_CLIENTES_11` (`LugarNacimiento`),
  KEY `fk_CLIENTES_12` (`ActividadFOMURID`),
  KEY `fk_TIPOSPUESTOS_13` (`TipoPuesto`),
  KEY `fk_CLIENTES_13` (`PaisConstitucionID`),
  KEY `INDEX_CLIENTES_22` (`SoloNombres`,`SoloApellidos`,`RFC`,`FechaNacimiento`,`LugarNacimiento`,`EstadoID`,`Estatus`,`TipoPersona`),
  KEY `INDEX_CLIENTES_23` (`SoloNombres`,`SoloApellidos`,`FechaNacimiento`,`RFC`,`Estatus`,`TipoPersona`),
  KEY `INDEX_CLIENTES_24` (`SoloNombres`,`SoloApellidos`,`LugarNacimiento`,`EstadoID`,`Estatus`,`TipoPersona`),
  KEY `INDEX_CLIENTES_25` (`SoloNombres`,`RFC`,`FechaNacimiento`,`LugarNacimiento`,`EstadoID`,`Estatus`,`TipoPersona`),
  KEY `INDEX_CLIENTES_26` (`SoloApellidos`,`RFC`,`FechaNacimiento`,`LugarNacimiento`,`EstadoID`,`Estatus`,`TipoPersona`),
  KEY `INDEX_CLIENTES_27` (`RazonSocial`,`RFCpm`,`Estatus`,`TipoPersona`),
  KEY `INDEX_CLIENTES_28` (`RazonSocial`,`RFCOficial`,`Estatus`,`TipoPersona`),
  CONSTRAINT `fk_CLIENTES_1` FOREIGN KEY (`ActividadBancoMX`) REFERENCES `ACTIVIDADESBMX` (`ActividadBMXID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_10` FOREIGN KEY (`ActividadFR`) REFERENCES `ACTIVIDADESFR` (`ActividadFRID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_11` FOREIGN KEY (`LugarNacimiento`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_12` FOREIGN KEY (`ActividadFOMURID`) REFERENCES `ACTIVIDADESFOMUR` (`ActividadFOMURID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_13` FOREIGN KEY (`PaisConstitucionID`) REFERENCES `PAISES` (`PaisID`),
  CONSTRAINT `fk_CLIENTES_2` FOREIGN KEY (`PaisResidencia`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_3` FOREIGN KEY (`EstadoID`) REFERENCES `ESTADOSREPUB` (`EstadoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_4` FOREIGN KEY (`PromotorInicial`) REFERENCES `PROMOTORES` (`PromotorID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_5` FOREIGN KEY (`PromotorActual`) REFERENCES `PROMOTORES` (`PromotorID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_6` FOREIGN KEY (`SectorEconomico`) REFERENCES `SECTORESECONOM` (`SectorEcoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_7` FOREIGN KEY (`SucursalOrigen`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_8` FOREIGN KEY (`SectorGeneral`) REFERENCES `SECTORES` (`SectorID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_9` FOREIGN KEY (`ActividadINEGI`) REFERENCES `ACTIVIDADESINEGI` (`ActividadINEGIID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TIPOSPUESTOS_13` FOREIGN KEY (`TipoPuesto`) REFERENCES `TIPOSPUESTOS` (`TipoPuestoID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$