-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- CONOCIMIENTOCTE
DELIMITER ;
DROP TABLE IF EXISTS `CONOCIMIENTOCTE`;
DELIMITER $$

CREATE TABLE `CONOCIMIENTOCTE` (
  `ClienteID` int(11) NOT NULL,
  `EmpresaID` int(11) DEFAULT NULL,
  `NomGrupo` varchar(100) DEFAULT NULL COMMENT 'En caso de pertenecer a una sociedad, grupo o filial\n',
  `RFC` varchar(13) DEFAULT NULL COMMENT 'En caso de pertenecer a una sociedad, grupo o filial',
  `Participacion` decimal(14,2) DEFAULT NULL COMMENT 'En caso de pertenecer a una sociedad, grupo o filial',
  `Nacionalidad` varchar(45) DEFAULT NULL COMMENT 'En caso de pertenecer a una sociedad, grupo o filial',
  `RazonSocial` varchar(100) DEFAULT NULL COMMENT 'En caso de tener actividad empresarial\n',
  `Giro` varchar(100) DEFAULT NULL COMMENT 'En caso de tener actividad empresarial',
  `PEPs` char(1) DEFAULT NULL COMMENT 'Persona politicamente expuesta, aque individuo que desempeña o ha desempeñado funciones publicas destacadas en un pais extrajero o territorio nacional\nValor: S =Si\nN= No\n',
  `FuncionID` int(11) DEFAULT NULL,
  `ParentescoPEP` char(1) DEFAULT NULL COMMENT 'Valor: S =Si\nN= No',
  `NombFamiliar` varchar(50) DEFAULT NULL,
  `APaternoFam` varchar(50) DEFAULT NULL,
  `AMaternoFam` varchar(50) DEFAULT NULL,
  `NoEmpleados` char(10) DEFAULT NULL,
  `Serv_Produc` varchar(50) DEFAULT NULL,
  `Cober_Geograf` char(1) DEFAULT NULL COMMENT 'valor : L=Local\nE=Estatal\nR=Regional\nN=Nacional\nI=Internacional\n',
  `Estados_Presen` varchar(45) DEFAULT NULL,
  `ImporteVta` decimal(14,2) DEFAULT NULL,
  `Activos` decimal(14,2) DEFAULT NULL,
  `EvaluaXMatriz` char(1) DEFAULT 'S' COMMENT 'Evalua o no en la matriz de riesgos.',
  `NoCuentaRefCom` varchar(50) NOT NULL COMMENT 'Numero de cuenta de la referencia comercial',
  `NoCuentaRefCom2` varchar(50) NOT NULL COMMENT 'Numero de cuenta de la segunda referencia comercial',
  `DireccionRefCom` varchar(500) NOT NULL COMMENT 'Direccion de la referencia comercial',
  `DireccionRefCom2` varchar(500) NOT NULL COMMENT 'Direccion de la segunda referencia comercial',
  `BanTipoCuentaRef` varchar(50) NOT NULL COMMENT 'Tipo de cuenta de la referencia comercial bancaria',
  `BanTipoCuentaRef2` varchar(50) NOT NULL COMMENT 'Tipo de cuenta de la segunda referencia comercial bancaria',
  `BanSucursalRef` varchar(50) NOT NULL COMMENT 'Sucursal de la referencia comercial bancaria',
  `BanSucursalRef2` varchar(50) NOT NULL COMMENT 'Sucursal de la segunda referencia comercial bancaria',
  `BanNoTarjetaRef` varchar(50) NOT NULL COMMENT 'Numero de tarjeta de la referencia comercial bancaria',
  `BanNoTarjetaRef2` varchar(50) NOT NULL COMMENT 'Numero de tarjeta de la segunda referencia comercial bancaria',
  `BanTarjetaInsRef` varchar(50) NOT NULL COMMENT 'Institucion de la tarjeta de la referencia comercial bancaria',
  `BanTarjetaInsRef2` varchar(50) NOT NULL COMMENT 'Institucion de la tarjeta de la segunda referencia comercial bancaria',
  `BanCredOtraEnt` char(1) NOT NULL COMMENT 'Indica si la referencia comercial bancaria tiene o no un credito con otra entidad',
  `BanCredOtraEnt2` char(1) NOT NULL COMMENT 'Indica si la segunda referencia comercial bancaria tiene o no un credito con otra entidad',
  `BanInsOtraEnt` varchar(50) NOT NULL COMMENT 'Institucion con la que la referencia comercial bancaria tiene otro credito',
  `BanInsOtraEnt2` varchar(50) NOT NULL COMMENT 'Institucion con la que la segunda referencia comercial bancaria tiene otro credito',
  `FechaNombramiento` date DEFAULT NULL COMMENT 'Fecha de Nombramiento en caso de PEPs\nParametro para Cuestionarios Adicionales.',
  `PeriodoCargo` varchar(100) DEFAULT NULL COMMENT 'Periodo del cargo en caso de PEPs\nParametro para Cuestionarios Adicionales.',
  `PorcentajeAcciones` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje de Acciones en caso de PEPs\nParametro para Cuestionarios Adicionales.',
  `MontoAcciones` decimal(12,2) DEFAULT NULL COMMENT 'Monto de las acciones en caso de PEPs\nParametro para Cuestionarios Adicionales.',
  `TiposClientes` char(1) DEFAULT NULL COMMENT 'Tipos de Clientes \nF) Persona Fisica\nM) Persona Moral\nParametro para Cuestionarios Adicionales.',
  `InstrumentosMonetarios` char(1) DEFAULT NULL COMMENT 'Instrumentos monetarios\nE) Efectivo\nC) Cheque\nT) Transferencia\nParametro para Cuestionarios Adicionales.',
  `ComentarioNivel` varchar(200) DEFAULT NULL COMMENT 'Comentario si es que el OC Cambia el nivel de Riesgo',
  `Pasivos` decimal(14,2) DEFAULT NULL,
  `Capital` decimal(14,2) DEFAULT NULL,
  `Importa` char(1) DEFAULT NULL COMMENT 'Valores Si=S\nNo=N',
  `DolaresImport` char(5) DEFAULT NULL COMMENT 'valores:\nmenos1000:DImp\n1,001 a 5,000:DImp2\n5,001 a 10,000:DImp3\nMayores 10,001DImp4',
  `PaisesImport` varchar(50) DEFAULT NULL,
  `PaisesImport2` varchar(50) DEFAULT NULL,
  `PaisesImport3` varchar(50) DEFAULT NULL,
  `Exporta` char(1) DEFAULT NULL COMMENT 'Valores Si=S\nNo=N',
  `DolaresExport` char(5) DEFAULT NULL COMMENT 'valores:\nmenos1000:DExp\n1,001 a 5,000: DExp2\n5,001 a 10,000: DExp3\nmayor10001:DExp4\n\n',
  `PaisesExport` varchar(50) DEFAULT NULL,
  `PaisesExport2` varchar(50) DEFAULT NULL,
  `PaisesExport3` varchar(50) DEFAULT NULL,
  `NombRefCom` varchar(50) DEFAULT NULL COMMENT 'Referencias comerciales (clientes/proveedores\n',
  `NombRefCom2` varchar(50) DEFAULT NULL,
  `TelRefCom` varchar(20) DEFAULT NULL COMMENT 'Referencias comerciales (clientes/proveedores',
  `TelRefCom2` varchar(20) DEFAULT NULL,
  `BancoRef` varchar(45) DEFAULT NULL COMMENT 'Referencias Bancarias\n',
  `BancoRef2` varchar(45) DEFAULT NULL,
  `NoCuentaRef` varchar(30) DEFAULT NULL COMMENT 'Referencias Bancarias',
  `NoCuentaRef2` varchar(30) DEFAULT NULL,
  `NombreRef` varchar(50) DEFAULT NULL COMMENT 'Referencias que no vivan en su domicilio',
  `NombreRef2` varchar(50) DEFAULT NULL,
  `DomicilioRef` varchar(150) DEFAULT NULL COMMENT 'Referencias que no vivan en su domicilio',
  `DomicilioRef2` varchar(150) DEFAULT NULL,
  `TelefonoRef` varchar(20) DEFAULT NULL COMMENT 'Referencias que no vivan en su domicilio',
  `TelefonoRef2` varchar(20) DEFAULT NULL,
  `PFuenteIng` varchar(100) DEFAULT NULL COMMENT 'Principal Fuente de Ingresos\n',
  `IngAproxMes` varchar(10) DEFAULT NULL,
  `extTelefonoRefUno` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extension del telefono (Primer Referencia)',
  `extTelefonoRefDos` varchar(6) DEFAULT NULL COMMENT 'Contiene el numero de extensión de teléfono (Segunda Referencia)',
  `ExtTelRefCom` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extensión de telefono de referencia comercial',
  `ExtTelRefCom2` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extensión de telefono de referencia comercial',
  `TipoRelacion1` int(11) DEFAULT NULL COMMENT 'ID de Tipo relacion del Cliente',
  `TipoRelacion2` int(11) DEFAULT NULL COMMENT 'ID de Tipo relacion del Cliente',
  `PreguntaCte1` varchar(100) DEFAULT NULL COMMENT 'Primer pregunta al Cliente en caso de que se trate de Riesgo Alto.',
  `RespuestaCte1` varchar(200) DEFAULT NULL COMMENT 'Primer respuesta del Cliente en caso de que se trate de Riesgo Alto.',
  `PreguntaCte2` varchar(100) DEFAULT NULL COMMENT 'Segunda pregunta al Cliente en caso de que se trate de Riesgo Alto.',
  `RespuestaCte2` varchar(200) DEFAULT NULL COMMENT 'Segunda respuesta del Cliente en caso de que se trate de Riesgo Alto.',
  `PreguntaCte3` varchar(100) DEFAULT NULL COMMENT 'Tercer pregunta al Cliente en caso de que se trate de Riesgo Alto.',
  `RespuestaCte3` varchar(200) DEFAULT NULL COMMENT 'Tercer respuesta del Cliente en caso de que se trate de Riesgo Alto.',
  `PreguntaCte4` varchar(100) DEFAULT NULL COMMENT 'Cuarta pregunta al Cliente en caso de que se trate de Riesgo Alto.',
  `RespuestaCte4` varchar(200) DEFAULT NULL COMMENT 'Cuarta respuesta del Cliente en caso de que se trate de Riesgo Alto.',
  `CapitalContable` decimal(14,2) DEFAULT '0.00' COMMENT 'Capital Contable',
  `OperacionAnios` int(11) DEFAULT 0 COMMENT 'Años de operación',
  `GiroAnios` int(11) DEFAULT 0 COMMENT 'Años de Giro',
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,

  PRIMARY KEY (`ClienteID`),
  KEY `fk_CONOCIMIENTOCTE_1` (`FuncionID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Conocimiento del Cliente'$$