-- TABLA CONOCIMIENTOUSUSERV

DELIMITER ;
DROP TABLE IF EXISTS `CONOCIMIENTOUSUSERV`;

DELIMITER $$
CREATE TABLE `CONOCIMIENTOUSUSERV` (
  `UsuarioServicioID`       BIGINT(11)      NOT NULL                      COMMENT 'Identificador del usuario de servicios.',
  `NombreGrupo`             VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Grupo o filial - Nombre de persona.',
  `RFC`                     VARCHAR(13)     NOT NULL DEFAULT ''           COMMENT 'Grupo o filial - RFC de persona.',
  `Participacion`           DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Grupo o filial - Porcentaje de participacion.',
  `Nacionalidad`            VARCHAR(45)     NOT NULL DEFAULT ''           COMMENT 'Grupo o filial - Nacionalidad de persona.',
  `RazonSocial`             VARCHAR(150)    NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Razon social.',
  `Giro`                    VARCHAR(150)    NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Giro de la empresa.',
  `AniosOperacion`          INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Actividad empresarial - Años de operación.',
  `AniosGiro`               INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Actividad empresarial - Años de giro.',
  `PEPs`                    CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Confirmación persona expuesta politicamente S=si, N=no.',
  `FuncionID`               INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Actividad empresarial - Identificador de la función.',
  `FechaNombramiento`       DATE            NOT NULL DEFAULT '1900-01-01' COMMENT 'Actividad empresarial - Fecha de nombramiento en caso de PEPs.',
  `PorcentajeAcciones`      DECIMAL(12, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Porcentaje de Acciones en caso de PEPs.',
  `PeriodoCargo`            VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Periodo del cargo en caso de PEPs.',
  `MontoAcciones`           DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Monto de las acciones en caso de PEPs.',
  `ParentescoPEP`           CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Confirmación de parentesco con PEP S=si, N=no.',
  `NombreFamiliar`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Nombre del familiar.',
  `APaternoFamiliar`        VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Apellido paterno del familiar.',
  `AMaternoFamiliar`        VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Apellido materno del familiar.',
  `NumeroEmpleados`         INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Actividad empresarial - Número de empleados de la empresa.',
  `ServiciosProductos`      VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Principales productos o servicios.',
  `CoberturaGeografica`     CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - L=local, E=estatal, R=regional, N=nacional, I=internacional.',
  `EstadosPresencia`        INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Actividad empresarial - En cuantos estados se tiene presencia.',
  `ImporteVentas`           DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Importes de ventas.',
  `Activos`                 DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Importe activos.',
  `Pasivos`                 DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Importe de pasivos.',
  `CapitalContable`         DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Capital contable de la empresa.',
  `CapitalNeto`             DECIMAL(14, 2)  NOT NULL DEFAULT '0.00'       COMMENT 'Actividad empresarial - Capital neto de la empresa.',
  `Importa`                 CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Confirmación de importacion S=si, N=no.',
  `DolaresImporta`          VARCHAR(10)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - DImp1=menos1000, DImp2=1001-5000, DImp3=5001-10000, DImp4=mayor10001.',
  `PaisesImporta1`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Paises a los que se importa (DImp1=menos1000).',
  `PaisesImporta2`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Paises a los que se importa (DImp2=1001-5000).',
  `PaisesImporta3`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Paises a los que se importa (DImp3=5001-10000).',
  `Exporta`                 CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Confirmación de exportación S=si, N=no.',
  `DolaresExporta`          VARCHAR(10)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - DExp1=menos1000, DExp2=1001-5000, DExp3=5001-10000, DExp4=mayor10001.',
  `PaisesExporta1`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Paises a los que se exporta (DExp1=menos1000).',
  `PaisesExporta2`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Paises a los que se exporta (DExp2=1001-5000).',
  `PaisesExporta3`          VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Paises a los que se exporta (DExp3=5001-10000).',
  `TiposClientes`           CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - F=persona fisica, M=persona moral.',
  `InstrMonetarios`         CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Actividad empresarial - Instrumentos monetarios: E=efectivo, C=cheque, T=transferencia.',
  `NombreRefCom1`           VARCHAR(150)    NOT NULL DEFAULT ''           COMMENT 'Primera referencia comercial - Nombre completo.',
  `NoCuentaRefCom1`         VARCHAR(30)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia comercial - Número de cuenta.',
  `DireccionRefCom1`        VARCHAR(500)    NOT NULL DEFAULT ''           COMMENT 'Primera referencia comercial - Dirección completa.',
  `TelefonoRefCom1`         VARCHAR(20)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia comercial - Número telefonico.',
  `ExtTelefonoRefCom1`      VARCHAR(6)      NOT NULL DEFAULT ''           COMMENT 'Primera referencia comercial - Número de extención del númumero telefonico.',
  `NombreRefCom2`           VARCHAR(150)    NOT NULL DEFAULT ''           COMMENT 'Segunda referencia comercial - Nombre completo.',
  `NoCuentaRefCom2`         VARCHAR(30)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia comercial - Número de cuenta.',
  `DireccionRefCom2`        VARCHAR(500)    NOT NULL DEFAULT ''           COMMENT 'Segunda referencia comercial - Dirección completa.',
  `TelefonoRefCom2`         VARCHAR(20)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia comercial - Número telefonico.',
  `ExtTelefonoRefCom2`      VARCHAR(6)      NOT NULL DEFAULT ''           COMMENT 'Segunda referencia comercial - Númuero de extención del número telefonico.',
  `BancoRefBanc1`           VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Nombre del banco.',
  `TipoCuentaRefBanc1`      VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Tipo de cuenta.',
  `NoCuentaRefBanc1`        VARCHAR(30)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Número de cuenta.',
  `SucursalRefBanc1`        VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Sucursal del banco.',
  `NoTarjetaRefBanc1`       VARCHAR(20)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Número de tarjeta del banco.',
  `InstitucionRefBanc1`     VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Institución bancaria de la tarjeta.',
  `CredOtraEntRefBanc1`     CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Confirmación de crédito en otra entidad S=si, N=no.',
  `InstitucionEntRefBanc1`  VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Primera referencia bancaria - Institución del crédito en otra entidad.',
  `BancoRefBanc2`           VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Nombre del banco.',
  `TipoCuentaRefBanc2`      VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Tipo de cuenta.',
  `NoCuentaRefBanc2`        VARCHAR(30)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Número de cuenta.',
  `SucursalRefBanc2`        VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Sucursal del banco.',
  `NoTarjetaRefBanc2`       VARCHAR(20)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Número de tarjeta del banco.',
  `InstitucionRefBanc2`     VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Institución bancaria de la tarjeta.',
  `CredOtraEntRefBanc2`     CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Confirmación de crédito en otra entidad S=si, N=no.',
  `InstitucionEntRefBanc2`  VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Segunda referencia bancaria - Institución del crédito en otra entidad.',
  `NombreRefPers1`          VARCHAR(150)    NOT NULL DEFAULT ''           COMMENT 'Referencia (1) que no viva en su domicilio - Nombre de la persona.',
  `DomicilioRefPers1`       VARCHAR(500)    NOT NULL DEFAULT ''           COMMENT 'Referencia (1) que no viva en su domicilio - Domicilio de la persona.',
  `TelefonoRefPers1`        VARCHAR(20)     NOT NULL DEFAULT ''           COMMENT 'Referencia (1) que no viva en su domicilio - Número telefonico de la persona.',
  `ExtTelefonoRefPers1`     VARCHAR(6)      NOT NULL DEFAULT ''           COMMENT 'Referencia (1) que no viva en su domicilio - Núm. de extención del núm. telefonico.',
  `TipoRelacionRefPers1`    INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Referencia (1) que no viva en su domicilio - ID tipo de relación con la persona.',
  `NombreRefPers2`          VARCHAR(150)    NOT NULL DEFAULT ''           COMMENT 'Referencia (2) que no viva en su domicilio - Nombre de la persona.',
  `DomicilioRefPers2`       VARCHAR(500)    NOT NULL DEFAULT ''           COMMENT 'Referencia (2) que no viva en su domicilio - Domicilio de la persona.',
  `TelefonoRefPers2`        VARCHAR(20)     NOT NULL DEFAULT ''           COMMENT 'Referencia (2) que no viva en su domicilio - Número telefonico de la persona.',
  `ExtTelefonoRefPers2`     VARCHAR(6)      NOT NULL DEFAULT ''           COMMENT 'Referencia (2) que no viva en su domicilio - Núm. de extención del núm. telefonico.',
  `TipoRelacionRefPers2`    INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Referencia (2) que no viva en su domicilio - ID tipo de relación con la persona.',
  `PreguntaUsuario1`        VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Primera pregunta.',
  `RespuestaUsuario1`       VARCHAR(200)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Primera respuesta.',
  `PreguntaUsuario2`        VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Segunda pregunta.',
  `RespuestaUsuario2`       VARCHAR(200)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Segunda respuesta.',
  `PreguntaUsuario3`        VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Tercera pregunta.',
  `RespuestaUsuario3`       VARCHAR(200)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Tercera respuesta.',
  `PreguntaUsuario4`        VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Cuarta pregunta.',
  `RespuestaUsuario4`       VARCHAR(200)    NOT NULL DEFAULT ''           COMMENT 'Usuario de servicios de riesgo alto - Cuarta respuesta.',
  `PrincipalFuenteIng`      VARCHAR(100)    NOT NULL DEFAULT ''           COMMENT 'Principal fuente de ingresos.',
  `IngAproxPorMes`          VARCHAR(10)     NOT NULL DEFAULT ''           COMMENT 'Ing1=menos20,000, Ing2=20,001-50,000, Ing3=50,001-100,000, Ing4=mayor100,000.',
  `EvaluaXMatriz`           CHAR(1)         NOT NULL DEFAULT ''           COMMENT 'Confirmación evalua o no la matriz de riesgo S=si, N=no.',
  `ComentarioNivel`         VARCHAR(200)    NOT NULL DEFAULT ''           COMMENT 'Comentario si el el OC cambió el nivel de riesgo.',
  `EmpresaID`               INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Parámetro de auditoría ID de la empresa.',
  `Usuario`                 INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Parámetro de auditoría ID del usuario.',
  `FechaActual`             DATETIME        NOT NULL DEFAULT '1900-01-01' COMMENT 'Parámetro de auditoría fecha actual.',
  `DireccionIP`             VARCHAR(15)     NOT NULL DEFAULT ''           COMMENT 'Parámetro de auditoría direccion IP.',
  `ProgramaID`              VARCHAR(50)     NOT NULL DEFAULT ''           COMMENT 'Parámetro de auditoría programa.',
  `Sucursal`                INT(11)         NOT NULL DEFAULT '0'          COMMENT 'Parámetro de auditoría ID de la sucursal.',
  `NumTransaccion`          BIGINT(20)      NOT NULL DEFAULT '0'          COMMENT 'Parámetro de auditoría numero de transaccion.',
  PRIMARY KEY (`UsuarioServicioID`),
  KEY `INDEX_CONOCIMIENTOUSUSERV_1` (`FuncionID`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Tab: Tabla de Conocimiento del Usuario de Servicios.'$$