DELIMITER ;
DROP TABLE IF EXISTS CREDITOSDIFER;

DELIMITER ;
CREATE TABLE `CREDITOSDIFER` (
  `CreditoID` BIGINT(12) NOT NULL COMMENT 'Numero de Credito, sigue la misma nomenclatura que usa las cuentas de ahorro\n',
  `NumeroDiferimientos` INT(11) NOT NULL COMMENT 'Numero de Diferimientos',
  `LineaCreditoID` BIGINT(20) DEFAULT NULL COMMENT 'Linea de Credito\n',
  `ClienteID` INT(11) DEFAULT NULL COMMENT 'Numero de Cliente\n',
  `CuentaID` BIGINT(12) DEFAULT NULL,
  `Clabe` VARCHAR(18) DEFAULT NULL COMMENT 'No de Cuenta Clabe del Credito',
  `MonedaID` INT(11) DEFAULT NULL COMMENT 'Moneda',
  `ProductoCreditoID` INT(4) DEFAULT NULL,
  `DestinoCreID` INT(11) DEFAULT NULL,
  `MontoCredito` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto del Credito',
  `TipoCredito` CHAR(1) DEFAULT NULL COMMENT 'Indica el tratamiento al credito N=nuevo, R=reestructura, O=renovacion',
  `Relacionado` BIGINT(12) DEFAULT NULL COMMENT 'Credito relacionado por: Renovacion o Reestructura, puede ser vacio',
  `SolicitudCreditoID` BIGINT(11) DEFAULT NULL COMMENT 'Solicitud de Credito. Sera una tabla de solicitudes\nPor el momento Es capturable, es un entero',
  `TipoFondeo` CHAR(1) DEFAULT NULL COMMENT 'Tipo de Fondeo:\nP .- Recursos Propios\nF .- Institucion de Fondeo',
  `InstitFondeoID` INT(11) DEFAULT NULL COMMENT 'Insitucion de Fondeo, puede no escoger linea de fondeo',
  `LineaFondeo` INT(11) DEFAULT NULL COMMENT 'Si escoge una institucion de fondeo, debe escoger sobre \nQue linea De fondeo (LINEAFONDEADOR)\n',
  `FechaInicio` DATE DEFAULT NULL COMMENT 'Fecha de Inicio del Credito',
  `FechaInicioAmor` DATE DEFAULT NULL COMMENT 'Fecha en la que inician las amortizaciones y cobro de intereses, en un desembolso anticipado',
  `FechaVencimien` DATE DEFAULT NULL COMMENT 'Fecha de Vencimiento\n',
  `CalcInteresID` INT(11) DEFAULT NULL COMMENT 'Tipo de calculo de interes\n1:TasaFija\n2:TasaBase de inicio de cupon+Puntos\n3:Tasa Base de inicio de cupon+Puntos, con Piso y Techo',
  `TasaBase` INT(11) DEFAULT NULL,
  `TasaFija` DECIMAL(12,4) DEFAULT NULL,
  `SobreTasa` FLOAT DEFAULT NULL COMMENT 'Si es formula dos (Tasa base mas puntos), aqui se definen\n Los puntosSi es formula uno (Tasa Fija), aqui se especifica el valor de dicha\ntasa fija\n',
  `PisoTasa` FLOAT DEFAULT NULL COMMENT 'Piso, Si es formula tres\n',
  `TechoTasa` FLOAT DEFAULT NULL COMMENT 'Techo, Si es formula tres',
  `TipCobComMorato` CHAR(1) DEFAULT NULL,
  `FactorMora` FLOAT DEFAULT NULL COMMENT 'Factor de Moratorio\n\n',
  `FrecuenciaCap` CHAR(1) DEFAULT NULL COMMENT 'Frecuencia de Pago de las Amortizaciones de Capital\nS .- Semanal,\nC .- Catorcenal\nQ .- Quincenal\nM .- Mensual\nP .- Periodo\nB.-Bimestral \nT.-Trimestral \nR.-TetraMestral\nE.-Semestral \nA.-Anual\nL.- Libres',
  `PeriodicidadCap` INT(11) DEFAULT NULL COMMENT 'Periodicidad de Capital en dias\n',
  `FrecuenciaInt` CHAR(1) DEFAULT NULL COMMENT 'Frecuencia de Interes\nS .- Semanal,\nC .- Catorcenal\nQ .- Quincenal\nM .- Mensual\nP .- Periodo\nB.-Bimestral \nT.-Trimestral \nR.-TetraMestral\nE.-Semestral \nA.-Anual\nL.-Libres',
  `PeriodicidadInt` INT(11) DEFAULT NULL COMMENT 'Periodicidad de Interes en dias',
  `TipoPagoCapital` CHAR(1) DEFAULT NULL COMMENT 'Tipo de Pago de Capital\nC .-Crecientes\nI .- Iguales\nL .-Libres\n',
  `NumAmortizacion` INT(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones o Cuotas (de Capital)\\n',
  `MontoCuota` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto de la Cuota\n',
  `FechTraspasVenc` DATE DEFAULT NULL COMMENT 'Fecha de Traspaso a Vencido, nace con fecha vacia\n',
  `FechTerminacion` DATE DEFAULT NULL COMMENT 'Fecha de Pago del Credito, nace con fecha vacia\n',
  `IVAInteres` DECIMAL(12,2) DEFAULT NULL COMMENT 'Tasa de Iva a Cobrar por los Intereses, o Cero si es Exento\n',
  `IVAComisiones` DECIMAL(12,2) DEFAULT NULL COMMENT 'Tasa de Iva a Cobrar por las Comisiones, o Cero si es Exento\n',
  `Estatus` CHAR(1) DEFAULT NULL COMMENT 'Estatus del Credito, no se pide en el alta. Nace inactivo\nI .- Inactivo\nA.- Autorizado\nV.- Vigente\nP .- Pagado\nC .- Cancelado\nB.- Vencido\nK.- Castigado',
  `FechaAutoriza` DATE DEFAULT NULL COMMENT 'Fecha de \nAutorizacion o \nLiberacion',
  `UsuarioAutoriza` INT(11) DEFAULT NULL COMMENT 'Usuairo que autoriza\nel Credito',
  `SaldoCapVigent` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vigente, en el alta nace con ceros\n',
  `SaldoCapAtrasad` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Atrasado, en el alta nace con ceros\n',
  `SaldoCapVencido` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido, en el alta nace con ceros\n',
  `SaldCapVenNoExi` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido no Exigible, en el alta nace con ceros\n',
  `SaldoInterOrdin` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Ordinario, en el alta nace con ceros\n',
  `SaldoInterAtras` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Atrasado, en el alta nace con ceros\n',
  `SaldoInterVenc` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Vencido, en el alta nace con ceros\n',
  `SaldoInterProvi` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Provision, en el alta nace con ceros\n',
  `SaldoIntNoConta` DECIMAL(14,4) DEFAULT NULL COMMENT 'Saldo de Interes\nNo Contabilizado',
  `SaldoIVAInteres` DECIMAL(12,2) DEFAULT NULL COMMENT 'Saldo Iva Interes, en el alta nace con ceros\n',
  `SaldoMoratorios` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo Moratorios, en el alta nace con ceros\n',
  `SaldoIVAMorator` DECIMAL(12,2) DEFAULT NULL COMMENT 'Saldo Iva Mora, en el alta nace con ceros\n',
  `SaldComFaltPago` DECIMAL(12,2) DEFAULT NULL COMMENT 'Saldo Comision Falta Pago, en el alta nace con ceros\n',
  `SalIVAComFalPag` DECIMAL(12,2) DEFAULT NULL COMMENT 'Saldo IVA Com Falta Pago, en el alta nace con ceros\n',
  `SaldoComServGar` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Comision por Servicio de Garantia Agro',
  `SaldoIVAComSerGar` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Iva Comision por Servicio de Garantia Agro',
  `SaldoOtrasComis` DECIMAL(12,2) DEFAULT NULL COMMENT 'Saldo Otras Comisiones, en el alta nace con ceros\n',
  `SaldoIVAComisi` DECIMAL(12,2) DEFAULT NULL COMMENT 'Saldo Iva Otras Com, en el alta nace con ceros\n',
  `ProvisionAcum` DECIMAL(14,4) DEFAULT NULL COMMENT 'Provision\nAcumulada ',
  `PagareImpreso` CHAR(1) DEFAULT NULL COMMENT 'Pagaré impreso\nN=No,S=Si',
  `FechaInhabil` CHAR(1) DEFAULT NULL COMMENT 'En Fecha Inhabil Tomar:\nS.- Siguiente\nA.- Anterior\n',
  `CalendIrregular` CHAR(1) DEFAULT NULL COMMENT 'Calendario Irregular\nS.- Si\nN.-No\n',
  `DiaPagoInteres` CHAR(1) DEFAULT NULL COMMENT 'Dia de Pago Interes\nF.-Pago  final del mes \nA.- Por aniversario\nD.- Dia del mes\nI.- Indistinto\n',
  `DiaPagoCapital` CHAR(1) DEFAULT NULL COMMENT 'Dia de Pago Capital\nF.-Pago  final del mes \nA.- Por aniversario\nD.- Dia del mes\nI.- Indistinto\n\n',
  `DiaPagoProd` CHAR(1) DEFAULT NULL COMMENT 'Dia de pago de capital del producto de credito: F=fin de mes, D=dia \ndel mes, A=aniversario, I=indistinto',
  `DiaMesInteres` INT(11) DEFAULT NULL COMMENT 'Dia del Mes interes',
  `DiaMesCapital` INT(11) DEFAULT NULL COMMENT 'Dia del Mes capital\n',
  `AjusFecUlVenAmo` CHAR(1) DEFAULT NULL COMMENT 'Ajustar la fecha de vencimiento de la ultima \namortizacion a fecha de vencimiento de credito\nS.- Si\nN.- No',
  `AjusFecExiVen` CHAR(1) DEFAULT NULL COMMENT 'Ajustar Fecha de exigibilidad a fecha de vencimiento\nS.- Si\nN.- No\n',
  `NumTransacSim` BIGINT(20) DEFAULT NULL COMMENT 'Numero de transaccion en el simulador de amortizaciones\n',
  `FechaMinistrado` DATE DEFAULT NULL COMMENT 'Fecha de ministración\ndel credito',
  `FolioDispersion` INT(11) DEFAULT NULL,
  `SucursalID` INT(11) DEFAULT NULL COMMENT 'Sucursal donde se dio de alta el credito',
  `ValorCAT` DECIMAL(12,4) DEFAULT '0.0000' COMMENT 'Valor del CAT (Costo Anual Total)',
  `ClasifRegID` INT(11) DEFAULT NULL COMMENT 'Clasificacion Segun Reportes Regulatorios',
  `MontoComApert` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto de comision por apertura',
  `IVAComApertura` DECIMAL(12,2) DEFAULT NULL COMMENT 'IVA de la comision por apertura',
  `PlazoID` VARCHAR(20) DEFAULT NULL COMMENT 'Plazo del credito\\n',
  `TipoDispersion` CHAR(1) DEFAULT NULL COMMENT 'Tipo de Dispersion\\n	S .- SPEI\\n	C .- Cheque\\n	O .- Orden de Pago\\n	E.- Efectivo',
  `CuentaCLABE` CHAR(18) DEFAULT NULL,
  `TipoCalInteres` INT(11) DEFAULT NULL COMMENT '1 .- Saldos Insolutos\n2 .- Monto Original (Saldos Globales)',
  `TipoGeneraInteres` CHAR(1) NOT NULL COMMENT 'Tipo de Monto Original (Saldos Globales): \n"I".- Iguales \n"D".- Dias Transcurridos',
  `MontoDesemb` DECIMAL(14,2) DEFAULT NULL COMMENT 'Monto del Credito que ya ha sido Desembolsado o Ministrado',
  `MontoPorDesemb` DECIMAL(14,2) DEFAULT NULL COMMENT 'Monto del Credito Pendiente de Desembolso o Ministracion',
  `NumAmortInteres` INT(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones (cuotas) de Interes',
  `AporteCliente` DECIMAL(12,2) DEFAULT NULL COMMENT 'Aporte del Cliente de la \nGarantia Liquida',
  `PorcGarLiq` DECIMAL(12,2) DEFAULT NULL COMMENT 'Especifica el porcentaje  de garantia liquida',
  `MontoSeguroVida` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto del Seguro de Vida',
  `SeguroVidaPagado` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto que el cliente ya ha pagado del Seguro de Vida',
  `ForCobroSegVida` CHAR(1) DEFAULT NULL COMMENT 'A: Anticipado, D: Deduccion, F: Financiamiento',
  `ComAperPagado` DECIMAL(12,2) DEFAULT NULL COMMENT 'Comision por Apertura Ya pagada por el Cliente',
  `ForCobroComAper` CHAR(1) DEFAULT NULL COMMENT 'Forma de cobro de comision por apertura.\nA: Anticipado \nD: Deduccion\nF: Financiamiento\nP: Programado',
  `ClasiDestinCred` CHAR(1) DEFAULT NULL,
  `CicloGrupo` INT(11) DEFAULT NULL COMMENT 'Ciclo del Grupo, en Caso de un Credito Grupal',
  `GrupoID` INT(11) DEFAULT NULL COMMENT 'Numero o ID del Grupo, en caso de ser un Credito Grupal',
  `TipoPrepago` CHAR(1) DEFAULT NULL COMMENT 'Tipo de prepago a aplicar\nU-Pago de capital a ultimas cuotas\nI-A las cuotas siguientes inmediatas\nV-Prorrateo de pago en cuotas vivas',
  `SaldoMoraVencido` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Interes Moratorio en atraso o vencido',
  `SaldoMoraCarVen` DECIMAL(14,2) DEFAULT NULL COMMENT 'Saldo de Moratorios deirvado de cartera vencida, en ctas de orden',
  `DescuentoSeguro` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto de seguro de vida con descuento',
  `MontoSegOriginal` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto de seguro de vida original',
  `IdenCreditoCNBV` VARCHAR(29) DEFAULT NULL COMMENT 'Identificador del Credito Utilizando Metodologia CNBV',
  `CobraSeguroCuota` CHAR(1) DEFAULT NULL COMMENT 'Valida si el producto cobra seguro por cuota, este campo es del producto\n',
  `CobraIVASeguroCuota` CHAR(1) DEFAULT NULL COMMENT 'Valida si el producto cobra IVA seguro por cuota, este campo es del producto',
  `MontoSeguroCuota` DECIMAL(12,2) DEFAULT NULL COMMENT 'Monto por Cuota para el pago del seguro por cuota.',
  `IVASeguroCuota` DECIMAL(12,2) DEFAULT NULL COMMENT 'IVA para el monto por seguro por cuota',
  `CobraComAnual` VARCHAR(1) DEFAULT NULL COMMENT 'Cobra Comision S:Si N:No',
  `TipoComAnual` VARCHAR(1) DEFAULT NULL COMMENT 'Tipo de Comision P:Porcentaje M:Monto',
  `BaseCalculoComAnual` VARCHAR(1) DEFAULT NULL COMMENT 'Base del Cálculo M:Monto del crédito Original S:Saldo Insoluto',
  `MontoComAnual` DECIMAL(14,2) DEFAULT NULL COMMENT 'Monto de la Comision en caso de que el tipo de comision sea M',
  `PorcentajeComAnual` DECIMAL(14,4) DEFAULT NULL COMMENT 'Porcentaje de la comision en caso de que el tipo de comision sea P',
  `DiasGraciaComAnual` INT(11) DEFAULT NULL COMMENT 'Dias de gracia que se dan antes de cobrar la comisión',
  `SaldoComAnual` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Saldo Comision Anual',
  `TipoLiquidacion` CHAR(1) DEFAULT 'T' COMMENT 'Tipo de Liquidacion para una Renovacion de Credito\nT: Total\nP: Parcial',
  `CantidadPagar` DECIMAL(12,2) DEFAULT '0.00' COMMENT 'Cantidad a Pagar en una Renovacion de Credito',
  `ComAperCont` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Monto de la Comisión por Apertura Contabilizada',
  `IVAComAperCont` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Monto del IVA de la Comision por Apertura Contabilizada',
  `ComAperReest` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Nuevo Monto a Contabilizar cuando se hace una Reestructura',
  `IVAComAperReest` DECIMAL(14,2) DEFAULT '0.00' COMMENT ' Monto del IVA de la Comision por Apertura a Contabilizar cuando se hace una Reestructura',
  `FechaAtrasoCapital` DATE DEFAULT '1900-01-01' COMMENT 'Fecha de Atraso de Capital',
  `FechaAtrasoInteres` DATE DEFAULT '1900-01-01' COMMENT 'Fecha de Atraso de Interes',
  `TipoConsultaSIC` CHAR(2) DEFAULT NULL COMMENT 'Se indica BC si la Consulta se realizó a Buró de Crédito o CC si se realizó a  Círculo de Crédito',
  `FolioConsultaBC` VARCHAR(30) DEFAULT NULL COMMENT 'Folio de consulta de Buro de Credito',
  `FolioConsultaCC` VARCHAR(30) DEFAULT NULL COMMENT 'Folio de consulta de Circulo de Credito',
  `EsAgropecuario` CHAR(1) DEFAULT 'N' COMMENT 'Indica si el credito es de tipo Agropecuario. Se hereda desde el Producto de Credito/Solicitud de Credito.',
  `TipoCancelacion` CHAR(1) DEFAULT 'U' COMMENT 'Tipo de cancelación a aplicar. Se hereda del producto de crédito.\nU.- Últimas cuotas.\nI.- Cuotas siguientes inmediatas.\nV.- Prorrateo en cuotas vivas.',
  `Refinancia` CHAR(1) DEFAULT 'N' COMMENT 'Indica si los intereses serán refinanciados\nS: Si\nN: N',
  `CadenaProductivaID` INT(11) DEFAULT NULL COMMENT 'ID del Catalogo CATCADENAPRODUCTIVA',
  `RamaFIRAID` INT(11) DEFAULT NULL COMMENT 'ID de la Tabla CATRAMAFIRA',
  `SubramaFIRAID` INT(11) DEFAULT NULL COMMENT 'ID de la tabla CATSUBRAMAFIRA',
  `ActividadFIRAID` INT(11) DEFAULT NULL COMMENT 'ID de la Tabla CATACTIVIDADESFIRA',
  `TipoGarantiaFIRAID` INT(11) DEFAULT NULL COMMENT 'ID de la Tabla CATTIPOGARANTIAFIRA',
  `EstatusGarantiaFIRA` CHAR(1) DEFAULT NULL COMMENT 'Determina el estatus de la contratación de garantias Fega y Fonaga, para creditos fondeados con FIRA el Estatus es automatico como procesado.\nI  : Inactivo\nA : Autorizado\nC : Cancelado \n',
  `ProgEspecialFIRAID` VARCHAR(10) DEFAULT NULL COMMENT 'ID de la TABLA CATFIRAPROGESP',
  `FechaCobroComision` DATE DEFAULT '1900-01-01' COMMENT 'Fecha de Cobro de la comision cuando la forma del cobro sea programada',
  `EsAutomatico` CHAR(1) DEFAULT 'N' COMMENT 'Indica si el credito es Automatico\nS: Si\nN: No',
  `TipoAutomatico` CHAR(1) DEFAULT '' COMMENT 'Indica si el credito es automatico sobre.\nA: Ahorro\nI: Inversion',
  `InvCredAut` INT(11) DEFAULT '0' COMMENT 'Inversion relacionada al Credito Automatico',
  `CtaCredAut` BIGINT(12) DEFAULT '0' COMMENT 'Cuenta de Ahorro relacionada al Credito Automatico',
  `AcreditadoIDFIRA` BIGINT(20) DEFAULT NULL COMMENT 'Numero de Acreditado FIRA',
  `CreditoIDFIRA` BIGINT(20) DEFAULT NULL COMMENT 'Numero de Credito FIRA',
  `InteresAcumulado` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Guarda el interes acumulado en cada mes. Utilizado para el refinanciamiento de creditos agro.',
  `InteresRefinanciar` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Guarda el interes a refinanciar en cada mes utilizado en la base de calculo para intereses ordinarios en creditos agropecuarios',
  `Reacreditado` CHAR(1) DEFAULT 'N' COMMENT 'Indica si un Crédito esta Reacreditado',
  `TipoComXApertura` CHAR(1) DEFAULT '' COMMENT 'Tipo de Comision por apertura',
  `MontoComXApertura` DECIMAL(14,2) DEFAULT '0.00' COMMENT 'Monto de Comision por Apertura',
  `DiasAtrasoMin` INT(11) DEFAULT NULL COMMENT 'Número de Dias de Atraso Minimo para el proceso de Castigo',
  `ReferenciaPago` VARCHAR(20) DEFAULT NULL COMMENT 'Refencia de Pago (Para el proceso de Pago Refenreciado)',
  `NivelID` INT(11) DEFAULT '0' COMMENT 'Nivel, corresponde al catálogo NIVELCREDITO.',
  `CobraAccesorios` CHAR(1) DEFAULT 'N' COMMENT 'Indica si el credito cobra accesorios',
  `EmpresaID` INT(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Usuario` INT(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` DATETIME DEFAULT NULL,
  `DireccionIP` VARCHAR(15) DEFAULT NULL,
  `ProgramaID` VARCHAR(50) DEFAULT NULL,
  `Sucursal` INT(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` BIGINT(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`CreditoID`,`NumeroDiferimientos`),
  KEY `fk_ClienteID` (`ClienteID`),
  KEY `fk_CuentaID` (`CuentaID`),
  KEY `fk_CREDITOS_1` (`MonedaID`),
  KEY `fk_InstitFodeo` (`InstitFondeoID`),
  KEY `fk_LineaFondeo` (`LineaFondeo`),
  KEY `fk_CREDITOS_2` (`ProductoCreditoID`),
  KEY `fk_CREDITOS_3` (`DestinoCreID`),
  KEY `fk_CalculoInteres` (`CalcInteresID`),
  KEY `fk_LineasCredID` (`LineaCreditoID`),
  KEY `fk_CREDITOS_4` (`SolicitudCreditoID`),
  KEY `fk_CREDITOS_5` (`FechaMinistrado`,`Estatus`),
  KEY `idx_CREDITOS_1` (`ClienteID`,`Estatus`),
  KEY `IDX_CREDITOS_2` (`AcreditadoIDFIRA`),
  KEY `IDX_CREDITOS_3` (`CreditoIDFIRA`),
  KEY `IDX_CREDITOS_5` (`ReferenciaPago`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 COMMENT='Tabla de Creditos\n';
