
DELIMITER ;
DROP TABLE IF EXISTS `CREDITOSVTA`;
DELIMITER $$

CREATE TABLE `CREDITOSVTA` (
  `CreditoID` bigint(12) NOT NULL COMMENT 'Numero de Credito, sigue la misma nomenclatura que usa las cuentas de ahorro\n',
  `LineaCreditoID` bigint(20) DEFAULT NULL COMMENT 'Linea de Credito\n',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente\n',
  `CuentaID` bigint(12) DEFAULT NULL,
  `Clabe` varchar(18) DEFAULT NULL COMMENT 'No de Cuenta Clabe del Credito',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Moneda',
  `ProductoCreditoID` int(4) DEFAULT NULL,
  `DestinoCreID` int(11) DEFAULT NULL,
  `MontoCredito` decimal(12,2) DEFAULT NULL COMMENT 'Monto del Credito',
  `TipoCredito` char(1) DEFAULT NULL COMMENT 'Indica el tratamiento al credito N=nuevo, R=reestructura, O=renovacion',
  `Relacionado` bigint(12) DEFAULT NULL COMMENT 'Credito relacionado por: Renovacion o Reestructura, puede ser vacio',
  `SolicitudCreditoID` bigint(11) DEFAULT NULL COMMENT 'Solicitud de Credito. Sera una tabla de solicitudes\nPor el momento Es capturable, es un entero',
  `TipoFondeo` char(1) DEFAULT NULL COMMENT 'Tipo de Fondeo:\nP .- Recursos Propios\nF .- Institucion de Fondeo',
  `InstitFondeoID` int(11) DEFAULT NULL COMMENT 'Insitucion de Fondeo, puede no escoger linea de fondeo',
  `LineaFondeo` int(11) DEFAULT NULL COMMENT 'Si escoge una institucion de fondeo, debe escoger sobre \nQue linea De fondeo (LINEAFONDEADOR)\n',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio del Credito',
  `FechaInicioAmor` date DEFAULT NULL COMMENT 'Fecha en la que inician las amortizaciones y cobro de intereses, en un desembolso anticipado',
  `FechaVencimien` date DEFAULT NULL COMMENT 'Fecha de Vencimiento\n',
  `CalcInteresID` int(11) DEFAULT NULL COMMENT 'Tipo de calculo de interes\n1:TasaFija\n2:TasaBase de inicio de cupon+Puntos\n3:Tasa Base de inicio de cupon+Puntos, con Piso y Techo',
  `TasaBase` int(11) DEFAULT NULL,
  `TasaFija` decimal(12,4) DEFAULT NULL,
  `SobreTasa` float DEFAULT NULL COMMENT 'Si es formula dos (Tasa base mas puntos), aqui se definen\n Los puntosSi es formula uno (Tasa Fija), aqui se especifica el valor de dicha\ntasa fija\n',
  `PisoTasa` float DEFAULT NULL COMMENT 'Piso, Si es formula tres\n',
  `TechoTasa` float DEFAULT NULL COMMENT 'Techo, Si es formula tres',
  `TipCobComMorato` char(1) DEFAULT NULL,
  `FactorMora` float DEFAULT NULL COMMENT 'Factor de Moratorio\n\n',
  `FrecuenciaCap` char(1) DEFAULT NULL COMMENT 'Frecuencia de Pago de las Amortizaciones de Capital\nS .- Semanal,\nC .- Catorcenal\nQ .- Quincenal\nM .- Mensual\nP .- Periodo\nB.-Bimestral \nT.-Trimestral \nR.-TetraMestral\nE.-Semestral \nA.-Anual\nL.- Libres',
  `PeriodicidadCap` int(11) DEFAULT NULL COMMENT 'Periodicidad de Capital en dias\n',
  `FrecuenciaInt` char(1) DEFAULT NULL COMMENT 'Frecuencia de Interes\nS .- Semanal,\nC .- Catorcenal\nQ .- Quincenal\nM .- Mensual\nP .- Periodo\nB.-Bimestral \nT.-Trimestral \nR.-TetraMestral\nE.-Semestral \nA.-Anual\nL.-Libres',
  `PeriodicidadInt` int(11) DEFAULT NULL COMMENT 'Periodicidad de Interes en dias',
  `TipoPagoCapital` char(1) DEFAULT NULL COMMENT 'Tipo de Pago de Capital\nC .-Crecientes\nI .- Iguales\nL .-Libres\n',
  `NumAmortizacion` int(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones o Cuotas (de Capital)\\n',
  `MontoCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto de la Cuota\n',
  `FechTraspasVenc` date DEFAULT NULL COMMENT 'Fecha de Traspaso a Vencido, nace con fecha vacia\n',
  `FechTerminacion` date DEFAULT NULL COMMENT 'Fecha de Pago del Credito, nace con fecha vacia\n',
  `IVAInteres` decimal(12,2) DEFAULT NULL COMMENT 'Tasa de Iva a Cobrar por los Intereses, o Cero si es Exento\n',
  `IVAComisiones` decimal(12,2) DEFAULT NULL COMMENT 'Tasa de Iva a Cobrar por las Comisiones, o Cero si es Exento\n',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus del Credito, no se pide en el alta. Nace inactivo\nI .- Inactivo\nA.- Autorizado\nV.- Vigente\nP .- Pagado\nC .- Cancelado\nB.- Vencido\nK.- Castigado\nS.-Suspendido',
  `FechaAutoriza` date DEFAULT NULL COMMENT 'Fecha de \nAutorizacion o \nLiberacion',
  `UsuarioAutoriza` int(11) DEFAULT NULL COMMENT 'Usuairo que autoriza\nel Credito',
  `SaldoCapVigent` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vigente, en el alta nace con ceros\n',
  `SaldoCapAtrasad` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Atrasado, en el alta nace con ceros\n',
  `SaldoCapVencido` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido, en el alta nace con ceros\n',
  `SaldCapVenNoExi` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido no Exigible, en el alta nace con ceros\n',
  `SaldoInterOrdin` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Ordinario, en el alta nace con ceros\n',
  `SaldoInterAtras` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Atrasado, en el alta nace con ceros\n',
  `SaldoInterVenc` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Vencido, en el alta nace con ceros\n',
  `SaldoInterProvi` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de Provision, en el alta nace con ceros\n',
  `SaldoIntNoConta` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de Interes\nNo Contabilizado',
  `SaldoIVAInteres` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Iva Interes, en el alta nace con ceros\n',
  `SaldoMoratorios` decimal(14,2) DEFAULT NULL COMMENT 'Saldo Moratorios, en el alta nace con ceros\n',
  `SaldoIVAMorator` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Iva Mora, en el alta nace con ceros\n',
  `SaldComFaltPago` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Comision Falta Pago, en el alta nace con ceros\n',
  `SalIVAComFalPag` decimal(12,2) DEFAULT NULL COMMENT 'Saldo IVA Com Falta Pago, en el alta nace con ceros\n',
  `SaldoComServGar` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Comision por Servicio de Garantia Agro',
  `SaldoIVAComSerGar` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Iva Comision por Servicio de Garantia Agro',
  `SaldoOtrasComis` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Otras Comisiones, en el alta nace con ceros\n',
  `SaldoIVAComisi` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Iva Otras Com, en el alta nace con ceros\n',
  `ProvisionAcum` decimal(14,4) DEFAULT NULL COMMENT 'Provision\nAcumulada ',
  `PagareImpreso` char(1) DEFAULT NULL COMMENT 'Pagaré impreso\nN=No,S=Si',
  `FechaInhabil` char(1) DEFAULT NULL COMMENT 'En Fecha Inhabil Tomar:\nS.- Siguiente\nA.- Anterior\n',
  `CalendIrregular` char(1) DEFAULT NULL COMMENT 'Calendario Irregular\nS.- Si\nN.-No\n',
  `DiaPagoInteres` char(1) DEFAULT NULL COMMENT 'Dia de Pago Interes\nF.-Pago  final del mes \nA.- Por aniversario\nD.- Dia del mes\nI.- Indistinto\n',
  `DiaPagoCapital` char(1) DEFAULT NULL COMMENT 'Dia de Pago Capital\nF.-Pago  final del mes \nA.- Por aniversario\nD.- Dia del mes\nI.- Indistinto\n\n',
  `DiaPagoProd` char(1) DEFAULT NULL COMMENT 'Dia de pago de capital del producto de credito: F=fin de mes, D=dia \ndel mes, A=aniversario, I=indistinto',
  `DiaMesInteres` int(11) DEFAULT NULL COMMENT 'Dia del Mes interes',
  `DiaMesCapital` int(11) DEFAULT NULL COMMENT 'Dia del Mes capital\n',
  `AjusFecUlVenAmo` char(1) DEFAULT NULL COMMENT 'Ajustar la fecha de vencimiento de la ultima \namortizacion a fecha de vencimiento de credito\nS.- Si\nN.- No',
  `AjusFecExiVen` char(1) DEFAULT NULL COMMENT 'Ajustar Fecha de exigibilidad a fecha de vencimiento\nS.- Si\nN.- No\n',
  `NumTransacSim` bigint(20) DEFAULT NULL COMMENT 'Numero de transaccion en el simulador de amortizaciones\n',
  `FechaMinistrado` date DEFAULT NULL COMMENT 'Fecha de ministración\ndel credito',
  `FolioDispersion` int(11) DEFAULT NULL,
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Sucursal donde se dio de alta el credito',
  `ValorCAT` decimal(12,4) DEFAULT '0.0000' COMMENT 'Valor del CAT (Costo Anual Total)',
  `ClasifRegID` int(11) DEFAULT NULL COMMENT 'Clasificacion Segun Reportes Regulatorios',
  `MontoComApert` decimal(12,2) DEFAULT NULL COMMENT 'Monto de comision por apertura',
  `IVAComApertura` decimal(12,2) DEFAULT NULL COMMENT 'IVA de la comision por apertura',
  `PlazoID` varchar(20) DEFAULT NULL COMMENT 'Plazo del credito\\n',
  `TipoDispersion` char(1) DEFAULT NULL COMMENT 'Tipo de Dispersion\\n	S .- SPEI\\n	C .- Cheque\\n	O .- Orden de Pago\\n	E.- Efectivo',
  `CuentaCLABE` char(18) DEFAULT NULL,
  `TipoCalInteres` int(11) DEFAULT NULL COMMENT '1 .- Saldos Insolutos\n2 .- Monto Original (Saldos Globales)',
  `TipoGeneraInteres` char(1) NOT NULL COMMENT 'Tipo de Monto Original (Saldos Globales): \n"I".- Iguales \n"D".- Dias Transcurridos',
  `MontoDesemb` decimal(14,2) DEFAULT NULL COMMENT 'Monto del Credito que ya ha sido Desembolsado o Ministrado',
  `MontoPorDesemb` decimal(14,2) DEFAULT NULL COMMENT 'Monto del Credito Pendiente de Desembolso o Ministracion',
  `NumAmortInteres` int(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones (cuotas) de Interes',
  `AporteCliente` decimal(12,2) DEFAULT NULL COMMENT 'Aporte del Cliente de la \nGarantia Liquida',
  `PorcGarLiq` decimal(12,2) DEFAULT NULL COMMENT 'Especifica el porcentaje  de garantia liquida',
  `MontoSeguroVida` decimal(12,2) DEFAULT NULL COMMENT 'Monto del Seguro de Vida',
  `SeguroVidaPagado` decimal(12,2) DEFAULT NULL COMMENT 'Monto que el cliente ya ha pagado del Seguro de Vida',
  `ForCobroSegVida` char(1) DEFAULT NULL COMMENT 'A: Anticipado, D: Deduccion, F: Financiamiento',
  `ComAperPagado` decimal(12,2) DEFAULT NULL COMMENT 'Comision por Apertura Ya pagada por el Cliente',
  `ForCobroComAper` char(1) DEFAULT NULL COMMENT 'Forma de cobro de comision por apertura.\nA: Anticipado \nD: Deduccion\nF: Financiamiento\nP: Programado',
  `ClasiDestinCred` char(1) DEFAULT NULL,
  `CicloGrupo` int(11) DEFAULT NULL COMMENT 'Ciclo del Grupo, en Caso de un Credito Grupal',
  `GrupoID` int(11) DEFAULT NULL COMMENT 'Numero o ID del Grupo, en caso de ser un Credito Grupal',
  `TipoPrepago` char(1) DEFAULT NULL COMMENT 'Tipo de prepago a aplicar\nU-Pago de capital a ultimas cuotas\nI-A las cuotas siguientes inmediatas\nV-Prorrateo de pago en cuotas vivas\nP-Pago Cuotas Completas Proyectadas',
  `SaldoMoraVencido` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Interes Moratorio en atraso o vencido',
  `SaldoMoraCarVen` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Moratorios deirvado de cartera vencida, en ctas de orden',
  `DescuentoSeguro` decimal(12,2) DEFAULT NULL COMMENT 'Monto de seguro de vida con descuento',
  `MontoSegOriginal` decimal(12,2) DEFAULT NULL COMMENT 'Monto de seguro de vida original',
  `IdenCreditoCNBV` varchar(29) DEFAULT NULL COMMENT 'Identificador del Credito Utilizando Metodologia CNBV',
  `CobraSeguroCuota` char(1) DEFAULT NULL COMMENT 'Valida si el producto cobra seguro por cuota, este campo es del producto\n',
  `CobraIVASeguroCuota` char(1) DEFAULT NULL COMMENT 'Valida si el producto cobra IVA seguro por cuota, este campo es del producto',
  `MontoSeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto por Cuota para el pago del seguro por cuota.',
  `IVASeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'IVA para el monto por seguro por cuota',
  `CobraComAnual` varchar(1) DEFAULT NULL COMMENT 'Cobra Comision S:Si N:No',
  `TipoComAnual` varchar(1) DEFAULT NULL COMMENT 'Tipo de Comision P:Porcentaje M:Monto',
  `BaseCalculoComAnual` varchar(1) DEFAULT NULL COMMENT 'Base del Cálculo M:Monto del crédito Original S:Saldo Insoluto',
  `MontoComAnual` decimal(14,2) DEFAULT NULL COMMENT 'Monto de la Comision en caso de que el tipo de comision sea M',
  `PorcentajeComAnual` decimal(14,4) DEFAULT NULL COMMENT 'Porcentaje de la comision en caso de que el tipo de comision sea P',
  `DiasGraciaComAnual` int(11) DEFAULT NULL COMMENT 'Dias de gracia que se dan antes de cobrar la comisión',
  `SaldoComAnual` decimal(14,2) DEFAULT '0.00' COMMENT 'Saldo Comision Anual',
  `TipoLiquidacion` char(1) DEFAULT 'T' COMMENT 'Tipo de Liquidacion para una Renovacion de Credito\nT: Total\nP: Parcial',
  `CantidadPagar` decimal(12,2) DEFAULT '0.00' COMMENT 'Cantidad a Pagar en una Renovacion de Credito',
  `ComAperCont` decimal(14,2) DEFAULT '0.00' COMMENT 'Monto de la Comisión por Apertura Contabilizada',
  `IVAComAperCont` decimal(14,2) DEFAULT '0.00' COMMENT 'Monto del IVA de la Comision por Apertura Contabilizada',
  `ComAperReest` decimal(14,2) DEFAULT '0.00' COMMENT 'Nuevo Monto a Contabilizar cuando se hace una Reestructura',
  `IVAComAperReest` decimal(14,2) DEFAULT '0.00' COMMENT ' Monto del IVA de la Comision por Apertura a Contabilizar cuando se hace una Reestructura',
  `FechaAtrasoCapital` date DEFAULT '1900-01-01' COMMENT 'Fecha de Atraso de Capital',
  `FechaAtrasoInteres` date DEFAULT '1900-01-01' COMMENT 'Fecha de Atraso de Interes',
  `TipoConsultaSIC` char(2) DEFAULT NULL COMMENT 'Se indica BC si la Consulta se realizó a Buró de Crédito o CC si se realizó a  Círculo de Crédito',
  `FolioConsultaBC` varchar(30) DEFAULT NULL COMMENT 'Folio de consulta de Buro de Credito',
  `FolioConsultaCC` varchar(30) DEFAULT NULL COMMENT 'Folio de consulta de Circulo de Credito',
  `EsAgropecuario` char(1) DEFAULT 'N' COMMENT 'Indica si el credito es de tipo Agropecuario. Se hereda desde el Producto de Credito/Solicitud de Credito.',
  `TipoCancelacion` char(1) DEFAULT 'U' COMMENT 'Tipo de cancelación a aplicar. Se hereda del producto de crédito.\nU.- Últimas cuotas.\nI.- Cuotas siguientes inmediatas.\nV.- Prorrateo en cuotas vivas.',
  `Refinancia` char(1) DEFAULT 'N' COMMENT 'Indica si los intereses serán refinanciados\nS: Si\nN: N',
  `CadenaProductivaID` int(11) DEFAULT NULL COMMENT 'ID del Catalogo CATCADENAPRODUCTIVA',
  `RamaFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la Tabla CATRAMAFIRA',
  `SubramaFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la tabla CATSUBRAMAFIRA',
  `ActividadFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la Tabla CATACTIVIDADESFIRA',
  `TipoGarantiaFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la Tabla CATTIPOGARANTIAFIRA',
  `EstatusGarantiaFIRA` char(1) DEFAULT NULL COMMENT 'Determina el estatus de la contratación de garantias Fega y Fonaga, para creditos fondeados con FIRA el Estatus es automatico como procesado.\nI  : Inactivo\nA : Autorizado\nC : Cancelado \n',
  `ProgEspecialFIRAID` varchar(10) DEFAULT NULL COMMENT 'ID de la TABLA CATFIRAPROGESP',
  `FechaCobroComision` date DEFAULT '1900-01-01' COMMENT 'Fecha de Cobro de la comision cuando la forma del cobro sea programada',
  `EsAutomatico` char(1) DEFAULT 'N' COMMENT 'Indica si el credito es Automatico\nS: Si\nN: No',
  `TipoAutomatico` char(1) DEFAULT '' COMMENT 'Indica si el credito es automatico sobre.\nA: Ahorro\nI: Inversion',
  `InvCredAut` int(11) DEFAULT '0' COMMENT 'Inversion relacionada al Credito Automatico',
  `CtaCredAut` bigint(12) DEFAULT '0' COMMENT 'Cuenta de Ahorro relacionada al Credito Automatico',
  `AcreditadoIDFIRA` bigint(20) DEFAULT NULL COMMENT 'Numero de Acreditado FIRA',
  `CreditoIDFIRA` bigint(20) DEFAULT NULL COMMENT 'Numero de Credito FIRA',
  `InteresAcumulado` decimal(14,2) DEFAULT '0.00' COMMENT 'Guarda el interes acumulado en cada mes. Utilizado para el refinanciamiento de creditos agro.',
  `InteresRefinanciar` decimal(14,2) DEFAULT '0.00' COMMENT 'Guarda el interes a refinanciar en cada mes utilizado en la base de calculo para intereses ordinarios en creditos agropecuarios',
  `Reacreditado` char(1) DEFAULT 'N' COMMENT 'Indica si un Crédito esta Reacreditado',
  `TipoComXApertura` char(1) DEFAULT '' COMMENT 'Tipo de Comision por apertura',
  `MontoComXApertura` decimal(14,2) DEFAULT '0.00' COMMENT 'Monto de Comision por Apertura',
  `DiasAtrasoMin` int(11) DEFAULT NULL COMMENT 'Número de Dias de Atraso Minimo para el proceso de Castigo',
  `ReferenciaPago` varchar(20) DEFAULT NULL COMMENT 'Refencia de Pago (Para el proceso de Pago Refenreciado)',
  `NivelID` int(11) DEFAULT '0' COMMENT 'Nivel, corresponde al catálogo NIVELCREDITO.',
  `CobraAccesorios` char(1) DEFAULT 'N' COMMENT 'Indica si el credito cobra accesorios',
  `EstatusInstalacion` char(1) DEFAULT 'N' COMMENT 'Indica si un credito de Nomina ya fue instalado.\nI: Instalado\nN: No Instalado',
  `FolioInstalacion` varchar(25) DEFAULT '' COMMENT 'Folio de instalacion de Creditos de Nomina que se actualiza mediante un WS',
  `AprobadoInfoComercial` char(1) NOT NULL DEFAULT 'N' COMMENT 'campo para guardar la aprobacion del cliente para que sus datos personales puedan utilizarse como mercadeo',
  `ClabeCtaDomici` varchar(20) DEFAULT NULL COMMENT 'Cuenta CLABE para domiciliacion',
  `MontoClienteCartas` decimal(14,2) DEFAULT '0.00' COMMENT 'Monto a Favor del Cliente a Dispersar cuando presenta Cartas de Liquidacion',
  `AplicaDescServicio` char(1) DEFAULT NULL COMMENT 'Indica si el crédito tiene servicios adicionales',
  `EsConsolidado` char(1) NOT NULL DEFAULT 'N' COMMENT 'Indica si la solicitud proviene de una consolidacion. S.- Si, N.- No',
  `FlujoOrigen` char(1) NOT NULL DEFAULT '' COMMENT 'Indica el flujo por el que nace la solicitu de credito C.- Flujo Consolidacion',
  `ConvenioNominaID` bigint(20) unsigned DEFAULT NULL COMMENT 'Convenio de Nómina',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `InstitNominaID` int(11) DEFAULT NULL COMMENT 'ID de Instituto de nomina',
  `EtiquetaFondeo` char(1) DEFAULT 'N' COMMENT 'Estatus del Fondeo, nace como No Enviado \nN = No enviado \nE = Envio de cartera etiquetado \nC = Cedido',
  `FechaEtiqueta` date DEFAULT '1900-01-01' COMMENT 'Fecha en la que el credito fue marcado como Etiquetado a una Institucion de Fondeo (Nace con fecha vacia).',
  `EtiquetaAFM` char(1) DEFAULT NULL COMMENT 'Etiqueta del Administrador del Fideicomiso Maestro, N = No enviado \nE = Envio de cartera etiquetado',
  `FecEtiquetaAFM` date DEFAULT NULL COMMENT 'Fecha en que se asigno la Etiqueta del Administrador del Fideicomiso Maestro',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`CreditoID`),
  KEY `fk_CREDITOSVTA_ClienteID` (`ClienteID`),
  KEY `fk_CREDITOSVTA_CuentaID` (`CuentaID`),
  KEY `fk_CREDITOSVTA_CREDITOS_1` (`MonedaID`),
  KEY `fk_CREDITOSVTA_InstitFodeo` (`InstitFondeoID`),
  KEY `fk_CREDITOSVTA_LineaFondeo` (`LineaFondeo`),
  KEY `fk_CREDITOSVTA_CREDITOS_2` (`ProductoCreditoID`),
  KEY `fk_CREDITOSVTA_CREDITOS_3` (`DestinoCreID`),
  KEY `fk_CREDITOSVTA_CalculoInteres` (`CalcInteresID`),
  KEY `fk_CREDITOSVTA_LineasCredID` (`LineaCreditoID`),
  KEY `fk_CREDITOSVTA_CREDITOS_4` (`SolicitudCreditoID`),
  KEY `fk_CREDITOSVTA_CREDITOS_5` (`FechaMinistrado`,`Estatus`),
  KEY `idx_CREDITOSVTA_CREDITOS_1` (`ClienteID`,`Estatus`),
  KEY `IDX_CREDITOSVTA_CREDITOS_2` (`AcreditadoIDFIRA`),
  KEY `IDX_CREDITOSVTA_CREDITOS_3` (`CreditoIDFIRA`),
  KEY `IDX_CREDITOSVTA_CREDITOS_5` (`ReferenciaPago`),
  CONSTRAINT `fk_CREDITOSVTA_CREDITOS_1` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_CREDITOSVTA_CREDITOS_2` FOREIGN KEY (`ProductoCreditoID`) REFERENCES `PRODUCTOSCREDITO` (`ProducCreditoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITOSVTA_CREDITOS_3` FOREIGN KEY (`DestinoCreID`) REFERENCES `DESTINOSCREDITO` (`DestinoCreID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITOSVTA_CalculoInteres` FOREIGN KEY (`CalcInteresID`) REFERENCES `FORMTIPOCALINT` (`FormInteresID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_CREDITOSVTA_ClienteID` FOREIGN KEY (`ClienteID`) REFERENCES `CLIENTES` (`ClienteID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_CREDITOSVTA_CuentaID` FOREIGN KEY (`CuentaID`) REFERENCES `CUENTASAHO` (`CuentaAhoID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_CREDITOSVTA_CREDITOS_4` FOREIGN KEY (`SolicitudCreditoID`) REFERENCES `SOLICITUDCREDITO` (`SolicitudCreditoID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='RESPALDO Tabla de Creditos en venta de cartera\n';$$
