-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- CREDITOFONDEO
DELIMITER ;
DROP TABLE IF EXISTS `CREDITOFONDEO`;DELIMITER $$

CREATE TABLE `CREDITOFONDEO` (
  `CreditoFondeoID` bigint(20) NOT NULL COMMENT 'Numero o ID de Fondeo, consecutivo',
  `LineaFondeoID` int(11) DEFAULT NULL COMMENT 'Linea de Fondeo, corresponde con la tabla LINEAFONDEADOR',
  `InstitutFondID` int(11) DEFAULT NULL COMMENT 'id de institucion de fondeo corresponde con la tabla INSTITUTFONDEO',
  `Folio` varchar(150) DEFAULT NULL COMMENT 'Folio del Fondeo corresponde con lo que da la inst de fondeo.',
  `TipoCalInteres` int(11) DEFAULT NULL COMMENT '1 .- Saldos Insolutos\n2 .- Monto Original (Saldos Globales)',
  `CalcInteresID` int(11) DEFAULT NULL COMMENT 'Formula para el calculo de Interes',
  `TasaBase` int(11) DEFAULT NULL COMMENT 'Tasa Base, necesario dependiendo de la Formula',
  `SobreTasa` decimal(12,4) DEFAULT NULL COMMENT 'Si es formula dos (Tasa base mas puntos), aqui se definen\n Los puntos',
  `TasaFija` decimal(12,4) DEFAULT NULL COMMENT 'Si es formula uno (Tasa Fija), aqui se especifica el valor de dicha\ntasa fija',
  `PisoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Piso, Si es formula tres',
  `TechoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Techo, Si es formula tres',
  `FactorMora` decimal(12,4) DEFAULT NULL COMMENT 'Factor de Moratorio',
  `Monto` decimal(14,2) DEFAULT NULL COMMENT 'Monto del credito de  Fondeo',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Moneda',
  `PlazoContable` char(1) DEFAULT NULL COMMENT 'Indica el Plazo Contable . C.- Corto Plazo L.- Largo Plazo',
  `FechaContable` date DEFAULT NULL COMMENT 'Fecha En la que se empiezan los movimientos Contables, corresponde con la fecha del sistema.',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio',
  `FechaVencimien` date DEFAULT NULL COMMENT 'Fecha de Vencimiento',
  `FechaTerminaci` date DEFAULT NULL COMMENT 'Fecha de pago del credito, nace con fecha vacia o nula',
  `Estatus` char(1) NOT NULL COMMENT 'Estatus del Fondeo	\nN .- Vigente o en Proceso\nP .- Pagada\nNace con estatus Vigente (N)',
  `SaldoCapVigente` decimal(14,4) DEFAULT NULL COMMENT 'Saldo\nde Capital\nVigente',
  `SaldoCapAtrasad` decimal(14,4) DEFAULT NULL COMMENT 'Saldo\nde Capital\nen Atraso',
  `SaldoInteresAtra` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de Interes Exigible o en atraso',
  `SaldoInteresPro` decimal(14,4) DEFAULT NULL COMMENT 'Saldo\nde Interes',
  `SaldoIVAInteres` decimal(14,4) DEFAULT NULL COMMENT 'Saldo IVA Interes, en el alta nace con ceros',
  `SaldoMoratorios` decimal(14,4) DEFAULT NULL COMMENT 'Saldo Moratorio',
  `SaldoIVAMora` decimal(14,4) DEFAULT NULL COMMENT 'SaldoIvaMoratorio',
  `SaldoComFaltaPa` decimal(14,4) DEFAULT NULL COMMENT 'Saldo Comision por Falta de Pago',
  `SaldoIVAComFalP` decimal(14,4) DEFAULT NULL COMMENT 'Saldo Iva comision Falta Pago',
  `SaldoOtrasComis` varchar(45) DEFAULT NULL COMMENT 'Saldo Otras Comisiones, en el alta nace con ceros',
  `SaldoIVAComisi` varchar(45) DEFAULT NULL COMMENT 'Saldo IVA Otras Com, en el alta nace con ceros',
  `SaldoRetencion` decimal(12,2) DEFAULT NULL,
  `ProvisionAcum` decimal(14,4) DEFAULT NULL COMMENT 'Provision\nAcumulada ',
  `TipoPagoCapital` char(1) DEFAULT NULL COMMENT 'Tipo de Pago de Capital\nC .-Crecientes\nI .- Iguales\nL .-Libres',
  `FrecuenciaCap` char(1) DEFAULT NULL COMMENT 'Frecuencia de Pago de las Amortizaciones de Capital\nS .- Semanal,\nC .- Catorcenal\nQ .- Quincenal\nM .- Mensual\nP .- Periodo\nB.-Bimestral \nT.-Trimestral \nR.-TetraMestral\nE.-Semestral \nA.-Anual',
  `PeriodicidadCap` int(11) DEFAULT NULL COMMENT 'Periodicidad de Capital en dias',
  `NumAmortizacion` int(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones o Cuotas (de Capital)\\n',
  `FrecuenciaInt` char(1) DEFAULT NULL COMMENT 'Frecuencia de Interes\nS .- Semanal,\nC .- Catorcenal\nQ .- Quincenal\nM .- Mensual\nP .- Periodo\nB.-Bimestral \nT.-Trimestral \nR.-TetraMestral\nE.-Semestral \nA.-Anual',
  `PeriodicidadInt` int(11) DEFAULT NULL COMMENT 'Periodicidad de Interes en dias',
  `NumAmortInteres` int(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones (cuotas) de Interes',
  `MontoCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto de la Cuota\n',
  `FechaInhabil` char(1) DEFAULT NULL COMMENT 'Fecha Inhabil: S.-Siguiente  A.-Anterior',
  `CalendIrregular` char(1) DEFAULT NULL COMMENT 'Calendario Irregular S.- Si N.-No',
  `DiaPagoInteres` char(1) DEFAULT NULL COMMENT 'Día de pago Interes \\nF-Pago Final de mes\\nA-Por aniversario',
  `DiaPagoCapital` char(1) DEFAULT NULL COMMENT 'Dia de pago  Capital F.-Pago final del mes A.-Por aniversario',
  `DiaMesInteres` int(11) DEFAULT NULL COMMENT 'Día del mes interés	',
  `DiaMesCapital` int(11) DEFAULT NULL COMMENT 'Día del mes Capital',
  `AjusFecUlVenAmo` char(1) DEFAULT NULL COMMENT 'Ajustar la fecha de vencimiento de la ultima amortizacion a fecha de vencimiento\nde credito S.-Si  N.-No',
  `AjusFecExiVen` char(1) DEFAULT NULL COMMENT 'Ajustar Fecha de exigibilidad a fecha de vencimiento\nS.-Si  N.-No',
  `NumTransacSim` bigint(20) DEFAULT NULL COMMENT 'Numero de transacción en el simulador de Amortizaciones',
  `PlazoID` varchar(20) DEFAULT NULL COMMENT 'Plazo del credito\nCorresponde con la tabla CREDITOSPLAZOS',
  `PagaIva` char(1) DEFAULT NULL COMMENT 'Indica si paga o no iva',
  `PorcentanjeIVA` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje de iva',
  `MargenPagIgual` decimal(12,2) DEFAULT NULL COMMENT 'Margen de pagos iguales para cuotas de pago de capital creciente',
  `InstitucionID` int(11) NOT NULL COMMENT 'Corresponde con la Institucion del Banco (INSTITUCIONES)',
  `CuentaClabe` char(18) NOT NULL COMMENT 'Cuenta Clabe. CUENTASAHOTESO.',
  `NumCtaInstit` varchar(20) NOT NULL COMMENT 'Numero de Cuenta de Institucion. CUENTASAHOTESO.',
  `TipoInstitID` int(11) NOT NULL COMMENT 'Corresponde con el campo TipoInstitID de la tabla TIPOSINSTITUCION ',
  `NacionalidadIns` char(1) DEFAULT NULL COMMENT 'Especifica la nacionalidad de la institucion, corresponde con la tabla SUBCTANACINSFON',
  `ComDispos` decimal(12,2) DEFAULT NULL COMMENT 'Comision Por Disposicion(No requerido)',
  `IvaComDispos` decimal(12,2) DEFAULT NULL COMMENT 'Comision Por Disposicion(No requerido)',
  `CobraISR` char(1) DEFAULT NULL COMMENT 'Indica si cobra o no ISR \nS = SI\nN = NO',
  `TasaISR` decimal(12,2) DEFAULT NULL COMMENT 'Tasa ISR ',
  `MargenPriCuota` int(11) DEFAULT NULL COMMENT 'Margen para generar la primer cuota ',
  `CapitalizaInteres` char(1) DEFAULT NULL COMMENT 'Indica si el Credito Pasivo, capitaliza Intereses o no\nS .- Si\nN .- No',
  `TipoFondeador` char(1) DEFAULT NULL COMMENT 'Indica el tipo de Fondeador INVERSIONISTA/FONDEADOR',
  `PagosParciales` char(1) DEFAULT NULL COMMENT 'Indica si el pago es parcial o no SI/NO',
  `EsAgropecuario` char(1) DEFAULT 'N' COMMENT 'Indica si el credito es de tipo Agropecuario. Se hereda desde el Credito Activo.',
  `TipoCancelacion` char(1) DEFAULT 'U' COMMENT 'Tipo de cancelación a aplicar. Se hereda desde el Credito Activo.\nU.- Últimas cuotas.\nI.- Cuotas siguientes inmediatas.\nV.- Prorrateo en cuotas vivas.',
  `Refinancia` char(1) DEFAULT 'N' COMMENT 'Indica si los intereses serán refinanciados\nS: Si\nN: N',
  `EsContingente` char(1) DEFAULT 'N' COMMENT 'Indica si el credito es de tipo Contingente.',
  `TipoGarantiaFIRAID` int(11) DEFAULT '0' COMMENT 'ID de garantia Fira Aplicada en creacion de creditos contingentes',
  `TipoCredito` char(1) DEFAULT 'N' COMMENT 'Tipo de Credito de Fondeo\nN: Nuevo\nR: Reestructura',
  `InteresAcumulado` decimal(14,2) DEFAULT '0.00' COMMENT 'Guarda el interes acumulado en cada mes. Utilizado para el refinanciamiento de creditos agro.',
  `InteresRefinanciar` decimal(14,2) DEFAULT '0.00' COMMENT 'Guarda el interes a refinanciar utilizado en la base de calculo para intereses ordinarios en creditos agropecuarios',
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` date DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CreditoFondeoID`),
  KEY `fk_CREDITOFONDEO_1` (`LineaFondeoID`),
  KEY `fk_CREDITOFONDEO_2` (`InstitutFondID`),
  KEY `INDEX_MONEDA` (`MonedaID`),
  KEY `fk_CREDITOFONDEO_3_idx` (`InstitucionID`,`NumCtaInstit`),
  KEY `fk_CREDITOFONDEO_5_idx` (`PlazoID`),
  CONSTRAINT `fk_CREDITOFONDEO_1` FOREIGN KEY (`LineaFondeoID`) REFERENCES `LINEAFONDEADOR` (`LineaFondeoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITOFONDEO_2` FOREIGN KEY (`InstitutFondID`) REFERENCES `INSTITUTFONDEO` (`InstitutFondID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITOFONDEO_3` FOREIGN KEY (`InstitucionID`, `NumCtaInstit`) REFERENCES `CUENTASAHOTESO` (`InstitucionID`, `NumCtaInstit`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITOFONDEO_4` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREDITOFONDEO_5` FOREIGN KEY (`PlazoID`) REFERENCES `CREDITOSPLAZOS` (`PlazoID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla de Fondeos de Credito'$$