-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- CRWFONDEO
DELIMITER ;
DROP TABLE IF EXISTS `CRWFONDEO`;

DELIMITER $$
CREATE TABLE `CRWFONDEO` (
  `SolFondeoID` bigint(20) NOT NULL COMMENT 'Numero o ID del Fondeo, no es el id de la solicitud de fondeo',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero o ID del Cliente',
  `CreditoID` bigint(12) DEFAULT NULL COMMENT 'Numero de Credito',
  `CuentaAhoID` bigint(12) DEFAULT NULL COMMENT 'Cuenta de \nAhorro del \nCliente o \nInversionista',
  `SolicitudCreditoID` bigint(20) DEFAULT NULL COMMENT 'Numero de Solicitud',
  `Consecutivo` bigint(20) DEFAULT NULL COMMENT 'Numero Consecutivo de Fondeo por Solicitud\n',
  `Folio` varchar(20) DEFAULT NULL COMMENT 'Folio del Fondeo\nNumero de\nCredito + \nConsecutivo,\nconvertidos a\n Char',
  `CalcInteresID` int(11) DEFAULT NULL COMMENT 'Formula para el calculo de Interes',
  `TasaBaseID` int(11) DEFAULT NULL COMMENT 'Tasa Base, necesario dependiendo de la Formula',
  `SobreTasa` decimal(12,4) DEFAULT NULL COMMENT 'Si es formula dos (Tasa base mas puntos), aqui se definen\n Los puntos',
  `TasaFija` decimal(12,4) DEFAULT NULL COMMENT 'Si es formula uno (Tasa Fija), aqui se especifica el valor de dicha\ntasa fija',
  `PisoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Piso, Si es formula tres',
  `TechoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Techo, Si es formula tres',
  `MontoFondeo` decimal(14,2) DEFAULT NULL COMMENT 'Monto del Fondeo',
  `PorcentajeFondeo` decimal(10,6) DEFAULT NULL COMMENT 'Porcentaje del Fondeo',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Moneda',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio',
  `FechaVencimiento` date DEFAULT NULL COMMENT 'Fecha de Vencimiento',
  `TipoFondeo` int(11) NOT NULL COMMENT 'Tipo de FondeoID',
  `NumCuotas` int(11) DEFAULT NULL COMMENT 'Numero de Cuotas o Amortizaciones de Fondeo',
  `NumRetirosMes` int(11) DEFAULT NULL COMMENT 'Numero de \nRetiros en el\nMes',
  `PorcentajeMora` decimal(8,4) DEFAULT NULL COMMENT 'Porcentaje de Participacion en la Mora',
  `PorcentajeComisi` decimal(8,4) DEFAULT NULL COMMENT 'Porcentaje de Participacion en Comisiones',
  `Estatus` char(1) NOT NULL COMMENT 'Estatus del Fondeo	\nN .- Vigente o en Proceso\nP .- Pagada\nV .- Vencida',
  `SaldoCapVigente` decimal(14,2) DEFAULT NULL COMMENT 'Saldo\nde Capital\nVigente',
  `SaldoCapExigible` decimal(14,2) DEFAULT NULL COMMENT 'Saldo\nde Capital\nExigible o\nen Atraso',
  `SaldoInteres` decimal(14,4) DEFAULT NULL COMMENT 'Saldo\nde Interes',
  `SaldoIntMoratorio` decimal(14,4) DEFAULT NULL COMMENT 'Saldo de interes Moratorio, este saldo se registra en cuentas de orden',
  `SaldoCapCtaOrden` decimal(14,4) DEFAULT NULL COMMENT 'Capital que se encuentra en las cuentas de orden(capital que se uso para aplicar la garantia del credito)',
  `SaldoIntCtaOrden` decimal(14,4) DEFAULT NULL COMMENT 'interes que se encuentra en cuentas de Orden(interes que se uso para aplicar la garantia al credito)',
  `ProvisionAcum` decimal(14,4) DEFAULT NULL COMMENT 'Provision\nAcumulada ',
  `MoratorioPagado` decimal(12,2) DEFAULT NULL COMMENT 'Acumulado de \nMoratorios\nPagados al\nInversionista',
  `ComFalPagPagada` decimal(12,2) DEFAULT NULL COMMENT 'Acumulado de \nComision por Falta de Pago\nPagados al\nInversionista',
  `IntOrdRetenido` decimal(14,4) DEFAULT NULL COMMENT 'Acumulado de \nInteres Ordinario\nRetenido\nal Inversionista',
  `IntMorRetenido` decimal(12,4) DEFAULT NULL COMMENT 'Acumulado de \nInteres Moratorio\nRetenido\nal Inversionista',
  `ComFalPagRetenido` decimal(12,4) DEFAULT NULL COMMENT 'Acumulado de \nComisio Falta Pago\nRetenido\nal Inversionista',
  `Gat` decimal(12,2) DEFAULT NULL COMMENT 'Calculo GAT',
  `ValorGatReal` decimal(12,2) DEFAULT NULL COMMENT 'Valor Gat real.',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoría.',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoría.',
  `FechaActual` date DEFAULT NULL COMMENT 'Campo de Auditoría.',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Campo de Auditoría.',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoría.',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoría.',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoría.',
  PRIMARY KEY (`SolFondeoID`),
  KEY `INDEX_CRWFONDEO_1` (`CreditoID`),
  KEY `INDEX_CRWFONDEO_2` (`SolicitudCreditoID`),
  KEY `INDEX_CRWFONDEO_3` (`ClienteID`,`CuentaAhoID`,`Estatus`) USING BTREE,
  KEY `INDEX_CRWFONDEO_4` (`FechaInicio`) USING BTREE,
  KEY `INDEX_CRWFONDEO_5` (`CuentaAhoID`,`Estatus`),
  KEY `INDEX_CRWFONDEO_6` (`CuentaAhoID`,`FechaInicio`,`Estatus`) USING BTREE,
  KEY `INDEX_CRWFONDEO_7` (`NumTransaccion`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tab: Fondeos de Crédito (Crowdfunding).'
PARTITION BY RANGE (SolFondeoID)
(PARTITION part0 VALUES LESS THAN (300000) ENGINE = InnoDB,
 PARTITION part1 VALUES LESS THAN (600000) ENGINE = InnoDB,
 PARTITION part2 VALUES LESS THAN (900000) ENGINE = InnoDB,
 PARTITION part3 VALUES LESS THAN (1200000) ENGINE = InnoDB,
 PARTITION part4 VALUES LESS THAN (1500000) ENGINE = InnoDB,
 PARTITION part5 VALUES LESS THAN (1800000) ENGINE = InnoDB,
 PARTITION part6 VALUES LESS THAN (2100000) ENGINE = InnoDB,
 PARTITION part7 VALUES LESS THAN (2400000) ENGINE = InnoDB,
 PARTITION part8 VALUES LESS THAN (2700000) ENGINE = InnoDB,
 PARTITION part9 VALUES LESS THAN (3000000) ENGINE = InnoDB,
 PARTITION part10 VALUES LESS THAN (3300000) ENGINE = InnoDB,
 PARTITION part11 VALUES LESS THAN (3600000) ENGINE = InnoDB,
 PARTITION part12 VALUES LESS THAN (3900000) ENGINE = InnoDB,
 PARTITION part13 VALUES LESS THAN (4100000) ENGINE = InnoDB,
 PARTITION part14 VALUES LESS THAN (4400000) ENGINE = InnoDB,
 PARTITION part15 VALUES LESS THAN (4700000) ENGINE = InnoDB,
 PARTITION part16 VALUES LESS THAN (5000000) ENGINE = InnoDB,
 PARTITION part17 VALUES LESS THAN (5300000) ENGINE = InnoDB,
 PARTITION part18 VALUES LESS THAN (5600000) ENGINE = InnoDB,
 PARTITION part19 VALUES LESS THAN MAXVALUE ENGINE = InnoDB) $$
