-- CS_CRCBDESCREDINDGRUPWSPRO
DELIMITER ;
DROP TABLE IF EXISTS CS_CRCBDESCREDINDGRUPWSPRO;

DELIMITER $$
CREATE TABLE `CS_CRCBDESCREDINDGRUPWSPRO` (
  `CrcbDesCredIndGrupWSID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FechaCarga` datetime DEFAULT NULL,
  `FolioCarga` int(11) DEFAULT NULL,
  `CreditoID` bigint(12) DEFAULT '0' COMMENT 'ID del credito',
  `GrupoID` int(11) DEFAULT '0' COMMENT 'ID del grupo',
  PRIMARY KEY (`CrcbDesCredIndGrupWSID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$