-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- CUENTASAHO
DELIMITER ;
DROP TABLE IF EXISTS `CUENTASAHO`;
DELIMITER $$

CREATE TABLE `CUENTASAHO` (
  `CuentaAhoID` bigint(12) NOT NULL,
  `SucursalID` int(11) NOT NULL COMMENT 'Numero de Sucursal',
  `ClienteID` int(11) NOT NULL COMMENT 'Numero de Cliente',
  `Clabe` varchar(18) NOT NULL COMMENT 'Cuenta Clabe',
  `MonedaID` int(11) NOT NULL COMMENT 'Numero de Moneda',
  `Gat` decimal(12,2) DEFAULT NULL COMMENT 'Valor GAT',
  `TipoCuentaID` int(11) NOT NULL COMMENT 'Numero de Tipo de Cuenta',
  `FechaReg` date NOT NULL COMMENT 'Fecha de registro de cuenta',
  `FechaApertura` date DEFAULT NULL COMMENT 'Fecha de apertura de cuenta',
  `UsuarioApeID` int(11) DEFAULT NULL COMMENT 'usuario que autoriza la apertura de cuenta',
  `Etiqueta` varchar(60) DEFAULT NULL COMMENT 'motivo por el que abrio la cuenta',
  `UsuarioCanID` int(11) DEFAULT NULL COMMENT 'usuario que cancela la apertura de cuenta',
  `FechaCan` date DEFAULT NULL COMMENT 'fecha de cancelacion de cuenta',
  `MotivoCan` varchar(100) DEFAULT NULL COMMENT 'motivo de cancelacion de cuenta',
  `MotivoBlo` varchar(100) DEFAULT NULL COMMENT 'Motivo de bloqueo de cuenta',
  `FechaBlo` date DEFAULT NULL COMMENT 'fecha de bloqueo de cuenta',
  `UsuarioBloID` int(11) DEFAULT NULL COMMENT 'Usuario que autoriza el bloqueo de la cuenta',
  `MotivoDesbloq` varchar(100) DEFAULT NULL COMMENT 'motivo de desbloqueo',
  `FechaDesbloq` date DEFAULT NULL COMMENT 'Fecha de desbloqueo',
  `UsuarioDesbID` int(11) DEFAULT NULL COMMENT 'id del usuario que desbloquea la cuenta',
  `Saldo` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Real\n',
  `SaldoDispon` decimal(12,2) DEFAULT NULL,
  `SaldoBloq` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Bloqueado',
  `SaldoSBC` decimal(12,2) DEFAULT NULL COMMENT 'Saldo Buen Cobro\n',
  `SaldoIniMes` decimal(12,2) DEFAULT NULL,
  `CargosMes` decimal(12,2) DEFAULT NULL,
  `AbonosMes` decimal(12,2) DEFAULT NULL,
  `Comisiones` decimal(12,2) DEFAULT NULL,
  `SaldoProm` decimal(12,2) DEFAULT NULL,
  `TasaInteres` decimal(12,2) DEFAULT NULL,
  `InteresesGen` decimal(12,2) DEFAULT NULL,
  `ISR` decimal(12,2) DEFAULT NULL,
  `TasaISR` decimal(12,2) DEFAULT NULL,
  `SaldoIniDia` decimal(12,2) DEFAULT NULL,
  `CargosDia` decimal(12,2) DEFAULT NULL,
  `AbonosDia` decimal(12,2) DEFAULT NULL,
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus de la cta; A - Activa	B - Bloqueada	C - Cancelada I – Inactiva R .- Registrada',
  `EstadoCta` char(1) DEFAULT NULL COMMENT 'Indica a donde sera mandado el estado de cuenta\n“D” Domicilio\n“I” Internet\n“S” Sucursal\n',
  `InstitucionID` int(11) DEFAULT NULL COMMENT 'Indica el ID de la institucion hace referencia a INSTITUCIONES',
  `EsPrincipal` char(1) DEFAULT NULL COMMENT 'Indica si es cuenta Principal \nS - Si\nN - No',
  `GatReal` decimal(12,2) DEFAULT NULL,
  `ISRReal` decimal(12,2) DEFAULT '0.00' COMMENT 'La columna sirver paara acumular el sr Diario por socio solo cuando estee activa esta opcion en  PARAMGENERALES',
  `TelefonoCelular` varchar(20) DEFAULT NULL COMMENT 'Numero de Telefono celular',
  `MontoDepInicial` decimal(21,2) DEFAULT NULL COMMENT 'Monto del Deposito Inicial en la Cuenta de Ahorro',
  `FechaDepInicial` date DEFAULT NULL COMMENT 'Fecha del Deposito inicial de la cuenta',
  `TasaPactada` decimal(14,2) NULL COMMENT 'Tasa Pactada contiene el valor de la tasa originalmente pactado',
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CuentaAhoID`),
  KEY `fk_CUENTASAHO_1` (`SucursalID`),
  KEY `fk_CUENTASAHO_2` (`ClienteID`),
  KEY `fk_CUENTASAHO_3` (`MonedaID`),
  KEY `fk_CUENTASAHO_4` (`TipoCuentaID`),
  KEY `fk_CUENTASAHO_5` (`UsuarioApeID`),
  KEY `fk_CUENTASAHO_6` (`UsuarioCanID`),
  KEY `fk_CUENTASAHO_7` (`UsuarioBloID`),
  KEY `fk_CUENTASAHO_8` (`UsuarioDesbID`),
  KEY `fk_CUENTASAHO_9` (`InstitucionID`),
  CONSTRAINT `fk_CUENTASAHO_1` FOREIGN KEY (`SucursalID`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_2` FOREIGN KEY (`ClienteID`) REFERENCES `CLIENTES` (`ClienteID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_3` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_4` FOREIGN KEY (`TipoCuentaID`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_5` FOREIGN KEY (`UsuarioApeID`) REFERENCES `USUARIOS` (`UsuarioID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_6` FOREIGN KEY (`UsuarioCanID`) REFERENCES `USUARIOS` (`UsuarioID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_7` FOREIGN KEY (`UsuarioBloID`) REFERENCES `USUARIOS` (`UsuarioID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUENTASAHO_8` FOREIGN KEY (`UsuarioDesbID`) REFERENCES `USUARIOS` (`UsuarioID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Cuentas de Ahorro'$$