-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- DIRECTIVOS
DELIMITER ;
DROP TABLE IF EXISTS `DIRECTIVOS`;
DELIMITER $$

CREATE TABLE `DIRECTIVOS` (
	`ClienteID` int(11) NOT NULL COMMENT 'Numero de Cliente',
	`GaranteID` int(11) NOT NULL COMMENT 'Identificador de un Garante',
	`AvalID` int(11) NOT NULL COMMENT 'Identifador para un Aval',
	`DirectivoID` int(12) NOT NULL COMMENT 'Numero de Directivo\n',
	`RelacionadoID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente(Directivo)',
	`GaranteRelacion` int(11) DEFAULT NULL COMMENT 'Referencia para un directivo Garante de tipo personas fisicas',
	`AvalRelacion` int(11) DEFAULT NULL COMMENT 'Referencia para un Aval de personas fisicas ',
	`PersonaID` int(11) DEFAULT '0' COMMENT 'Numero de Persona Relacionada(CUENTASPERSONA)',
	`CargoID` int(11) DEFAULT NULL COMMENT 'Cargo ID (Catalogo de Cargos)',
	`EsApoderado` char(1) DEFAULT NULL COMMENT 'indica si la persona es o no Apoderado	S=Si N=No',
	`ConsejoAdmon` char(1) DEFAULT NULL COMMENT 'Referencia para saber si pertenece al consejo de administracionS = si, N=no',
	`EsAccionista` char(1) DEFAULT NULL COMMENT 'Indica si la persona es Accionista de la empresa.',
	`Titulo` varchar(10) DEFAULT NULL COMMENT 'Titulo del Cliente\nTitulo del Cliente, Ej. Sr., Sra, Srita, Lic, Dr. Ing, Prof.,CP, etc',
	`PrimerNombre` varchar(50) DEFAULT NULL COMMENT 'Primer Nombre de la persona relacionada',
	`SegundoNombre` varchar(50) DEFAULT NULL COMMENT 'Segundo Nombre de la persona',
	`TercerNombre` varchar(50) DEFAULT NULL COMMENT 'Tercer Nombre Del Cliente\n',
	`ApellidoPaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Paterno del Cliente\n',
	`ApellidoMaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Materno del Cliente\n',
	`NombreCompleto` varchar(200) DEFAULT NULL COMMENT 'Este campo no se captura, se forma en base a los nombres y apellidos\n',
	`FechaNac` date DEFAULT NULL COMMENT 'Fecha Nacimiento del Cliente.',
	`PaisNacimiento` int(5) DEFAULT NULL COMMENT 'Pais de Nacimiento',
	`EdoNacimiento` int(11) DEFAULT '0' COMMENT 'Estado de nacimiento de la cuenta por persona FK a ESTADOSREPUB',
	`EstadoCivil` char(2) DEFAULT NULL COMMENT 'Clave Estado Civil:\n''S'' = Soltero\n''C''  = Casado\n''V'' = Viudo\n''D'' = Divorciado\n''S''  = Separado\n''U'' = Union Libre',
	`Sexo` char(1) DEFAULT NULL COMMENT 'Codigo de sexo del cliente\nClave Sexo:\n''M'' = Masculino\n''F''  = Femenino',
	`Nacionalidad` char(1) DEFAULT NULL COMMENT 'Nacionalidad del cliente\n''N'' = Nacional\n''E'' = Extranjero\n',
	`CURP` char(18) DEFAULT NULL COMMENT 'Clave Unica de Registro Poblacional\n',
	`RFC` char(13) DEFAULT NULL COMMENT 'Registro Federal de Contribuyentes del Cliente\n',
	`OcupacionID` int(5) DEFAULT NULL COMMENT 'Clave de Ocupacion (Catalog Ocupaciones)',
	`FEA` varchar(250) DEFAULT NULL COMMENT 'Firma Electrónica Avanzada, en caso de contar con ella.',
	`PaisFEA` int(11) DEFAULT NULL COMMENT 'Pais de la Firma Electronica',
	`PaisRFC` int(11) DEFAULT NULL COMMENT 'Pais de Registro Fiscal',
	`PuestoA` varchar(100) DEFAULT NULL COMMENT 'Puesto del apoderado',
	`SectorGeneral` int(3) DEFAULT NULL COMMENT 'Sector General del Cliente,Llave Foranea Hacia tabla SECTORES\n',
	`ActividadBancoMX` varchar(15) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun Banco de Mexico,Llave Foranea Hacia tabla ACTIVIDADESBMX\n',
	`ActividadINEGI` int(5) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun INEGI,Llave Foranea Hacia tabla ACTIVIDADESINEGI\n',
	`SectorEconomico` int(3) DEFAULT NULL COMMENT 'Sector Economico Segun INEGI,Llave Foranea Hacia tabla SECTORESECONOM\n',
	`TipoIdentiID` int(11) DEFAULT NULL COMMENT 'Tipo de identificacion.',
	`OtraIdentifi` varchar(20) DEFAULT NULL COMMENT 'Otra Identificacion',
	`NumIdentific` varchar(20) DEFAULT NULL COMMENT 'Numero de Identificacion',
	`FecExIden` date DEFAULT NULL COMMENT 'Fecha de expedicion de la identificacion',
	`FecVenIden` date DEFAULT NULL COMMENT 'Fecha de vencimiento de la identificacion',
	`Domicilio` varchar(200) DEFAULT NULL COMMENT 'Domicilio\n',
	`TelefonoCasa` varchar(20) DEFAULT NULL COMMENT 'Telefono de casa\n',
	`TelefonoCelular` varchar(20) DEFAULT NULL COMMENT 'Telefono de celular\n',
	`Correo` varchar(50) DEFAULT NULL COMMENT 'Correo Electronico\n',
	`PaisResidencia` int(5) DEFAULT NULL COMMENT 'Pais de Residencia, Llave Foranea Hacia tabla PAISES',
	`DocEstanciaLegal` varchar(3) DEFAULT NULL COMMENT 'Documento de estancial Legal\n',
	`DocExisLegal` varchar(30) DEFAULT NULL COMMENT 'Documento de existencia legal\n',
	`FechaVenEst` date DEFAULT NULL COMMENT 'Fecha de vencimiento de la estancia',
	`NumEscPub` varchar(50) DEFAULT NULL COMMENT 'Numero de la Escritura Publica',
	`FechaEscPub` date DEFAULT NULL COMMENT 'Fecha de la escritura publica',
	`EstadoID` int(11) DEFAULT NULL COMMENT 'Estado donde se encuentra la notaria',
	`MunicipioID` int(11) DEFAULT NULL COMMENT 'Municipio donde se encuentra la notaria',
	`NotariaID` int(11) DEFAULT NULL COMMENT 'Identificador de la notaria',
	`TitularNotaria` varchar(100) DEFAULT NULL COMMENT 'Titular de la notaria',
	`Fax` varchar(30) DEFAULT NULL COMMENT 'Fax del Cliente\n',
	`ExtTelefonoPart` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extensión del teléfono',
	`EstatusRelacion` char(1) DEFAULT NULL COMMENT 'Estatus de la persona relacionada a la cuenta "V" Vigente , "C" Cancelado',
	`IngresoRealoRecur` decimal(14,2) DEFAULT NULL COMMENT 'Ingresos Propietario Real o Proveedor de Recursos',
	`TipoAccionista` CHAR(1) NOT NULL COMMENT 'Tipo de accionista:\nA.- Persona Fisica Con Actividad Empresarial\nF.- Persona Fisica Sin Actividad Empresarial\nM.- Persona Moral  \nG.- Gobierno',
	`PorcentajeAcciones` decimal(12,4) DEFAULT NULL COMMENT 'Porcentaje que el accionista tiene en la empresa',
	`EsPropietarioReal` char(1) DEFAULT NULL COMMENT 'Es propietario real\nS > Si\nN > No',
	`ValorAcciones` decimal(12,2) DEFAULT NULL COMMENT 'Valor de las Acciones',
	`FolioMercantil` varchar(10) DEFAULT NULL COMMENT 'Folio Mercantil Electronico',
	`NombreCompania` VARCHAR(150) NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Nombre de la Compañia del Accionista\n',
	`Direccion1`   VARCHAR(150) NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Dirección Número 1 de la Compañia del Accionista',
	`Direccion2`   VARCHAR(150) NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Dirección Número 2 de la Compañia del Accionista',
	`MunNacimiento`  INT(11)    NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Municipio de la Compañia del Accionista',
	`LocNacimiento`  INT(11)    NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Localidad de la Compañia del Accionista',
	`ColoniaID`    INT(11)    NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Colonia de la Compañia del Accionista',
	`NombreCiudad`   VARCHAR(40)  NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Nombre de la Ciudad de la Compañia del Accionista',
	`CodigoPostal`   VARCHAR(5)   NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Código Postal de la Ciudad de la Compañia del Accionista',
	`EdoExtranjero`  VARCHAR(40)  NOT NULL COMMENT 'Campo Disponible para Accionista de Tipo Persona Moral\n Estado Extranjero de la Ciudad de la Compañia del Accionista',
	`EsSolicitante` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indica que la persona adicional es quien solicita el alta  S=Si N=No' ,
	`EsAutorizador` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indica que la persona adicional es quien autoriza el alta  S=Si N=No' ,
	`EsAdministrador` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indica que la persona adicional es el administrador  S=Si N=No' ,
	`PaisIDDom` INT(11) NULL DEFAULT 0 COMMENT 'Pais de Nacimiento para el domicilio',
	`EstadoIDDom` INT(11) NULL DEFAULT 0 COMMENT 'Estado para el domicilio',
	`MunicipioIDDom` INT(11) NULL DEFAULT 0 COMMENT 'Municipio para el domicilio',
	`LocalidadIDDom` INT(11) NULL DEFAULT 0 COMMENT 'Localidad para el domicilio',
	`ColoniaIDDom` INT(11) NULL DEFAULT 0 COMMENT 'Colonia para el domicilio',
	`NombreColoniaDom` VARCHAR(100) NULL DEFAULT '' COMMENT 'Colonia para el domicilio',
	`NombreCiudadDom` VARCHAR(50) NULL DEFAULT '' COMMENT 'Ciudad para el domicilio',
	`CalleDom` VARCHAR(50) NULL DEFAULT '' COMMENT 'Calle para el domicilio',
	`NumExteriorDom` VARCHAR(10) NULL DEFAULT '' COMMENT 'Numero exterior para el domicilio',
	`NumInteriorDom` VARCHAR(10) NULL DEFAULT '' COMMENT 'Numero interior para el domicilio',
	`PisoDom` VARCHAR(10) NULL    DEFAULT '' COMMENT 'Piso para el domicilio',
	`PrimeraEntreDom` VARCHAR(50) NULL DEFAULT '' COMMENT 'Primera entre para el domicilio',
	`SegundaEntreDom` VARCHAR(50) NULL DEFAULT '' COMMENT 'Segunda entre para el domicilio',
	`CodigoPostalDom` VARCHAR(5) NULL DEFAULT '' COMMENT 'Codigo postal para el domicilio',
	`EmpresaID` int(11) DEFAULT NULL COMMENT 'Auditoria\n',
	`Usuario` int(11) DEFAULT NULL COMMENT 'Auditoria',
	`FechaActual` datetime DEFAULT NULL COMMENT 'Auditoria',
	`DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Auditoria',
	`ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Auditoria',
	`Sucursal` int(11) DEFAULT NULL COMMENT 'Auditoria',
	`NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Auditoria',
	PRIMARY KEY (`ClienteID`,`GaranteID`,`AvalID`,`DirectivoID`),
	KEY `INDEX_DIRECTIVOS_2` (`SectorGeneral`),
	KEY `INDEX_DIRECTIVOS_3` (`ActividadBancoMX`),
	KEY `INDEX_DIRECTIVOS_4` (`ActividadINEGI`),
	KEY `INDEX_DIRECTIVOS_5` (`SectorEconomico`),
	KEY `INDEX_DIRECTIVOS_6` (`TipoIdentiID`),
	KEY `INDEX_DIRECTIVOS_7` (`PaisResidencia`),
	KEY `INDEX_DIRECTIVOS_1` (`ClienteID`),
	KEY `idx_DIRECTIVOS_8` (`PrimerNombre`,`SegundoNombre`,`TercerNombre`,`ApellidoPaterno`,`ApellidoMaterno`),
	KEY `idx_DIRECTIVOS_9` (`RFC`),
	CONSTRAINT `FK_DIRECTIVOS_5` FOREIGN KEY (`SectorEconomico`) REFERENCES `SECTORESECONOM` (`SectorEcoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_DIRECTIVOS_7` FOREIGN KEY (`PaisResidencia`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla que almancena los directivos de la una Persona Moral.'$$