-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- EDOCTADATOSCTE
DELIMITER ;
DROP TABLE IF EXISTS `EDOCTADATOSCTE`;
DELIMITER $$

CREATE TABLE `EDOCTADATOSCTE` (
  `AnioMes` int(11) NOT NULL COMMENT 'Anio y Mes para generar Estado de Cuenta',
  `SucursalID` int(11) NOT NULL COMMENT 'Numero de Sucursal del Cliente',
  `NombreSucursalCte` varchar(60) NOT NULL COMMENT 'Nombre de la Sucursal del Cliente',
  `ClienteID` int(11) NOT NULL COMMENT 'Numero de Cliente',
  `NombreComple` varchar(170) NOT NULL COMMENT 'Nombre Completo del Cliente',
  `TipPer` char(1) DEFAULT NULL COMMENT 'Tipo Persona:\nF = Fisica\nM = Moral\nA = Fisica con Actividad Empresarial',
  `TipoPersona` varchar(50) NOT NULL COMMENT 'Descripcion Tipo Persona',
  `Calle` varchar(50) NOT NULL COMMENT 'Descripcion de la calle',
  `NumInt` char(15) DEFAULT NULL COMMENT 'Numero Interior',
  `NumExt` char(15) DEFAULT NULL COMMENT 'Numero Exterior',
  `Colonia` varchar(200) NOT NULL COMMENT 'Nombre de la Colonia',
  `MunicipioDelegacion` varchar(50) NOT NULL COMMENT 'Nombre del Municipio',
  `Localidad` varchar(50) NOT NULL COMMENT 'Nombre de la Localidad',
  `Estado` varchar(50) NOT NULL COMMENT 'Nombre del Estado',
  `CodigoPostal` char(5) DEFAULT NULL COMMENT 'Codigo Postal',
  `RFC` varchar(13) NOT NULL COMMENT 'RFC del Cliente',
  `InstrucEnvio` char(1) NOT NULL COMMENT 'Instruccion Envio',
  `DireccionCompleta` varchar(500) DEFAULT NULL COMMENT 'Direccion Completa del Cliente',
  `NombreInstitucion` varchar(250) DEFAULT NULL COMMENT 'Nombre de la Institucion',
  `DireccionInstitucion` varchar(250) DEFAULT NULL COMMENT 'Direccion de la Institucion',
  `FechaGeneracion` date DEFAULT NULL COMMENT 'Fecha Generacion de Registros',
  `RegHacienda` char(1) DEFAULT NULL COMMENT 'Especifica si el cliente esta registrado en Hacienda\nS.- Si\nN.- No',
  `CadenaCFDI` varchar(10000) DEFAULT NULL COMMENT 'Cadena para archivo de timbrado CFDI para Ingresos',
  `ComisionAhorro` decimal(12,2) DEFAULT NULL COMMENT 'Total de Comisiones por Cuenta de Ahorro',
  `ComisionCredito` decimal(12,2) DEFAULT NULL COMMENT 'Total de Comision por Creditos',
  `ISR` decimal(12,2) DEFAULT NULL COMMENT 'ISR Cuentas e Inversiones',
  `CFDIFechaEmision` date DEFAULT NULL COMMENT 'Fecha de Emision del CFDI para Ingresos',
  `CFDIVersion` varchar(10) DEFAULT NULL COMMENT 'Tag Version del CFDI',
  `CFDINoCertSAT` varchar(45) DEFAULT NULL COMMENT 'No Certificado del SAT para Ingresos',
  `CFDIUUID` varchar(50) DEFAULT NULL COMMENT 'UUID del CFDI para Ingresos',
  `CFDIFechaTimbrado` varchar(50) DEFAULT NULL COMMENT 'Fecha de Timbrado para Ingresos',
  `CFDISelloCFD` varchar(1000) DEFAULT NULL COMMENT 'Sello CFD del CFDI para Ingresos',
  `CFDISelloSAT` varchar(1000) DEFAULT NULL COMMENT 'Sello del SAT para Ingresos',
  `CFDICadenaOrig` varchar(2000) DEFAULT NULL COMMENT 'Cadena Original para Ingresos',
  `DiasPeriodo` varchar(45) DEFAULT NULL COMMENT 'Dias del Periodo',
  `CFDIFechaCertifica` varchar(45) DEFAULT NULL COMMENT 'Fecha Certificacion para Ingresos',
  `CFDINoCertEmisor` varchar(80) DEFAULT NULL COMMENT 'Numero Certificacion Emisor para Ingresos',
  `CFDILugExpedicion` varchar(50) DEFAULT NULL COMMENT 'Lugar Expedicion para Ingresos',
  `Estatus` int(11) DEFAULT '1' COMMENT 'Estatus Timbrado Ingresos:\n1 = No Procesada\n2 = Procesada\n3 = Error al Procesar',
  `TotalInteres` decimal(12,2) DEFAULT NULL COMMENT 'Total Interes Credito',
  `IvaComisiones` decimal(12,2) DEFAULT NULL COMMENT 'Iva Comisiones',
  `Comisiones` decimal(12,2) DEFAULT NULL COMMENT 'Comisiones',
  `CadenaCFDIRet` varchar(10000) DEFAULT NULL COMMENT 'Cadena para archivo de timbrado CFDI para Retenciones',
  `CFDINoCertSATRet` varchar(45) DEFAULT NULL COMMENT 'No. Certificado del SAT para Retenciones',
  `CFDIUUIDRet` varchar(50) DEFAULT NULL COMMENT 'UUID del CFDI para Retenciones',
  `CFDIFechaTimRet` varchar(50) DEFAULT NULL COMMENT 'Fecha de Timbrado para Retenciones',
  `CFDISelloCFDRet` varchar(1000) DEFAULT NULL COMMENT 'Sello CFD del CFDI para Retenciones',
  `CFDISelloSATRet` varchar(1000) DEFAULT NULL COMMENT 'Sello del SAT para Retenciones',
  `CFDICadenaOrigRet` varchar(2000) DEFAULT NULL COMMENT 'Cadena Original para Retenciones',
  `CFDIFechaCertRet` varchar(45) DEFAULT NULL COMMENT 'Fecha Certificacion para Retenciones',
  `CFDINoCertEmiRet` varchar(80) DEFAULT NULL COMMENT 'Numero Certificacion Emisor para Retenciones',
  `CFDILugExpediRet` varchar(50) DEFAULT NULL COMMENT 'Lugar Expedicion para Retenciones',
  `CFDISubTotal` varchar(20) NOT NULL COMMENT 'Subtotal del timbre rescatado del XML',
  `CFDITotalXML` varchar(20) NOT NULL COMMENT 'Total del timbre rescatado del XML',
  `EstatusRet` int(11) DEFAULT '1' COMMENT 'Estatus Timbrado Retenciones:\n1 = No Procesada\n2 = Procesada\n3 = Error al Procesar',
  `Intereses` decimal(12,2) DEFAULT NULL COMMENT 'Total Intereses Inversiones y Cuentas',
  `ProductoCredID` int(4) NOT NULL,
  `CFDITotal` varchar(25) DEFAULT NULL,
  `CreditoID` bigint(12) NOT NULL,
  `EstatusCadenaProd` char(1) DEFAULT 'N' COMMENT 'Estatus de generacion de cadena por producto\nS=SI\nN=NO',
  `PDFGenerado` CHAR(1) NULL DEFAULT 'N' COMMENT 'N= PDF no Generado\nS= PDF Generado Antes del Timbrado\nD= PDF Generado Despues del Timbrado',
  PRIMARY KEY (`AnioMes`,`SucursalID`,`ClienteID`,`ProductoCredID`,`CreditoID`),
  KEY `fk_EDOCTADATOSCTE_1_idx` (`Estatus`),
  KEY `fk_EDOCTADATOSCTE_2_idx` (`EstatusRet`),
  KEY `INDEX_EDOCTADATOSCTE_3` (`ClienteID`),
  CONSTRAINT `fk_EDOCTADATOSCTE_1` FOREIGN KEY (`Estatus`) REFERENCES `CATESTATUSEDOCTA` (`idEstatus`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EDOCTADATOSCTE_2` FOREIGN KEY (`EstatusRet`) REFERENCES `CATESTATUSEDOCTA` (`idEstatus`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Datos Principales del Estado de Cuenta'$$
