-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- HISAPORTACIONES
DELIMITER ;
DROP TABLE IF EXISTS `HISAPORTACIONES`;

DELIMITER $$
CREATE TABLE `HISAPORTACIONES` (
  `HisAportID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Numero consecutivo.',
  `AportacionID` int(11) NOT NULL COMMENT 'ID de la Aportación PK.',
  `TipoAportacionID` int(11) DEFAULT NULL COMMENT 'Tipo de Aportación.',
  `CuentaAhoID` bigint(12) DEFAULT NULL COMMENT 'Cuenta de ahorro.',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Cliente ID.',
  `AperturaAport` char(2) DEFAULT 'FA' COMMENT 'Indica fecha de apertura de aportacion. FA:Fecha Actual / FP:Fecha Posterior',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de inicio de la Aportación.',
  `FechaVencimiento` date DEFAULT NULL COMMENT 'Fecha de vencimiento.',
  `FechaPago` date DEFAULT NULL COMMENT 'Fecha de pago.',
  `Monto` decimal(18,2) DEFAULT NULL COMMENT 'Monto de la Aportación.',
  `Plazo` int(11) DEFAULT NULL COMMENT 'Plazo de la Aportación.',
  `TasaFija` decimal(14,4) DEFAULT NULL COMMENT 'tasa fija.',
  `TasaISR` decimal(12,4) DEFAULT NULL COMMENT 'tasa ISR.',
  `TasaNeta` decimal(12,4) DEFAULT NULL COMMENT 'tasa Neta.',
  `CalculoInteres` int(1) DEFAULT NULL COMMENT 'Calculo de interes.',
  `TasaBase` int(1) DEFAULT NULL COMMENT 'tasa base.',
  `SobreTasa` decimal(12,4) DEFAULT NULL COMMENT 'sobre tasa.',
  `PisoTasa` decimal(12,4) DEFAULT NULL COMMENT 'piso tasa.',
  `TechoTasa` decimal(12,4) DEFAULT NULL COMMENT 'techo tasa.',
  `InteresGenerado` decimal(18,2) DEFAULT NULL COMMENT 'interes generado.',
  `InteresRecibir` decimal(18,2) DEFAULT NULL COMMENT 'interes a recibir.',
  `InteresRetener` decimal(18,2) DEFAULT NULL COMMENT 'interes a retener.',
  `SaldoProvision` decimal(18,2) DEFAULT NULL COMMENT 'Se Inicializa al Inicio de cada mes.',
  `SaldoISR` decimal(18,2) DEFAULT '0.00' COMMENT 'Saldo del devengo diario de ISR',
  `ValorGat` decimal(12,4) DEFAULT NULL COMMENT 'valor del Gat.',
  `ValorGatReal` decimal(12,4) DEFAULT NULL COMMENT 'valor del Gat real .',
  `EstatusImpresion` char(1) DEFAULT NULL COMMENT 'Estatus de la impresión .',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'ID de la moneda.',
  `FechaVenAnt` date DEFAULT NULL COMMENT 'Fecha de vencimiento anticipado .',
  `FechaApertura` date DEFAULT NULL COMMENT 'fecha de apertura .',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus\nN =vigente\nP =Pagada\nC =Cancelada\nA =Registrada\nL =Autorizada.',
  `TipoPagoInt` char(1) DEFAULT NULL COMMENT 'Indica la forma de pago de interes.\nV - Vencimiento\nF - Fin del Mes\nP - Por Periodo.\nE - Programado.',
  `DiasPeriodo` int(11) DEFAULT '0' COMMENT 'Indica el numero de dias si la forma de pago de interes es por PERIODO.',
  `PagoIntCal` char(2) DEFAULT NULL COMMENT 'Indica el tipo de pago de interes.\nI - Iguales\nD - Devengado.',
  `AportacionRenovada` int(11) DEFAULT '0' COMMENT 'Numero de Aportación que Fue Renovada.',
  `PlazoOriginal` int(11) DEFAULT NULL COMMENT 'Plazo Original de la Aportación.',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Sucursal donde fue Autorizada la Aportación.',
  `Reinversion` char(1) DEFAULT NULL COMMENT 'Especifica si realiza Reinversion Automatica\nS.- Si realiza Reinversion Automatica\nN.- No Realiza Reinversion.\nF.- Posterior',
  `Reinvertir` char(3) DEFAULT NULL COMMENT 'Tipo de Reinversión Automatica \nC = Capital \nCI = Capital mas interes \nN = Ninguna.',
  `FechaCancela` date DEFAULT NULL COMMENT 'Fecha de cancelación de la Aportación.',
  `UsuarioAut` int(11) DEFAULT NULL COMMENT 'Usuario que realiza la autorizacion de la cancelacion o el vencimiento anticipado de la Aportación.',
  `CajaRetiro` int(11) DEFAULT NULL COMMENT 'Sucursal en la que se retirara el monto de la inversión al finalizar.',
  `ISRReal` decimal(14,2) DEFAULT '0.00' COMMENT 'Acumula el ISR Diario por socio solo cuando este activa esta opcion en PARAMGENERALES.',
  `MontoGlobal` decimal(18,2) DEFAULT '0.00' COMMENT 'Monto Global del Cliente. Puede incluir el monto de los productos vigentes de los integrantes de su gpo. familiar.',
  `TasaMontoGlobal` char(1) DEFAULT 'N' COMMENT 'Valor del Tipo de Aportación al momento del registro.\nN: NO.\nS: SI.',
  `IncluyeGpoFam` char(1) DEFAULT 'N' COMMENT 'Valor del Tipo de Aportación al momento del registro.\nN: NO.\nS: SI.',
  `DiasPago` int(11) DEFAULT '0' COMMENT 'Indica el dia de pago de la aportacion',
  `PagoIntCapitaliza` char(1) DEFAULT 'I' COMMENT 'Indica si capitaliza interes S:Si, N:No, I:Indistinto',
  `OpcionAport` varchar(50) DEFAULT '' COMMENT 'Indica la opcion elegida en el combo aportacion. En alta de aportacion',
  `CantidadReno` decimal(18,2) DEFAULT '0.00' COMMENT 'Indica la cantidad de renovacion de la aportacion',
  `InvRenovar` int(11) DEFAULT '0' COMMENT 'Numero Aportacion renovada en alta y modificacion de Aportaciones',
  `Notas` varchar(500) DEFAULT '' COMMENT 'Notas puntuales de la aportacion',
  `MotivoCancela` varchar(100) DEFAULT '' COMMENT 'Motivo de cancelación de la aportación.',
  `ConCondiciones` char(1) DEFAULT 'N' COMMENT 'Indica si la aportación tiene condiciones capturadas.\nS.- Si\nN.- N',
  `ConsolidarSaldos` char(1) DEFAULT 'N' COMMENT 'Indica si Consolida Aportaciones Vigentes que venzan\nel mismo día que la Aportación a Consolidar.\nAplica para Tipo de Reinversión con Más.\nN: No (default)\nG: Sí Tipo Grupo\nI: Sí Tipo Integrante',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Parametro de auditoria.',
  `UsuarioID` int(11) DEFAULT NULL COMMENT 'Parametro de auditoria.',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Parametro de auditoria.',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Parametro de auditoria.',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Parametro de auditoria.',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Parametro de auditoria.',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Parametro de auditoria.',
  PRIMARY KEY (`HisAportID`),
  KEY `INDEX_HISAPORTACIONES_1` (`AportacionID`),
  KEY `INDEX_HISAPORTACIONES_2` (`ClienteID`),
  KEY `INDEX_HISAPORTACIONES_3` (`CuentaAhoID`),
  KEY `INDEX_HISAPORTACIONES_4` (`MonedaID`),
  KEY `INDEX_HISAPORTACIONES_5` (`TipoAportacionID`),
  KEY `INDEX_HISAPORTACIONES_6` (`FechaPago`,`Reinversion`,`Estatus`,`ConCondiciones`),
  KEY `INDEX_HISAPORTACIONES_7` (`Estatus`,`ConCondiciones`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='His: Respaldo de las Aportaciones cuando hay un cambio de Tasa ISR (respaldo antes del cambio).'$$