-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- HISCLIENTES
DELIMITER ;
DROP TABLE IF EXISTS `HISCLIENTES`;DELIMITER $$

CREATE TABLE `HISCLIENTES` (
  `NumTransaccionAct` bigint(20) NOT NULL COMMENT 'Numero de Transaccion que realizo la actualización de los datos',
  `ClienteID` int(11) NOT NULL COMMENT 'LLave Primaria para Identificar los Clientes',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de Personalidad del Cliente M.- Persona Moral A.- Persona Fisica Con Actividad Empresarial F.- Persona Fisica Sin Actividad Empresarial',
  `Titulo` varchar(10) DEFAULT NULL COMMENT 'Titulo del Cliente\nTitulo del Cliente, Ej. Sr., Sra, Srita, Lic, Dr. Ing, Prof.,CP, etc',
  `PrimerNombre` varchar(50) DEFAULT NULL COMMENT 'Primer Nombre del Cliente',
  `SegundoNombre` varchar(50) DEFAULT NULL COMMENT 'Segundo Nombre del Cliente',
  `TercerNombre` varchar(50) DEFAULT NULL COMMENT 'Tercer Nombre Del Cliente',
  `ApellidoPaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Paterno del Cliente',
  `ApellidoMaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Materno del Cliente',
  `FechaNacimiento` date DEFAULT NULL COMMENT 'Fecha Nacimiento del Cliente o Rep Legal',
  `CURP` char(18) DEFAULT NULL COMMENT 'Clave Unica de Registro Poblacional',
  `Nacion` char(1) DEFAULT NULL COMMENT 'Nacionalidad del cliente''N'' = Nacional''E'' = Extranjero',
  `PaisResidencia` int(5) DEFAULT NULL COMMENT 'Pais de Residencian, Llave Foranea Hacia tabla PAISES',
  `GrupoEmpresarial` int(11) DEFAULT NULL COMMENT 'Llave Foranea Hacia tabla GRUPOSEMP si existe peor no es necesaria.',
  `RazonSocial` varchar(150) DEFAULT NULL COMMENT 'Razon Social',
  `TipoSociedadID` int(11) DEFAULT NULL COMMENT 'Tipo de Sociedad, tiene llave foranea a la tabla  TIPOSOCIEDAD si existe pero no es necesaria',
  `RFC` char(13) DEFAULT NULL COMMENT 'Registro Federal de Contribuyentes del Cliente',
  `RFCpm` char(13) DEFAULT NULL COMMENT 'RFC de persona moral',
  `RFCOficial` char(13) DEFAULT NULL COMMENT 'RFC del cliente ya sea RFC que es asignado como persona fisica o el RFC como persona moral',
  `SectorGeneral` int(3) DEFAULT NULL COMMENT 'Sector General del Cliente,Llave Foranea Hacia tabla SECTORES',
  `ActividadBancoMX` varchar(15) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun Banco de Mexico,Llave Foranea Hacia tabla ACTIVIDADESBMX',
  `ActividadINEGI` int(11) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun INEGI,Llave Foranea Hacia tabla ACTIVIDADESINEGI',
  `ActividadFR` bigint(20) DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun la ACTIVIDADESFR',
  `ActividadFOMURID` int(11) DEFAULT NULL COMMENT 'Actividad Fomur del Cte, segun la ACTIVIDADESFOMUR',
  `SectorEconomico` int(11) DEFAULT NULL COMMENT 'Sector Economico Segun INEGI,Llave Foranea Hacia tabla SECTORESECONOM',
  `Sexo` char(1) DEFAULT NULL COMMENT 'Codigo de sexo del cliente\nClave Sexo:''M'' = Masculino''F''  = Femenino',
  `EstadoCivil` char(2) DEFAULT NULL COMMENT 'Clave Estado Civil:\\n\\''S\\'' = Soltero\\n\\''CS\\''  = Casado Bienes Separados\\n\\''CM\\''  = Casado Bienes Mancomunados\\n\\''CC\\''  = Casado Bienes Mancomunados Con Capitulacion\\n\\''V\\'' = Viudo\\n\\''D\\'' = Divorciado\\n\\''SE\\''  = Separado\\n\\''U\\'' = Union Libre',
  `LugarNacimiento` int(11) DEFAULT NULL COMMENT 'Pais de Nacimiento, llave foranea a PAISES',
  `EstadoID` int(11) DEFAULT NULL COMMENT 'Identificador de Estado que Se Encuentra en la tabla ESTADOSREPUB',
  `OcupacionID` int(5) DEFAULT NULL COMMENT 'Profesión del cliente,Llave Foranea Hacia tabla OCUPACIONES si existe pero no es necesario.',
  `LugardeTrabajo` varchar(100) DEFAULT NULL COMMENT 'Lugar donde Trabaja',
  `Puesto` varchar(100) DEFAULT NULL COMMENT 'Puesto en el Trabajo',
  `NivelRiesgo` char(1) DEFAULT NULL COMMENT '\nNivel de riesgo del cliente:\nA .-  Alto\nM .- Medio\nB .-  Bajo',
  `NombreCompleto` varchar(200) DEFAULT NULL COMMENT 'Este campo no se captura, se forma en base a los nombres y apellidos',
  `FechaConstitucion` date DEFAULT NULL COMMENT 'Fecha de Constitucion ante el Registro Federal de Contribuyentes.',
  `FEA` varchar(250) DEFAULT NULL COMMENT 'Firma Electrónica Avanzada, en caso de contar con ella.',
  `PaisConstitucionID` int(11) DEFAULT NULL COMMENT 'Pais de Constitucion de la empresa',
  `NombreNotario` varchar(150) DEFAULT NULL COMMENT 'Nombre Notario campo para Persona Moral',
  `NumNotario` int(11) DEFAULT NULL COMMENT 'Numero de Notario campo para Persona Moral',
  `InscripcionReg` varchar(50) DEFAULT NULL COMMENT 'Inscripcion en el registro publico campo para Persona Moral',
  `EscrituraPubPM` varchar(20) DEFAULT NULL COMMENT 'Escritura Publica Persona Moral',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Auditoria',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Auditoria',
  PRIMARY KEY (`ClienteID`,`NumTransaccionAct`),
  KEY `INDEX_HISCLIENTES_1` (`RFCOficial`),
  KEY `FK_HISCLIENTES_1` (`ActividadBancoMX`),
  KEY `FK_HISCLIENTES_2` (`PaisResidencia`),
  KEY `FK_HISCLIENTES_3` (`EstadoID`),
  KEY `FK_HISCLIENTES_6` (`SectorEconomico`),
  KEY `FK_HISCLIENTES_8` (`SectorGeneral`),
  KEY `FK_HISCLIENTES_9` (`ActividadINEGI`),
  KEY `FK_HISCLIENTES_10` (`ActividadFR`),
  KEY `FK_HISCLIENTES_11` (`LugarNacimiento`),
  KEY `FK_HISCLIENTES_12` (`ActividadFOMURID`),
  KEY `FK_HISCLIENTES_13` (`PaisConstitucionID`),
  KEY `INDEX_HISCLIENTES_9` (`RazonSocial`,`RFCpm`,`TipoPersona`),
  KEY `INDEX_HISCLIENTES_10` (`RazonSocial`,`RFCOficial`,`TipoPersona`),
  KEY `INDEX_HISCLIENTES_4` (`RFC`,`FechaNacimiento`,`LugarNacimiento`,`EstadoID`,`TipoPersona`),
  KEY `INDEX_HISCLIENTES_5` (`FechaNacimiento`,`RFC`,`TipoPersona`),
  KEY `INDEX_HISCLIENTES_6` (`LugarNacimiento`,`EstadoID`,`TipoPersona`),
  KEY `INDEX_HISCLIENTES_7` (`RFC`,`FechaNacimiento`,`LugarNacimiento`,`EstadoID`,`TipoPersona`),
  KEY `INDEX_HISCLIENTES_8` (`RFC`,`FechaNacimiento`,`LugarNacimiento`,`EstadoID`,`TipoPersona`),
  CONSTRAINT `FK_HISCLIENTES_1` FOREIGN KEY (`ActividadBancoMX`) REFERENCES `ACTIVIDADESBMX` (`ActividadBMXID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_10` FOREIGN KEY (`ActividadFR`) REFERENCES `ACTIVIDADESFR` (`ActividadFRID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_11` FOREIGN KEY (`LugarNacimiento`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_12` FOREIGN KEY (`ActividadFOMURID`) REFERENCES `ACTIVIDADESFOMUR` (`ActividadFOMURID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_13` FOREIGN KEY (`PaisConstitucionID`) REFERENCES `PAISES` (`PaisID`),
  CONSTRAINT `FK_HISCLIENTES_2` FOREIGN KEY (`PaisResidencia`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_3` FOREIGN KEY (`EstadoID`) REFERENCES `ESTADOSREPUB` (`EstadoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_6` FOREIGN KEY (`SectorEconomico`) REFERENCES `SECTORESECONOM` (`SectorEcoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_8` FOREIGN KEY (`SectorGeneral`) REFERENCES `SECTORES` (`SectorID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_HISCLIENTES_9` FOREIGN KEY (`ActividadINEGI`) REFERENCES `ACTIVIDADESINEGI` (`ActividadINEGIID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla Historica de los Modificaciones de los Registros de la tabla de CLIENTES'$$