-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- LINEATARJETACRED
DELIMITER ;
DROP TABLE IF EXISTS `LINEATARJETACRED`;
DELIMITER $$


CREATE TABLE `LINEATARJETACRED` (
  `LineaTarCredID` int(20) NOT NULL DEFAULT '0' COMMENT 'Identificador de la Linea de Credito',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Identificador del Cliente',
  `TarjetaPrincipal` char(16) DEFAULT '' COMMENT 'Numero de tarjeta titular, actual',
  `SucursalID` int(11) DEFAULT '0' COMMENT 'Identificador de Sucursal donde se da de alta la linea',
  `MontoLinea` decimal(16,2) DEFAULT NULL COMMENT 'Monto Limite de la linea de credito',
  `MontoDisponible` decimal(16,2) DEFAULT NULL COMMENT 'Monto Disponible en la Linea de Credito',
  `MontoBloqueado` decimal(16,2) DEFAULT NULL COMMENT 'Monto bloqueado de la linea',
  `SaldoAFavor` decimal(16,2) DEFAULT NULL COMMENT 'Saldo a Favor por pagos',
  `SaldoCapVigente` decimal(16,2) DEFAULT NULL COMMENT 'Saldo acumulado de los cargos',
  `SaldoCapVencido` decimal(16,2) DEFAULT NULL COMMENT 'Saldo acumulado que no fue pagado en tiempo',
  `SaldoInteres` decimal(16,2) DEFAULT NULL COMMENT 'Saldo de  intereses',
  `SaldoIVAInteres` decimal(16,2) DEFAULT NULL COMMENT 'Iva del interes',
  `SaldoMoratorios` decimal(16,2) DEFAULT NULL COMMENT 'Saldo de interes moratorio',
  `SaldoIVAMoratorios` decimal(16,2) DEFAULT NULL COMMENT 'Saldo iva de moratorios',
  `SalComFaltaPag` decimal(16,2) DEFAULT NULL COMMENT 'Saldo de comision por falta ed pago',
  `SalIVAComFaltaPag` decimal(16,2) DEFAULT NULL COMMENT 'Saldo iva de comision por falta de pago',
  `SalOrtrasComis` decimal(16,2) DEFAULT NULL COMMENT 'Saldo de otras comisiones',
  `SalIVAOrtrasComis` decimal(16,2) DEFAULT NULL COMMENT 'Saldo IVA de otras comisiones',
  `MontoBaseCal` decimal(16,2) DEFAULT NULL COMMENT 'Montoo Base para calculo de Intereses',
  `SaldoCorte` decimal(16,2) DEFAULT NULL COMMENT 'Saldo de la Linea a la Fecha de Corte',
  `PagoNoGenInteres` decimal(16,2) DEFAULT NULL COMMENT 'Monto del Pago para no generar interes',
  `PagoMinimo` decimal(16,2) DEFAULT NULL COMMENT 'Monto del Pago Minimo',
  `SaldoInicial` decimal(16,2) DEFAULT NULL COMMENT 'Monto del Pago Minimo',
  `ComprasPeriodo` decimal(16,2) DEFAULT NULL COMMENT 'Monto del Pago Minimo',
  `RetirosPeriodo` decimal(16,2) DEFAULT NULL COMMENT 'Monto del Pago Minimo',
  `PagosPeriodo` decimal(16,2) DEFAULT NULL COMMENT 'Monto del Pago Minimo',
  `CAT` decimal(12,4) DEFAULT NULL COMMENT 'CAT Informativo',
  `TipoTarjetaDeb` int(11) DEFAULT NULL COMMENT 'Identificador del tipo de Tarjeta',
  `ProductoCredID` int(11) DEFAULT NULL COMMENT 'Identificador del Producto de Credito',
  `TasaFija` decimal(8,4) DEFAULT NULL COMMENT 'Tasa Fija de la Linea',
  `TipoCorte` char(1) DEFAULT NULL COMMENT 'F: Fin de Mes, D: Dia es especifico',
  `DiaCorte` int(11) DEFAULT NULL COMMENT 'Dia en que se realiza el corte de la tarjeta, aplica si el Tipo de Corte es "D" dia en especifico',
  `TipoPago` char(1) DEFAULT NULL COMMENT 'Tipo de Pago de la tarjeta:  D: Dia en especifico, V: 20 dias Naturales, M: Un Mes natural (30 dias)',
  `DiaPago` int(11) DEFAULT NULL COMMENT 'Dia en que se realiza el pago de la tarjeta, aplica si el Tipo de Pago es "D" dia en especifico',
  `CobraMora` char(1) DEFAULT NULL COMMENT 'Indica si la Linea cobra Moratorios',
  `TipoCobMora` char(1) DEFAULT NULL COMMENT 'Indica la forma de cobro de moratorios, N: N veces la tasa, T: Tasa fija anualizada',
  `FactorMora` decimal(8,4) DEFAULT NULL COMMENT 'Indica el factor a utilizar para el cobro de moratorios',
  `TipoPagMin` char(1) DEFAULT NULL COMMENT 'P: Porcentaje, F: Formula',
  `FactorPagMin` decimal(8,4) DEFAULT NULL COMMENT 'Porcentaje de cobro cuando el tipo de pago minimo es "P"',
  `CobraFaltaPago` char(1) DEFAULT NULL COMMENT 'Indica si cobra Comision por Falta de Pago \nS .- Si cobra\r\n\nN .- No cobra',
  `TipCobComFalPago` char(1) DEFAULT NULL COMMENT 'Tipo de Cobro por Falta de Pago\nP .- Porcentaje\nM .- Monto Fijo',
  `FactorFaltaPago` decimal(12,4) DEFAULT NULL COMMENT 'Factor Falta Pago',
  `CobComisionAper` char(1) DEFAULT NULL COMMENT 'Indica si cobra Comision por Apertura\nS .- Si cobra\nN .- No cobra',
  `TipoCobComAper` char(1) DEFAULT NULL COMMENT 'Tipo de Cobro por Apertura\nP .- Porcentaje\nM .- Monto Fijo',
  `FacComisionAper` decimal(12,4) DEFAULT NULL COMMENT 'Factor por Apertura',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus de la linea R: Registrada, V: Vigente, B: Bloqueada, C: Cancelada',
  `FechaRegistro` date DEFAULT NULL COMMENT 'Fecha de registro de la linea, nace con la fecha en que se otorgo la tarjeta al cliente',
  `FechaActivacion` date DEFAULT NULL COMMENT 'Fecha de activacion de la linea, nace con 1900-01-01',
  `FechaCancelacion` date DEFAULT NULL COMMENT 'Fecha de cancelacion de la linea, nace con 1900-01-01',
  `FechaUltCorte` date DEFAULT '1900-01-01' COMMENT 'Fecha del ultimo corte',
  `FechaProxCorte` date DEFAULT '1900-01-01' COMMENT 'Indica na Fecha del Proximo corte de la linea\\n',
  `CuentaClabe` char(18) DEFAULT NULL COMMENT 'Cuenta CLABE para pago de credito',
  `FechaProxpago` date DEFAULT '1900-01-01' COMMENT 'Fecha Limite de Pago, del periodo anterior',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Auditoria',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Auditoria',
  PRIMARY KEY (`LineaTarCredID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TAB: Registro de las Lineas de Credito Asignadas a Cada Cliente'$$
