-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- LINEASCREDITO
DELIMITER ;
DROP TABLE IF EXISTS `LINEASCREDITO`;

DELIMITER $$
CREATE TABLE `LINEASCREDITO` (
  `LineaCreditoID` bigint(20) NOT NULL COMMENT 'Numero de Linea de Credito. Es un consecutivo',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente',
  `CuentaID` bigint(12) DEFAULT NULL,
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Numero de Moneda',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Numero de Sucursal',
  `FolioContrato` varchar(15) DEFAULT NULL COMMENT 'Folio del Contrato. Es dato que ingresa el ejecutivo',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio de la Linea de Credito',
  `FechaVencimiento` date DEFAULT NULL COMMENT 'Fecha de Vencimiento de la Linea de Credito',
  `ProductoCreditoID` int(11) DEFAULT NULL COMMENT 'Tipo de Linea',
  `Solicitado` decimal(12,2) DEFAULT NULL COMMENT 'Monto solicitado\npor el usuario',
  `Autorizado` decimal(12,2) DEFAULT NULL COMMENT 'Monto Autorizado de la Linea',
  `Dispuesto` decimal(12,2) DEFAULT NULL COMMENT 'Monto Dispuesto de la linea, nace con ceros',
  `Pagado` decimal(12,2) DEFAULT NULL COMMENT 'Monto Pagado de la linea, nace con ceros',
  `SaldoDisponible` decimal(12,2) DEFAULT NULL COMMENT 'Saldo de la Linea, nace con saldo = autorizado',
  `SaldoDeudor` decimal(12,2) DEFAULT NULL,
  `SaldoComAnual` decimal(14,2) DEFAULT NULL COMMENT 'Saldo Comision anual.',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus de la Linea\nC .- Cancelada\nB .- Bloqueada\nA .- Autorizada, Vigente\nI .- Inactiva (Nace con este Status)\nS .- Si es Automatico \nN .- No es Automatico \nR .- Rechazado \nE .- Vencido',
  `NumeroCreditos` int(11) DEFAULT NULL COMMENT 'Numero de Credito que tiene la linea, nace con ceros',
  `FechaCancelacion` date DEFAULT NULL COMMENT 'Fecha Cancelacion, nace con fecha vacia',
  `FechaBloqueo` date DEFAULT NULL COMMENT 'Fecha Bloqueo, nace con fecha vacia',
  `FechaDesbloqueo` date DEFAULT NULL,
  `FechaAutoriza` date DEFAULT NULL COMMENT 'Fecha en que se\nautoriza',
  `UsuarioAutoriza` int(11) DEFAULT NULL,
  `UsuarioBloqueo` int(11) DEFAULT NULL,
  `UsuarioDesbloq` int(11) DEFAULT NULL,
  `UsuarioCancela` int(11) DEFAULT NULL,
  `MotivoBloqueo` varchar(150) DEFAULT NULL,
  `MotivoDesbloqueo` varchar(150) DEFAULT NULL,
  `MotivoCancela` varchar(150) DEFAULT NULL,
  `IdenCreditoCNBV` varchar(29) DEFAULT NULL COMMENT 'Identificador del Credito Utilizando Metodologia CNBV',
  `CobraComAnual` char(1) DEFAULT NULL COMMENT 'Indica si cobra comision anual de linea.',
  `TipoComAnual` char(1) DEFAULT NULL COMMENT 'Tipo de comision anual.',
  `ValorComAnual` decimal(12,2) DEFAULT NULL COMMENT 'Valor de la comision anual.',
  `ComisionCobrada` char(1) DEFAULT NULL COMMENT 'Comision cobrada.',
  `EsAgropecuario` CHAR(1) NOT NULL COMMENT 'Es Agropecuario \nS.- SI \nN.- NO',
  `TipoLineaAgroID` INT(11) NOT NULL COMMENT 'Numero de Tipo de Línea Agropecuaria',
  `EsRevolvente` CHAR(1) NOT NULL COMMENT 'Es Revolvente \nS.- SI \nN.- NO',
  `ManejaComAdmon` CHAR(1) NOT NULL COMMENT 'Maneja Comisión Administración \nS.- SI \nN.- NO',
  `ForCobComAdmon` CHAR(1) NOT NULL COMMENT 'Forma Cobro Comisión Administración \n"".- No aplica \nD.- Disposición \nT.- Total en primera Disposición',
  `PorcentajeComAdmon` DECIMAL(6,2) NOT NULL COMMENT 'Permite un valor de 0% a 100%',
  `ManejaComGarantia` CHAR(1) NOT NULL COMMENT 'Maneja Comisión por Garantía \nS.- SI \nN.- NO',
  `ForCobComGarantia` CHAR(1) NOT NULL COMMENT 'Forma Cobro Comisión Garantía \n"".- No aplica \nC.- Cada Cuota',
  `PorcentajeComGarantia` DECIMAL(6,2) NOT NULL COMMENT 'Permite un valor de 0% a 100%',
  `FechaRechazo` DATE DEFAULT "1900-01-01" COMMENT 'Fecha de Rechazo de la Línea de Crédito',
  `UsuarioRechazo` INT(11) NOT NULL COMMENT 'ID de Usuario que realiza el Rechazo de la Línea de Crédito',
  `MontoUltimoIncremento` DECIMAL(14,2) NOT NULL COMMENT 'Monto de Ultimo Incremento',
  `FechaReactivacion` DATE DEFAULT "1900-01-01" COMMENT 'Fecha de la Reactivación de la Línea de Crédito',
  `UsuarioReactivacion` INT(11) NOT NULL COMMENT 'ID de Usuario que realiza la Reactivación de la Línea de Crédito',
  `UltFechaDisposicion` DATE DEFAULT "1900-01-01" COMMENT 'Fecha de Ultima Disposicion de la Línea de Crédito',
  `UltMontoDisposicion` DECIMAL(14,2) NOT NULL COMMENT 'Monto de la Ultima Disposicion',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Empresa ID',
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`LineaCreditoID`),
  KEY `fk_LINEASCREDITO_2` (`CuentaID`),
  KEY `fk_LINEASCREDITO_3` (`MonedaID`),
  KEY `fk_LINEASCREDITO_4` (`SucursalID`),
  KEY `fk_LINEASCREDITO_1` (`ClienteID`),
  KEY `fk_LINEASCREDITO_5` (`ProductoCreditoID`),
  CONSTRAINT `fk_LINEASCREDITO_1` FOREIGN KEY (`ClienteID`) REFERENCES `CLIENTES` (`ClienteID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINEASCREDITO_2` FOREIGN KEY (`CuentaID`) REFERENCES `CUENTASAHO` (`CuentaAhoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINEASCREDITO_3` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINEASCREDITO_4` FOREIGN KEY (`SucursalID`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINEASCREDITO_5` FOREIGN KEY (`ProductoCreditoID`) REFERENCES `PRODUCTOSCREDITO` (`ProducCreditoID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Lineas de Credito\n'$$