-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- migracion.CREDITOS
DELIMITER ;
DROP TABLE IF EXISTS `migracion.CREDITOS`;DELIMITER $$

CREATE TABLE `migracion.CREDITOS` (
  `FechaExtraccion` date DEFAULT NULL,
  `EsGrupal` char(1) DEFAULT NULL,
  `GrupoID` int(11) DEFAULT NULL,
  `TipoIntegrante` int(11) DEFAULT NULL,
  `CreditoID` bigint(11) NOT NULL DEFAULT '0',
  `LineaCreditoID` char(12) DEFAULT NULL,
  `ClienteID` varchar(20) DEFAULT NULL,
  `CuentaID` int(11) DEFAULT NULL,
  `MonedaID` int(11) DEFAULT NULL,
  `ProductoCreditoID` int(4) DEFAULT NULL,
  `DestinoCreID` int(11) DEFAULT NULL,
  `MontoCredito` decimal(12,2) DEFAULT NULL,
  `Relacionado` int(11) DEFAULT NULL,
  `SolicitudCreditoID` int(11) DEFAULT NULL,
  `TipoFondeo` char(1) DEFAULT NULL,
  `InstitFondeoID` int(11) DEFAULT NULL,
  `LineaFondeo` int(11) DEFAULT NULL,
  `FechaInicio` date DEFAULT NULL,
  `FechaVencimien` date DEFAULT NULL,
  `CalcInteresID` int(11) DEFAULT NULL,
  `TasaBase` int(11) DEFAULT NULL,
  `TasaFija` decimal(12,4) DEFAULT NULL,
  `SobreTasa` float DEFAULT NULL,
  `PisoTasa` float DEFAULT NULL,
  `TechoTasa` float DEFAULT NULL,
  `FactorMora` float DEFAULT NULL,
  `FrecuenciaCap` char(1) DEFAULT NULL,
  `PeriodicidadCap` int(11) DEFAULT NULL,
  `FrecuenciaInt` char(1) DEFAULT NULL,
  `PeriodicidadInt` int(11) DEFAULT NULL,
  `TipoPagoCapital` char(1) DEFAULT NULL,
  `NumAmortizacion` int(11) DEFAULT NULL,
  `MontoCuota` decimal(12,2) DEFAULT NULL,
  `FechTraspasVenc` date DEFAULT NULL,
  `FechTerminacion` date DEFAULT NULL,
  `IVAInteres` decimal(12,2) DEFAULT NULL,
  `IVAComisiones` decimal(12,2) DEFAULT NULL,
  `Estatus` char(1) DEFAULT NULL,
  `FechaAutoriza` date DEFAULT NULL,
  `UsuarioAutoriza` int(11) DEFAULT NULL,
  `SaldoCapVigent` decimal(14,2) DEFAULT NULL,
  `SaldoCapAtrasad` decimal(14,2) DEFAULT NULL,
  `SaldoCapVencido` decimal(14,2) DEFAULT NULL,
  `SaldCapVenNoExi` decimal(14,2) DEFAULT NULL,
  `SaldoInterOrdin` decimal(14,4) DEFAULT NULL,
  `SaldoInterAtras` decimal(14,4) DEFAULT NULL,
  `SaldoInterVenc` decimal(14,4) DEFAULT NULL,
  `SaldoInterProvi` decimal(14,4) DEFAULT NULL,
  `SaldoIntNoConta` decimal(14,4) DEFAULT NULL,
  `SaldoIVAInteres` decimal(12,2) DEFAULT NULL,
  `SaldoMoratorios` decimal(14,2) DEFAULT NULL,
  `SaldoIVAMorator` decimal(12,2) DEFAULT NULL,
  `SaldComFaltPago` decimal(12,2) DEFAULT NULL,
  `SalIVAComFalPag` decimal(12,2) DEFAULT NULL,
  `SaldoOtrasComis` decimal(12,2) DEFAULT NULL,
  `SaldoIVAComisi` decimal(12,2) DEFAULT NULL,
  `ProvisionAcum` decimal(14,4) DEFAULT NULL,
  `PagareImpreso` char(1) DEFAULT NULL,
  `FechaInhabil` char(1) DEFAULT NULL,
  `CalendIrregular` char(1) DEFAULT NULL,
  `DiaPagoInteres` char(1) DEFAULT NULL,
  `DiaPagoCapital` char(1) DEFAULT NULL,
  `DiaMesInteres` int(11) DEFAULT NULL,
  `DiaMesCapital` int(11) DEFAULT NULL,
  `AjusFecUlVenAmo` char(1) DEFAULT NULL,
  `AjusFecExiVen` char(1) DEFAULT NULL,
  `NumTransacSim` bigint(20) DEFAULT NULL,
  `FechaMinistrado` date DEFAULT NULL,
  `FolioDispersion` int(11) DEFAULT NULL,
  `SucursalID` int(11) DEFAULT NULL,
  `ValorCAT` decimal(12,4) DEFAULT NULL,
  `ClasifRegID` int(11) DEFAULT NULL,
  `MontoComApert` decimal(12,2) DEFAULT NULL,
  `IVAComApertura` decimal(12,2) DEFAULT NULL,
  `PlazoID` varchar(20) DEFAULT NULL,
  `TipoDispersion` char(1) DEFAULT NULL,
  `TipoCalInteres` int(11) DEFAULT NULL,
  `MontoDesemb` decimal(14,2) DEFAULT NULL,
  `MontoPorDesemb` decimal(14,2) DEFAULT NULL,
  `NumAmortInteres` int(11) DEFAULT NULL,
  `AporteCliente` decimal(12,4) DEFAULT NULL,
  `MontoSeguroVida` decimal(12,2) DEFAULT NULL,
  `SeguroVidaPagado` decimal(12,2) DEFAULT NULL,
  `ForCobroSegVida` char(1) DEFAULT NULL,
  `ComAperPagado` decimal(12,2) DEFAULT NULL,
  `ForCobroComAper` char(1) DEFAULT NULL,
  `ClasiDestinCred` char(1) DEFAULT NULL,
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CreditoID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla de Creditos\n'$$