-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- PARAMETROSCAJA
DELIMITER ;
DROP TABLE IF EXISTS `PARAMETROSCAJA`;DELIMITER $$

CREATE TABLE `PARAMETROSCAJA` (
  `EmpresaID` int(11) NOT NULL DEFAULT '0' COMMENT 'ID de la empresa',
  `CtaOrdinaria` int(11) DEFAULT NULL COMMENT 'Indica el tipo de cuenta que se considera como ordinaria',
  `CuentaVista` int(11) DEFAULT NULL COMMENT 'Indica el Tipo de Cuenta que se considera como vista',
  `CtaProtecCre` char(25) DEFAULT NULL COMMENT 'Cuenta contable de proteccion al credito ',
  `CtaProtecCta` char(25) DEFAULT NULL COMMENT 'Cuenta contable de proteccion al Ahorro',
  `HaberExSocios` char(25) DEFAULT NULL COMMENT 'Cuenta contable de haberes de Exsocios',
  `CtaContaPROFUN` char(25) DEFAULT NULL COMMENT 'Cuenta contable de profun',
  `MaxAtraPagPROFUN` int(11) DEFAULT NULL COMMENT 'Tiempo máximo en meses que puede atrasarse un socio en sus pagos antes de ser inactivado',
  `TipoCtaProtec` int(11) DEFAULT NULL COMMENT 'Tipo de Cuenta a la cual se permitira aplicar el programa de Proteccion de Ahorro y Credito',
  `TipoCtaProtecMen` int(11) DEFAULT NULL COMMENT 'Tipo de Cuenta a la cual se permitira aplicar el programa de Proteccion de Ahorro y Credito a clientes menores de edad',
  `MontoMaxProtec` decimal(14,2) DEFAULT NULL COMMENT 'Monto maximo del Beneficio del Programa de Proteccion al Ahorro y Credito',
  `PerfilAutoriProtec` int(11) DEFAULT NULL COMMENT 'Perfil que puede realizar la autorizacion de proteccion al ahorro y credito ',
  `MontoPROFUN` decimal(14,2) DEFAULT NULL COMMENT 'Monto a recibir como beneficio de programa PROFUN',
  `AporteMaxPROFUN` decimal(14,2) DEFAULT NULL COMMENT 'Monto de la aportacion maxima de los socios incritos en la mutual de PROFUN',
  `PerfilCancelPROFUN` int(11) DEFAULT NULL COMMENT 'Perfil que puede cancelar un registro en PROFUN\n\n',
  `MontoApoyoSRVFUN` decimal(12,2) DEFAULT NULL COMMENT 'Monto del Apoyo del Servicio Funerario',
  `MonApoFamSRVFUN` decimal(14,2) DEFAULT NULL COMMENT 'Monto de Apoyo por defuncion de familiar.',
  `PerfilAutoriSRVFUN` int(11) DEFAULT NULL COMMENT 'Rol del Pefil que puede hacer autorizaciones',
  `EdadMaximaSRVFUN` int(11) DEFAULT NULL COMMENT 'Edad al Ingresar a la Institucion',
  `TiempoMinimoSRVFUN` int(11) DEFAULT NULL COMMENT 'Tiempo Minimo de haber Ingresado. Expresado en meses',
  `MesesValAhoSRVFUN` int(11) DEFAULT NULL COMMENT 'Numero de Meses a Validar el Ahorro',
  `SaldoMinMesSRVFUN` decimal(12,2) DEFAULT NULL COMMENT 'Saldo a Validar en Ahorro',
  `CtaContaSRVFUN` char(25) DEFAULT NULL COMMENT 'Cuenta Contable de ServiFun',
  `RolAutoApoyoEsc` int(11) DEFAULT NULL COMMENT 'Rol del perfil que puede autorizar el apoyo escolar',
  `TipoCtaApoyoEscMay` int(11) DEFAULT NULL COMMENT 'Tipo de Cuenta de Ahorro para apoyo escolar de socio mayor de edad',
  `TipoCtaApoyoEscMen` int(11) DEFAULT NULL COMMENT 'Tipo de Cuenta de Ahorro para apoyo escolar de socio menor de edad',
  `MesInicioAhoCons` int(2) DEFAULT NULL,
  `MontoMinMesApoyoEsc` decimal(12,2) DEFAULT NULL COMMENT 'Monto minimo que debe tener ahorrado el socio  en el mes',
  `CtaContaApoyoEsc` char(25) DEFAULT NULL COMMENT 'Cuenta Contable de apoyo escolar',
  `CompromisoAhorro` decimal(14,2) DEFAULT NULL COMMENT 'indica la cantidad de compromiso de ahorro por mes',
  `PorcentajeCob` decimal(12,2) DEFAULT NULL COMMENT 'Indica el porcentaje de cobertura utilizado en los cálculos de estimación de capacidad pago',
  `CoberturaMin` decimal(12,2) DEFAULT NULL COMMENT 'Indica el porcentaje de cobertura mínima',
  `TipoCtaBeneCancel` int(11) DEFAULT NULL COMMENT 'Indica el Tipo de Cuenta para tomar los beneficiarios en la solicitud de cancelacion',
  `CtaContaPerdida` char(25) DEFAULT NULL COMMENT 'Cuenta contable que se afectara para registrar la perdida ocasionada por cancelacion de socios',
  `EjecutivoFR` int(11) DEFAULT NULL COMMENT 'Sirve para indicar el rol que corresponde al Ejecutivo FR que se usara en los WS de la caja',
  `CCHaberesEx` varchar(30) DEFAULT NULL COMMENT 'Nomenclatura para indicar el Centro de Costos a Usar en la Cuenta Contable de Haberes de Exosios\n&SC = Sucursal Cliente \n&SO = sucursal Origen de la Operacion',
  `CCProtecAhorro` varchar(30) DEFAULT NULL COMMENT 'Nomenclatura para indicar el Centro de Costos a usar en el Programa de Proteccion al Ahorro y Crédito\n&SC = Sucursal Cliente \n&SO = sucursal Origen de la Operacion',
  `CCServifun` varchar(30) DEFAULT NULL COMMENT 'Nomenclatura para indicar el Centro de Costos a usar en el Programa Gastos de Sepelio\n&SC = Sucursal Cliente \n&SO = sucursal Origen de la Operacion',
  `CCApoyoEscolar` varchar(30) DEFAULT NULL COMMENT 'Nomenclatura para indicar el Centro de Costos a usar en el Programa de Apoyo Escolar\n&SC = Sucursal Cliente \n&SO = sucursal Origen de la Operacion',
  `CCContaPerdida` varchar(30) DEFAULT NULL,
  `EdadMinimaCliMen` int(11) DEFAULT NULL COMMENT 'Edad mínima (en años) de un cliente para que sea considerado con cliente menor',
  `EdadMaximaCliMen` int(11) DEFAULT NULL COMMENT 'Edad máxima (en años) de un cliente para que sea considerado con cliente menor',
  `GastosRural` decimal(12,2) DEFAULT NULL COMMENT 'Monto Minimo de Gastos segun la zona Rural ',
  `GastosUrbana` decimal(12,2) DEFAULT NULL COMMENT 'Monto de Gastos Minimo segun la Zona Urbana',
  `IDGastoAlimenta` int(11) DEFAULT NULL COMMENT 'ID de Gastos de Alimentacion corresponde con la tabla CATDATSOCIOE',
  `GastosPasivos` varchar(200) DEFAULT NULL COMMENT 'Indica el ID de los  gastos que serán considerados como pasivos  corresponde con la tabla CATDATSOCIOE',
  `PuntajeMinimo` decimal(14,2) DEFAULT NULL COMMENT 'Puntos minimos que se se considera para el calculo del Ratios en caso que no se alcance este puntaje minimo la Solicitud de Credito será cancelada en el proceso de ratios',
  `VersionWS` varchar(40) DEFAULT NULL COMMENT 'Se utiliza para saber que version de ws de entura se usara.',
  `RolCancelaCheque` int(11) DEFAULT NULL COMMENT 'Rol para  autorizar la cancelacion del cheque',
  `CodCooperativa` varchar(9) DEFAULT NULL COMMENT 'Codigo que se utiliza en el Sistema Entura.',
  `CodMoneda` varchar(3) DEFAULT NULL COMMENT 'Especifica el código de moneda de la cuenta del cliente,\nDe acuerdo a la norma ISO3166-1, el valor asignado a la moneda mexicana es “484”.',
  `CodUsuario` varchar(19) DEFAULT NULL COMMENT 'Nick del usuario que hace el proceso, este usuario debe estar registrado en el Sistema Entura.',
  `PermiteAdicional` char(1) DEFAULT NULL COMMENT 'Especifica si permite una tarjeta adicional.\nS.- Si permite\nN.- No permite',
  `TipoProdCap` char(1) DEFAULT NULL COMMENT 'Tipo de producto de captacion\n',
  `AntigueSocio` int(11) DEFAULT NULL COMMENT 'Antiguedad del socio.',
  `MontoAhoMes` decimal(18,4) DEFAULT NULL COMMENT 'Monto de ahorro por mes.',
  `ImpMinParSoc` decimal(18,4) DEFAULT NULL COMMENT 'Importe minimo parte social.',
  `MesesEvalAho` int(11) DEFAULT NULL COMMENT 'Meses de evaluacion de ahorro.',
  `ValidaCredAtras` char(1) DEFAULT NULL COMMENT 'Valida creditos atrasados.',
  `ValidaGaranLiq` char(1) DEFAULT NULL COMMENT 'Si se valida la garantia liquida en el monto de ahorro de meses.',
  `montoMaxActCom` decimal(14,2) DEFAULT NULL,
  `montoMinActCom` decimal(14,2) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `MesesConsPago` int(11) DEFAULT '0' COMMENT 'Minimo de Meses Consantes de Pago para Autorizar solicitud PROFUN',
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` int(15) DEFAULT NULL,
  PRIMARY KEY (`EmpresaID`),
  KEY `FK_CuentaCompleta_1` (`CtaProtecCre`),
  KEY `FK_CuentaCompleta_2` (`CtaProtecCta`),
  KEY `FK_CuentaCompleta_3` (`HaberExSocios`),
  KEY `FK_CuentaCompleta_4` (`CtaContaPROFUN`),
  KEY `FK_CuentaCompleta_5` (`CtaContaSRVFUN`),
  KEY `FK_RolID_1` (`RolAutoApoyoEsc`),
  KEY `FK_TipoCuentaID_2` (`TipoCtaApoyoEscMay`),
  KEY `FK_TipoCuentaID_3` (`TipoCtaApoyoEscMen`),
  KEY `FK_CuentaCompleta_6` (`CtaContaApoyoEsc`),
  KEY `FK_TipoCuentaID_4` (`CtaOrdinaria`),
  KEY `fk_PARAMETROSCAJA_1_idx` (`CtaContaPerdida`),
  KEY `fk_PARAMETROSCAJA_2_idx` (`TipoCtaBeneCancel`),
  KEY `fk_PARAMETROSCAJA_3_idx` (`CuentaVista`),
  KEY `fk_PARAMETROSCAJA_4_idx` (`IDGastoAlimenta`),
  CONSTRAINT `FK_CuentaCompleta_1` FOREIGN KEY (`CtaProtecCre`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`),
  CONSTRAINT `FK_CuentaCompleta_2` FOREIGN KEY (`CtaProtecCta`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`),
  CONSTRAINT `FK_CuentaCompleta_3` FOREIGN KEY (`HaberExSocios`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`),
  CONSTRAINT `FK_CuentaCompleta_4` FOREIGN KEY (`CtaContaPROFUN`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`),
  CONSTRAINT `FK_CuentaCompleta_5` FOREIGN KEY (`CtaContaSRVFUN`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`),
  CONSTRAINT `FK_CuentaCompleta_6` FOREIGN KEY (`CtaContaApoyoEsc`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RolID_1` FOREIGN KEY (`RolAutoApoyoEsc`) REFERENCES `ROLES` (`RolID`),
  CONSTRAINT `FK_TipoCuentaID_2` FOREIGN KEY (`TipoCtaApoyoEscMay`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`),
  CONSTRAINT `FK_TipoCuentaID_3` FOREIGN KEY (`TipoCtaApoyoEscMen`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`),
  CONSTRAINT `FK_TipoCuentaID_4` FOREIGN KEY (`CtaOrdinaria`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARAMETROSCAJA_1` FOREIGN KEY (`CtaContaPerdida`) REFERENCES `CUENTASCONTABLES` (`CuentaCompleta`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARAMETROSCAJA_2` FOREIGN KEY (`TipoCtaBeneCancel`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARAMETROSCAJA_3` FOREIGN KEY (`CuentaVista`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla para guardar los parametros de caja'$$