-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- PARAMETROSSIS
DELIMITER ;
DROP TABLE IF EXISTS `PARAMETROSSIS`;
DELIMITER $$


CREATE TABLE `PARAMETROSSIS` (
  `EmpresaID` int(11) NOT NULL COMMENT 'Numero o ID\nde la Empresa',
  `FechaSistema` date DEFAULT NULL COMMENT 'Fecha del Sistema',
  `SucursalMatrizID` int(11) DEFAULT NULL COMMENT 'No Sucursal Matriz',
  `TelefonoLocal` varchar(20) DEFAULT NULL COMMENT 'Telefono Local',
  `TelefonoInterior` varchar(20) DEFAULT NULL COMMENT 'Telefono Corporativo\nInterior de la Rep',
  `InstitucionID` int(11) DEFAULT NULL COMMENT 'Numero de\nInstitucion',
  `EmpresaDefault` int(11) DEFAULT NULL COMMENT 'Numero Default\nde  Empresa\no Compania',
  `NombreRepresentante` varchar(100) DEFAULT NULL COMMENT 'Nombre del\nRepresentante\nLegal de la\nEmpresa',
  `RFCRepresentante` varchar(13) DEFAULT NULL COMMENT 'RFC del Rep\nLegal de la \nEmpresa',
  `MonedaBaseID` int(11) DEFAULT NULL COMMENT 'Moneda Base',
  `MonedaExtrangeraID` int(11) DEFAULT NULL COMMENT 'Moneda Extrangera',
  `TasaISR` decimal(12,2) DEFAULT NULL,
  `TasaIDE` decimal(12,2) DEFAULT NULL,
  `MontoExcIDE` decimal(12,2) DEFAULT NULL COMMENT 'Monto Excento para el IDE',
  `EjercicioVigente` int(11) DEFAULT NULL COMMENT 'Ejercicio Contable\nVigente',
  `PeriodoVigente` int(11) DEFAULT NULL COMMENT 'Periodo Contable\nVigente',
  `DiasInversion` int(11) DEFAULT NULL COMMENT 'Dias Base\nPara el modulo \nde Inversiones',
  `DiasCredito` int(11) DEFAULT NULL COMMENT 'Dias Base\nPara el modulo \nde Creditos',
  `DiasCambioPass` int(11) DEFAULT NULL COMMENT 'numero de Dias de cambio de password\n(cada cuantos dias se cambia)\n\n',
  `LonMinCaracPass` int(11) DEFAULT NULL COMMENT 'Longitud minima de caracteres del password\n',
  `ClienteInstitucion` int(11) DEFAULT NULL COMMENT 'numero de cliente de institucion ',
  `CuentaInstituc` bigint(12) DEFAULT NULL,
  `ManejaCaptacion` char(1) DEFAULT NULL,
  `BancoCaptacion` int(11) DEFAULT NULL,
  `TipoCuenta` int(11) DEFAULT NULL COMMENT 'Es tipo de Cuenta que tien asiganada el modulo de tesoreria que solo existe una Cuenta Bancaria',
  `RutaArchivos` varchar(150) DEFAULT NULL COMMENT 'Ruta en donde \nse guardan los \narchivos del\ncliente',
  `OficialCumID` int(11) DEFAULT NULL COMMENT 'Corresponde con el UsuarioID  de la tabla USUARIOS',
  `DirGeneralID` int(11) DEFAULT NULL COMMENT 'Corresponde con el UsuarioID  de la tabla USUARIOS',
  `DirOperID` int(11) DEFAULT NULL COMMENT 'Corresponde con el UsuarioID  de la tabla USUARIOS',
  `NombreJefeCobranza` varchar(100) DEFAULT NULL,
  `NomJefeOperayPromo` varchar(100) DEFAULT NULL,
  `RolTesoreria` int(11) DEFAULT NULL COMMENT 'Indica cual es el rol que debera de usar el usuario de tesoreria',
  `RolAdminTeso` int(11) DEFAULT NULL COMMENT ' Indica cual es el rol que debera de usar el usuario que corresponda con la administracion general de tesoreria',
  `RutaArchivosPLD` varchar(200) DEFAULT NULL,
  `Remitente` varchar(50) DEFAULT NULL COMMENT 'Correo del Remitente',
  `ServidorCorreo` varchar(30) DEFAULT NULL COMMENT 'Servidor de Correo',
  `Puerto` varchar(10) DEFAULT NULL COMMENT 'Puerto',
  `Contrasenia` varchar(20) DEFAULT NULL COMMENT 'Contraseña del remitente',
  `TipoCtaGLAdi` int(11) DEFAULT NULL COMMENT 'Indica el numero de tipo de cuenta que  se le dara al cliente para depositar la garantia liquida adicional\n',
  `CtaIniGastoEmp` varchar(45) DEFAULT NULL COMMENT 'Cuenta Inicial Gasto Empleado (filtro para Cuentas Contables)',
  `CtaFinGastoEmp` varchar(45) DEFAULT NULL COMMENT 'Cuenta Final Gasto Empleado (filtro para Cuentas Contables)',
  `ImpTicket` varchar(50) DEFAULT NULL COMMENT 'Nombre de la Impresora de Tickets',
  `TipoImpTicket` char(1) DEFAULT NULL COMMENT 'Tipo de Papel en el que se imprimira el ticket\nC: Tamanio Carta\nT: Tamanio Ticket',
  `MontoAportacion` decimal(14,2) DEFAULT NULL COMMENT 'Indica la Cantidad que deben de aportar los Socios de una caja de Ahorro  en Ventanilla (Monto de Aportacion Social)',
  `ReqAportacionSo` char(1) DEFAULT NULL COMMENT 'Indica si se Requiere Aportacion del Socio en Instrumentos (CUENTAS DE AHORRO)\nS= SI\nN=NO',
  `MontoPolizaSegA` decimal(14,2) DEFAULT NULL COMMENT 'Monto  de la poliza del Seguro de Apoyo en caso de Siniestro',
  `MontoSegAyuda` decimal(14,2) DEFAULT NULL COMMENT 'Monto que el cliente debe de pagar del Seguro de Apoyo',
  `CuentasCapConta` varchar(200) NOT NULL COMMENT 'Cuentas de Capital Contable',
  `LonMinPagRemesa` int(2) DEFAULT NULL COMMENT 'Longitud Minima del folio (Referencia) del pago de remesas  ',
  `LonMaxPagRemesa` int(2) DEFAULT NULL COMMENT 'Longitud Maxima del folio (referencia) del pago de remesas  ',
  `LonMinPagOport` int(2) DEFAULT NULL COMMENT 'Longitud Minima del Folio(Referencia) del Pago de Oportunidades',
  `LonMaxPagOport` int(2) DEFAULT NULL COMMENT 'Longitud Maxima del Folio (referencia) del Pago de Oportunidades',
  `SalMinDF` decimal(12,2) DEFAULT NULL COMMENT 'Indica el valor de la unidad de medida y actualizacion (UMA),\nutilizada para el calculo de ISR.',
  `SaldoCapContable` decimal(14,2) DEFAULT NULL COMMENT 'Saldo del Capital Contable, se calcula y actualiza en el Cierre de Diario',
  `DiasVigenciaBC` int(11) DEFAULT NULL COMMENT 'Es el número de  Días de Vigencia que tiene la consulta de \nBuro de Crédito de una persona',
  `ImpSaldoCred` char(1) DEFAULT NULL COMMENT 'indica si se imprimirá  en ticket el monto del proximo pago, fecha del proximo pago y saldo del credito despues de realizar el pago del credito\nSi= S\nNo =N',
  `ImpSaldoCta` char(1) DEFAULT NULL COMMENT 'Indica si se imprimira el saldo de la cuenta en el ticket abono a cuenta ',
  `GerenteGeneral` varchar(100) DEFAULT NULL,
  `PresidenteConsejo` varchar(100) DEFAULT NULL,
  `JefeContabilidad` varchar(100) DEFAULT NULL,
  `RecursoTicketVent` varchar(200) DEFAULT NULL COMMENT 'Recurso de ticket en ventanilla',
  `VigDiasSeguro` int(11) DEFAULT NULL COMMENT 'Dias de Vigencia del Seguro de Vida',
  `VencimAutoSeg` char(1) DEFAULT NULL COMMENT 'VENCIMIENTO  Automatica de Seguro',
  `TimbraEdoCta` char(1) DEFAULT NULL COMMENT 'Campo que indica si se realizara el Timbrado para los Estados de Cuenta\nS.- Si\nN.- No',
  `GeneraCFDINoReg` char(1) DEFAULT NULL COMMENT 'Campo que indica si se genera CFDI para Clientes NO registrados en SAT',
  `GeneraEdoCtaAuto` char(1) DEFAULT NULL COMMENT 'Campo que indica si se realiza la generacion de Edo de Cta Automatico despues del Cierre de Mes',
  `EstCreAltInvGar` varchar(50) DEFAULT NULL COMMENT 'Estatus que tendra el credito para poder dar de alta una inversion en garantia',
  `AplCobPenCieDia` char(1) DEFAULT NULL COMMENT 'Parametro para saber si aplica o no el procesos de cobros pendientes en el cierre de dia.',
  `UsuarioFactElec` varchar(45) DEFAULT NULL COMMENT 'Usuario ID para realizar la conexion con el Web Service \nde Timbrado, Cancelacion y Envio de Certificados del PAC',
  `PassFactElec` varchar(150) DEFAULT NULL COMMENT 'Password para realizar la conexion con el Web Service \nde Timbrado, Cancelacion y Envio de Certificados del PAC',
  `RFCFactElec` varchar(20) DEFAULT NULL COMMENT 'RFC para realizar Timbrado de Facturas Electronicas',
  `UrlWSDLFactElec` varchar(200) DEFAULT NULL COMMENT 'URL del WSDL con los Servicios de Timbrado PAC',
  `FecUltConsejoAdmon` date DEFAULT NULL COMMENT 'Ultima Fecha de Reunion del Consejo de Admon',
  `FoliosActasComite` char(1) DEFAULT NULL COMMENT 'Folio Automatico en Actas de Comite S .- Si, N .- No',
  `ServReactivaCte` int(11) DEFAULT NULL COMMENT 'Numero de servicio que pertenece a la Reactivacion del Cliente',
  `CtaContaSobrante` varchar(25) DEFAULT NULL COMMENT 'Cuenta Contable Para Faltantes en Ventanilla',
  `CtaContaFaltante` varchar(25) DEFAULT NULL COMMENT 'Cuenta Contable para Faltantes en Ventanilla',
  `CalifAutoCliente` char(1) DEFAULT NULL COMMENT 'Indica si se calificará automaticamente al cliente en el cierre de dia',
  `CtaContaDocSBCD` varchar(45) DEFAULT NULL COMMENT 'Cuenta Contable Documentos de Cobro Inmediato Salvo Buen Cobro Cuenta de Orden Deudora',
  `CtaContaDocSBCA` varchar(45) DEFAULT NULL COMMENT 'Cuenta Contable de  Documentos de Cobro Inmediato Salvo Buen Cobro Cuenta de Orden Acreedora',
  `AfectaContaRecSBC` char(1) DEFAULT NULL COMMENT 'Afectacion Contable en la Recepcion de Documentos SBC\nS=''SI''\nN=''N''',
  `ContabilidadGL` char(1) DEFAULT NULL COMMENT 'Indica si requiere anexar detalles de garanti liquida en contabilidad',
  `CenCostosChequeSBC` varchar(30) DEFAULT NULL COMMENT 'Debe de guardar &SO o en su caso &SC',
  `MostrarSaldDisCtaYSbc` char(1) DEFAULT NULL COMMENT 'Registra "S" o "N" para mostrar el saldo disponible de la cuenta.',
  `TipoContaMora` char(1) DEFAULT NULL COMMENT 'Tipo de Contabilizacion de los Moratorios, C .- Cuentas de Orden, I .- Ingresos',
  `DivideIngresoInteres` char(1) DEFAULT NULL COMMENT 'Dividir Ingresos por Interes de Cartera Vigente y Vencida .- S .- Si, N.-No',
  `ValidaAutComite` char(1) DEFAULT NULL COMMENT 'Especifica si validará que el Producto de Crédito aplica para funcionarios,empleados o relacionados a estos en una solicitud de credito, \nS=Si  \nN=No',
  `ExtTelefonoLocal` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extensión de teléfono Local',
  `ExtTelefonoInt` varchar(6) DEFAULT NULL COMMENT 'Contieneel número de extensión de teléfono Interior',
  `DetecOpeRelevante` char(1) DEFAULT NULL COMMENT 'Especifica si en el cierre diario validará automáticamente operaciones relevantes acumuladas en el mes, S=SI, N=NO',
  `DetecOpeInusual` char(1) DEFAULT NULL COMMENT 'Especifica si en el cierre diario validará automáticamente operaciones inusuales acumuladas en el mes, S=SI, N=NO',
  `CancelaAutMenor` char(1) DEFAULT NULL COMMENT 'Indica si se cancela de manera Automatica los menores que cumplan mayoria de edad N=NO S=SI',
  `FuncionHuella` char(1) DEFAULT NULL COMMENT 'Indica si se validaran los procesos por huella digital S=SI N=NO',
  `ValidaClaveKey` varchar(80) DEFAULT NULL COMMENT 'Indica si se valida clave key ',
  `NomCortoInstit` varchar(45) DEFAULT NULL COMMENT 'Nombre Corto de la Institucion, \npara claves activacion',
  `ReqHuellaProductos` char(1) DEFAULT NULL COMMENT 'Indica si es Requerido la Huella Digital del Cliente para creacion de Productos',
  `ConBuroCreDefaut` char(1) DEFAULT NULL COMMENT 'Indica cual es el valor por default para las consultas:\nB - Buro\nC - Circulo',
  `AbreviaturaCirculo` char(3) DEFAULT NULL COMMENT 'Abreviatura del cliente que llevara el numero de firma, requerido para circulo de credito',
  `ActivaPromotorCapta` char(1) DEFAULT NULL COMMENT 'S.- Activa campos de Promotor de Captación\nN.- Oculta campos de Promotor de Captación',
  `CambiaPromotor` char(1) DEFAULT NULL COMMENT 'Si se puede cambiar el promotor SI = ''S'' o NO = ''N''',
  `MostrarPrefijo` char(1) DEFAULT 'N' COMMENT 'MultiBases(Para determinar si el nombre de usuario tendra prefijo N.-No  S.-Si)',
  `TesoMovsCieMes` char(1) DEFAULT NULL COMMENT 'S - Se pemiten hacer movimientos aun cuando se haya realizado el cierre de mes',
  `ChecListCte` char(1) DEFAULT NULL COMMENT 'Indica si el proceso de cliente requiere de check List',
  `TarjetaIdentiSocio` char(1) DEFAULT NULL COMMENT 'indica si se requiere usar tarjeta para identficar el socio/cliente',
  `CancelaAutSolCre` char(1) DEFAULT NULL COMMENT 'Indica si se requiere realizar la cancelacion automatica de las solicitudes de credito',
  `DiasCancelaAutSolCre` int(11) DEFAULT NULL COMMENT 'Indica los días en que se cancelaran automaticamente las solicitudes de credito',
  `NumTratamienCre` int(11) DEFAULT NULL COMMENT 'Numero de veces que se permite renovar un mismo credito',
  `CapitalCubierto` decimal(12,2) DEFAULT NULL COMMENT 'Procentaje de Capital minimo cubierto del credito para permitir su renovacion o reestructura',
  `PagoIntVertical` char(1) DEFAULT NULL COMMENT 'Forma de pago de intereses con cargo a cuenta para Renovacion de credito, S=Total exigible, N= Parciales',
  `NumMaxDiasMora` int(11) DEFAULT NULL COMMENT 'Numero maximo de dias de mora para permitir reestructura del credito',
  `ClaveNivInstitucion` varchar(6) DEFAULT NULL,
  `CuentaEprc` varchar(10) DEFAULT NULL,
  `ClaveEntidad` varchar(6) DEFAULT NULL COMMENT 'Clave de la Entidad Financiera',
  `ImpFomatosInd` char(1) DEFAULT NULL COMMENT 'Indica si se imprimiran los formatos individuales al momento de imprimir un pagare grupal o el plan de pagos.',
  `ReqValidaCred` char(1) NOT NULL DEFAULT 'N' COMMENT 'Indica si requiere Validar el Credito antes de ser desembolsado',
  `FechaISR` date DEFAULT NULL,
  `SistemasID` int(11) DEFAULT NULL COMMENT 'Clave de Usuario que se encuentra como encargado del Area de Sistemas o Tecnologias de la Informacion.',
  `RutaNotifiCobranza` varchar(100) NOT NULL DEFAULT '' COMMENT 'Ruta de Documentos de Notificaciones de Cobranza',
  `CobraSeguroCuota` char(1) DEFAULT NULL COMMENT 'Indica si los productos permiten el cobro de seguro por Cuota. \nS: SI N: NO',
  `PerfilWsVbc` int(11) NOT NULL DEFAULT '0' COMMENT 'INDICA EL PERFIL QUE SE UTILIZA EN LOS WS VBC',
  `TipoDocumentoFirma` int(11) DEFAULT NULL COMMENT 'ID del Tipo de Documento',
  `ReestCalVenc` char(1) DEFAULT 'N' COMMENT 'Indica si se permite realizar una Reestructura a un Credito con el Calendario de Pagos Vencido\nS: SI N: NO',
  `EstValReest` char(1) DEFAULT 'S' COMMENT 'Indica si se permite realizar una Reestructura a un Credito con estatus Vigente\nS: SI N: NO',
  `TipoDetRecursos` int(11) DEFAULT '1' COMMENT 'Indica el tipo de detalle que se mostrara en el reporte bitacora de accesos 1= mostrara ruta safi, 2= nombre del recurso',
  `CalculaCURPyRFC` char(1) DEFAULT 'S' COMMENT 'Indica si se mostrara el boton para calcular la CURP y RFC en pantalla, S= si, N=no',
  `ManejaCarteraAgro` char(1) DEFAULT 'N' COMMENT 'Indica si la linea del negocio es Agropecuaria  S= SI N= NO.',
  `SalMinDFReal` decimal(12,2) DEFAULT NULL COMMENT 'Indica el salario Minimo del DF',
  `EvaluacionMatriz` char(1) DEFAULT 'N' COMMENT 'Indica si se realizará la Evaluación Periódica del Nivel de Riesgo de todos\nlos Clientes, de acuerdo a la Matriz de Riesgos.\nS.- SI\nN.- NO',
  `FrecuenciaMensual` int(11) DEFAULT '0' COMMENT 'Indica la frecuencia con la que se realizará la evaluación del Nivel de Riesgo de todos\nlos Clientes, de acuerdo a la Matriz de Riesgos. Este campo es expresado en Meses y \ndepende del campo EvaluacionMatriz.',
  `FechaEvaluacionMatriz` date DEFAULT '1900-01-01' COMMENT 'Indica la fecha en la que se realizará la evaluación del Nivel de Riesgo de todos\nlos Clientes. Esta fecha se calcula de acuerdo con la FrecuenciaMensual a partir de \nla fecha del sistema. Es el último día del mes.',
  `ActPerfilTransOpe` char(1) DEFAULT 'N' COMMENT 'Indica si se realizará la Actualización del Perfil Transaccional Operativo de los Clientes:\nS.- SI\nN.- NO',
  `FrecuenciaMensPerf` int(11) DEFAULT '0' COMMENT 'Indica la frecuencia con la que se realizará la actualización del perfil transaccional de los Clientes. Este campo es expresado en Meses y \ndepende del campo ActPerfilTransOpe.',
  `FechaActPerfil` date DEFAULT '1900-01-01' COMMENT 'Indica la fecha en la que se realizará la actualizacion del perfil transaccional operativo de todos\nlos Clientes. Esta fecha se calcula de acuerdo con la FrecuenciaMensPerf a partir de \nla fecha del sistema. Es el último día del mes.',
  `PorcCoincidencias` decimal(14,2) DEFAULT '100.00' COMMENT 'Porcentaje de Coincidencias en Deteccion en Listas aplica en los campos de Nombres y Apellidos.',
  `TipoMatrizPLD` int(11) DEFAULT '1' COMMENT 'Tipo de Matriz que ocupara el SAFI. 1. Conceptos 2. Porcentaje',
  `ModNivelRiesgo` char(1) DEFAULT 'N' COMMENT 'Define si puede modifcar el Nivel de Riesgo el O.C',
  `ValidarVigDomi` char(1) DEFAULT 'N' COMMENT 'Indica si se valida o no la vigencia del tipo de documento de domicilio\n',
  `FecVigenDomicilio` int(11) DEFAULT NULL COMMENT 'Campo que almacena el periodo en mese para la vigencia del documento de domicilio',
  `TipoDocDomID` int(11) DEFAULT NULL COMMENT 'Tipo de Documento ID TIPOSDOCUMENTOS',
  `CobranzaAutCierre` char(1) DEFAULT 'N' COMMENT 'Indica si se ejecuta la cobranza automatica como parte del cierre diario.\nS: SI\nN: NO\n',
  `CobroCompletoAut` char(1) DEFAULT 'N' COMMENT 'Indica si el proceso de cobranza a automatica aplicara el pago solo cuando se realicen pagos completos.\n\nS: Se aplica el pago solo cuando el saldo disponible de la cuenta pueda cubrir el total del pago de la amortizacion.\nN: Aplica el pago a la amortizacion con lo que tenga disponible el saldo de la cuenta del cliente, no es obligatorio realizar pagos completos.',
  `CapitalCubiertoReac` decimal(12,2) DEFAULT '0.00',
  `PorcPersonaFisica` decimal(14,2) DEFAULT '5.00' COMMENT 'Porcentaje permitido para que el saldo de los creditos del relacionado no sea mayor al capital neto.',
  `PorcPersonaMoral` decimal(14,2) DEFAULT '7.00' COMMENT 'Porcentaje permitido para que el saldo de los creditos del relacionado no sea mayor al capital neto.',
  `FechaConsDisp` char(1) DEFAULT 'N' COMMENT 'S=Si / N=No fecha de consulta disponible',
  `ActPerfilTransOpeMas` char(1) DEFAULT 'N' COMMENT 'Indica si se realizará la evaluacion masiva del Perfil Transaccional Operativo de los Clientes:\\nS.- SI\\nN.- NO',
  `NumEvalPerfilTrans` int(11) DEFAULT '0' COMMENT 'Numero de Mese  que se ejcuta la evaluacion.',
  `FechaSigEvalMasPerf` date DEFAULT NULL COMMENT 'Fecha siguiente en la que se ejecutara el proceso masivo de evaluacion del perfil transaccional.',
  `PerfilAutEspAport` int(11) DEFAULT NULL COMMENT 'Indica el perfil de quien puede autorizar una aportacion especial',
  `PerfilCamCarLiqui` int(11) DEFAULT NULL  COMMENT 'Indica el perfil de quien puede realizar cambios en las cartas de liquidacion',
  `EvaluaRiesgoComun` char(1) DEFAULT 'N' COMMENT 'Indica si se realizara la Evaluacion de Riesgo en la Autorizacion de la Solicitud y Alta de Credito\nS.- SI\nN.- NO',
  `CapitalContableNeto` decimal(14,2) DEFAULT '0.00' COMMENT 'Capital Contable Neto. Se utiliza para evaluar el riesgo Comun de un Credito',
  `InvPagoPeriodico` char(1) DEFAULT 'N' COMMENT 'S: Para realizar el Pago Periodico de las Inversiones.  N: No realiza Pago Periodico',
  `InstitucionCirculoCredito`  VARCHAR(3) NOT NULL COMMENT 'Tipo de Institucíon en Circulo de Crédito',
  `ClaveEntidadCirculo`    INT(11) NOT NULL COMMENT 'Clave de Entidad en Circulo de Crédito',
  `ReportarTotalIntegrantes`   CHAR(1) NOT NULL COMMENT 'Reporta todo los Directivos y Avales del Cliente',
  `DirectorFinanzas` char(1) DEFAULT NULL COMMENT 'Indica el nombre del director de finanzas para los reportes financieros',
  `ValidaFactura` CHAR(1) NULL DEFAULT 'N' COMMENT 'Indica si realizara la validacion de las facturas en la pantalla de facturacion a proveedores\nS = SI\nN = NO',
  `ValidaFacturaURL` VARCHAR(150) NULL COMMENT 'Ruta del WS que realizra la validacion de los xml de las facturas este campo solo se podra agregar info cuando el campo ValidaFactura indica S',
  `TiempoEsperaWS` INT(11) NULL COMMENT 'Tiempo de espera del WS para validar cfdi',
  `NumTratamienCreRees` int(11) DEFAULT NULL COMMENT 'Numero de veces que se permite reestructurar un mismo credito',
  `RestringeReporte` char(1) DEFAULT 'N' COMMENT 'La opcion S=si, limita la visualizacion de la informacion de los reportes del modulo de cartera de acuerdo a la persona que este generando dicho reporte ya que solo podra ver informacion que se va generando de sus subordinados(Organigrama).\nReportes: Vencimientos,  Reestructuras,  Ministraciones,  Saldos de Cartera,  Analitica Cartera,  Pagos de Créditos,  Cartera Castigada\nLa opcion N=no, tendra la funcionalidad de no restringir la informacion de los reportes del modulo de cartera.',
  `CamFuenFonGarFira` CHAR(1)  NOT NULL COMMENT 'Cambio Automático de Fuente de Fondeo por Garantía FIRA \n"S".- SI \n"N".-NO',
  `PersonNoDeseadas` char(1) DEFAULT NULL COMMENT 'Activación del proceso de validación de Personas No deseadas \n"S".- SI \n"N".-NO',
  `OcultaBtnRechazoSol` CHAR(1) NOT NULL COMMENT 'Campo que indica si debe ocultar el boton de rechazo segun el rol indicado. S = SI, N = NO',
  `RestringebtnLiberacionSol` CHAR(1) NOT NULL COMMENT 'Campo que indica si debe restringir la liberacion de solicitud de credito individual segun el rol indicado. S=SI, N =NO',
  `PrimerRolFlujoSolID` INT(11) NOT NULL COMMENT 'Primer rol permitido para la liberacion o rechazo de solicitudes dependiendo de lo parametrizado en OcultaBtnRechazoSol o RestringebtnLiberacionSol',
  `SegundoRolFlujoSolID` INT(11) NOT NULL COMMENT 'Segundo rol permitido para la liberacion o rechazo de solicitudes dependiendo de lo parametrizado en OcultaBtnRechazoSol o RestringebtnLiberacionSol',
  `VecesSalMinVig` INT(11)  COMMENT 'Veces el Salario Mínimo Vigente',
  `CaracterMinimo` INT(11) NOT NULL COMMENT 'Indicara el numero minimo de caracteres del que se compondra una contrasenia.',
  `ReqCaracterMayus` CHAR(1) DEFAULT 'N' COMMENT 'Indicará si la Contrasenia requiere caracteres Mayuscula: S.-SI, N.-NO.',
  `CaracterMayus` INT(11) NOT NULL COMMENT 'indica el numero de caracteres mayusculas en una contrasenia.',
  `ReqCaracterMinus` CHAR(1) DEFAULT 'N' COMMENT 'Indicará si la Contrasenia requiere caracteres Minuscula: S.-SI, N.-NO.',
  `CaracterMinus` INT(11) NOT NULL COMMENT 'Indica el numero de caracteres minusculas en una contrasenia.',
  `ReqCaracterNumerico` CHAR(1) DEFAULT 'N' COMMENT 'Indicará si la Contrasenia requiere caracteres Numericos: S.-SI, N.-NO.',
  `CaracterNumerico` INT(11) NOT NULL COMMENT 'Indica la cantidad de numeros en una contrasenia.',
  `ReqCaracterEspecial` CHAR(1) DEFAULT 'N' COMMENT 'Indicará si la Contrasenia requiere caracteres Especiales: S.-SI, N.-NO.',
  `CaracterEspecial` INT(11) NOT NULL COMMENT 'Indica el numero de caracteres especiales en una contrasenia.' ,
  `UltimasContra` INT(11) NOT NULL COMMENT 'Indica cuantas de las ultimas contrasenias no se pueden utilizar.',
  `DiaMaxCamContra` INT(11) NOT NULL COMMENT 'Indica el numero de dias que pasaran hasta que el sistema solicite una nueva contrasenia al usuario.',
  `DiaMaxInterSesion` INT(11) NOT NULL COMMENT 'Indica el numero en minutos que la sesion se mantendra activa mientras el usuario no tenga interaccion con el sistema.',
  `NumIntentos` INT(11) NOT NULL COMMENT 'Indica el numero de intentos que tendra el usuario antes de que se bloquee el usuario.',
  `NumDiaBloq` INT(11) NOT NULL COMMENT 'Incida el numero de dias que pasarán despues del ultimo acceso al sistema para que el usuario se bloquee automaticamente.',
  `AlerVerificaConvenio` char(2) DEFAULT NULL COMMENT 'Alerta de verificacion de convenios\nS=SI\nN=NO',
  `NoDiasAntEnvioCorreo` int(11) DEFAULT NULL COMMENT 'Número de días antes de la fecha de vencimiento de los convenios para el envío del correo',
  `RemitenteID` int(11) DEFAULT NULL COMMENT 'ID del remitente',
  `CorreoRemitente` varchar(100) DEFAULT NULL COMMENT 'Correo remitente para el envio de notificacion de convenios',
  `CorreoAdiDestino` varchar(500) DEFAULT NULL COMMENT 'Correso alternativos a enviar la notificacion de convenios\n',
  `ClabeInstitBancaria` VARCHAR(10) DEFAULT NULL COMMENT 'Clabe que otorga el banco para el cobro de domiciliacion de nomina',
  `PermitirMultDisp` char(1) DEFAULT 'N' COMMENT 'Indica si se han de permitir multiples dispersiones del monto de un credito o no',
  `DiasAplicaGarantia` int(3) NOT NULL COMMENT 'Indica a los cuantos dias de no pago se realizara la aplicacion Automatica de las Garantias',
  `TipoGarantia` char(1) NOT NULL COMMENT 'Tipo de aplicacion de Garantias\nI=Interes\nC=Capital\nA= Ambos',
  `ValidarEtiqCambFond` CHAR(1) DEFAULT NULL COMMENT 'Campo para validar la etiqueta de cambio de fondeador \n"S".- SI \n"N".-NO',
  `UnificaCI`      CHAR(1)     DEFAULT 'N' NULL COMMENT 'Parametro que permite la activacion de los procesos de unificacion de clientes en ambientes de captacion y cartera para Crediclub.',
  `OrigenReplica`  VARCHAR(50) DEFAULT '' NOT NULL COMMENT 'Indica el datasource al que se replicara el alta de clientes para el cliente Crediclub.',
  `ReplicaAct`     CHAR(1)     DEFAULT 'N' NULL COMMENT 'Indica si las actualizaciones de clientes se replican a un ambiente ALTERno.',
  `CierreAutomatico` CHAR(1) DEFAULT 'M' NOT NULL COMMENT 'Indica si el cierre es autómatico o manual',
  `RutaResCierre` VARCHAR(100) DEFAULT '' NOT NULL COMMENT 'Indica el lugar de respaldo de la BD',
  `BasesDatosCierre` VARCHAR(100) DEFAULT '' NOT NULL COMMENT 'Especifica la BD a ser respaldada',
  `ServidorCierre` VARCHAR(15) DEFAULT '' NOT NULL COMMENT 'Especifica la ip del servidor',
  `UsuarioCierre` VARCHAR(20) DEFAULT '' NOT NULL COMMENT 'Especifica usuario para conectar a la BD',
  `ContraCierre` VARCHAR(45) DEFAULT '' NOT NULL COMMENT 'Especifica la contraseña para conectar a la BD',
  `RemitenteCierreID` INT(11) DEFAULT 0 NOT NULL COMMENT 'Especifica el valor del ID para remitente de correo de cierre día',
  `CorreoRemCierre` VARCHAR(100) DEFAULT '' NOT NULL COMMENT 'Especifica el correo para el remitente de cierre dia',
  `EjecDepreAmortiAut`  CHAR(1) NOT NULL COMMENT 'habilitar o deshabilitar el proceso automático de la aplicación de Depreciación y Amortización. \nN.- NO \nS.-SI',
  `ZonaHoraria` VARCHAR(10) NOT NULL COMMENT 'Campo para la zona horaria de timbrado',
  `ProveedorTimbrado` CHAR(1) NOT NULL DEFAULT 'F' COMMENT 'Tipo de proveedor para realizar el timbrado fiscal (F = Facturacion Moderna, S = SmarterWeb).',
  `ValidaReferencia` char(1) DEFAULT 'N' COMMENT 'Indica si se valida que exista una Referencia relacionada al credito para poder imprimir la tabla de Amortizacion\n S: SI\n N:  NO.',
  `ValidaCapitalConta` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'VALIDA CAPITAL CONTABLE\n S: SI\n N:  NO.',
  `PorMaximoDeposito` VARCHAR(10) DEFAULT 0 COMMENT 'PORCENTAJE MAXIMO DE DEPOSITOS',
  `MostrarBtnResumen` CHAR(1) NOT NULL COMMENT 'Muestra el Botón de Impresión de Resumen en las Pantallas de Ventanilla y Envio SPEI. \nN.- NO \nS.-SI',
  `ValidaCicloGrupo` CHAR(1) DEFAULT 'N' COMMENT 'Indica si se valida el ciclo del grupo de credito de los integrantes relacionados al momento de liberar este mismo S:SI, N:NO',
  `URLCORE` varchar(150) NOT NULL COMMENT 'URL para Core Externo',
  `USUARIOHSM` varchar(150) NOT NULL COMMENT 'Usuario para Core Externo HSM',
  `CONTRASENIAHSM` varchar(150) NOT NULL COMMENT 'Contrasenia para Core Externo HSM',
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  `UsuarioCorreo` varchar(50) DEFAULT NULL,
  `AplicaGarAdiPagoCre` char(1) DEFAULT 'N' COMMENT 'Al estar activo el parametro el sistema devolvera el monto excedente al pago exigible del credito en ingreso de operaciones.',
  `CargaLayoutXLSDepRef` char(1) NOT NULL DEFAULT 'N' COMMENT 'Parametro para leer un layout en formato xls(excel) en el proceso de depositos referenciados, S= Si carga un xls, N=No carga un xls, solo un txt como esta originalmente',
  PRIMARY KEY (`EmpresaID`),
  KEY `fk_Moneda` (`MonedaBaseID`),
  KEY `fk_Institucion` (`InstitucionID`),
  KEY `fk_Sucursal` (`SucursalMatrizID`),
  KEY `fk_PARAMETROSSIS_1` (`ClienteInstitucion`),
  KEY `fk_cuenta` (`CuentaInstituc`),
  KEY `fk_TipoCuentaBan` (`TipoCuenta`),
  KEY `fk_PARAMETROSSIS_2_idx` (`MonedaExtrangeraID`),
  KEY `fk_RolTesoreria_idx` (`RolTesoreria`),
  KEY `fk_RolAdminTeso_idx` (`RolAdminTeso`),
  CONSTRAINT `fk_Institucion` FOREIGN KEY (`InstitucionID`) REFERENCES `INSTITUCIONES` (`InstitucionID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moneda` FOREIGN KEY (`MonedaBaseID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_MonedaExtranjeraID` FOREIGN KEY (`MonedaExtrangeraID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARAMETROSSIS_1` FOREIGN KEY (`ClienteInstitucion`) REFERENCES `CLIENTES` (`ClienteID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RolAdminTeso` FOREIGN KEY (`RolAdminTeso`) REFERENCES `ROLES` (`RolID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_RolTesoreria` FOREIGN KEY (`RolTesoreria`) REFERENCES `ROLES` (`RolID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal` FOREIGN KEY (`SucursalMatrizID`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoCuentaBan` FOREIGN KEY (`TipoCuenta`) REFERENCES `TIPOSCUENTAS` (`TipoCuentaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta` FOREIGN KEY (`CuentaInstituc`) REFERENCES `CUENTASAHO` (`CuentaAhoID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Parametros del Sistema o Aplicacion'$$
