-- PASIVOCAMBIOBASE
DELIMITER ;
DROP TABLE IF EXISTS `PASIVOCAMBIOBASE`;

DELIMITER $$
CREATE TABLE `PASIVOCAMBIOBASE` (
  `CreditoFondeoIDSAFI` bigint(20) NOT NULL,
  PRIMARY KEY (`CreditoFondeoIDSAFI`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tab:Almacena los creditos pasivos'$$