-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- PLDIDENTIDADCTE
DELIMITER ;
DROP TABLE IF EXISTS `PLDIDENTIDADCTE`;DELIMITER $$

CREATE TABLE `PLDIDENTIDADCTE` (
  `ClienteID` int(11) NOT NULL COMMENT 'Número de Cliente ',
  `AplicaCuest` char(1) DEFAULT NULL COMMENT 'Motivo de Aplicación del Cuestionario',
  `OtroAplDetalle` varchar(200) DEFAULT NULL COMMENT 'Otro motivo de aplicación del Cuestionario de Identidad',
  `RealizadoOp` char(1) DEFAULT NULL COMMENT 'Si Realiza Operaciones en Efectivo de Manera Frecuente',
  `FuenteRecursos` char(1) DEFAULT NULL COMMENT 'Fuente de Recursos ',
  `FuenteOtraDet` varchar(200) DEFAULT NULL COMMENT 'Otra  Fuente de Recursos',
  `ObservacionesEjec` varchar(200) DEFAULT NULL COMMENT 'Observaciones del Ejecutivo',
  `NegocioPersona` varchar(45) DEFAULT NULL,
  `TipoNegocio` char(1) DEFAULT NULL,
  `TipoOtroNegocio` varchar(100) DEFAULT NULL,
  `GiroNegocio` varchar(100) DEFAULT NULL,
  `AniosAntig` int(11) DEFAULT NULL,
  `MesesAntig` int(11) DEFAULT NULL,
  `UbicacNegocio` varchar(200) DEFAULT NULL,
  `EsNegocioPropio` char(1) DEFAULT NULL,
  `EspecificarNegocio` varchar(200) DEFAULT NULL,
  `TipoProducto` varchar(500) DEFAULT NULL,
  `MercadoDeProducto` varchar(200) DEFAULT NULL,
  `IngresosMensuales` decimal(14,2) DEFAULT NULL,
  `DependientesEcon` int(11) DEFAULT NULL,
  `DependienteHijo` int(11) DEFAULT NULL,
  `DependienteOtro` int(11) DEFAULT NULL,
  `TipoNuevoNegocio` char(1) DEFAULT NULL,
  `TipoOtroNuevoNegocio` varchar(100) DEFAULT NULL,
  `FteNuevosIngresos` varchar(500) DEFAULT NULL,
  `ParentescoApert` varchar(100) DEFAULT NULL,
  `ParentescoOtroDet` varchar(200) DEFAULT NULL,
  `TiempoEnvio` varchar(50) DEFAULT NULL,
  `CuantoEnvio` decimal(14,2) DEFAULT NULL,
  `TrabajoActual` varchar(100) DEFAULT NULL,
  `LugarTrabajoAct` varchar(300) DEFAULT NULL,
  `CargoTrabajo` varchar(100) DEFAULT NULL,
  `PeriodoDePago` varchar(100) DEFAULT NULL,
  `MontoPeriodoPago` decimal(14,2) DEFAULT NULL COMMENT 'Monto de Pago',
  `TiempoNuevoNeg` varchar(50) DEFAULT NULL,
  `TiempoLaborado` varchar(100) DEFAULT NULL COMMENT 'Tiempo que lleva laborando',
  `DependienteEconSA` int(11) DEFAULT NULL,
  `DependienteHijoSA` int(11) DEFAULT NULL,
  `DependienteOtroSA` int(11) DEFAULT NULL,
  `ProveedRecursos` char(1) DEFAULT NULL,
  `TipoProvRecursos` char(1) DEFAULT NULL,
  `NombreCompProv` varchar(100) DEFAULT NULL,
  `DomicilioProv` varchar(300) CHARACTER SET big5 DEFAULT NULL,
  `FechaNacProv` date DEFAULT NULL,
  `NacionalidadProv` varchar(100) DEFAULT NULL,
  `RfcProv` varchar(18) DEFAULT NULL,
  `RazonSocialProvB` varchar(100) DEFAULT NULL,
  `NacionalidProvB` varchar(100) DEFAULT NULL,
  `RfcProvB` varchar(18) DEFAULT NULL,
  `DomicilioProvB` varchar(300) DEFAULT NULL,
  `PropietarioDinero` char(1) DEFAULT NULL COMMENT 'Propietario Real ---> Propietario del dinero \nFamiliar \nOtros',
  `PropietarioOtroDet` varchar(100) DEFAULT NULL COMMENT 'Propietario Real ----> El propietario no es un Familiar ',
  `PropietarioNombreCom` varchar(45) DEFAULT NULL COMMENT 'Propietario Real ------->Nombre completo del propietario Real',
  `PropietarioDomicilio` varchar(300) DEFAULT NULL COMMENT 'Propietario Real ------->Domicilio del propietario Real',
  `PropietarioNacio` varchar(100) DEFAULT NULL COMMENT 'Propietario Real ------->Nacionalidad\n',
  `PropietarioCurp` varchar(18) DEFAULT NULL,
  `PropietarioRfc` varchar(18) DEFAULT NULL,
  `PropietarioGener` char(1) DEFAULT NULL COMMENT 'Propietario Real ------->Genero',
  `PropietarioOcupac` varchar(100) DEFAULT NULL,
  `PropietarioFecha` date DEFAULT NULL COMMENT 'Propietario Real ------->Fecha de Nacimiento',
  `PropietarioLugarNac` varchar(100) DEFAULT NULL,
  `PropietarioEntid` varchar(100) DEFAULT NULL,
  `PropietarioPais` varchar(100) DEFAULT NULL,
  `CargoPubPEP` char(1) DEFAULT NULL COMMENT 'PEPS ',
  `CargoPubPEPDet` varchar(100) DEFAULT NULL COMMENT 'Descripción del Cargo publico que ocupa/ba',
  `NivelCargoPEP` char(1) DEFAULT NULL,
  `Periodo1PEP` varchar(50) DEFAULT NULL,
  `Periodo2PEP` varchar(50) DEFAULT NULL,
  `IngresosMenPEP` decimal(14,2) DEFAULT NULL,
  `FamEnCargoPEP` char(1) DEFAULT NULL COMMENT 'PEPS ----> Si tiene algun familiar que ocupa otro cargo publico\n',
  `ParentescoPEP` char(1) DEFAULT NULL,
  `NombreCompletoPEP` varchar(100) DEFAULT NULL,
  `ParentescoPEPDet` varchar(100) DEFAULT NULL,
  `CargoPubPEPDetFam` varchar(100) DEFAULT NULL,
  `NivelCargoPEPFam` char(1) DEFAULT NULL,
  `Periodo1PEPFam` varchar(50) DEFAULT NULL,
  `Periodo2PEPFam` varchar(50) DEFAULT NULL,
  `ParentescoPEPFam` char(1) DEFAULT NULL,
  `NombreCtoPEPFam` varchar(100) DEFAULT NULL,
  `RelacionPEP` char(1) DEFAULT NULL,
  `NombreRelacionPEP` varchar(100) DEFAULT NULL,
  `IngresoAdici` varchar(100) DEFAULT NULL,
  `FuenteIngreOS` varchar(200) DEFAULT NULL,
  `UbicFteIngreOS` varchar(300) DEFAULT NULL,
  `EsPropioFteIng` char(1) DEFAULT NULL,
  `EsPropioFteDet` varchar(100) DEFAULT NULL,
  `IngMensualesOS` decimal(14,2) DEFAULT NULL,
  `TipoProdTN` varchar(500) DEFAULT NULL,
  `MercadoDeProdTN` varchar(200) DEFAULT NULL,
  `IngresosMensTN` decimal(14,2) DEFAULT NULL,
  `DependEconTN` int(11) DEFAULT NULL,
  `DependHijoTN` int(11) DEFAULT NULL,
  `DependOtroTN` int(11) DEFAULT NULL,
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Empresa',
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ClienteID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$