-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- PRODUCTOSCREDITO
DELIMITER ;
DROP TABLE IF EXISTS `PRODUCTOSCREDITO`;
DELIMITER $$


CREATE TABLE `PRODUCTOSCREDITO` (
  `ProducCreditoID` int(11) NOT NULL COMMENT 'Numero de Tipo de Producto',
  `Descripcion` varchar(100) DEFAULT NULL COMMENT 'Descripcion del\nTipo de Producto',
  `Caracteristicas` text COMMENT 'Breve\nDescripcion de las\nCaracteristicas del\nProducto de \nCredito',
  `CobraIVAInteres` char(1) DEFAULT NULL COMMENT 'Indica si el Producto cobra IVA sobre Intereses Ordinarios \nS .- Si cobra IVA\r\n\nN .- No cobra IVA',
  `CobraIVAMora` char(1) DEFAULT NULL COMMENT 'Indica si el Producto cobra IVA sobre Intereses Moratorios \nS .- Si cobra IVA\r\n\nN .- No cobra IVA',
  `CobraFaltaPago` char(1) DEFAULT NULL COMMENT 'Indica si cobra Comision por Falta de Pago \nS .- Si cobra\r\n\nN .- No cobra',
  `CobraMora` char(1) DEFAULT NULL COMMENT 'Indica si cobra Moratorios por Falta de Pago \nS .- Si cobra\r\n\nN .- No cobra',
  `FactorMora` decimal(12,4) DEFAULT NULL COMMENT 'Factor de \nMoratorio',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Especifica el Tipo de Persona a la cual aplica el Producto\nF .- Fisica\nM .- Moral\nA .- Ambas',
  `ManejaLinea` char(1) DEFAULT NULL COMMENT 'Indica si el Producto Maneja Linea\nS .- Si Maneja Linea\nN .- No Maneja Linea',
  `EsRevolvente` char(1) DEFAULT NULL COMMENT 'Indica si la Linea de Credito es Revolvente \nS .- Si es Revolvente\nN .- No es Revolvente',
  `EsGrupal` char(1) DEFAULT NULL COMMENT 'Especifica si el Credito es Grupal\nS .- Si Maneja Grupos de Credito\nN .- No Maneja Grupos de Credito',
  `RequiereGarantia` char(1) DEFAULT NULL COMMENT 'Especifica si el Tipo de Credito Requiere Garantias\nS .- Si Requiere\nN .- No Requiere',
  `BonificacionFOGA` char(1) DEFAULT 'N' COMMENT 'Especifica si se tendran bonificaciones por pagos puntuales del credito\nS .- Si\nN .- No',
  `DesbloqAutFOGA` char(1) DEFAULT 'N' COMMENT 'Especifica si se pueden realizar desbloqueos automaticos de la garantia FOGA al ejecutar la cobranza automatica\nS .- Si\nN .- No',
  `RequiereGarFOGAFI` char(1) DEFAULT 'N' COMMENT 'Especifica si el Tipo de Credito Requiere Garantia FOGAFI(Garantia Liquida Financiada)\nS .- Si Requiere\nN .- No Requiere',
  `ModalidadFOGAFI` char(1) DEFAULT '' COMMENT 'Indica si la garantia FOGAFI, se cobrara de manera anticipada o periodica.\nA .- Anticipadao\nP .- Periodico',
  `BonificacionFOGAFI` char(1) DEFAULT 'N' COMMENT 'Especifica si se tendran bonificaciones por pagos puntuales del credito\nS .- Si\nN .- No',
  `DesbloqAutFOGAFI` char(1) DEFAULT 'N' COMMENT 'Especifica si se pueden realizar desbloqueos automaticos de la garantia FOGAFI al ejecutar la cobranza automatica\nS .- Si\nN .- No',
  `RequiereAvales` char(1) DEFAULT NULL COMMENT 'Especifica si el Tipo de Credito Requiere Avales \nS .- Si Requiere \nN .- No Requiere',
  `GraciaFaltaPago` int(11) DEFAULT NULL COMMENT 'Numero de Dias de Gracia para el Cobro de Comision por Falta De Pago',
  `GraciaMoratorios` int(11) DEFAULT NULL COMMENT 'Numero de Dias de Gracia para el Cobro de Interes Moratorios',
  `Garantizado` char(1) DEFAULT NULL COMMENT 'Indica si el Tipo de Credito Requiere Garantia Liquida\nS=SI\nN=NO',
  `LiberarGaranLiq` char(1) DEFAULT NULL COMMENT 'S=SI, N=NO, Indica si la garantia liquida se libera automaticamente al liquidar el credito',
  `MontoMinimo` decimal(12,2) DEFAULT NULL COMMENT 'Monto Minimo del Credito',
  `MontoMaximo` decimal(12,2) DEFAULT NULL COMMENT 'Monto Maximo del Credito',
  `DiasSuspesion` int(11) DEFAULT NULL COMMENT 'Numero de Dias para Suspender el Cobro de Moratorios\nY Accesorios',
  `EsReestructura` char(1) DEFAULT NULL COMMENT 'Permite Reestructura / Renovacion: S=si  N=no',
  `EsAutomatico` char(1) DEFAULT NULL COMMENT 'Indica si el Producto de puede Prospectar de Manera Automatica \nS .- Si es Automatico \nN .- No es Automatico',
  `MargenPagIgual` int(4) DEFAULT NULL COMMENT 'margen para pagos iguales\n',
  `TipoComXapert` char(1) DEFAULT NULL COMMENT 'Comision por apertura\nPorcentaje = P\nMonto = M',
  `MontoComXapert` decimal(12,2) DEFAULT NULL COMMENT 'Monto o porcentaje de comision por apertura\n',
  `AhoVoluntario` char(1) DEFAULT NULL COMMENT 'Ahorro voluntario\nS= Si\nN=No',
  `PorcAhoVol` decimal(10,2) DEFAULT NULL COMMENT 'Porcentaje de \nAhorro Voluntario',
  `ClasifRegID` int(11) DEFAULT NULL COMMENT 'Clasificacion Segun Reportes Regulatorios',
  `Tipo` char(1) DEFAULT NULL COMMENT 'Tipo de Clasificacion\\\\nC . Comercial\\\\nO .- Consumo\\\\nH .- Hipotecario',
  `ForCobroComAper` char(1) DEFAULT NULL COMMENT 'Forma de cobro de comision por apertura.\\nA: Anticipado \\nD: Deduccion\\nF: Financiamiento\\n',
  `CalcInteres` char(1) DEFAULT NULL COMMENT '1.- TasaFija\\\\n2.- TasaBase de inicio de cupon+Puntos\\\\n3.- Tasa Base de inicio de cupon+Puntos, con Piso y Techo',
  `TipoContratoBCID` varchar(5) DEFAULT NULL COMMENT 'Tipo de Contrato',
  `TipoCalInteres` int(11) DEFAULT NULL COMMENT '1 .- Saldos Insolutos\n2 .- Monto Original (Saldos Globales)',
  `TipoGeneraInteres` char(1) NOT NULL COMMENT 'Tipo de Monto Original (Saldos Globales): \n"I".- Iguales \n"D".- Dias Transcurridos',
  `InstitutFondID` int(11) DEFAULT NULL,
  `MaxIntegrantes` int(11) DEFAULT NULL COMMENT 'Numero Maximo de Integrantes del Producto de Credito',
  `MinIntegrantes` int(11) DEFAULT NULL COMMENT 'Numero Minimo de Integrantes del Producto de Credito',
  `PerRompimGrup` char(1) DEFAULT NULL COMMENT 'Indica si permite rompimiento de grupo, en caso de ser producto grupal\\nS= Si\\nN=No',
  `RaIniCicloGrup` int(11) DEFAULT NULL COMMENT 'Rango Inicial del Ciclo Grupal\\nSolo si es grupal',
  `RaFinCicloGrup` int(11) DEFAULT NULL COMMENT 'Rango Final del Ciclo Grupal\\nSolo si es grupal',
  `RelGarantCred` decimal(12,4) DEFAULT NULL COMMENT 'Relacion Garantia Credito, en caso de que el producto especifique que si pide Garantia ( es un porcentaje )',
  `PerAvaCruzados` char(1) DEFAULT NULL COMMENT 'Permite Avales Cruzados, en caso de requerir avales\\nS= Si\\nN= No',
  `PerGarCruzadas` char(1) DEFAULT NULL COMMENT 'Permite Garantias Cruzadas, en caso de requerir Garantias\\nS= Si\\nN= No',
  `CriterioComFalPag` varchar(1) DEFAULT NULL COMMENT 'C .- Monto Original de la Cuota (Capital)\nT .- Monto Original de la Cuota (Capital + Int + IVA)\nS .- Saldo de la Cuota',
  `MontoMinComFalPag` decimal(12,2) DEFAULT NULL COMMENT 'Monto minimo para \ngenerar comision com Falta de Pago',
  `RegistroRECA` varchar(100) DEFAULT NULL COMMENT 'Numero del Registro de contratos de adhesion RECA de CONDUSEF',
  `FechaInscripcion` date DEFAULT '1900-01-01' COMMENT 'fecha de inscripcion al RECA',
  `NombreComercial` varchar(100) DEFAULT NULL COMMENT 'Nombre Comercial registrado en RECA',
  `TipoCredito` varchar(50) DEFAULT NULL COMMENT 'Tipo de credito en RECA',
  `MinMujeresSol` int(11) DEFAULT '0',
  `MaxMujeresSol` int(11) DEFAULT '0',
  `MinMujeres` int(11) DEFAULT '0',
  `MaxMujeres` int(11) DEFAULT '0',
  `MinHombres` int(11) DEFAULT '0',
  `MaxHombres` int(11) DEFAULT '0',
  `TasaPonderaGru` char(1) DEFAULT NULL COMMENT 'El dato puede obtener el valor de S=Si o N=No para asignar la Tasa Ponderada Grupal',
  `ReqSeguroVida` char(1) NOT NULL COMMENT 'Indica si Requiere Seguro de Vida: S .- Si, N .- No',
  `TipoPagoSeguro` char(1) DEFAULT NULL COMMENT 'Tipo de cobro del Seguro. A: Anticipado, D: Deduccion, F: Financiamiento',
  `FactorRiesgoSeguro` decimal(12,6) DEFAULT NULL COMMENT 'Factor de Riesgo del Seguro',
  `DescuentoSeguro` decimal(12,2) DEFAULT NULL COMMENT 'Descuento en el Monto de Cobro de Seguro, de acuerdo al Tipo de Pago del mismo',
  `MontoPolSegVida` decimal(12,2) DEFAULT NULL COMMENT 'Monto de la Poliza del Seguro de Vida en caso de siniestro',
  `ProyInteresPagAde` char(1) DEFAULT NULL COMMENT 'Proyectar o Adelantar Interes en el Pago de una Cuota por Anticipado\nS .- Si\nN .-No',
  `TipCobComFalPago` char(1) DEFAULT NULL COMMENT 'Tipo de Comision por Falta de Pago\nA .- Por Amortizacion\nC .- Por Credito',
  `PerCobComFalPag` char(1) DEFAULT NULL COMMENT 'Periodicidad en la Comision por Falta de Pago\nD .- Diariamente mientras la cuota esta en atraso\nI .- Por Incumplimiento (1 sola vez en la Fecha de Exigibilidad)',
  `ProrrateoComFalPag` char(1) DEFAULT NULL COMMENT 'Prorrateo en la Comision por Falta de Pago\nS .- Si\nN .- No',
  `TipCobComMorato` char(1) DEFAULT NULL COMMENT 'Tipo de Comision del Moratorio\nN .- N Veces la Tasa Ordinaria\nT .- Tasa Fija Anualizada\n',
  `DiasPasoAtraso` int(11) DEFAULT NULL COMMENT 'Dias para el Paso a Atrasado',
  `TipoPagoComFalPago` char(1) DEFAULT NULL COMMENT 'Tipo de Pago de la Comision por Falta de Pago\nC .- En cada Cuota (Metodo Tradicional)\nF .- Al Final de la Prelacion',
  `ValidaCapConta` char(1) DEFAULT NULL COMMENT 'Valida la capital social S.-si N.-no',
  `PorcMaxCapConta` decimal(8,2) DEFAULT NULL COMMENT 'Porcentaje de capital Social',
  `ProrrateoPago` char(1) DEFAULT NULL COMMENT 'Indica si el pago se prorratea entre los integrantes del grupo',
  `PermitePrepago` char(1) DEFAULT NULL COMMENT 'Indica si permite Prepago \nS = SI\nN =NO',
  `ProductoNomina` char(1) DEFAULT NULL COMMENT 'Indica si el Producto de credito pertenece a una institucion de nomina\nS.- SI\nN.- NO',
  `ModificarPrepago` char(1) DEFAULT NULL COMMENT 'indica si se puede modificar la forma de prepago base\nS- si\nN-no',
  `TipoPrepago` char(1) DEFAULT NULL COMMENT 'Tipo de prepago a aplicar\nU-Pago de capital a ultimas cuotas \nI-A las cuotas siguientes inmediatas\nV-Prorrateo de pago en cuotas vivas\nP-Pago Cuotas Completas Proyectadas',
  `AutorizaComite` char(1) DEFAULT NULL COMMENT 'Especifica que el Producto de Crédito aplica para funcionarios o relacionados a funcionarios, \nS=Si  \nN=No',
  `TipoContratoCCID` varchar(2) DEFAULT NULL,
  `CalculoRatios` char(1) DEFAULT NULL COMMENT ' Si Requiere Calculo de Ratios S=SI N=NO',
  `AfectacionContable` char(1) DEFAULT NULL COMMENT 'Afectación Contable',
  `InicioAfuturo` char(1) DEFAULT NULL COMMENT 'Indica si el producto de credito permite realizar desembolso del credito antes de su fecha de inicio',
  `DiasMaximo` int(11) DEFAULT NULL COMMENT 'Indica maximo cuantos dias con anticipacion se desembolsa el credito antes de su fecha de inicio',
  `Modalidad` char(1) DEFAULT NULL COMMENT 'Modalidad de Pago Unico = U, Por Tipo de Pago = T',
  `EsquemaSeguroID` int(11) DEFAULT NULL COMMENT 'Esquema de Seguro de Vida',
  `CantidadAvales` int(11) NOT NULL COMMENT 'Número de créditos que puede avalar una persona',
  `IntercambiaAvales` char(1) NOT NULL COMMENT 'Permite intercambiar aval(S=si, N=no)',
  `PermiteAutSolPros` char(1) DEFAULT NULL COMMENT 'Permite Autorización por Prospecto S:Si N:No',
  `ClaveRiesgo` char(1) DEFAULT NULL COMMENT 'Campo para matriz de riesgos PLD - valores A.- Alto , B.-Bajo',
  `RequiereReferencias` char(1) DEFAULT 'N' COMMENT 'Solicita Referencias S:Si N:No',
  `MinReferencias` int(11) DEFAULT NULL COMMENT 'Minimo de Referencias',
  `ClaveCNBV` varchar(10) DEFAULT NULL COMMENT 'Clave del producto CNBV',
  `RequiereCheckList` char(1) DEFAULT NULL COMMENT 'Requiere CheckList\nS = Si Requiere\nN = No Requiere\nI = Indistinto',
  `EsAgropecuario` char(1) DEFAULT 'N' COMMENT 'Especifica si el producto de credito es Agropecuario\nS:Si es Producto Agropecuario\nN:No es Producto Agropecuario',
  `Refinanciamiento` char(1) DEFAULT 'N' COMMENT 'Indica si el producto refinancia intereses.\nS.- Si refinancia\nN.- No refinancia',
  `TipoAutomatico` char(1) DEFAULT '' COMMENT 'Especifica si el producto de crédito es automático sobre \nI:Inversión, A:Ahorro',
  `PorcentajeMaximo` decimal(14,2) DEFAULT '0.00' COMMENT 'Porcentaje para calcular el monto maximo al otorgar el credito',
  `FinanciamientoRural` char(1) DEFAULT 'N' COMMENT 'Especifica si se realizara la evaluacion del numero de habitantes de una localidad.',
  `ParticipaSpei` char(1) DEFAULT NULL COMMENT 'Especifica si el producto de crédito es participante SPEI',
  `ProductoCLABE` char(3) DEFAULT NULL COMMENT 'No de CLABE del producto segun Banxico para creditos con SPEI',
  `DiasAtrasoMin` int(11) DEFAULT NULL COMMENT 'Número de Dias de Atraso Minimo para el proceso de Castigo',
  `ReqObligadosSolidarios` char(1) NOT NULL DEFAULT 'N' COMMENT 'Atributo para saber si el producto de credito requiere obligados solidarios',
  `PerObligadosCruzados` char(1) NOT NULL DEFAULT 'N' COMMENT 'Atributo para saber si permite obligados solidarios cruzados',
  `ReqConsultaSIC` char(1) NOT NULL DEFAULT 'N' COMMENT 'Atributo para saber si requiere consulta SIC',
  `CobraAccesorios` char(1) DEFAULT 'N' COMMENT 'Indica si el producto de credito cobra accesorios(CATI, CAP, AT)',
  `CobraComAnual` char(1) DEFAULT NULL COMMENT 'Indica si cobra comision anual de linea.',
  `TipoComAnual` char(1) DEFAULT NULL COMMENT 'Tipo de comision anual.',
  `ValorComAnual` decimal(12,2) DEFAULT NULL COMMENT 'Valor de la comision anual.',
  `CobraSeguroCuota` char(1) DEFAULT NULL COMMENT 'Cobra seguro por Cuota',
  `CobraIVASeguroCuota` char(1) DEFAULT NULL COMMENT 'Cobra Iva por seguro por cuota, dependiente si del campo de si cobra seguro por cuota',
  `RequiereAnalisiCre` char(1) DEFAULT 'N' COMMENT 'Indica si la solicitud de credito debera pasar de forma obligatoria al proceso de analisis de credito\nN No\nS  Si',
  `PerConsolidacion` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Especifica si permite Consolidación S=Si N=No',
  `ReqInsDispersion` CHAR (1) NOT NULL DEFAULT 'N' COMMENT 'Especifica si se introducen Instrucciones de Dispersión S=Si N=No',
  `ReqConsolidacionAgro` CHAR (1) NOT NULL DEFAULT 'N' COMMENT 'Especifica si Requiere Consolidacion para Productos Agro S=Si Requiere N=No Requiere',
  `FechaDesembolso` CHAR(1) NOT NULL COMMENT 'Campo Disponible si el campo ReqConsolidacionAgro tiene el valor SI. \nS.-SI \nN.-NO',
  `Estatus` CHAR(2) NOT NULL DEFAULT 'A' COMMENT 'Estatus del Tipo de Producto \nA.-Activo\n I.-Inactivo.',
  `ValidaConyuge` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Especifica si la Informacion del Conyuge es Obligatoria \S = Si \N = No',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Empresa ID',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`ProducCreditoID`),
  KEY `fk_PRODUCTOSCREDITO_1` (`TipoContratoBCID`),
  KEY `fk_PRODUCTOSCREDITO_2_idx` (`EsquemaSeguroID`),
  CONSTRAINT `fk_PRODUCTOSCREDITO_1` FOREIGN KEY (`TipoContratoBCID`) REFERENCES `BUCRETIPCONTRA` (`TipoContratoBCID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Catalogo de Productos de Credito'$$