-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- PROSPECTOS
DELIMITER ;
DROP TABLE IF EXISTS `PROSPECTOS`;
DELIMITER $$

CREATE TABLE `PROSPECTOS` (
  `ProspectoID` bigint(20) NOT NULL,
  `ProspectoIDExt` bigint(20) NOT NULL,
  `TipoPersona` char(1) DEFAULT NULL,
  `RazonSocial` varchar(50) DEFAULT NULL,
  `PrimerNombre` varchar(50) DEFAULT NULL,
  `SegundoNombre` varchar(50) DEFAULT NULL,
  `TercerNombre` varchar(50) DEFAULT NULL,
  `ApellidoPaterno` varchar(50) DEFAULT NULL,
  `ApellidoMaterno` varchar(50) DEFAULT NULL,
  `FechaNacimiento` date DEFAULT NULL COMMENT 'Fecha de nacimiento del prospecto',
  `RFC` char(13) DEFAULT NULL,
  `EstadoCivil` char(2) DEFAULT NULL COMMENT 'Clave Estado Civil: S = Soltero\\nCS  = Casado Bienes Separados\\nCM = Casado Bienes Mancomunados\\nCC = Casado Bienes Mancomunados Con Capitulacion\\nV = Viudo\\nD = Divorciado\\nSE  = Separado\\nU = Union Libre',
  `Telefono` char(13) DEFAULT NULL,
  `NombreCompleto` varchar(200) DEFAULT NULL,
  `Calle` varchar(50) DEFAULT NULL,
  `NumExterior` char(10) DEFAULT NULL,
  `NumInterior` char(10) DEFAULT NULL,
  `Manzana` varchar(20) DEFAULT NULL,
  `Lote` varchar(20) DEFAULT NULL,
  `Colonia` varchar(200) DEFAULT NULL COMMENT 'Colonia',
  `MunicipioID` int(11) DEFAULT NULL,
  `EstadoID` int(11) DEFAULT NULL,
  `CP` varchar(5) DEFAULT NULL,
  `ClienteID` int(11) DEFAULT NULL,
  `Latitud` varchar(45) DEFAULT NULL COMMENT 'Latitud de \nubicacion',
  `Longitud` varchar(45) DEFAULT NULL COMMENT 'Altitud de ubicación',
  `TipoDireccionID` int(11) DEFAULT NULL COMMENT 'ID de la direccion del cliente corresponde con la tabla TIPOSDIRECCION',
  `Sexo` char(1) DEFAULT NULL COMMENT 'Indica el genero de la persona.\nFemenimo = "F"\nMasculino = "M"',
  `LocalidadID` varchar(45) DEFAULT NULL COMMENT 'hace referencia con la tabla LOCALIDADREPUB',
  `ColoniaID` varchar(45) DEFAULT NULL COMMENT 'Hace referencia con la tabla COLONIASREPUB',
  `CalificaProspecto` char(1) DEFAULT NULL COMMENT 'Calificacion del Prospecto  N : NO ASIGNADA, A: EXCELENTE, B: BUENA , C: REGULAR',
  `OcupacionID` int(5) DEFAULT NULL COMMENT 'Profesión del cliente',
  `LugardeTrabajo` varchar(100) DEFAULT NULL COMMENT 'Lugar donde Trabaja\n',
  `Puesto` varchar(100) DEFAULT NULL COMMENT 'Puesto en el Trabajo\n',
  `TelTrabajo` varchar(20) DEFAULT NULL COMMENT 'Telefono del Trabajo\n',
  `AntiguedadTra` decimal(12,2) DEFAULT NULL COMMENT 'Antiguedad usado como decimal como años\nejemplo: 10.5\n10 años y 6 meses.',
  `Clasificacion` char(1) DEFAULT NULL COMMENT 'Clasificación del cliente, valores esperados:\nI .- Cliente independiente\nN.- Cliente Empresa  de Nomina \nE.- Cliente Empleado.\nC.- Cliente Corportativo\nR .- Relacionado a Corporativo, \nF .- Negocio Afiliado\nM.- Empleado de Nomina\nO.- Cliente Funcionario',
  `NoEmpleado` varchar(20) DEFAULT NULL COMMENT 'Numero de empleado en la institucion de nomina',
  `TipoEmpleado` char(1) DEFAULT NULL COMMENT 'Tipo de Empleado en la Institucion de Nomina',
  `RFCpm` char(13) DEFAULT NULL COMMENT 'RFC de persona moral',
  `ExtTelefonoPart` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extensión de teléfono Particular',
  `ExtTelefonoTrab` varchar(6) DEFAULT NULL COMMENT 'Contiene el número de extensión de teléfono de trabajo',
  `Nacion` char(1) DEFAULT NULL COMMENT 'Nacionalidad del prospecto\n''N'' = Nacional\n''E'' = Extranjero',
  `LugarNacimiento` int(11) DEFAULT NULL COMMENT 'Pais de Nacimiento, llave foranea a PAISES',
  `PaisID` int(11) NOT NULL COMMENT 'Identificador del Pais de residencia',
  `SoloNombres` varchar(500) DEFAULT '' COMMENT 'Primer Nombre, Segundo Nombre y Tercer Nombre.',
  `SoloApellidos` varchar(500) DEFAULT '' COMMENT 'Apellido Paterno y Apellido Materno.',
  `RazonSocialPLD` varchar(200) DEFAULT '' COMMENT 'Razón Social limpio de caracteres especiales.';
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` date DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` int(11) DEFAULT NULL,
  PRIMARY KEY (`ProspectoID`),
  KEY `prospectoIDExtIndex` (`ProspectoIDExt`),
  KEY `fk_PROSPECTOS_Municipios` (`MunicipioID`,`EstadoID`),
  KEY `fk_PROSPECTOS_Estados` (`EstadoID`),
  KEY `fk_PROSPECTOS_TipoDireccion_idx` (`TipoDireccionID`),
  CONSTRAINT `fk_PROSPECTOS_Estados` FOREIGN KEY (`EstadoID`) REFERENCES `ESTADOSREPUB` (`EstadoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROSPECTOS_Municipios` FOREIGN KEY (`MunicipioID`, `EstadoID`) REFERENCES `MUNICIPIOSREPUB` (`MunicipioID`, `EstadoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROSPECTOS_TipoDireccion` FOREIGN KEY (`TipoDireccionID`) REFERENCES `TIPOSDIRECCION` (`TipoDireccionID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$