-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- RATIOS
DELIMITER ;
DROP TABLE IF EXISTS `RATIOS`;DELIMITER $$

CREATE TABLE `RATIOS` (
  `SolicitudCreditoID` int(11) NOT NULL COMMENT 'Numero de Solicitud de Crédito',
  `PuntosTotal` decimal(14,2) DEFAULT NULL COMMENT 'porcentaje final del Calculo del Ratios',
  `NivelRiesgo` int(11) DEFAULT NULL COMMENT 'Nivel de Riesgo segun el Porcentaje final obtenido (RATIOSNIVELRIESGO)',
  `Caracter` decimal(14,2) DEFAULT NULL COMMENT 'porcentaje obtenido en el Caracter (C1)',
  `Capital` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje obtenido en el capital (C2)',
  `CapacidadPago` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en Capacidad de Pago (C3)',
  `Condiciones` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en  Condiciones (C4)',
  `TotalResidencia` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en  C1.1 Residencia',
  `TotalOupacion` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en Ocupacion (C1.2)',
  `TotalMora` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en Mora y Referencias Crediticias C1.3',
  `TotalAfiliacion` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en Afiliacion y Ahorro con la caja C1.4',
  `TotalDeudaActual` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido la Deuda Actual sin el Crédito con la caja C2.1',
  `TotalDeudaCredito` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido la Deuda Actual sin el Crédito con la caja C2.2',
  `TotalCobertura` decimal(14,2) DEFAULT NULL COMMENT 'Porcentaje total obtenido en la cobertura	 c3.1',
  `TotalGastos` decimal(14,2) DEFAULT NULL COMMENT 'Gastos actuales del Cliente sin el Credito',
  `TotalGastosCredito` decimal(14,2) DEFAULT NULL COMMENT 'Gastos Actuales + el Credito',
  `TotalEstabilidadIng` decimal(14,2) DEFAULT NULL COMMENT 'Estabilidad de ingresos del cte',
  `TotalNegocio` decimal(14,2) DEFAULT NULL COMMENT 'si el cliente tiene un negocio',
  `Vivienda` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun el tipo de Vivienda del Cliente',
  `MesesVivienda` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun los Meses en su Vivienda',
  `PorOcupacion` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun la ocupacion del Cliente',
  `MesesOcupacion` decimal(12,2) DEFAULT NULL,
  `MoraCredito` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido si el cliente tuvo mora en su ultimo credito\n',
  `MaximoMesesMora` decimal(12,2) DEFAULT NULL COMMENT 'Numero maximo de mora  que el cliente a tenido en sus creditos',
  `CalificaBuroCred` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun la Calificacion que le otorga buro de credito al cliente',
  `CalificaCaja` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun como califica la caja al cliente',
  `SocioCaja` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido dependiendo de si la Persona es Socio de la institucion financiera',
  `SaldoPromAhorro` decimal(12,2) DEFAULT NULL,
  `Deuda` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun la Cobertura de Pago de Credito del cliente',
  `DeudaConCredito` decimal(12,2) DEFAULT NULL COMMENT 'Porcentaje obtenido segun la Cobertura tomado en cuenta el credito Solicitado',
  `PorCobertura` varchar(45) DEFAULT NULL,
  `GastosActual` decimal(12,2) DEFAULT NULL,
  `GastosCredito` decimal(12,2) DEFAULT NULL,
  `EstabilidadEmp` decimal(12,2) DEFAULT NULL,
  `VentasMensuales` decimal(12,2) DEFAULT NULL,
  `Liquidez` decimal(12,2) DEFAULT NULL,
  `Mercado` decimal(12,2) DEFAULT NULL,
  `MontoTerreno` decimal(14,2) DEFAULT NULL COMMENT 'Cantidad que tiene el cliente en Terrenos',
  `MontoVivienda` decimal(14,2) DEFAULT NULL COMMENT 'Cantidad que tiene el cliente en vivienda',
  `MontoVehiculos` decimal(14,2) DEFAULT NULL COMMENT 'Cantidad que tiene el cliente en Vehiculos',
  `MontoOtros` decimal(14,2) DEFAULT NULL COMMENT 'monto de otros aspectos que forman aprte de los activos del cte',
  `PuntosIDEstNeg` int(11) DEFAULT NULL COMMENT 'corresponde con la tabla RATIOSPUNTOS',
  `TieneNegocio` char(1) DEFAULT NULL,
  `PuntosIDVentasMen` int(11) DEFAULT NULL COMMENT 'corresponde con la tabla RATIOSPUNTOS',
  `PuntosIDLiquidez` int(11) DEFAULT NULL COMMENT 'corresponde con la tabla RATIOSPUNTOS',
  `PuntosIDMercado` int(11) DEFAULT NULL COMMENT 'corresponde con la tabla RATIOSPUNTOS',
  `FechaCalculo` date DEFAULT NULL COMMENT 'Fecha en que se genera y Guarda el Calculo',
  `Estatus` char(1) DEFAULT NULL COMMENT 'G= Calculado y Guardado \nC = Calculado\nR = Rechazado\nP = Procesado\nE = Regresado al Ejecutivo\n\n\n',
  `MontoGarantizado` decimal(14,2) DEFAULT NULL COMMENT 'monto Garantizado de Garantia Prendaria',
  `UsuarioAlta` int(11) DEFAULT NULL COMMENT 'Usuario que da de alta la consulta de ratios',
  `FechaRegistro` date DEFAULT NULL COMMENT 'Fecha de Registro de la Consulta de Ratios',
  `FechaAutoriza` date DEFAULT NULL COMMENT 'Fecha de Formalización',
  `UsuarioAutoriza` int(11) DEFAULT NULL COMMENT 'Usuario que Autoriza',
  `FechaRechazo` datetime DEFAULT NULL COMMENT 'Fecha en que se realizo el rechazo de la Solicitud',
  `UsuarioRechazo` int(11) DEFAULT NULL COMMENT 'Usuario que rechazo la solicitud',
  `ComentarioRech` varchar(800) DEFAULT NULL COMMENT 'Comentario de Rechazo',
  `MotivoRechazo` int(11) DEFAULT NULL COMMENT 'Motivo Rechazo',
  `ComentarioEjecutivo` varchar(2600) DEFAULT NULL COMMENT 'Comentario que envia la persona que autoriza al Ejecutivo de Cuenta cuando le Regresa la Solicitud para alguna modificacion',
  `ComentarioMesaControl` varchar(800) DEFAULT NULL COMMENT 'Comentario que se agrega al checkList de Mesa de Control los store que usan esta columnaADD COLUMN solo tendran 800',
  `Colaterales` decimal(14,2) DEFAULT '0.00' COMMENT 'Porcentaje total  C5 Colaterales',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Auditoria Empresa ID',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Auditoria Usuario ID',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Auditoria Fecha del sistema',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Auditoria Direccion IP',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Auditoria Programa ID donde se realizo la operacion',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Auditoria Sucursal',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Auditoria Numero de Transaccion',
  PRIMARY KEY (`SolicitudCreditoID`),
  KEY `fk_RATIOS_5_idx` (`NivelRiesgo`),
  CONSTRAINT `fk_RATIOS_5` FOREIGN KEY (`NivelRiesgo`) REFERENCES `RATIOSNIVELRIESGO` (`NivelRiesgoID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Almacena la información de cada estimacion de reatios genrad'$$