-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- REIMPRESIONTICKET
DELIMITER ;
DROP TABLE IF EXISTS `REIMPRESIONTICKET`;DELIMITER $$

CREATE TABLE `REIMPRESIONTICKET` (
  `ReimpresionID` int(11) NOT NULL,
  `TransaccionID` bigint(20) NOT NULL COMMENT 'Numero de Transacción',
  `TipoOperacionID` int(11) DEFAULT NULL COMMENT 'Tipo Operación',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Sucursal del Usuario',
  `CajaID` int(11) DEFAULT NULL COMMENT 'Numero de Caja',
  `UsuarioID` int(11) DEFAULT NULL COMMENT 'Clave del usuario',
  `Fecha` date DEFAULT NULL COMMENT 'Fecha de la operación',
  `Hora` time DEFAULT NULL COMMENT 'hora de la operación',
  `OpcionCajaID` int(11) DEFAULT NULL,
  `Descripcion` varchar(100) DEFAULT NULL COMMENT 'Descripción de la operación(como se describe en el tickte)',
  `MontoOperacion` decimal(14,2) DEFAULT NULL COMMENT 'Monto total de la operación',
  `Efectivo` decimal(14,2) DEFAULT NULL COMMENT 'Monto total Entregado o recibido',
  `Cambio` decimal(14,2) DEFAULT NULL COMMENT 'Total Cambio sobre el monto recibido',
  `NombrePersona` varchar(200) DEFAULT NULL COMMENT 'Nombre del Cliente, Beneficiario, empleado que se muestra eb el Ticket',
  `NombreBeneficiario` varchar(100) DEFAULT NULL COMMENT 'Persona Beneficiario o Nombre de quien recibe los pagos',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente',
  `ProspectoID` int(11) DEFAULT NULL,
  `EmpleadoID` int(11) DEFAULT NULL,
  `NombreEmpleado` varchar(100) DEFAULT NULL,
  `CuentaIDRetiro` bigint(12) DEFAULT NULL COMMENT 'Numero de Cuenta',
  `CuentaIDDeposito` bigint(12) DEFAULT NULL COMMENT 'Numero de Cuenta',
  `EtiquetaCtaRetiro` varchar(60) DEFAULT NULL,
  `EtiquetaCtaDepo` varchar(60) DEFAULT NULL,
  `DesTipoCuenta` varchar(100) DEFAULT NULL COMMENT 'Descripción del tipo de Cuenta',
  `DesTipoCtaDepo` varchar(100) DEFAULT NULL,
  `SaldoActualCta` decimal(14,2) DEFAULT NULL COMMENT 'Saldo Actual de la cuenta, Para deposito a cta',
  `Referencia` varchar(200) DEFAULT NULL COMMENT 'Referencia del Deposito o retiro(del movimiento)',
  `FormaPagoCobro` char(1) DEFAULT NULL COMMENT 'Forma en la que se cobro o pago el monto de la operación\nR  = Efectivo\nC  = Chequ',
  `CreditoID` bigint(12) DEFAULT NULL COMMENT 'Numero de Credito',
  `ProducCreditoID` int(11) DEFAULT NULL COMMENT 'Nombre del Producto de Credito',
  `NombreProdCred` varchar(100) DEFAULT NULL,
  `MontoCredito` decimal(14,2) DEFAULT NULL,
  `MontoPorDesem` decimal(14,2) DEFAULT NULL,
  `MontoDesemb` decimal(14,2) DEFAULT NULL,
  `GrupoID` int(11) DEFAULT NULL COMMENT 'Nombre del Grupo de Credito',
  `NombreGrupo` varchar(100) DEFAULT NULL,
  `CicloActual` int(11) DEFAULT NULL COMMENT 'Ciclo del Grupo',
  `MontoProximoPago` char(20) DEFAULT NULL COMMENT 'Monto del Proximo  Pago de Credito',
  `FechaProximoPago` char(20) DEFAULT NULL COMMENT 'Fecha del Proximo Pago',
  `TotalAdeudo` char(20) DEFAULT NULL COMMENT 'Total del Adeudo',
  `Capital` char(20) DEFAULT NULL COMMENT 'indica cuanto de capital se pago en la operación',
  `Interes` char(20) DEFAULT NULL COMMENT 'Monto de interés que se pago ',
  `Moratorios` char(20) DEFAULT NULL COMMENT 'monto de  moratorios que se pagaron',
  `Comision` char(20) DEFAULT NULL COMMENT 'Para pago de Servicios y pago de credito',
  `ComisionAdmon` char(20) DEFAULT NULL COMMENT 'monto de  moratorios que se pagaron',
  `IVA` char(20) DEFAULT NULL COMMENT 'Iva, tambien para el pago de Credito',
  `GarantiaAdicional` char(20) DEFAULT NULL COMMENT 'Monto de Garantía Adicional',
  `InstitucionID` int(11) DEFAULT NULL COMMENT 'Numero de Institución Bancaria.',
  `NumCtaInstit` varchar(20) DEFAULT NULL COMMENT 'Numero de cuenta Bancaria',
  `NumCheque` bigint(10) DEFAULT NULL COMMENT 'Numero de cheque',
  `NombreInstit` varchar(100) DEFAULT NULL,
  `PolizaID` bigint(20) DEFAULT NULL COMMENT 'Número de Póliza de la Operación',
  `Telefono` varchar(20) DEFAULT NULL COMMENT 'Numero de Telefono',
  `Identificacion` varchar(100) DEFAULT NULL COMMENT 'Descripcion del tipo de identificación',
  `FolioIdentificacion` varchar(100) DEFAULT NULL COMMENT 'Numero de Folio de la identificación',
  `FolioPago` varchar(45) DEFAULT NULL COMMENT 'Para el caso de Remesas y Oportunidades',
  `CatalogoServID` int(11) DEFAULT NULL,
  `NombreCatalServ` varchar(100) DEFAULT NULL,
  `MontoServicio` decimal(14,2) DEFAULT NULL COMMENT 'Monto el servicio',
  `IVAServicio` decimal(14,2) DEFAULT NULL,
  `OrigenServicio` char(1) DEFAULT NULL,
  `MontoComision` decimal(14,2) DEFAULT NULL COMMENT 'Monto de la comision',
  `TotalCastigado` decimal(14,2) DEFAULT NULL COMMENT 'Monto total del credito castigado',
  `TotalRecuperado` decimal(14,2) DEFAULT NULL COMMENT 'Monto Total del credito que se ha recuperado',
  `Monto_PorRecuperar` decimal(14,2) DEFAULT NULL COMMENT 'Monto del credito que se abonara ',
  `FechaCastigo` date DEFAULT NULL,
  `TipoServServifun` char(1) DEFAULT NULL,
  `MonedaIDOperacion` int(11) DEFAULT NULL,
  `MontoPendPagoAportSocial` decimal(14,2) DEFAULT NULL COMMENT 'Monto pendiente de pago para la aportacion social\n',
  `MontoPagAportSocial` decimal(14,2) DEFAULT NULL COMMENT 'Monto Pagado por Aportacion social\n',
  `CobraSeguroCuota` char(1) DEFAULT NULL COMMENT 'Cobra seguro por cuota el crédito',
  `MontoSeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto por seguro por cuota pagado',
  `IVASeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'IVA Seguro Cuota',
  `ArrendaID` bigint(12) NOT NULL DEFAULT '0' COMMENT 'Numero de Arrendamiento',
  `ProdArrendaID` int(4) NOT NULL DEFAULT '0' COMMENT 'Numero del Producto de Arrendamiento',
  `NomProdArrendaID` varchar(30) NOT NULL DEFAULT '' COMMENT 'Nombre del Producto de Arrendamiento',
  `SeguroVida` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto Seguro de Vida',
  `Seguro` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto Seguro Inmobiliario',
  `IVASeguroVida` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Seguro de Vida',
  `IVASeguro` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Seguro Inmobiliario',
  `IVACapital` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Capital',
  `IVAInteres` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Interes',
  `IVAMora` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Mora',
  `IVAOtrasComi` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Otras Comisiones',
  `IVAComFaltaPag` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto IVA Comisión Falta de Pago',
  `AccesorioID` int(11) DEFAULT NULL COMMENT 'ID del Accesorio (ACCESORIOSCRED)',
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de auditoria',
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'IVA Seguro Cuota',
  PRIMARY KEY (`TransaccionID`,`ReimpresionID`),
  KEY `CajaID` (`CajaID`),
  KEY `TipoOperacionID` (`TipoOperacionID`),
  KEY `SucursalID` (`SucursalID`),
  KEY `fk_Usuarios_idx` (`UsuarioID`),
  KEY `fk_REIMPRESIONTICKET_1` (`SucursalID`,`CajaID`),
  KEY `fk_REIMPRESIONTICKET_2` (`ClienteID`),
  KEY `fk_REIMPRESIONTICKET_3` (`CuentaIDRetiro`),
  KEY `fk_REIMPRESIONTICKET_4` (`CuentaIDDeposito`),
  CONSTRAINT `Fk_CajasTipoOpera` FOREIGN KEY (`TipoOperacionID`) REFERENCES `CAJATIPOSOPERA` (`Numero`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_REIMPRESIONTICKET_1` FOREIGN KEY (`SucursalID`, `CajaID`) REFERENCES `CAJASVENTANILLA` (`SucursalID`, `CajaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursales` FOREIGN KEY (`SucursalID`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios` FOREIGN KEY (`UsuarioID`) REFERENCES `USUARIOS` (`UsuarioID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$