DELIMITER ;
DROP TABLE IF EXISTS `RELACIONADOSFISCALES`;
DELIMITER $$

CREATE TABLE `RELACIONADOSFISCALES` (
  `RelacionadoFiscalID` int(11) NOT NULL COMMENT 'PK Identificador consecutivo del relacionado fiscal',
  `ClienteID` int(11) NOT NULL COMMENT 'ID del cliente que tendra las relaciones fiscales tabla CLIENTES',
  `ParticipaFiscalCte` decimal(14,2) NOT NULL COMMENT 'Indica el % que corresponde a la participacion fiscal del cliente puede ser un valor a dos decimales en un rango del 0 al 100',
  `Ejercicio` int(11) NOT NULL COMMENT 'Anio del ejercicio',
  `TipoRelacionado` char(1) NOT NULL COMMENT 'Tipo relacionado: C= es un cliente tabla CLIENTES, R = es un relacionado fiscal tabla RELACIONADOSFICALES',
  `CteRelacionadoID` int(11) NOT NULL COMMENT 'Identificador del relacionado, id de cliente o 0 si es relacionado fiscal no cliente',
  `ParticipacionFiscal` decimal(14,2) NOT NULL COMMENT 'Indica el % que corresponde a la participacion fiscal del relacionado puede ser un valor a dos decimales en un rango del 0 al 100',
  `TipoPersona` char(1) NOT NULL COMMENT 'Tipo de Personalidad: F.- Persona Fisica Sin Actividad Empresarial, A.- Persona Fisica Con Actividad Empresarial',
  `PrimerNombre` varchar(50) NOT NULL COMMENT 'Primer Nombre',
  `SegundoNombre` varchar(50) NOT NULL COMMENT 'Segundo Nombre',
  `TercerNombre` varchar(50) NOT NULL COMMENT 'Tercer Nombre',
  `ApellidoPaterno` varchar(50) NOT NULL COMMENT 'Apellido Paterno',
  `ApellidoMaterno` varchar(50) NOT NULL COMMENT 'Apellido Materno',
  `RegistroHacienda` char(1) NOT NULL COMMENT 'Registro alta en hacienda S= si, N= no',
  `Nacion` char(1) NOT NULL COMMENT 'Nacionalidad N = Nacional, E = Extranjero',
  `PaisResidencia` int(5) NOT NULL COMMENT 'Pais de Residencia, Llave Foranea Hacia tabla PAISES',
  `RFC` char(13) NOT NULL COMMENT 'Registro Federal de Contribuyentes',
  `CURP` char(18) NOT NULL COMMENT 'Clave Unica de Registro Poblacional',
  `EstadoID` int(11) NOT NULL COMMENT 'Hace referencia al ID del estado del cliente',
  `MunicipioID` int(11) NOT NULL COMMENT 'Hace referencia al ID del muncipio del cliente',
  `LocalidadID` int(11) NOT NULL COMMENT 'Numero de Localidad Correspondiente al Municipio',
  `ColoniaID` int(11) NOT NULL COMMENT 'iD de la colonia',
  `Calle` varchar(50) NOT NULL COMMENT 'Nombre de la calle',
  `NumeroCasa` char(10) NOT NULL COMMENT 'Numero de casa',
  `NumInterior` char(10) NOT NULL COMMENT 'Numero interior de la casa.',
  `Piso` char(50) NOT NULL COMMENT 'Número de piso.',
  `CP` char(5) NOT NULL COMMENT 'Codigo Postal',
  `Lote` char(50) NOT NULL COMMENT 'Lote',
  `Manzana` char(50) NOT NULL COMMENT 'Manzana',
  `DireccionCompleta` varchar(500) NOT NULL COMMENT 'Este campo se arma con los campos calle, numero, colonia, y CP.',
  `Estatus` char(1) NOT NULL COMMENT 'Indica el estatus de la generacion de la Constancia de Retencion\nP = Pendiente\nG = Generada',
  `EmpresaID` int(11) NOT NULL COMMENT 'Parametro de auditoria ID de la empresa',
  `Usuario` int(11) NOT NULL COMMENT 'Parametro de auditoria ID del usuario',
  `FechaActual` datetime NOT NULL COMMENT 'Parametro de auditoria Fecha actual',
  `DireccionIP` varchar(15) NOT NULL COMMENT 'Parametro de auditoria Direccion IP ',
  `ProgramaID` varchar(50) NOT NULL COMMENT 'Parametro de auditoria Programa ',
  `Sucursal` int(11) NOT NULL COMMENT 'Parametro de auditoria ID de la sucursal',
  `NumTransaccion` bigint(20) NOT NULL COMMENT 'Parametro de auditoria Numero de la transaccion',
  PRIMARY KEY (`RelacionadoFiscalID`),
  KEY `idx_RELACIONADOSFICALES_1` (`PaisResidencia`),
  KEY `idx_RELACIONADOSFICALES_2` (`EstadoID`),
  KEY `idx_RELACIONADOSFICALES_3` (`MunicipioID`),
  KEY `idx_RELACIONADOSFICALES_4` (`LocalidadID`),
  KEY `idx_RELACIONADOSFICALES_5` (`ColoniaID`),
  KEY `idx_RELACIONADOSFICALES_6` (`ClienteID`),
  KEY `idx_RELACIONADOSFICALES_7` (`TipoRelacionado`,`CteRelacionadoID`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TAB: Almacena datos de las personas fiscales relacionadas'$$
