-- RES_CNBV_CLIENTES
DELIMITER ;
DROP TABLE IF EXISTS `RES_CNBV_CLIENTES`;
DELIMITER $$

CREATE TABLE RES_CNBV_CLIENTES (
	ClienteID 				INT(11) 		NOT NULL 	 COMMENT 'LLave Primaria para Identificar los Clientes\n',
	EmpresaID 				INT(11) 		DEFAULT NULL COMMENT 'Llave Foranea Hacia Paquete Empresa si existe pero no es necesaria.\n',
	SucursalOrigen 			INT(5) 			DEFAULT NULL COMMENT 'No de Sucursal a la que pertenece el cliente, Llave Foranea Hacia Tabla SUCURSALES\n',
	TipoPersona 			CHAR(1) 		DEFAULT NULL COMMENT 'Tipo de Personalidad del Cliente M.- Persona Moral A.- Persona Fisica Con Actividad Empresarial F.- Persona Fisica Sin Actividad Empresarial\n',
	Titulo 					VARCHAR(10) 	DEFAULT NULL COMMENT 'Titulo del Cliente\nTitulo del Cliente, Ej. Sr., Sra, Srita, Lic, Dr. Ing, Prof.,CP, etc',
	PrimerNombre 			VARCHAR(50) 	DEFAULT NULL COMMENT 'Primer Nombre del Cliente',
	SegundoNombre 			VARCHAR(50) 	DEFAULT NULL COMMENT 'Segundo Nombre del Cliente\n',
	TercerNombre 			VARCHAR(50) 	DEFAULT NULL COMMENT 'Tercer Nombre Del Cliente\n',
	ApellidoPaterno 		VARCHAR(50) 	DEFAULT NULL COMMENT 'Apellido Paterno del Cliente\n',
	ApellidoMaterno 		VARCHAR(50) 	DEFAULT NULL COMMENT 'Apellido Materno del Cliente\n',
	FechaNacimiento 		DATE 			DEFAULT NULL COMMENT 'Fecha Nacimiento del Cliente o Rep Legal\n',
	CURP 					CHAR(18) 		DEFAULT NULL COMMENT 'Clave Unica de Registro Poblacional\n',
	Nacion 					CHAR(1) 		DEFAULT NULL COMMENT 'Nacionalidad del cliente\n''N'' = Nacional\n''E'' = Extranjero\n',
	PaisResidencia 			INT(5) 			DEFAULT NULL COMMENT 'Pais de Residencian, Llave Foranea Hacia tabla PAISES',
	GrupoEmpresarial 		INT(11) 		DEFAULT NULL COMMENT 'Llave Foranea Hacia tabla GRUPOSEMP si existe peor no es necesaria.\n',
	RazonSocial 			VARCHAR(150) 	DEFAULT NULL COMMENT 'Razon Social\n',
	TipoSociedadID 			INT(11) 		DEFAULT NULL COMMENT 'Tipo de Sociedad, tiene llave foranea a la tabla	TIPOSOCIEDAD si existe pero no es necesaria',
	Fax 					VARCHAR(30) 	DEFAULT NULL COMMENT 'Fax o Faxes del Cliente\n',
	Correo 					VARCHAR(50) 	DEFAULT NULL COMMENT 'Fax o Faxes del Cliente\n',
	RFC 					CHAR(13) 		DEFAULT NULL COMMENT 'Registro Federal de Contribuyentes del Cliente\n',
	RFCpm 					CHAR(13) 		DEFAULT NULL COMMENT 'RFC de persona moral',
	RFCOficial 				CHAR(13) 		DEFAULT NULL COMMENT 'RFC del cliente ya sea RFC que es asignado como persona fisica o el RFC como persona moral',
	SectorGeneral 			INT(3) 			DEFAULT NULL COMMENT 'Sector General del Cliente,Llave Foranea Hacia tabla SECTORES\n',
	ActividadBancoMX 		VARCHAR(15) 	DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun Banco de Mexico,Llave Foranea Hacia tabla ACTIVIDADESBMX\n',
	ActividadINEGI 			INT(11) 		DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun INEGI,Llave Foranea Hacia tabla ACTIVIDADESINEGI\n',
	ActividadFR 			BIGINT(20) 		DEFAULT NULL COMMENT 'Actividad Principal del Cte, segun la ACTIVIDADESFR',
	ActividadFOMURID 		INT(11) 		DEFAULT NULL COMMENT 'Actividad Fomur del Cte, segun la ACTIVIDADESFOMUR',
	SectorEconomico 		INT(11) 		DEFAULT NULL COMMENT 'Sector Economico Segun INEGI,Llave Foranea Hacia tabla SECTORESECONOM\n',
	Sexo 					CHAR(1) 		DEFAULT NULL COMMENT 'Codigo de sexo del cliente\nClave Sexo:\n''M'' = Masculino\n''F''	= Femenino',
	EstadoCivil 			CHAR(2) 		DEFAULT NULL COMMENT 'Clave Estado Civil:\\n\\''S\\'' = Soltero\\n\\''CS\\''	= Casado Bienes Separados\\n\\''CM\\''	= Casado Bienes Mancomunados\\n\\''CC\\''	= Casado Bienes Mancomunados Con Capitulacion\\n\\''V\\'' = Viudo\\n\\''D\\'' = Divorciado\\n\\''SE\\''	= Separado\\n\\''U\\'' = Union Libre',
	LugarNacimiento 		INT(11) 		DEFAULT NULL COMMENT 'Pais de Nacimiento, llave foranea a PAISES\n',
	EstadoID 				INT(11) 		DEFAULT NULL COMMENT 'Identificador de Estado que Se Encuentra en la tabla ESTADOSREPUB',
	OcupacionID 			INT(5) 			DEFAULT NULL COMMENT 'Profesión del cliente,Llave Foranea Hacia tabla OCUPACIONES si existe pero no es necesario.\n',
	LugardeTrabajo 			VARCHAR(100) 	DEFAULT NULL COMMENT 'Lugar donde Trabaja\n',
	Puesto 					VARCHAR(100) 	DEFAULT NULL COMMENT 'Puesto en el Trabajo\n',
	DomicilioTrabajo 		VARCHAR(500) 	NOT NULL 	 COMMENT 'Domicilio de trabajo del cliente',
	TelTrabajo 				VARCHAR(20) 	DEFAULT NULL COMMENT 'Telefono del Trabajo\n',
	AntiguedadTra 			DECIMAL(12,2)	DEFAULT NULL COMMENT 'Antiguedad usado como decimal como años\nejemplo: 10.5\n10 años y 6 meses.',
	TelefonoCelular 		VARCHAR(20) 	DEFAULT NULL COMMENT 'TelefonoCelular\n',
	Telefono 				VARCHAR(20) 	DEFAULT NULL COMMENT 'Telefonos del Cliente\n',
	Clasificacion 			CHAR(1) 		DEFAULT NULL COMMENT 'Clasificación del cliente, valores esperados:\nI .- Cliente independiente\nN.- Cliente Empresa de Nomina \nE.- Cliente Empleado.\nC.- Cliente Corportativo\nR .- Relacionado a Corporativo, \nF .- Negocio Afiliado\nM.- Empleado de Nomina\nO.- Cliente Funcionario',
	MotivoApertura 			CHAR(1) 		DEFAULT NULL COMMENT 'Motivo de Apertura Razon del alta del cliente, valores esperados:\n1.- Credito \n2.- Recomendado \n3.- Publicidad	Campaña Promocion \n4.- Necesidad/ Proveedor \n5.- Cercania de Sucursal\n6.- Cuenta de Captacion.',
	PagaISR 				CHAR(1) 		DEFAULT NULL COMMENT 'Paga ISR en Inversiones\nEspecifica si el cliente paga o no ISR por los \nIntereses de Inversión\n	''S''.- Si Paga\n	''N''.- No Paga',
	PagaIVA 				CHAR(1) 		DEFAULT NULL COMMENT 'Paga IVA\nEspecifica si el cliente paga o no IVA\n	''S''.- Si Paga\n	''N''.- No Paga',
	PagaIDE 				CHAR(1)			DEFAULT NULL COMMENT 'Especifica si Cobra Impuesto de Depositos En Efectivo\nEspecifica si Cobra Impuesto de Depositos en Efectivo\n''N'' = No \n''S'' = Si',
	NivelRiesgo 			CHAR(1)			DEFAULT NULL COMMENT '\nNivel de riesgo del cliente:\nA .-	Alto\nM .- Medio\nB .-	Bajo',
	PromotorInicial 		INT(6) 			DEFAULT NULL COMMENT 'Promotor original asignado al cliente,Llave Foranea Hacia tabla PROMOTORES\n',
	PromotorActual 			INT(6) 			DEFAULT NULL COMMENT 'Promotor actual del cliente	,Llave Foranea Hacia tabla PROMOTORES\n',
	FechaAlta 				DATE 			DEFAULT NULL COMMENT 'Fecha de Alta o Registro. Mostra Fec. Hoy\n',
	Estatus 				CHAR(1) 		DEFAULT NULL COMMENT 'Estatus del cliente. Inicialmente nace Activo \n''A''.- Activo\n''I'' .- Inactivo',
	NombreCompleto 			VARCHAR(200) 	DEFAULT NULL COMMENT 'Este campo no se captura, se forma en base a los nombres y apellidos\n',
	TipoInactiva 			INT(11) 		DEFAULT NULL COMMENT 'Tipo de movimiento 1.-Activación, 2.-Inactivacion\n',
	MotivoInactiva 			VARCHAR(150) 	DEFAULT NULL COMMENT 'Motivo de la Activación/Inactivacion\n',
	EsMenorEdad 			CHAR(1) 		DEFAULT NULL COMMENT 'Campo que identifica si un cliente es menor de edad S.- Si	N.-NO',
	CorpRelacionado 		VARCHAR(45) 	DEFAULT NULL COMMENT 'Es el dato de corporativo \nrelacionado a el \ncliente (el \ncorporativo es otro \ncliente moral)\nademás solo debe \nde tener datos si \nel en el campo \nclasificación tiene\nel valor de "R"',
	CalificaCredito 		CHAR(1) 		DEFAULT NULL COMMENT 'Calificacion del cliente\\n\\nN : NO ASIGNADA\\nA: EXCELENTE\\nB : BUENA\\nC: REGULAR',
	RegistroHacienda 		CHAR(1) 		DEFAULT NULL COMMENT 'Registro de Hacienda',
	FechaBaja 				DATE 			DEFAULT NULL COMMENT 'Indica la fecha en la que se da de baja el cliente',
	Observaciones 			VARCHAR(500) 	DEFAULT NULL COMMENT 'Observaciones Sobre el cliente. Opcional',
	NoEmpleado 				VARCHAR(20) 	DEFAULT NULL COMMENT 'Numero de empleado en la institucion de nomina',
	TipoEmpleado 			CHAR(1) 		DEFAULT NULL COMMENT 'Tipo de Empleado en la Institucion de Nomina',
	ExtTelefonoPart 		VARCHAR(7) 		DEFAULT NULL COMMENT 'Contiene en número de extensión del teléfono de trabajo',
	ExtTelefonoTrab 		VARCHAR(6) 		DEFAULT NULL,
	EjecutivoCap 			INT(11) 		DEFAULT NULL COMMENT 'Ejecutivo de captación\n0.- No Asignado',
	PromotorExtInv 			INT(11) 		DEFAULT NULL COMMENT 'Promotor Extreno de inversion\n0.- No Asignado',
	TipoPuesto 				INT(11) 		DEFAULT NULL COMMENT 'Tipo de Puesto de Empleados Nomina',
	FechaIniTrabajo 		DATE 			DEFAULT '1900-01-01' COMMENT 'Fecha de inicio en el trabajo actual',
	UbicaNegocioID 			INT(11) 		DEFAULT '0' COMMENT 'ID de la ubicacion del negocio, relacion con CATUBICANEGOCIO',
	FechaConstitucion 		DATE 			DEFAULT NULL COMMENT 'Fecha de Constitucion ante el Registro Federal de Contribuyentes.',
	FEA 					VARCHAR(250) 	DEFAULT NULL COMMENT 'Firma Electrónica Avanzada, en caso de contar con ella.',
	PaisFEA 				INT(11) 		DEFAULT NULL,
	PaisConstitucionID 		INT(11) 		DEFAULT NULL COMMENT 'Pais de Constitucion de la empresa',
	CorreoAlterPM 			VARCHAR(50) 	DEFAULT NULL COMMENT 'Correo Alternativo Persona Moral',
	NombreNotario 			VARCHAR(150) 	DEFAULT NULL COMMENT 'Nombre Notario campo para Persona Moral',
	NumNotario 				INT(11) 		DEFAULT NULL COMMENT 'Numero de Notario campo para Persona Moral',
	InscripcionReg 			VARCHAR(50) 	DEFAULT NULL COMMENT 'Inscripcion en el registro publico campo para Persona Moral',
	EscrituraPubPM 			VARCHAR(20)		DEFAULT NULL COMMENT 'Escritura Publica Persona Moral',
	SoloNombres 			VARCHAR(500) 	NOT NULL COMMENT 'Primer Nombre, Segundo Nombre y Tercer Nombre',
	SoloApellidos 			VARCHAR(500) 	NOT NULL COMMENT 'Apellido Paterno y Apellido Materno',
	FechaSigEvalPLD 		DATE 			DEFAULT NULL COMMENT 'Fecha de la siguiente evaluación para el Nivel de Riesgo',
	Usuario 				INT(11) 		DEFAULT NULL COMMENT 'Campo de auditoria',
	FechaActual 			DATETIME 		DEFAULT NULL COMMENT 'Campo de auditoria',
	DireccionIP 			VARCHAR(15) 	DEFAULT NULL COMMENT 'Campo de auditoria',
	ProgramaID 				VARCHAR(50) 	DEFAULT NULL COMMENT 'Campo de auditoria',
	Sucursal 				INT(11) 		DEFAULT NULL COMMENT 'Campo de auditoria',
	NumTransaccion 			BIGINT(20) 		DEFAULT NULL COMMENT 'Campo de auditoria',
	PRIMARY KEY (ClienteID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tab Respaldo de datos de tabla Clientes'$$