-- RES_CNBV_HISCLIENTES
DELIMITER ;
DROP TABLE IF EXISTS `RES_CNBV_HISCLIENTES`;
DELIMITER $$

CREATE TABLE RES_CNBV_HISCLIENTES (
	NumTransaccionAct 	BIGINT(20) 	NOT NULL COMMENT 		'Numero de Transaccion que realizo la actualización de los datos',
	ClienteID 			INT(11) 	NOT NULL COMMENT 		'LLave Primaria para Identificar los Clientes',
	TipoPersona 		CHAR(1) 	DEFAULT NULL COMMENT 	'Tipo de Personalidad del Cliente M.- Persona Moral A.- Persona Fisica Con Actividad Empresarial F.- Persona Fisica Sin Actividad Empresarial',
	Titulo 				VARCHAR(10) DEFAULT NULL COMMENT 	'Titulo del Cliente\nTitulo del Cliente, Ej. Sr., Sra, Srita, Lic, Dr. Ing, Prof.,CP, etc',
	PrimerNombre 		VARCHAR(50) DEFAULT NULL COMMENT 	'Primer Nombre del Cliente',
	SegundoNombre 		VARCHAR(50) DEFAULT NULL COMMENT 	'Segundo Nombre del Cliente',
	TercerNombre 		VARCHAR(50) DEFAULT NULL COMMENT 	'Tercer Nombre Del Cliente',
	ApellidoPaterno		VARCHAR(50) DEFAULT NULL COMMENT 	'Apellido Paterno del Cliente',
	ApellidoMaterno 	VARCHAR(50) DEFAULT NULL COMMENT 	'Apellido Materno del Cliente',
	FechaNacimiento 	DATE 		DEFAULT NULL COMMENT 	'Fecha Nacimiento del Cliente o Rep Legal',
	CURP 				CHAR(18) 	DEFAULT NULL COMMENT 	'Clave Unica de Registro Poblacional',
	Nacion 				CHAR(1) 	DEFAULT NULL COMMENT 	'Nacionalidad del cliente''N'' = Nacional''E'' = Extranjero',
	PaisResidencia 		INT(5) 		DEFAULT NULL COMMENT 	'Pais de Residencian, Llave Foranea Hacia tabla PAISES',
	GrupoEmpresarial 	INT(11) 	DEFAULT NULL COMMENT 	'Llave Foranea Hacia tabla GRUPOSEMP si existe peor no es necesaria.',
	RazonSocial 		VARCHAR(150) DEFAULT NULL COMMENT 	'Razon Social',
	TipoSociedadID 		INT(11) 	DEFAULT NULL COMMENT 	'Tipo de Sociedad, tiene llave foranea a la tabla  TIPOSOCIEDAD si existe pero no es necesaria',
	RFC 				CHAR(13) 	DEFAULT NULL COMMENT 	'Registro Federal de Contribuyentes del Cliente',
	RFCpm 				CHAR(13) 	DEFAULT NULL COMMENT 	'RFC de persona moral',
	RFCOficial 			CHAR(13) 	DEFAULT NULL COMMENT 	'RFC del cliente ya sea RFC que es asignado como persona fisica o el RFC como persona moral',
	SectorGeneral 		INT(3) 		DEFAULT NULL COMMENT 	'Sector General del Cliente,Llave Foranea Hacia tabla SECTORES',
	ActividadBancoMX 	VARCHAR(15) DEFAULT NULL COMMENT 	'Actividad Principal del Cte, segun Banco de Mexico,Llave Foranea Hacia tabla ACTIVIDADESBMX',
	ActividadINEGI 		INT(11) 	DEFAULT NULL COMMENT 	'Actividad Principal del Cte, segun INEGI,Llave Foranea Hacia tabla ACTIVIDADESINEGI',
	ActividadFR 		BIGINT(20) 	DEFAULT NULL COMMENT 	'Actividad Principal del Cte, segun la ACTIVIDADESFR',
	ActividadFOMURID 	INT(11) 	DEFAULT NULL COMMENT 	'Actividad Fomur del Cte, segun la ACTIVIDADESFOMUR',
	SectorEconomico 	INT(11) 	DEFAULT NULL COMMENT 	'Sector Economico Segun INEGI,Llave Foranea Hacia tabla SECTORESECONOM',
	Sexo 				CHAR(1) 	DEFAULT NULL COMMENT 	'Codigo de sexo del cliente\nClave Sexo:''M'' = Masculino''F''  = Femenino',
	EstadoCivil 		CHAR(2) 	DEFAULT NULL COMMENT 	'Clave Estado Civil:\\n\\''S\\'' = Soltero\\n\\''CS\\''  = Casado Bienes Separados\\n\\''CM\\''  = Casado Bienes Mancomunados\\n\\''CC\\''  = Casado Bienes Mancomunados Con Capitulacion\\n\\''V\\'' = Viudo\\n\\''D\\'' = Divorciado\\n\\''SE\\''  = Separado\\n\\''U\\'' = Union Libre',
	LugarNacimiento 	INT(11) 	DEFAULT NULL COMMENT 	'Pais de Nacimiento, llave foranea a PAISES',
	EstadoID 			INT(11) 	DEFAULT NULL COMMENT 	'Identificador de Estado que Se Encuentra en la tabla ESTADOSREPUB',
	OcupacionID 		INT(5) 		DEFAULT NULL COMMENT 	'Profesión del cliente,Llave Foranea Hacia tabla OCUPACIONES si existe pero no es necesario.',
	LugardeTrabajo 		VARCHAR(100) DEFAULT NULL COMMENT 	'Lugar donde Trabaja',
	Puesto 				VARCHAR(100) DEFAULT NULL COMMENT 	'Puesto en el Trabajo',
	NivelRiesgo 		CHAR(1) 	DEFAULT NULL COMMENT 	'\nNivel de riesgo del cliente:\nA .-  Alto\nM .- Medio\nB .-  Bajo',
	NombreCompleto 		VARCHAR(200) DEFAULT NULL COMMENT 	'Este campo no se captura, se forma en base a los nombres y apellidos',
	FechaConstitucion 	DATE 		DEFAULT NULL COMMENT 	'Fecha de Constitucion ante el Registro Federal de Contribuyentes.',
	FEA 				VARCHAR(250) DEFAULT NULL COMMENT 	'Firma Electrónica Avanzada, en caso de contar con ella.',
	PaisConstitucionID 	INT(11) 	DEFAULT NULL COMMENT 	'Pais de Constitucion de la empresa',
	NombreNotario 		VARCHAR(150) DEFAULT NULL COMMENT 	'Nombre Notario campo para Persona Moral',
	NumNotario 			INT(11) 	DEFAULT NULL COMMENT 	'Numero de Notario campo para Persona Moral',
	InscripcionReg 		VARCHAR(50) DEFAULT NULL COMMENT 	'Inscripcion en el registro publico campo para Persona Moral',
	EscrituraPubPM 		VARCHAR(20) DEFAULT NULL COMMENT 	'Escritura Publica Persona Moral',
	Usuario 			INT(11) 	DEFAULT NULL COMMENT 	'Auditoria',
	FechaActual 		DATETIME 	DEFAULT NULL COMMENT 	'Auditoria',
	DireccionIP 		VARCHAR(15) DEFAULT NULL COMMENT 	'Auditoria',
	ProgramaID 			VARCHAR(50) DEFAULT NULL COMMENT 	'Auditoria',
	Sucursal 			INT(11) 	DEFAULT NULL COMMENT 	'Auditoria',
	NumTransaccion 		BIGINT(20) 	DEFAULT NULL COMMENT 	'Auditoria',
	PRIMARY KEY (ClienteID,NumTransaccionAct)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tab: Respaldo de Tabla Historica de los Modificaciones de los Registros de la tabla de CLIENTES'$$
