-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- SOLICITUDCREDITO
DELIMITER ;
DROP TABLE IF EXISTS `SOLICITUDCREDITO`;

DELIMITER $$
CREATE TABLE `SOLICITUDCREDITO` (
  `SolicitudCreditoID` bigint(20) NOT NULL COMMENT 'Número de Solicitud',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'ID o Número de Cliente',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Moneda',
  `ProductoCreditoID` int(11) DEFAULT NULL COMMENT 'ID del Producto o Tipo de Credito',
  `ProspectoID` bigint(20) DEFAULT NULL COMMENT 'ID o Número de Prospecto',
  `FechaRegistro` date DEFAULT NULL COMMENT 'Fecha de Registro de la Solicitud',
  `FechaAutoriza` date DEFAULT NULL COMMENT 'Fecha de Formalización',
  `MontoSolici` decimal(12,2) DEFAULT NULL COMMENT 'Monto Solicitado',
  `MontoAutorizado` decimal(12,2) DEFAULT NULL COMMENT 'Monto Autorizado',
  `PlazoID` varchar(20) DEFAULT NULL COMMENT 'Plazo en meses para el Vencimiento de Crédito',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus de la Solicitud \nI = Inactiva  \nL = Liberada  \nA = Autorizada  \nC = Cancelada  \nR =  Rechazada  \nD =  Desembolsada',
  `TipoDispersion` char(1) DEFAULT NULL COMMENT 'Tipo de Dispersión  \nS.- SPEI \nC.- Cheque \nO.- Orden de Pago \nE.- Efectivo \nA.- Dispersion Santander',
  `CuentaCLABE` char(18) DEFAULT NULL COMMENT 'Cuenta CLABE para realizar SPEIS',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Sucursal donde se dio de alta la solicitud del credito',
  `ForCobroComAper` char(1) DEFAULT NULL COMMENT 'Forma de cobro de comision por apertura.\nA: Anticipado \nD: Deduccion\nF: Financiamiento\nP: Programado',
  `MontoPorComAper` decimal(12,4) DEFAULT NULL COMMENT 'Monto de la comision por apertura',
  `IVAComAper` decimal(12,4) DEFAULT NULL COMMENT 'IVA de comision por apertura',
  `DestinoCreID` int(11) DEFAULT NULL COMMENT 'Destino de credito',
  `PromotorID` int(11) DEFAULT NULL COMMENT 'Promotor',
  `CalcInteresID` int(11) DEFAULT NULL,
  `TasaFija` decimal(8,4) DEFAULT NULL,
  `TasaBase` decimal(8,4) DEFAULT NULL,
  `SobreTasa` decimal(8,4) DEFAULT NULL,
  `PisoTasa` decimal(8,4) DEFAULT NULL,
  `TechoTasa` decimal(8,4) DEFAULT NULL,
  `FactorMora` decimal(8,4) DEFAULT NULL,
  `FrecuenciaCap` char(1) DEFAULT NULL COMMENT 'Pago de la cuota cAPITAL(Semanal (S), Catorcenal(C) , Quincenal (Q), Mensual(M), P .- Periodo B.-Bimestral T.-Trimestral R.-TetraMestral E.-Semestral A.-Anual L.-Libres)',
  `PeriodicidadCap` int(11) DEFAULT NULL,
  `FrecuenciaInt` char(1) DEFAULT NULL COMMENT 'Pago de la cuota Interes(Semanal (S), Catorcenal(C) , Quincenal (Q), Mensual(M), P .- Periodo B.-Bimestral T.-Trimestral R.-TetraMestral E.-Semestral A.-Anual L.-Libres)',
  `PeriodicidadInt` int(11) DEFAULT NULL,
  `TipoPagoCapital` char(1) DEFAULT NULL,
  `NumAmortizacion` int(11) DEFAULT NULL COMMENT 'numero de amortizaciones (de capital)',
  `CalendIrregular` char(1) DEFAULT NULL,
  `DiaPagoInteres` char(1) DEFAULT NULL,
  `DiaPagoCapital` char(1) DEFAULT NULL,
  `DiaPagoProd` char(1) DEFAULT NULL COMMENT 'Dia de pago de capital del producto de credito: F=fin de mes, D=dia \ndel mes, A=aniversario, I=indistinto',
  `DiaMesInteres` int(11) DEFAULT NULL,
  `DiaMesCapital` int(11) DEFAULT NULL,
  `AjusFecUlVenAmo` char(1) DEFAULT NULL,
  `AjusFecExiVen` char(1) DEFAULT NULL,
  `NumTransacSim` bigint(20) DEFAULT NULL,
  `ValorCAT` decimal(12,4) DEFAULT NULL,
  `FechaInhabil` char(1) DEFAULT NULL,
  `AporteCliente` decimal(12,2) DEFAULT NULL COMMENT 'Aporte del Cliente (Deposito)',
  `PorcGarLiq` decimal(12,2) DEFAULT NULL COMMENT 'Especifica el porcentaje  de garantia liquida',
  `UsuarioAutoriza` int(11) DEFAULT NULL COMMENT 'Usuario que Autoriza',
  `FechaRechazo` datetime DEFAULT NULL,
  `UsuarioRechazo` int(11) DEFAULT NULL,
  `ComentarioRech` varchar(1000) DEFAULT NULL COMMENT 'Comentario de Rechazo',
  `MotivoRechazo` int(11) DEFAULT NULL COMMENT 'Motivo Rechazo',
  `TipoCredito` char(1) DEFAULT NULL COMMENT 'Indica el tratamiento al credito N=nuevo, R=reestructura, O=renovacion',
  `NumCreditos` int(11) DEFAULT NULL COMMENT 'Numero de Creditos en caso de ser tipo de credito Renovado',
  `Relacionado` bigint(12) DEFAULT NULL COMMENT 'Credito relacionado por: Renovacion o Reestructura, puede ser vacio',
  `Proyecto` varchar(500) DEFAULT NULL COMMENT 'Descripcion del proyecto',
  `TipoFondeo` char(1) DEFAULT NULL COMMENT 'Tipo de Fondeo:\nP .- Recursos Propios\nF .- Institucion de Fondeo',
  `InstitFondeoID` int(11) DEFAULT NULL COMMENT 'Insitucion de Fondeo, puede no escoger linea de fondeo',
  `LineaFondeo` int(11) DEFAULT NULL COMMENT 'Si escoge una institucion de fondeo, debe escoger sobre \nQue linea De fondeo (LINEAFONDEADOR)\n',
  `TipoCalInteres` int(11) DEFAULT NULL COMMENT '1 .- Saldos Insolutos\n2 .- Monto Original (Saldos Globales)',
  `TipoGeneraInteres` char(1) NOT NULL COMMENT 'Tipo de Monto Original (Saldos Globales): \n"I".- Iguales \n"D".- Dias Transcurridos',
  `CreditoID` bigint(20) DEFAULT NULL COMMENT 'Numero de Credito',
  `FechaFormalizacion` date DEFAULT NULL COMMENT 'Fecha Formalizacion',
  `MontoFondeado` decimal(14,2) DEFAULT NULL,
  `PorcentajeFonde` decimal(14,6) DEFAULT NULL,
  `NumeroFondeos` int(11) DEFAULT NULL,
  `NumAmortInteres` int(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones (cuotas) de Interes',
  `MontoCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto de la Cuota\\n',
  `FechaVencimiento` date DEFAULT NULL,
  `GrupoID` int(11) DEFAULT NULL COMMENT 'ID del Grupo',
  `ComentarioEjecutivo` varchar(5000) DEFAULT NULL COMMENT 'Comentario que envia la persona que autoriza al Ejecutivo de Cuenta cuando le Regresa la Solicitud para alguna modificacion',
  `ComentarioMesaControl` varchar(6000) DEFAULT NULL COMMENT 'Comentario que se agrega al checkList de Mesa de Control los store que usan esta columna  solo tendran 800',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de inicio',
  `FechaInicioAmor` date DEFAULT NULL COMMENT 'Fecha en la que inician las amortizaciones y cobro de intereses, en un desembolso anticipado',
  `MontoSeguroVida` decimal(12,2) DEFAULT NULL COMMENT 'Monto del Seguro de Vida',
  `ForCobroSegVida` char(1) DEFAULT NULL COMMENT 'A: Anticipado, D: Deduccion, F: Financiamiento',
  `ClasiDestinCred` char(1) DEFAULT NULL,
  `CicloGrupo` int(11) DEFAULT NULL COMMENT 'Ciclo del Grupo, en Caso de un Credito Grupal',
  `InstitucionNominaID` int(11) DEFAULT NULL COMMENT 'Institucion de Nomina a la que pertenece el Credito',
  `FolioCtrl` varchar(20) DEFAULT NULL COMMENT 'Numero de control que la institucion de nomina tiene para el control de sus empleados',
  `HorarioVeri` varchar(20) DEFAULT NULL COMMENT 'Horario de llamada al cliente para la verificacion de sus datos\n\nEjemplo:\n12:00pm - 2:00pm',
  `UsuarioAltaSol` int(11) DEFAULT NULL COMMENT 'Indica el Usuario Que Registra la Solicitud de Crédito',
  `DescuentoSeguro` decimal(12,2) DEFAULT NULL COMMENT 'Pocentaje de descuento Aplicado al Monto de seguro de vida ',
  `MontoSegOriginal` decimal(12,2) DEFAULT NULL COMMENT 'Monto de seguro de vida original',
  `CobraSeguroCuota` char(1) DEFAULT NULL COMMENT 'Valida si el producto cobra seguro por cuota, este campo es del producto\n',
  `CobraIVASeguroCuota` char(1) DEFAULT NULL COMMENT 'Valida si el producto cobra IVA seguro por cuota, este campo es del producto',
  `MontoSeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto por Seguro por Cuota',
  `IVASeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto a cobrar de IVA para el monto por seguro por cuota',
  `FechaLiberada` datetime DEFAULT NULL COMMENT 'Fecha de Liberacion',
  `FechaActualizada` datetime DEFAULT NULL COMMENT 'Fecha de Regreso al Ejecutivo',
  `Condicionada` char(1) DEFAULT 'N' COMMENT 'Valida si la Solicitud de Credito esta Condicionada',
  `CanalIngreso` char(1) DEFAULT 'S' COMMENT 'S .- Sucursal\nM .- Banca Movil\nL .- Banca en Linea',
  `SolicitudOrigen` bigint(20) DEFAULT '0' COMMENT 'Solicitud de Origen si es una Reestructura',
  `TipoLiquidacion` char(1) DEFAULT 'T' COMMENT 'Tipo de Liquidacion para una Renovacion de Credito\nT: Total\nP: Parcial',
  `CantidadPagar` decimal(12,2) DEFAULT '0.00' COMMENT 'Cantidad a Pagar en una Renovacion de Credito',
  `FechaCancela` datetime DEFAULT '1900-01-01 00:00:00' COMMENT 'Fecha de Cancelacion de la Solicitud de Credito',
  `TipoConsultaSIC` char(2) DEFAULT NULL COMMENT 'Se indica BC si la Consulta se realizó a Buró de Crédito o CC si se realizó a  Círculo de Crédito',
  `FolioConsultaBC` varchar(30) DEFAULT NULL COMMENT 'Folio de consulta de Buro de Credito',
  `FolioConsultaCC` varchar(30) DEFAULT NULL COMMENT 'Folio de consulta de Circulo de Credito',
  `EsAgropecuario` char(1) DEFAULT 'N' COMMENT 'Define si la solicitud de credito es de tipo Agropecuario. Esto lo define el Producto de Credito',
  `EsConsolidacionAgro`   CHAR(1) NOT NULL COMMENT 'Indica si la solicitud de credito Agro de una consolidación.\nS.- SI \nN.- NO',
  `DeudorOriginalID`   INT(11) NOT NULL COMMENT 'Indica el Cliente Original de la Solicitud de Crédito en caso de ser Consolidado Agro',
  `CadenaProductivaID` int(11) DEFAULT NULL COMMENT 'ID del Catalogo CATCADENAPRODUCTIVA',
  `RamaFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la Tabla CATRAMAFIRA',
  `SubramaFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la tabla CATSUBRAMAFIRA',
  `ActividadFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la Tabla CATACTIVIDADESFIRA',
  `TipoGarantiaFIRAID` int(11) DEFAULT NULL COMMENT 'ID de la Tabla CATTIPOGARANTIAFIRA',
  `EstatusGarantiaFIRA` char(1) DEFAULT NULL COMMENT 'Determina el estatus de la contratación de garantias Fega y Fonaga, para creditos fondeados con FIRA el Estatus es automatico como procesado.\nI  : Inactivo\nA : Autorizado\nC : Cancelado \nP : Aplicado\n',
  `ProgEspecialFIRAID` varchar(10) DEFAULT NULL COMMENT 'ID de la TABLA CATFIRAPROGESP',
  `Refinancia` char(1) DEFAULT 'N' COMMENT 'Indica si los intereses serán refinanciados\nS: Si\nN: No',
  `FechaCobroComision` date DEFAULT '1900-01-01' COMMENT 'Fecha de Cobro de la comision cuando la forma del cobro sea programada',
  `EsAutomatico` char(1) DEFAULT 'N' COMMENT 'Indica si el credito es Automatico\nS: Si\nN: No',
  `TipoAutomatico` char(1) DEFAULT '' COMMENT 'Indica si el credito es automatico sobre.\nA: Ahorro\nI: Inversion',
  `InvCredAut` int(11) DEFAULT '0' COMMENT 'Inversion relacionada al Credito Automatico',
  `CtaCredAut` bigint(12) DEFAULT '0' COMMENT 'Cuenta de Ahorro relacionada al Credito Automatico',
  `AcreditadoIDFIRA` bigint(20) DEFAULT NULL COMMENT 'Numero de Acreditado FIRA',
  `CreditoIDFIRA` bigint(20) DEFAULT NULL COMMENT 'Numero de Credito FIRA',
  `Reacreditado` char(1) DEFAULT 'N' COMMENT 'Indica si un Crédito esta Reacreditado',
  `NivelID` int(11) DEFAULT '0' COMMENT 'Nivel, corresponde al catálogo NIVELCREDITO.',
  `CobraAccesorios` char(1) DEFAULT 'N' COMMENT 'Indica si el credito cobra accesorios',
  `Cobertura` decimal(14,2) DEFAULT '0.00' COMMENT 'Monto que corresponde al seguro de vida',
  `Prima` decimal(14,2) DEFAULT '0.00' COMMENT 'Monto que el cliente paga/cubre respecto al seguro de vida',
  `Vigencia` int(11) DEFAULT '0' COMMENT 'Meses en que es valido el seguro de vida a partir de su contratacion',
  `AplicaTabla` CHAR(1) DEFAULT 'N' COMMENT 'Indica si aplica tabla real S:SI/N:NO',
  `MotivoRechazoID` varchar(50) DEFAULT NULL COMMENT 'Cadena motivoID por el cual fue rechazado la solicitud sobre el catalogo CATALOGOMOTRECHAZO ',
  `ComentarioRechazo` varchar(200)  COMMENT 'Comentarios del analista sobre el rechazo de la solicitud',
  `ConvenioNominaID` bigint unsigned DEFAULT NULL COMMENT 'Numero de convenio en caso que el producto de credito sea de nomina',
  `FolioSolici` varchar(20) DEFAULT NULL COMMENT 'Folio solicitud "Convenio de nomina"',
  `QuinquenioID` int(11) DEFAULT NULL COMMENT 'Quinquenio  del  catalogo "CATQUINQUENIOS"',
  `ClabeCtaDomici` VARCHAR(20) DEFAULT NULL COMMENT 'Cuenta CLABE para domiciliacion',
  `AplicaDescServicio` char(1) NULL COMMENT 'Indica si la solicitud de crédito tiene servicios adicionales',
  `EsConsolidado` CHAR(1) NOT NULL DEFAULT 'N'  COMMENT 'Indica si la solicitud proviene de una consolidación. S.- Si, N.- No',
  `FlujoOrigen`   CHAR(1) NOT NULL DEFAULT ''   COMMENT 'Indica el flujo por el que nace la solicitu de crédito C.- Flujo Consolidación',
  `TipoCtaSantander` CHAR(1)  DEFAULT NULL COMMENT 'Tipo de cuenta para Dispersion Santander A = Santander = Otro',
  `CtaSantander` VARCHAR(20) DEFAULT NULL COMMENT 'Numero de cuenta Santander cuando la dispersion es TRAN. SANTNADER y TipoCtaSantander es Santander',
  `CtaClabeDisp` VARCHAR(20) DEFAULT NULL COMMENT 'Numero de cuenta Clabe cuando la dispersion es TRAN. SANTANDER y TipoCtaSantander es Otro',
  `LineaCreditoID` BIGINT(20) NOT NULL COMMENT 'Número de Línea de Crédito.',
  `ManejaComAdmon` CHAR(1) NOT NULL COMMENT 'Maneja Comisión Administración \nS.- SI \nN.- NO',
  `ComAdmonLinPrevLiq` CHAR(1) NOT NULL COMMENT 'Comisión de Admon que ha sido pagada de manera anticipada (Previamente Liquidada) \n"".- No aplica \nN.- NO \nS.- SI',
  `ForCobComAdmon` CHAR(1) NOT NULL COMMENT 'Forma de Cobro Comisión Administración \n"".- No aplica \nD.- Disposición \nT.- Total en primera Disposición',
  `ForPagComAdmon` CHAR(1) NOT NULL COMMENT 'Forma de Pago Comisión por Administración \n"".- No aplica \nD.- Deducción \nF.- Financiado',
  `PorcentajeComAdmon` DECIMAL(6,2) NOT NULL COMMENT 'permite un valor de 0% a 100%',
  `MontoPagComAdmon` DECIMAL(14,2) NOT NULL COMMENT 'Monto a Pagar por Comisión por Administración',
  `ManejaComGarantia` CHAR(1) NOT NULL COMMENT 'Maneja Comisión por Garantía \nS.- SI \nN.- NO',
  `ComGarLinPrevLiq` CHAR(1) NOT NULL COMMENT 'Comisión de Garantia que ha sido pagada de manera anticipada (Previamente Liquidada) \n"".- No aplica \nN.- NO \nS.- SI',
  `ForCobComGarantia` CHAR(1) NOT NULL COMMENT 'Forma de Cobro Comisión Garantía \n"".- No aplica \nC.- Cada Cuota',
  `ForPagComGarantia` CHAR(1) NOT NULL COMMENT 'Forma de pago Comision por Garantia \n"".- No aplica \nD.- Deducción \nF.- Financiado',
  `PorcentajeComGarantia` DECIMAL(6,2) NOT NULL COMMENT 'permite un valor de 0% a 100%',
  `MontoPagComGarantia` DECIMAL(14,2) NOT NULL COMMENT 'Monto a Pagar por Comisión por Servicio de Garantía',
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` date DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`SolicitudCreditoID`),
  KEY `INDEX_SOLICITUDCREDITO_1` (`Relacionado`),
  KEY `FK_CLIENTE_SOLICITUDCREDITO` (`ClienteID`),
  KEY `fk_SOLICITUDCREDITO_1_idx` (`MonedaID`),
  KEY `fk_SOLICITUDCREDITO_2_idx` (`ProductoCreditoID`),
  KEY `fk_SOLICITUDCREDITO_3_idx` (`DestinoCreID`),
  KEY `fk_SOLICITUDCREDITO_4_idx` (`ProspectoID`),
  KEY `fk_SOLICITUDCREDITO_5_idx` (`PlazoID`),
  KEY `fk_SOLICITUDCREDITO_6_idx` (`SucursalID`),
  KEY `fk_SOLICITUDCREDITO_7_idx` (`CreditoID`),
  KEY `fk_SOLICITUDCREDITO_4_idx1` (`RamaFIRAID`),
  KEY `fk_SOLICITUDCREDITO_7_idx1` (`CadenaProductivaID`),
  KEY `fk_SOLICITUDCREDITO_8_idx` (`ProgEspecialFIRAID`),
  KEY `fk_SOLICITUDCREDITO_9_idx` (`TipoGarantiaFIRAID`),
  CONSTRAINT `fk_SOLICITUDCREDITO_1` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_2` FOREIGN KEY (`ProductoCreditoID`) REFERENCES `PRODUCTOSCREDITO` (`ProducCreditoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_3` FOREIGN KEY (`DestinoCreID`) REFERENCES `DESTINOSCREDITO` (`DestinoCreID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_SOLICITUDCREDITO_4` FOREIGN KEY (`RamaFIRAID`) REFERENCES `CATRAMAFIRA` (`CveRamaFIRA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_5` FOREIGN KEY (`PlazoID`) REFERENCES `CREDITOSPLAZOS` (`PlazoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_6` FOREIGN KEY (`SucursalID`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_7` FOREIGN KEY (`CadenaProductivaID`) REFERENCES `CATCADENAPRODUCTIVA` (`CveCadena`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_8` FOREIGN KEY (`ProgEspecialFIRAID`) REFERENCES `CATFIRAPROGESP` (`CveSubProgramaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDCREDITO_9` FOREIGN KEY (`TipoGarantiaFIRAID`) REFERENCES `CATTIPOGARANTIAFIRA` (`TipoGarantiaID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla de Solicitudes de Crédito'$$
