-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- SPEIREMESAS
DELIMITER ;
DROP TABLE IF EXISTS `SPEIREMESAS`;
DELIMITER $$


CREATE TABLE `SPEIREMESAS` (
  `SpeiRemID` bigint(20) NOT NULL COMMENT 'Numero del movimiento',
  `ClaveRastreo` varchar(30) NOT NULL COMMENT 'Clave de rastreo del spei',
  `TipoPagoID` int(2) NOT NULL COMMENT 'Tipo de pago spei corresponde al Catálogo Tipo de Pago',
  `CuentaAho` bigint(20) DEFAULT NULL,
  `TipoCuentaOrd` int(2) NOT NULL COMMENT 'Tipo de cuenta ordenante corresponde al Catálogo de tipos cuentas',
  `CuentaOrd` blob NOT NULL COMMENT 'Cuenta del ordenante que realiza la transferencia.',
  `NombreOrd` blob NOT NULL COMMENT 'Nombre del ordenante',
  `RFCOrd` blob NOT NULL COMMENT 'RFC del Ordenante',
  `MonedaID` int(11) NOT NULL COMMENT 'Tipo de la moneda',
  `TipoOperacion` int(2) NOT NULL COMMENT 'Tipo de Operacion spei Corresponde al Catálogo Tipo de Operación',
  `MontoTransferir` blob NOT NULL COMMENT 'Monto de la transferencia.',
  `IVAPorPagar` decimal(16,2) NOT NULL COMMENT 'IVA por pagar.',
  `ComisionTrans` decimal(16,2) NOT NULL COMMENT 'Comision por la transferencia.',
  `IVAComision` decimal(16,2) NOT NULL COMMENT 'Iva de la Comision',
  `TotalCargoCuenta` blob NOT NULL COMMENT 'Monto total de cargo a cuenta',
  `InstiRemitenteID` int(5) NOT NULL COMMENT 'Institucion remitente u ordenante',
  `InstiReceptoraID` int(5) NOT NULL COMMENT 'Institucion receptora',
  `CuentaBeneficiario` blob NOT NULL COMMENT 'Cuenta del Beneficiario',
  `NombreBeneficiario` blob NOT NULL COMMENT 'Nombre del Benefiaciario',
  `RFCBeneficiario` blob NOT NULL COMMENT 'RFC del Beneficiario',
  `TipoCuentaBen` int(2) NOT NULL COMMENT 'Tipo de Cuenta Corresponde al Catálogo Tipo de Cuenta',
  `ConceptoPago` blob NOT NULL COMMENT 'Concepto de Pago',
  `CuentaBenefiDos` varchar(20) NOT NULL COMMENT 'Cuenta del Beneficiario Dos',
  `NombreBenefiDos` varchar(40) NOT NULL COMMENT 'Nombre del Benefiaciario Dos',
  `RFCBenefiDos` varchar(18) NOT NULL COMMENT 'RFC del Beneficiario Dos',
  `TipoCuentaBenDos` int(2) NOT NULL COMMENT 'Tipo de Cuenta Beneficiario dos Corresponde al Catálogo Tipo de Cuenta',
  `ConceptoPagoDos` varchar(40) NOT NULL COMMENT 'Concepto de Pago Beneficiario Dos',
  `ReferenciaCobranza` varchar(40) NOT NULL COMMENT 'Referencia de cobranza',
  `ReferenciaNum` int(7) NOT NULL COMMENT 'Referencia Numero',
  `PrioridadEnvio` int(1) NOT NULL COMMENT 'Prioridad de envio',
  `FechaAutorizacion` datetime NOT NULL COMMENT 'Fecha de autorizacion',
  `EstatusRem` int(3) NOT NULL COMMENT 'Estatus del Movimiento',
  `UsuarioEnvio` varchar(30) NOT NULL COMMENT 'Usuario que realiza la operacion',
  `AreaEmiteID` int(2) NOT NULL COMMENT 'Area que emite la operacion',
  `Estatus` char(1) NOT NULL COMMENT 'Estatus del Movimiento:\nP) Pendiente por autorizar\nA) Autorizada \nC) Cancelada\nT) Detenida\nV) Verificada para Envio\nE) Enviada\nD) Devuelta\n',
  `UsuarioAutoriza` varchar(30) NOT NULL COMMENT 'Usuario que Autoriza la operacion',
  `FolioSpei` bigint(20) NOT NULL COMMENT 'Folio de Spei de envio',
  `FechaRecepcion` datetime NOT NULL COMMENT 'Fecha de recepcion de la orden',
  `CausaDevol` int(2) NOT NULL COMMENT 'Causa devolucion',
  `Topologia` char(1) NOT NULL COMMENT 'Topologia:\nT)Topologia T \nV)Topologia V',
  `Folio` bigint(20) NOT NULL COMMENT 'Folio',
  `FolioPaquete` bigint(20) NOT NULL COMMENT 'Folio del paquete',
  `FolioServidor` bigint(20) NOT NULL COMMENT 'Folio del servidor',
  `Firma` varchar(250) NOT NULL COMMENT 'Firma',
  `SpeiDetSolDesID` bigint(20) DEFAULT NULL COMMENT 'llave foranea descargas remesas',
  `SpeiSolDesID` bigint(20) DEFAULT NULL COMMENT 'llave foranea de solicitud remesa',
  `SucursalOpera`	INT(11)		NOT NULL COMMENT 'Sucursal de la operacion. Toma valor en el alta del registro.',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria',
  `DireccionIP` varchar(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`SpeiRemID`),
  KEY `fk_SPEIREMESAS_1` (`MonedaID`),
  KEY `fk_SPEIREMESAS_2` (`TipoPagoID`),
  KEY `fk_SPEIREMESAS_3` (`InstiRemitenteID`),
  KEY `fk_SPEIREMESAS_4` (`InstiReceptoraID`),
  KEY `fk_SPEIREMESAS_5` (`AreaEmiteID`),
  CONSTRAINT `fk_SPEIREMESAS_1` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIREMESAS_2` FOREIGN KEY (`TipoPagoID`) REFERENCES `TIPOSPAGOSPEI` (`TipoPagoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIREMESAS_3` FOREIGN KEY (`InstiRemitenteID`) REFERENCES `INSTITUCIONESSPEI` (`InstitucionID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIREMESAS_4` FOREIGN KEY (`InstiReceptoraID`) REFERENCES `INSTITUCIONESSPEI` (`InstitucionID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIREMESAS_5` FOREIGN KEY (`AreaEmiteID`) REFERENCES `AREASEMITESPEI` (`AreaEmiteID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla que almacena las remesas de SPEI'$$