-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- SPEIENVIOS
DELIMITER ;
DROP TABLE IF EXISTS `SPEIENVIOS`;
DELIMITER $$


CREATE TABLE `SPEIENVIOS` (
  `FolioSpeiID` bigint(20) NOT NULL COMMENT 'Folio de SPEI',
  `ClaveRastreo` varchar(30) NOT NULL COMMENT 'Clave de rastreo del movimiento',
  `TipoPagoID` int(2) NOT NULL COMMENT 'Tipo de pago corresponde al Catálogo Tipo de Pago',
  `CuentaAho` bigint(12) DEFAULT NULL,
  `TipoCuentaOrd` int(2) NOT NULL COMMENT 'Tipo de cuenta ordenante corresponde al Catálogo de tipos cuentas',
  `CuentaOrd` blob NOT NULL COMMENT 'Numero de CLABE, Numero de tarjeta o Numero de celular.',
  `NombreOrd` blob NOT NULL COMMENT 'Nombre del ordenante',
  `RFCOrd` blob NOT NULL COMMENT 'RFC del Ordenante',
  `MonedaID` int(11) NOT NULL COMMENT 'Numero de la moneda',
  `TipoOperacion` int(2) NOT NULL COMMENT 'Tipo de Operacion Corresponde al Catálogo Tipo de Operación',
  `MontoTransferir` blob NOT NULL COMMENT 'Monto de la transferencia',
  `IVAPorPagar` decimal(16,2) NOT NULL COMMENT 'Monto del iva que pagará el cliente al beneficiario del SPEI',
  `ComisionTrans` decimal(16,2) NOT NULL COMMENT 'Comision SPEI dependiendo el tipo de persona (Fisica/Moral)',
  `IVAComision` decimal(16,2) NOT NULL COMMENT 'Iva Comision SPEI',
  `InstiRemitenteID` int(5) NOT NULL COMMENT 'Institucion del remitente',
  `TotalCargoCuenta` blob NOT NULL COMMENT 'Monto total de cargo a cuenta',
  `InstiReceptoraID` int(5) NOT NULL COMMENT 'Institucion receptora',
  `CuentaBeneficiario` blob NOT NULL COMMENT 'Cuenta del Beneficiario',
  `NombreBeneficiario` blob NOT NULL COMMENT 'Nombre del Benefiaciario',
  `RFCBeneficiario` blob NOT NULL COMMENT 'RFC del Beneficiario',
  `TipoCuentaBen` int(2) NOT NULL COMMENT 'Tipo de Cuenta Corresponde al Catálogo Tipo de Cuenta',
  `ConceptoPago` blob NOT NULL COMMENT 'Concepto de Pago',
  `CuentaBenefiDos` varchar(20) NOT NULL COMMENT 'Cuenta del Beneficiario Dos',
  `NombreBenefiDos` varchar(40) NOT NULL COMMENT 'Nombre del Benefiaciario Dos',
  `RFCBenefiDos` varchar(18) NOT NULL COMMENT 'RFC del Beneficiario Dos',
  `TipoCuentaBenDos` int(2) NOT NULL COMMENT 'Tipo de Cuenta Beneficiario dos Corresponde al Catálogo Tipo de Cuenta',
  `ConceptoPagoDos` varchar(40) NOT NULL COMMENT 'Concepto de Pago Dos',
  `ReferenciaCobranza` varchar(40) NOT NULL COMMENT 'Referencia de cobranza',
  `ReferenciaNum` int(7) NOT NULL COMMENT 'Referencia Numero',
  `PrioridadEnvio` int(1) NOT NULL COMMENT 'Prioridad de envio',
  `FechaAutorizacion` datetime NOT NULL COMMENT 'Fecha de autorizacion',
  `EstatusEnv` int(3) NOT NULL COMMENT 'Estatus de envio del Movimiento',
  `ClavePago` varchar(10) NOT NULL COMMENT 'Clave de pago',
  `UsuarioEnvio` varchar(30) NOT NULL COMMENT 'Usuario que realiza la operacion',
  `AreaEmiteID` int(2) NOT NULL COMMENT 'Area que emite la operacion',
  `Estatus` char(1) NOT NULL COMMENT 'Estatus del Movimiento:\nP) Pendiente por autorizar\nA) Autorizada \nC) Cancelada\nT) Detenida\nV) Verificada para Envio\nE) Enviada\nD) Devuelta\n',
  `FechaRecepcion` datetime NOT NULL COMMENT 'Fecha de recepcion del spei',
  `FechaEnvio` datetime NOT NULL COMMENT 'Fecha de Envio spei',
  `CausaDevol` int(2) NOT NULL COMMENT 'clave de Causa devolucion del catalogo',
  `FechaCan` datetime NOT NULL COMMENT 'Fecha Cancelacion',
  `Comentario` varchar(500) NOT NULL COMMENT 'Comentario de cancelacion',
  `FechaOperacion` date NOT NULL COMMENT 'Fecha Operacion',
  `Firma` varchar(1000) NOT NULL COMMENT 'Firma encriptada por la transferencia.',
  `UsuarioAutoriza` int(11) NOT NULL COMMENT 'ID del usuario que autoriza el Envio.',
  `UsuarioVerifica` int(11) NOT NULL COMMENT 'ID del usuario que verifica el Envio.',
  `FechaVerifica` datetime NOT NULL COMMENT 'Fecha en la que se verifica el envio.',
  `OrigenOperacion` char(1) DEFAULT 'V' COMMENT 'Origen de la Operacion\nv = ventanilla\nM = Banca Movil\nC = Cliente SPEI\nR = Remesa\nD = Desembolso de Credito',
  `NumIntentos` INT(11) NOT NULL COMMENT 'Numero de veces que se ha intentado realizar el envio de la orden de pago a STP',
  `FolioSTP` INT(11) NOT NULL COMMENT 'Folio de la Orden de Pago que regresa el servicio web de STP',
  `PIDTarea` VARCHAR(50) NOT NULL COMMENT 'Numero referente a la Tarea',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria',
  `DireccionIP` varchar(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`FolioSpeiID`),
  UNIQUE KEY `ClaveRastreo` (`ClaveRastreo`),
  KEY `fk_SPEIENVIOS_1` (`MonedaID`),
  KEY `fk_SPEIENVIOS_2` (`TipoPagoID`),
  KEY `fk_SPEIENVIOS_3` (`InstiRemitenteID`),
  KEY `fk_SPEIENVIOS_4` (`InstiReceptoraID`),
  KEY `fk_SPEIENVIOS_5` (`AreaEmiteID`),
  CONSTRAINT `fk_SPEIENVIOS_1` FOREIGN KEY (`MonedaID`) REFERENCES `MONEDAS` (`MonedaId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIENVIOS_2` FOREIGN KEY (`TipoPagoID`) REFERENCES `TIPOSPAGOSPEI` (`TipoPagoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIENVIOS_3` FOREIGN KEY (`InstiRemitenteID`) REFERENCES `INSTITUCIONESSPEI` (`InstitucionID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIENVIOS_4` FOREIGN KEY (`InstiReceptoraID`) REFERENCES `INSTITUCIONESSPEI` (`InstitucionID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPEIENVIOS_5` FOREIGN KEY (`AreaEmiteID`) REFERENCES `AREASEMITESPEI` (`AreaEmiteID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla que almacena los envios de SPEI'$$