-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TARDEBBITACORAMOVS
DELIMITER ;
DROP TABLE IF EXISTS `TARDEBBITACORAMOVS`;
DELIMITER $$


CREATE TABLE `TARDEBBITACORAMOVS` (
  `TarDebMovID` int(11) NOT NULL COMMENT 'PK de la tabla',
  `TipoMensaje` char(4) DEFAULT NULL COMMENT 'Tipo Mensaje de la Transaccion:\n1200 \n1210 Transacción Normal ATMs y POS\n1220\n1230  Transacción Forzada POS (se debe aplicar el cobro)\n1400\n1410 Transacción Reverso ATMs\n1420\n1430 Transacción Reverso ATMs y POS (Prosa)',
  `TipoOperacionID` char(2) DEFAULT NULL COMMENT 'Campo 2 ISO 8583 de tipo de operacion',
  `TarjetaDebID` char(16) DEFAULT NULL COMMENT 'Numero de tarjeta a 16 posiciones',
  `OrigenInst` char(2) DEFAULT NULL COMMENT 'Origen instrumento. Campo 3 Subcampo 3 ISO 8583 MSG',
  `MontoOpe` decimal(12,2) DEFAULT NULL COMMENT 'Monto operacion formato 9999999999.99',
  `FechaHrOpe` varchar(20) DEFAULT NULL COMMENT 'Fecha operacion formato YYYY-MM-DD hh:mm:ss',
  `NumeroTran` bigint(20) DEFAULT NULL COMMENT 'Numero transaccion. Campo 11 ISO 8583 System Trace Audit Number',
  `GiroNegocio` varchar(5) DEFAULT NULL COMMENT 'Campo 18 ISO 8583 Merchant Type Formato 9999',
  `PuntoEntrada` char(2) DEFAULT NULL COMMENT 'Campo 22 ISO 8583 Punto de entrada ',
  `TerminalID` varchar(50) DEFAULT NULL COMMENT 'Campo 41 ISO 8583 codigo de la terminal o cajero que envio la transaccion',
  `NombreUbicaTer` varchar(50) DEFAULT NULL COMMENT 'Nombre ubicacion terminal. Campo 43 ISO 8583 codigo de ubicacion de la terminal',
  `NIP` varchar(256) DEFAULT NULL COMMENT 'NIP',
  `CodigoMonOpe` varchar(10) DEFAULT NULL COMMENT 'Codigo Moneda Operacion. Campo 49 ISO 8583 ',
  `MontosAdiciona` decimal(12,2) DEFAULT NULL COMMENT 'MontosAdicionales. Monto de Cashback 999999.99',
  `MontoSurcharge` decimal(12,2) DEFAULT NULL COMMENT 'Monto de SurCharge formato 9999999999.99',
  `MontoLoyaltyfee` decimal(12,2) DEFAULT NULL COMMENT 'Monto de Loyalty fee formato 999999999.99',
  `Referencia` varchar(30) DEFAULT NULL COMMENT 'Código de Referencia asignado a la Transacción por la terminal o ATM origen.',
  `DatosTiempoAire` varchar(90) DEFAULT NULL COMMENT 'Datos para Transaccion de Compra de Tiempo Aire',
  `EstatusConcilia` char(1) DEFAULT NULL COMMENT 'Estatus de la Conciliacion \nC.- Conciliado\nN.- NO Conciliado\n',
  `FolioConcilia` bigint(20) DEFAULT NULL COMMENT 'Folio de Carga Conciliacion',
  `DetalleConciliaID` int(11) DEFAULT NULL COMMENT 'ID detalle de Conciliacion',
  `TransEnLinea` char(1) DEFAULT NULL COMMENT 'Transaccion en Linea \nS.- Si\nN.- No',
  `CheckIn` char(1) DEFAULT NULL COMMENT 'parametro que indica una preautorizacion de check in',
  `CodigoAprobacion` bigint(20) DEFAULT NULL COMMENT 'Indica el Numero de la Transaccion Original',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus de los movimientos realizados con las tarjetas\nR = Registrado\nP = Procesado',
  `EmisorID` int(11) DEFAULT '0' COMMENT 'Campo identificador provisto por ISOTRX ',
  `MensajeID` varchar(50) DEFAULT '' COMMENT 'Identificador del Mensaje. Valor único global ISOTRX ',
  `ModoEntrada` int(11) DEFAULT '0' COMMENT 'CId Catalogo CATTIPOPERACIONISOTRX ISOTRX ',
  `ResultadoOperacion` int(11) DEFAULT '0' COMMENT 'Identificador de respuesta ISOTRX \n0 = Sin Respuesta\n1 = Aprobada\n2 = Declinada\n3 = Rechazada',
  `EstatusOperacion` int(11) DEFAULT '0' COMMENT 'Estatus de operacion\n0 = Indefinida\n1 = Abierta\n2 = Completada\n3 = Devuelta\n5 = Cancelada\n6 = Reversa por ISOTRX ',
  `FechaOperacion` date DEFAULT '1900-01-01' COMMENT 'Fecha en formato AAAAMMDD ISOTRX ',
  `HoraOperacion` time DEFAULT '00:00:00' COMMENT 'Hora en formato HHMMSS  ISOTRX ',
  `CodigoRespuesta` varchar(2) DEFAULT '' COMMENT 'Codigo de respuesta del autorizador ISOTRX de la tabla ISOTRXCODRESPUESTA ',
  `CodigoRechazo` int(11) DEFAULT '0' COMMENT 'Codigo de rechazo ISOTRX del Catalogo ISOTRXCODRECHAZO ',
  `NumeroCuenta` bigint(20) DEFAULT '0' COMMENT 'Numero de tarjeta provisto por ISOTRX ',
  `MontoRemplazo` decimal(12,2) DEFAULT '0.00' COMMENT 'Monto de remplazo por devolución o disposicion parcial ISOTRX ',
  `SaldoDisponible` decimal(12,4) DEFAULT '0.0000' COMMENT 'Saldo disponible ISOTRX ',
  `ProDiferimiento` int(11) DEFAULT '0' COMMENT 'Numero de meses a diferir el primer pago ISOTRX. ',
  `ProNumeroPagos` int(11) DEFAULT '0' COMMENT 'NUmero de parcialidades en las que se divide el monto ISOTRX. ',
  `ProTipoPlan` int(11) DEFAULT '0' COMMENT 'Tipo plan\n0 = Sin Plan\n3 = Sin Intereses\n5 = Con Intereses\n7 = Diferimiento  ',
  `OriCodigoAutorizacion` varchar(6) DEFAULT '' COMMENT 'Codigo transacción original ISOTRX ',
  `OriFechaTransaccion` date DEFAULT '1900-01-01' COMMENT 'Fecha de la transacción original , formato MMDD ISOTRX',
  `OriHoraTransaccion` time DEFAULT '00:00:00' COMMENT 'Hora de la transacción original,  formato HHMMSS ISOTRX ',
  `DesNumeroCuenta` bigint(20) DEFAULT '0' COMMENT 'Número de cuenta destino de la trasferencia  ISOTRX',
  `DesNumeroTarjeta` varchar(16) DEFAULT '' COMMENT 'Número de tarjeta destino de la transferencia local ISOTRX ',
  `TrsClaveRastreo` varchar(30) DEFAULT '' COMMENT 'Clave de rastreo de la transferencia ISOTRX ',
  `TrsInstitucionRemitente` int(11) DEFAULT '0' COMMENT 'Clave de la institución desde donde se envía la transferencia ISOTRX',
  `TrsNombreEmisor` varchar(50) DEFAULT '' COMMENT 'Nombre de quien envía la transferencia ISOTRX',
  `TrsTipoCuentaRemitente` int(11) DEFAULT '0' COMMENT 'Tipo de Cuenta de quien envía la transferencia ISOTRX ',
  `TrsCuentaRemitente` varchar(16) DEFAULT '' COMMENT 'Numero de cuenta de quien envía la transferencia ISOTRX ',
  `TrsConceptoPago` varchar(50) DEFAULT '' COMMENT 'Concepto de la transferencia ISOTRX',
  `TrsReferenciaNumerica` int(11) DEFAULT '0' COMMENT 'Referencia numérica asociada a la transferencia',
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TarDebMovID`),
  KEY `Idx_TipoMensaje` (`TipoMensaje`),
  KEY `Idx_Referencia` (`Referencia`),
  KEY `idx01TARDEBBITACORAMOVS` (`TarjetaDebID`,`Referencia`,`TerminalID`,`MontoOpe`,`Estatus`,`FechaHrOpe`),
  KEY `idx02TARDEBBITACORAMOVS` (`TarDebMovID`),
  KEY `idx03TARDEBBITACORAMOVS` (`TipoOperacionID`,`Referencia`,`TarjetaDebID`,`NumTransaccion`,`Estatus`,`TarDebMovID`),
  KEY `idx04TARDEBBITACORAMOVS` (`TarDebMovID`),
  KEY `idx05TARDEBBITACORAMOVS` (`TarjetaDebID`,`CodigoAprobacion`,`FechaHrOpe`,`Estatus`,`MontoOpe`,`TerminalID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='BITACORA PARA MOVIMIENTOS DE OPERACIONES DE TARJETAS'$$