-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TCR_DETARCOUT_ADM
DELIMITER ;
DROP TABLE IF EXISTS `TCR_DETARCOUT_ADM`;DELIMITER $$

CREATE TABLE `TCR_DETARCOUT_ADM` (
  `Dao_FolioAr` decimal(6,0) NOT NULL COMMENT 'Folio de los archivos CARD.',
  `Dao_FecRes` datetime NOT NULL COMMENT 'fecha de respuesta archivo CARD.',
  `Dao_Consecutivo` int(11) NOT NULL COMMENT 'Consecutivo de respuesta archivo CARD.',
  `Dao_NomArchiGen` varchar(20) DEFAULT NULL COMMENT 'Nombre del Archivo Generado de respuesta archivo CARD.',
  `Dao_NumLote` int(11) DEFAULT NULL COMMENT 'Numero de Lote de Tarjeta de  archivo CARD respuesta.',
  `Dao_Campo1` varchar(16) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 1',
  `Dao_Campo2` varchar(16) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 2',
  `Dao_Campo3` varchar(7) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 3',
  `Dao_Campo4` varchar(9) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 4',
  `Dao_Campo5` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 5',
  `Dao_Campo6` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 6',
  `Dao_Campo7` varchar(5) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 7',
  `Dao_Campo8` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 8',
  `Dao_Campo9` varchar(30) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 9',
  `Dao_Campo10` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 10',
  `Dao_Campo11` varchar(15) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 11',
  `Dao_Campo12` varchar(19) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 12',
  `Dao_Campo13` varchar(19) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 13',
  `Dao_Campo14` varchar(7) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 14',
  `Dao_Campo15` varchar(8) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 15',
  `Dao_Campo16` varchar(8) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 16',
  `Dao_Campo17` varchar(15) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 17',
  `Dao_Campo18` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 18',
  `Dao_Campo19` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 19',
  `Dao_Campo20` varchar(6) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 20',
  `Dao_Campo21` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 21',
  `Dao_Campo22` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 22',
  `Dao_Campo23` varchar(27) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 23',
  `Dao_Campo24` varchar(25) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 24',
  `Dao_Campo25` varchar(16) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 25',
  `Dao_Campo26` varchar(79) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 26',
  `Dao_Campo27` varchar(40) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 27',
  `Dao_Campo28` varchar(16) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 28',
  `Dao_Campo29` varchar(8) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 29',
  `Dao_Campo30` varchar(16) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 30',
  `Dao_Campo31` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 31',
  `Dao_Campo32` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 32',
  `Dao_Campo33` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 33',
  `Dao_Campo34` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 34',
  `Dao_Campo35` varchar(8) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 35',
  `Dao_Campo36` varchar(25) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 36',
  `Dao_Campo37` varchar(25) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 37',
  `Dao_Campo38` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 38',
  `Dao_Campo39` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 39',
  `Dao_Campo40` varchar(60) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 40',
  `Dao_Campo41` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 41',
  `Dao_Campo42` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 42',
  `Dao_Campo43` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 43',
  `Dao_Campo44` varchar(15) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 44',
  `Dao_Campo45` varchar(10) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 45',
  `Dao_Campo46` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 46',
  `Dao_Campo47` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 47',
  `Dao_Campo48` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 48',
  `Dao_Campo49` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 49',
  `Dao_Campo50` varchar(30) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 50',
  `Dao_Campo51` varchar(16) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 51',
  `Dao_Campo52` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 52',
  `Dao_Campo53` varchar(127) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 53',
  `Dao_Campo54` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 54',
  `Dao_Campo55` varchar(4) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 55',
  `Dao_Campo56` varchar(10) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 56',
  `Dao_Campo57` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 57',
  `Dao_Campo58` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 58',
  `Dao_Campo59` varchar(40) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 59',
  `Dao_Campo60` varchar(40) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 60',
  `Dao_Campo61` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 61',
  `Dao_Campo62` varchar(60) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 62',
  `Dao_Campo63` varchar(60) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 63',
  `Dao_Campo64` varchar(5) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 64',
  `Dao_Campo65` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 65',
  `Dao_Campo66` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 66',
  `Dao_Campo67` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 67',
  `Dao_Campo68` varchar(7) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 68',
  `Dao_Campo69` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 69',
  `Dao_Campo70` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 70',
  `Dao_Campo71` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 71',
  `Dao_Campo72` varchar(2) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 72',
  `Dao_Campo73` varchar(1) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 73',
  `Dao_Campo74` varchar(3) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 74',
  `Dao_Campo75` varchar(9) DEFAULT NULL COMMENT 'Detalle  de los archivos CARD Campo 75',
  `Dao_Status` char(1) DEFAULT NULL COMMENT 'Estatus de los archivos CARD',
  `Dao_TipoTarjeta` char(1) DEFAULT NULL COMMENT 'Tipo Tarjeta de los archivos CARD'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Detalle  de los archivos CARD.'$$