-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TEMPCEDES
DELIMITER ;
DROP TABLE IF EXISTS `TEMPCEDES`;DELIMITER $$

CREATE TABLE `TEMPCEDES` (
  `CedeID` int(11) NOT NULL DEFAULT '0' COMMENT 'CedeID a Reinvertir',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'ClienteID',
  `CuentaAhoID` bigint(20) DEFAULT NULL COMMENT 'CuentaAhoID a la cual se Carga y Abonara',
  `TipoCedeID` int(11) DEFAULT NULL COMMENT 'TipoCedeID que se Reinvertira.',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'MonedaID',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio de la Cede Nueva',
  `Monto` decimal(18,2) DEFAULT NULL COMMENT 'Monto de la CEDE',
  `PlazoOriginal` int(11) DEFAULT NULL COMMENT 'Plazo con el que se Buscara es Esquema de Tasas',
  `Plazo` int(11) DEFAULT NULL COMMENT 'Plazo Pagado',
  `Tasa` decimal(12,4) DEFAULT NULL COMMENT 'Tasa Orginal',
  `TasaISR` decimal(12,4) DEFAULT NULL COMMENT 'Tasa ISR',
  `TasaNeta` decimal(12,4) DEFAULT NULL COMMENT 'Tasa Neta',
  `InteresGenerado` decimal(18,2) DEFAULT NULL COMMENT 'Interes Generado Original',
  `InteresRecibir` decimal(18,2) DEFAULT NULL COMMENT 'Interes Recibir Original',
  `InteresRetener` decimal(18,2) DEFAULT NULL COMMENT 'Interes Retener Original',
  `TipoPagoInteres` char(1) DEFAULT NULL COMMENT 'Indica la forma de pago de interes.\nV - Vencimiento\nF - Fin del Mes\nP - Por Periodo',
  `DiasPeriodo` int(11) DEFAULT '0' COMMENT 'Indica el numero de dias si la forma de pago de interes es por PERIODO.',
  `PagoIntCal` char(2) DEFAULT '' COMMENT 'Indica el tipo de pago de interes.\nI - Iguales\nD - Devengado',
  `Reinversion` char(2) DEFAULT NULL COMMENT 'Indica si hay Reinversion Automatica',
  `Reinvertir` char(2) DEFAULT NULL COMMENT 'Indica la Manera en que se Reinvertira',
  `SaldoProAcumulado` decimal(18,2) DEFAULT NULL COMMENT 'Saldo Provision Acumulado',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Sucursal de la Cede',
  `TasaFV` char(1) DEFAULT NULL COMMENT 'Tipo de Tasa que Maneja',
  `Calificacion` char(2) DEFAULT NULL COMMENT 'Calificacion del Cliente',
  `PlazoInferior` int(11) DEFAULT NULL COMMENT 'Plazo Inferior para la Nueva Cede',
  `PlazoSuperior` int(11) DEFAULT NULL COMMENT 'Plazo Superior para la Nueva Cede',
  `MontoInferior` decimal(18,2) DEFAULT NULL COMMENT 'Monto Infeior para la Nueva Cede',
  `MontoSuperior` decimal(18,2) DEFAULT NULL COMMENT 'Monto Superior para la Nueva Cede',
  `FechaVencimiento` date DEFAULT NULL COMMENT 'Nueva Fecha de Vencimiento para la Cede Renovada',
  `FechaPago` date DEFAULT NULL COMMENT 'Fecha de pago.',
  `NuevoPlazo` int(11) DEFAULT NULL COMMENT 'Dias a Pagar de la Nueva Cede',
  `MontoReinvertir` decimal(18,2) DEFAULT NULL COMMENT 'Monto que se Reinvertira',
  `NuevaTasa` decimal(12,4) DEFAULT NULL COMMENT 'Tasa de la Nueva Cede',
  `NuevaTasaISR` decimal(12,2) DEFAULT NULL COMMENT 'TasaISR de la Nueva Cede',
  `NuevaTasaNeta` decimal(12,4) DEFAULT NULL COMMENT 'Tasa Neta de la Nueva Cede',
  `NuevoCalInteres` int(11) DEFAULT NULL COMMENT 'Calculo Interes de la Nueva Cede',
  `NuevaTasaBaseID` int(11) DEFAULT NULL COMMENT 'TasaBaseID de la Nueva Cede',
  `NuevaSobreTasa` decimal(12,4) DEFAULT NULL COMMENT 'Sobre Tasa de la Nueva Cede',
  `NuevoPisoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Piso Tasa de la Nueva Cede',
  `NuevoTechoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Techo Tasa de la Nueva Cede',
  `NuevoIntGenerado` decimal(18,2) DEFAULT NULL COMMENT 'Interes Generado de la Nueva Cede',
  `NuevoIntRetener` decimal(18,2) DEFAULT NULL COMMENT 'Interes Retener de la Nueva Cede',
  `NuevoIntRecibir` decimal(18,2) DEFAULT NULL COMMENT 'Interes Recibir de la Nueva Cede',
  `NuevoValorGat` decimal(12,2) DEFAULT NULL COMMENT 'Valor Gat de la Nueva Cede',
  `NuevoValorGatReal` decimal(12,2) DEFAULT NULL COMMENT 'Valor Gat Real de la Nueva Cede',
  `AmortizacionID` int(11) DEFAULT NULL COMMENT 'AmotizacionID.',
  `DiaInhabil` char(2) DEFAULT NULL COMMENT 'Indica el Dia Inhabil:\nSD = Sabado y Domingo\nD = Domingo',
  `CajaRetiro` int(11) DEFAULT NULL COMMENT 'Numero de caja de retiro del Cede',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `UsuarioID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria',
  `DireccionIP` varchar(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`CedeID`),
  KEY `ClienteID` (`ClienteID`),
  KEY `TipoCedeID` (`TipoCedeID`),
  KEY `PlazoOriginal` (`PlazoOriginal`),
  KEY `MontoReinvertir` (`MontoReinvertir`),
  KEY `MontoInferior` (`MontoInferior`),
  KEY `MontoSuperior` (`MontoSuperior`),
  KEY `PlazoInferior` (`PlazoInferior`),
  KEY `PlazoSuperior` (`PlazoSuperior`),
  KEY `Calificacion` (`Calificacion`),
  KEY `SucursalID` (`SucursalID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla para el Proceso de Reinversion Automatica de CEDES.'$$