-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPAVALESREP
DELIMITER ;
DROP TABLE IF EXISTS `TMPAVALESREP`;DELIMITER $$

CREATE TABLE `TMPAVALESREP` (
  `NumTransaccionID` int(20) NOT NULL COMMENT 'Numero de Transaccion',
  `Identificador` bigint(12) NOT NULL,
  `Consecutivo` int(11) NOT NULL DEFAULT '0',
  `ClienteID` int(20) DEFAULT NULL COMMENT 'Identificador de un Aval tipo Cliente',
  `ProspectoID` int(20) DEFAULT NULL COMMENT 'Identificador de un Aval tipo Prospecto',
  `AvalID` int(20) DEFAULT NULL COMMENT 'Identificador de un Aval',
  `Nombres` varchar(150) DEFAULT NULL COMMENT 'Nombre del Aval',
  `ApellidoPat` varchar(50) DEFAULT NULL COMMENT 'Apellido Paterno del Aval',
  `ApellidoMat` varchar(50) DEFAULT NULL COMMENT 'Apellido Materno edl Aval',
  `NombreCompleto` varchar(250) DEFAULT NULL COMMENT 'Nombre Completo del Aval',
  `DatVivTipDom` varchar(45) DEFAULT NULL COMMENT 'Datos SocioEconomicos Datos de vivienda Tipo de Domicilo',
  `DirNumExt` varchar(10) DEFAULT NULL COMMENT 'Direccion del Aval, Numero Exterior',
  `DirCalle` varchar(50) DEFAULT NULL COMMENT 'Direccion del Aval, Nombre de la Calle',
  `DirColonia` varchar(200) DEFAULT NULL COMMENT 'Direccion del Aval, Nombre de la Colonia',
  `DirCP` varchar(15) DEFAULT NULL COMMENT 'Direccion del Aval, Codigo Postal',
  `DirLocalidad` varchar(200) DEFAULT NULL COMMENT 'Direccion del Aval, Localidad',
  `DirMunicipio` varchar(200) DEFAULT NULL COMMENT 'Direccion del Aval, Municipio',
  `DirEstado` varchar(100) DEFAULT NULL COMMENT 'Direccion del Aval, Estado',
  `DirCompleta` varchar(350) DEFAULT NULL COMMENT 'Direccion Completa del Aval',
  `RFC` varchar(15) DEFAULT NULL COMMENT 'RFC del Aval',
  `Sexo` varchar(10) DEFAULT NULL COMMENT 'Sexo del Aval',
  `FechaNac` varchar(100) DEFAULT NULL COMMENT 'Fecha de Nacimiento del Aval',
  `Edad` varchar(100) DEFAULT NULL COMMENT 'Edad del Aval',
  `EdoNac` varchar(100) DEFAULT NULL COMMENT 'Estado de Nacimiento del Aval',
  `PaisNac` varchar(150) DEFAULT NULL COMMENT 'Pais de Nacimiento del Aval',
  `Nacion` varchar(15) DEFAULT NULL COMMENT 'Nacionalidad del Aval',
  `Ocupacion` text COMMENT 'Ocupación del Aval',
  `Puesto` varchar(100) DEFAULT NULL COMMENT 'Puesto del Aval',
  `GradoEstudio` varchar(50) DEFAULT NULL COMMENT 'Grado de Estudio del Aval',
  `Profesion` varchar(100) DEFAULT NULL COMMENT 'Profesion del Aval',
  `ActEconom` varchar(200) DEFAULT NULL COMMENT 'Actividad Economica del Aval',
  `EdoCivil` varchar(50) DEFAULT NULL COMMENT 'Estado Civil del Aval',
  `Telefono` varchar(20) DEFAULT NULL COMMENT 'Telefono del Aval',
  `Correo` varchar(50) DEFAULT NULL COMMENT 'Correo Electronico del Aval',
  `CURP` varchar(20) DEFAULT NULL COMMENT 'CURP del Aval',
  `TipoPersona` varchar(50) DEFAULT NULL COMMENT 'Tipo Persona del Aval\nM.- Persona Moral\nA.- Persona Fisica Con Actividad Empresarial\nF.- Persona Fisica Sin Actividad Empresarial\n',
  `RazonSocial` varchar(150) DEFAULT NULL COMMENT 'Razon Social del Aval',
  `RepLegal` varchar(250) DEFAULT NULL COMMENT 'Representante Legal del Aval, en caso de ser una persona Moral',
  `EscConsNumero` varchar(50) DEFAULT NULL COMMENT 'Numero de la Escritura Constitutiva',
  `EscPodNumero` varchar(50) DEFAULT NULL COMMENT 'Numero de la Escritura de Poder',
  `EscConsCiud` varchar(100) DEFAULT NULL COMMENT 'Ciudad de la Escritura Constitutiva',
  `EscPodCiud` varchar(100) DEFAULT NULL COMMENT 'Ciudad de la Escritura de Poder',
  `EscConsLocalid` varchar(200) DEFAULT NULL COMMENT 'Localidad de la Escritura Constitutiva',
  `EscPodLocalid` varchar(200) DEFAULT NULL COMMENT 'Localidad de la Escritura de Poder',
  `EscConsFecha` varchar(100) DEFAULT NULL COMMENT 'Fecha de la Escritura Constitutiva',
  `EscPodFecha` varchar(100) DEFAULT NULL COMMENT 'Fecha de la Escritura de Poder',
  `EscConsNomNotar` varchar(100) DEFAULT NULL COMMENT 'Nombre del Notario de la Escritura Constitutiva',
  `EscPodNomNotar` varchar(100) DEFAULT NULL COMMENT 'Nombre del Notario de la Escritura de Poder',
  `EscConsNumNotar` varchar(10) DEFAULT NULL COMMENT 'Numero de Notario de la Escritura Constitutiva',
  `EscPodNumNotar` varchar(10) DEFAULT NULL COMMENT 'Numero de Notario de la Escritura de Poder',
  `EscConsEdoNotar` varchar(200) DEFAULT NULL COMMENT 'Estado de la Notaria de la Escritura Constitutiva',
  `EscPodEdoNotar` varchar(200) DEFAULT NULL COMMENT 'Estado de la Notaria de la Escritura de Poder',
  `EscConsEdoReg` varchar(100) DEFAULT NULL COMMENT 'Estado de Registro de la Escritura Constitutiva',
  `EscPodEdoReg` varchar(100) DEFAULT NULL COMMENT 'Estado de Registro de la Escritura de Poder',
  `EscConsLocNotar` varchar(100) DEFAULT NULL COMMENT 'Localidad de la Notaria de la Escritura Constitutiva',
  `EscPodLocNotar` varchar(100) DEFAULT NULL COMMENT 'Localidad de la Notaria de la Escritura de Poder',
  `EscPodNomApode` varchar(150) DEFAULT NULL COMMENT 'Nombre del Apoderado de la Escritura de Poder',
  `EscPodNotaria` varchar(45) DEFAULT NULL COMMENT 'Numero de la Notaria de la Escritura de Poder',
  `EscConsNotaria` varchar(45) DEFAULT NULL COMMENT 'Numero de la Notaria de la Escritura Constitutiva',
  `SucursalOrigen` varchar(50) DEFAULT NULL COMMENT 'Sucursal Origen del Aval',
  `OcupacionID` int(11) NOT NULL COMMENT 'Identificador de la ocupacion del aval',
  `DomicilioTrabajo` varchar(500) NOT NULL COMMENT 'Domicilio de trabajo del aval',
  `TelefonoTrabajo` varchar(13) NOT NULL COMMENT 'Telefono de trabajo del aval',
  `ExtTelTrabajo` varchar(4) NOT NULL COMMENT 'Extension del telefono de trabajo del aval',
  `TipoRelacion` varchar(50) NOT NULL COMMENT 'Identificador del tipo de relacion',
  `TiempoDeConocido` decimal(12,2) NOT NULL COMMENT 'Tiempo de conocido del Aval en anios utilizando decimal',
  `Aval_ant` varchar(2) DEFAULT NULL,
  `EmpresaID` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria EmpresaID',
  `Usuario` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria UsuarioID',
  `FechaActual` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria FechaActual',
  `DireccionIP` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria DireccionIP',
  `ProgramaID` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria ProgramaID',
  `Sucursal` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria Sucursal',
  `NumTransaccion` varchar(45) DEFAULT NULL COMMENT 'Parametro de Auditoria NumTransaccion',
  PRIMARY KEY (`NumTransaccionID`,`Identificador`,`Consecutivo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Temporal para calcular datos de avales'$$