-- TMPAPORTDISPERSION
DELIMITER ;
DROP TABLE IF EXISTS TMPAPORTDISPERSION;
DELIMITER $$

CREATE TABLE TMPAPORTDISPERSION(
	`AportacionID` INT(11) NOT NULL COMMENT 'ID de Aportacion.',
	`AmortizacionID` INT(11) NOT NULL DEFAULT '0' COMMENT 'Id de la Amortizacion.',
	`CuentaTranID` INT(11) NOT NULL COMMENT 'No consecutivo de cuentas transfer por cliente.',
	`NumTransaccion` BIGINT(20) DEFAULT NULL COMMENT 'Numero de Transaccion',
 	PRIMARY KEY (`AportacionID`,`AmortizacionID`,`CuentaTranID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TMP: TABLA AUXILIAR PARA GUARDAR LAS APORTACIONES Y VALIDARLAS'$$