DELIMITER ;
DROP TABLE IF EXISTS `TMPARCHIVOCARGADEPREF`;
DELIMITER $$

CREATE TABLE `TMPARCHIVOCARGADEPREF` (
  `NumTransaccionCarga` bigint(20) NOT NULL COMMENT 'Numero de Transaccion de Carga.',
  `FolioCargaID` bigint(20) NOT NULL COMMENT 'Folio unico de Carga de Archivo a Conciliar.',
  `InstitucionID` int(11) DEFAULT NULL COMMENT 'Numero de la Institucion Bancaria.',
  `NumCtaInstit` varchar(20) DEFAULT NULL COMMENT 'Numero de Cuenta En el Banco(Institucion)',
  `TipoFormato` char(1) DEFAULT NULL COMMENT 'Tipo de formato del layout B= banco , E= estandar',
  `FechaInicial` date DEFAULT NULL COMMENT 'Fecha Inicial de Rango de pantalla',
  `FechaFinal` date DEFAULT NULL COMMENT 'Fecha Final de Rango de pantalla',
  `TipoCanal` int(11) DEFAULT NULL COMMENT 'Identificacion por donde vino el deposito, corresponde con la tabla :TIPOCANAL',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Numero de la Moneda. MONEDAS se obtiene de la pantalla',
  `CuentaAhoID` varchar(20) DEFAULT NULL COMMENT 'ID de la Cuenta de ahorro.',
  `NumCtaInstitArchivo` varchar(20) DEFAULT NULL COMMENT 'Numero de Cuenta En el Banco(Institucion) que se obtiene del archivo de carga',
  `FechaOperacionArchivo` date DEFAULT NULL COMMENT 'Fecha de operacion que se obtiene del archivo de carga',
  `ReferenciaMovArchivo` varchar(40) DEFAULT NULL COMMENT 'Referencia del Movimiento Debe ser el CREDITO o CUENTA se obtiene del archivo de carga',
  `ReferenciaMov2Archivo` varchar(40) DEFAULT NULL COMMENT 'Referencia 2 se obtiene del archivo de carga',
  `ReferenciaMov3Archivo` varchar(40) DEFAULT NULL COMMENT 'Referencia 3 se obtiene del archivo de carga',
  `ReferenciaMov4Archivo` varchar(40) DEFAULT NULL COMMENT 'Referencia 4 se obtiene del archivo de carga',
  `DescripcionMovArchivo` varchar(150) DEFAULT NULL COMMENT 'Decripcion del Movimiento se obtiene del archivo de carga',
  `NatMovimientoArchivo` char(1) DEFAULT NULL COMMENT 'Naturaleza del Movimiento.C.- Cargo.A.- Abono se obtiene del archivo de carga',
  `MontoMovArchivo` decimal(12,2) DEFAULT NULL COMMENT 'Monto del Movimiento se obtiene del archivo de carga',
  `MontoPendApliArchivo` decimal(12,2) DEFAULT NULL COMMENT 'Monto Pendiente de Aplicar se obtiene del archivo de carga',
  `TipoCanalArchivo` int(11) DEFAULT NULL COMMENT 'Identificacion por donde vino el deposito, corresponde con la tabla :TIPOCANAL se obtiene del archivo de carga',
  `TipoDepositoArchivo` char(1) DEFAULT NULL COMMENT 'Tipo de Deposito.E .-  Si pago Efectivo, T .-  Otro tipo deposito, se obtiene del archivo de carga',
  `TipoMonedaArchivo` int(11) DEFAULT NULL COMMENT 'Numero de la Moneda. MONEDAS se obtiene del archivo de carga',
  `TipoMovArchivo` int(11) DEFAULT NULL COMMENT 'Tipo de Movimiento se obtiene del archivo de carga',
  `NumIdenArchivo` varchar(50) DEFAULT NULL COMMENT 'Numero de identificacion del archivo se obtiene del archivo de carga',
  `CodigoLeyendaArchivo` varchar(50) DEFAULT NULL COMMENT 'Codigo Leyenda se obtiene del archivo de carga',
  `ConvenioArchivo` varchar(50) DEFAULT NULL COMMENT 'Convenio se obtiene del archivo de carga',
  `OficinaArchivo` varchar(50) DEFAULT NULL COMMENT 'Oficina se obtiene del archivo de carga',
  `GuiaCIEArchivo` varchar(50) DEFAULT NULL COMMENT 'Guia CIE se obtiene del archivo de carga',
  `ConceptoArchivo` varchar(50) DEFAULT NULL COMMENT 'Concepto se obtiene del archivo de carga',
  `ReferenciaVPArchivo` varchar(50) DEFAULT NULL COMMENT 'Referencia VPA se obtiene del archivo de carga',
  `ReferenciaNumArchivo` varchar(50) DEFAULT NULL COMMENT 'Referencia Numerica se obtiene del archivo de carga',
  `NumVal` int(11) DEFAULT NULL COMMENT 'Numero de validacion.',
  `Validacion` varchar(150) DEFAULT NULL COMMENT 'Mensaje de Validacion.',
  `NumeroFila` int(11) NOT NULL DEFAULT '0' COMMENT 'Numero de Fila del deposito en el archivo cargado',
  `AplicarDeposito` char(1) NOT NULL DEFAULT 'N' COMMENT 'En la pantalla de Depositos se selecciono para aplicar el deposito S= si, N = no',
  `NombreArchivoCarga` varchar(500) NOT NULL DEFAULT '' COMMENT 'Nombre del archivo donde se cargo el deposito',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus del registro del archivo R=registrado, P= procesado',
  `ExisteRef` char(1) DEFAULT NULL COMMENT 'S= si existe la referencia, N= no existe,',
  `InstrumentoID` bigint(12) DEFAULT NULL COMMENT 'ID del instrumento (CuentaAhoID, CreditoID, tarjeta, cliente)',
  `ReferenciaMovRespaldo` varchar(40) DEFAULT NULL COMMENT 'Referencia del Movimiento respaldo',
  `ConsecutivoIDAux` int(11) DEFAULT NULL COMMENT 'Consecutivo auxiliar para recorrer registros',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria.',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria.',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria.',
  `DireccionIP` varchar(20) DEFAULT NULL COMMENT 'Campo de Auditoria.',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria.',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria.',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria.',
  PRIMARY KEY (`NumTransaccionCarga`,`FolioCargaID`),
  KEY `IDX_TMPARCHIVOCARGADEPREF_1` (`NumTransaccionCarga`),
  KEY `IDX_TMPARCHIVOCARGADEPREF_2` (`FolioCargaID`),
  KEY `IDX_TMPARCHIVOCARGADEPREF_3` (`NumeroFila`),
  KEY `IDX_TMPARCHIVOCARGADEPREF_4` (`NumTransaccionCarga`,`NumeroFila`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TMP: Almacena los registros leidos del archivo de carga en la pantalla de Depositos Referenciados por el ETL.'$$