-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPARCHRESERVNOFIRA
DELIMITER ;
DROP TABLE IF EXISTS `TMPARCHRESERVNOFIRA`;DELIMITER $$

CREATE TABLE `TMPARCHRESERVNOFIRA` (
  `TransaccionID` bigint(20) NOT NULL COMMENT 'Numero de Transaccion',
  `NumControl` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `IdCreditoFira` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `IdAcreditadoFira` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `NomAcreditadoFira` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `RfcAcreditado` varchar(200) NOT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `NomAcreditado` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `IdCreditoIfnb` varchar(200) NOT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `IdAcredIfnb` varchar(200) NOT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `Ei` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `PiAcred` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `TipoGaranteAval` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `RfcAval` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `PiAval` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `PorcentajeAval` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `Sp` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `SpFinal` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `MetodoCalculoCnbv` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `GarantiaP` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `StCredito` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `CoberturaPasoYMedida` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `RfcGarantePm` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `TipoGarantePm` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `PiPm` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `IdPortafolioPp` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `MontoPortafolioPp` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `RfcGarantePp` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `TipoGarantePp` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `PiPp` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `ReservaTotal` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `PorcReservaTotal` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA',
  `GradoRiesgoCredito` varchar(200) DEFAULT NULL COMMENT 'DATOS CARGADOS DEL CSV DE ARCHVISO DE RESERVA NO FIRA'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TMP:Tabla temporal para los archivos de perdida no fira'$$