-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPAPORTCONDICIONES
DELIMITER ;
DROP TABLE IF EXISTS `TMPAPORTCONDICIONES`;
DELIMITER $$

CREATE TABLE `TMPAPORTCONDICIONES` (
  `AportacionID` int(11) NOT NULL DEFAULT '0' COMMENT 'AportacionID a Reinvertir',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'ClienteID',
  `CuentaAhoID` bigint(20) DEFAULT NULL COMMENT 'CuentaAhoID a la cual se Carga y Abonara',
  `TipoAportacionID` int(11) DEFAULT NULL COMMENT 'TipoAportacionID que se Reinvertira.',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'MonedaID',
  `AperturaAport` char(2) DEFAULT 'FA' COMMENT 'Indica fecha de apertura de aportacion. FA:Fecha Actual / FP:Fecha Posterior',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio de la Aportación Nueva',
  `Monto` decimal(18,2) DEFAULT NULL COMMENT 'Monto de la Aportación',
  `PlazoOriginal` int(11) DEFAULT NULL COMMENT 'Plazo con el que se Buscara es Esquema de Tasas',
  `Plazo` int(11) DEFAULT NULL COMMENT 'Plazo Pagado',
  `Tasa` decimal(12,4) DEFAULT NULL COMMENT 'Tasa Orginal',
  `TasaISR` decimal(12,4) DEFAULT NULL COMMENT 'Tasa ISR',
  `TasaNeta` decimal(12,4) DEFAULT NULL COMMENT 'Tasa Neta',
  `CalculoInteres` int(11) DEFAULT '0' COMMENT 'Cálculo de Interés.',
  `InteresGenerado` decimal(18,2) DEFAULT NULL COMMENT 'Interes Generado Original',
  `InteresRecibir` decimal(18,2) DEFAULT NULL COMMENT 'Interes Recibir Original',
  `InteresRetener` decimal(18,2) DEFAULT NULL COMMENT 'Interes Retener Original',
  `TipoPagoInteres` char(1) DEFAULT NULL COMMENT 'Indica la forma de pago de interes.\nV - Vencimiento\nF - Fin del Mes\nP - Por Periodo.\nE - Programado',
  `DiasPeriodo` int(11) DEFAULT '0' COMMENT 'Indica el numero de dias si la forma de pago de interes es por PERIODO.',
  `PagoIntCal` char(2) DEFAULT '' COMMENT 'Indica el tipo de pago de interes.\nI - Iguales\nD - Devengado',
  `Reinversion` char(2) DEFAULT NULL COMMENT 'Indica si hay Reinversion Automatica',
  `Reinvertir` char(2) DEFAULT NULL COMMENT 'Indica la Manera en que se Reinvertira',
  `SaldoProAcumulado` decimal(18,2) DEFAULT NULL COMMENT 'Saldo Provision Acumulado',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Sucursal de la Aportación',
  `TasaFV` char(1) DEFAULT NULL COMMENT 'Tipo de Tasa que Maneja',
  `Calificacion` char(2) DEFAULT NULL COMMENT 'Calificacion del Cliente',
  `PlazoInferior` int(11) DEFAULT NULL COMMENT 'Plazo Inferior para la Nueva Aportación',
  `PlazoSuperior` int(11) DEFAULT NULL COMMENT 'Plazo Superior para la Nueva Aportación',
  `MontoInferior` decimal(18,2) DEFAULT NULL COMMENT 'Monto Infeior para la Nueva Aportación',
  `MontoSuperior` decimal(18,2) DEFAULT NULL COMMENT 'Monto Superior para la Nueva Aportación',
  `FechaVencimiento` date DEFAULT NULL COMMENT 'Nueva Fecha de Vencimiento para la Aportación Renovada',
  `FechaPago` date DEFAULT NULL COMMENT 'Fecha de pago.',
  `NuevoPlazo` int(11) DEFAULT NULL COMMENT 'Dias a Pagar de la Nueva Aportación',
  `MontoReinvertir` decimal(18,2) DEFAULT NULL COMMENT 'Monto que se Reinvertira',
  `NuevaTasa` decimal(12,4) DEFAULT NULL COMMENT 'Tasa de la Nueva Aportación',
  `NuevaTasaISR` decimal(12,2) DEFAULT NULL COMMENT 'TasaISR de la Nueva Aportación',
  `NuevaTasaNeta` decimal(12,4) DEFAULT NULL COMMENT 'Tasa Neta de la Nueva Aportación',
  `NuevoCalInteres` int(11) DEFAULT NULL COMMENT 'Calculo Interes de la Nueva Aportación',
  `NuevaTasaBaseID` int(11) DEFAULT NULL COMMENT 'TasaBaseID de la Nueva Aportación',
  `NuevaSobreTasa` decimal(12,4) DEFAULT NULL COMMENT 'Sobre Tasa de la Nueva Aportación',
  `NuevoPisoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Piso Tasa de la Nueva Aportación',
  `NuevoTechoTasa` decimal(12,4) DEFAULT NULL COMMENT 'Techo Tasa de la Nueva Aportación',
  `NuevoIntGenerado` decimal(18,2) DEFAULT NULL COMMENT 'Interes Generado de la Nueva Aportación',
  `NuevoIntRetener` decimal(18,2) DEFAULT NULL COMMENT 'Interes Retener de la Nueva Aportación',
  `NuevoIntRecibir` decimal(18,2) DEFAULT NULL COMMENT 'Interes Recibir de la Nueva Aportación',
  `NuevoValorGat` decimal(12,2) DEFAULT NULL COMMENT 'Valor Gat de la Nueva Aportación',
  `NuevoValorGatReal` decimal(12,2) DEFAULT NULL COMMENT 'Valor Gat Real de la Nueva Aportación',
  `AmortizacionID` int(11) DEFAULT NULL COMMENT 'AmotizacionID.',
  `DiaInhabil` char(2) DEFAULT NULL COMMENT 'Indica el Día Inhabil:\nSD = Sabado y Domingo\nD = Domingo',
  `CajaRetiro` int(11) DEFAULT NULL COMMENT 'Numero de caja de retiro del Aportación',
  `MontoGlobal` decimal(18,2) DEFAULT '0.00' COMMENT 'Monto Global del Cliente. Puede incluir el monto de los productos vigentes de los integrantes de su gpo. familiar.',
  `TasaMontoGlobal` char(1) DEFAULT 'N' COMMENT 'Valor del Tipo de Aportación al momento del registro.\nN: NO.\nS: SI.',
  `IncluyeGpoFam` char(1) DEFAULT 'N' COMMENT 'Valor del Tipo de Aportación al momento del registro.\nN: NO.\nS: SI.',
  `DiasPago` int(11) DEFAULT '0' COMMENT 'Indica el dia de pago de la aportacion',
  `PagoIntCapitaliza` char(1) DEFAULT 'I' COMMENT 'Indica si capitaliza interes S:Si, N:No, I:Indistinto',
  `OpcionAport` varchar(50) DEFAULT '' COMMENT 'Indica la opcion elegida en el combo aportacion. En alta de aportacion',
  `CantidadReno` decimal(14,2) DEFAULT '0.00' COMMENT 'Indica la cantidad de renovocacion de la aportacion',
  `InvRenovar` int(11) DEFAULT '0' COMMENT 'Inversion renovar',
  `Notas` varchar(500) DEFAULT '' COMMENT 'Notas puntuales de la aportacion',
  `ConCondiciones` char(1) DEFAULT 'N' COMMENT 'Indica si existen condiciones de vecimiento.\nS.-Si\nN.- No',
  `ReinversionPact` char(1) DEFAULT 'N' COMMENT 'Indica si se pactó un tipo de reinversión de acuerdo a las condiciones \nde vencimiento.\nS.- Si\nN.-No',
  `MotivoCancela` varchar(50) DEFAULT '' COMMENT 'Motivo de cancelación de la aportacion',
  `NuevaOpcionAportID` int(11) DEFAULT '0' COMMENT 'Indica la opcion elegida en el combo Tipo de Aportación en Condiciones de Vencimiento.',
  `NuevaCantidadReno` decimal(18,2) DEFAULT '0.00' COMMENT 'Nueva cantidad a Renovar.',
  `NuevaNotas` varchar(500) DEFAULT '' COMMENT 'Nuevas notas desde Condiciones de Vencimiento.',
  `NuevoCapitalInteres` char(1) DEFAULT 'N' COMMENT 'Indica si capitaliza interes desde las Condiciones de Vencimiento.\nS:Si, \nN:No.',
  `NuevoDiasPago` int(11) DEFAULT '0' COMMENT 'Indica el dia de pago de la aportacion',
  `ConsolidarSaldos` char(1) DEFAULT 'N' COMMENT 'Indica si Consolida Aportaciones Vigentes que venzan\nel mismo día que la Aportación a Consolidar.\nAplica para Tipo de Reinversión con Más.\nN: No (default)\nG: Sí Tipo Grupo\nI: Sí Tipo Integrante',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `UsuarioID` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria',
  `DireccionIP` varchar(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`AportacionID`),
  KEY `INDEX_TMPAPORTCONDICIONES_1` (`ClienteID`),
  KEY `INDEX_TMPAPORTCONDICIONES_2` (`TipoAportacionID`),
  KEY `INDEX_TMPAPORTCONDICIONES_3` (`PlazoOriginal`),
  KEY `INDEX_TMPAPORTCONDICIONES_4` (`MontoReinvertir`),
  KEY `INDEX_TMPAPORTCONDICIONES_5` (`MontoInferior`),
  KEY `INDEX_TMPAPORTCONDICIONES_6` (`MontoSuperior`),
  KEY `INDEX_TMPAPORTCONDICIONES_7` (`PlazoInferior`),
  KEY `INDEX_TMPAPORTCONDICIONES_8` (`PlazoSuperior`),
  KEY `INDEX_TMPAPORTCONDICIONES_9` (`Calificacion`),
  KEY `INDEX_TMPAPORTCONDICIONES_10` (`SucursalID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tmp: Proceso de Reinversion Automatica de Aportaciones con Condiciones de Vencimiento.'$$