-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPCUENTASAHOCI
DELIMITER ;
DROP TABLE IF EXISTS `TMPCUENTASAHOCI`;
DELIMITER $$


CREATE TABLE `TMPCUENTASAHOCI` (
  `RegistroID` bigint UNSIGNED AUTO_INCREMENT,
  `CuentaAhoID` bigint(12) DEFAULT NULL,
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Numero de Sucursal',
  `SucursalOrigen` int(11) DEFAULT NULL COMMENT 'Numero de Sucursal del Cliente',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de persona del cliente',
  `MonedaID` int(11) DEFAULT NULL COMMENT 'Numero de Moneda',
  `TipoCuentaID` int(11) DEFAULT NULL COMMENT 'Numero de Tipo de Cuenta',
  `FechaApertura` datetime DEFAULT NULL COMMENT 'Fecha de apertura de cuenta',
  `AnioAper` year(4) DEFAULT NULL COMMENT 'anio de apertura de la cuenta',
  `MesAper` int(2) DEFAULT NULL COMMENT 'mes de apertura de la cuenta',
  `SaldoAnterior` decimal(14,2) DEFAULT NULL,
  `Saldo` decimal(14,2) DEFAULT NULL,
  `SaldoDispon` decimal(14,2) DEFAULT NULL,
  `SaldoBloq` decimal(14,2) DEFAULT NULL,
  `SaldoSBC` decimal(14,2) DEFAULT NULL,
  `SaldoIniMes` decimal(14,2) DEFAULT NULL,
  `CargosMes` decimal(14,2) DEFAULT NULL,
  `AbonosMes` decimal(14,2) DEFAULT NULL,
  `Comisiones` decimal(14,2) DEFAULT NULL,
  `SaldoProm` decimal(14,2) DEFAULT NULL,
  `TasaInteres` decimal(14,2) DEFAULT NULL,
  `InteresesGen` decimal(14,2) DEFAULT NULL,
  `ISR` decimal(14,2) DEFAULT NULL,
  `TasaISR` decimal(14,2) DEFAULT NULL,
  `SaldoIniDia` decimal(14,2) DEFAULT NULL,
  `CargosDia` decimal(14,2) DEFAULT NULL,
  `AbonosDia` decimal(14,2) DEFAULT NULL,
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus de la cta; A - Activa	B - Bloqueada	C - Cancelada I – Inactiva R .- Registrada',
  `GeneraInteres` char(1) DEFAULT NULL COMMENT 'Si la cuenta genera o no interes. S Si genera, N no genera ',
  `TipoInteres` char(1) DEFAULT NULL COMMENT 'tipo de intereses que genera, ''D'' = diario; ''M'' = mensual',
  `EsServicio` char(1) DEFAULT NULL COMMENT '¿Es Cuenta de Servicio? S si, N no',
  `EsBancaria` char(1) DEFAULT NULL COMMENT '¿Es Cuenta bancaria? S si, N no',
  `ComApertura` decimal(14,2) DEFAULT NULL,
  `IvaComApertura` decimal(14,2) DEFAULT NULL,
  `ComManejoCta` decimal(14,2) DEFAULT NULL,
  `IvaComManejoCta` decimal(14,2) DEFAULT NULL,
  `ComAniversario` decimal(14,2) DEFAULT NULL,
  `IvaComAniv` decimal(14,2) DEFAULT NULL,
  `ComFalsoCobro` decimal(14,2) DEFAULT NULL,
  `IvaComFalsoCob` decimal(14,2) DEFAULT NULL,
  `ExPrimDispSeg` char(1) DEFAULT NULL COMMENT 'Exenta de Cobro de Comisión el Primer Dispositivo Seguridad\r\nS - Si lo exenta, No cobra comisión el primer token\r\nN - No lo exenta, Si cobra comisión        ',
  `ComDispSeg` decimal(14,2) DEFAULT NULL,
  `IvaComDispSeg` decimal(14,2) DEFAULT NULL,
  `PagaIva` char(1) DEFAULT NULL COMMENT 'Valor para saber \nsi el cliente \nPaga o No IVA\n\nS - SI\nN - NO\n',
  `Iva` decimal(14,2) DEFAULT NULL,
  `PagaISR` char(1) DEFAULT NULL,
  `PagaIDE` char(1) DEFAULT NULL,
  `EsConcentradora` char(1) DEFAULT NULL,
  `Gat` decimal(12,2) DEFAULT NULL COMMENT 'Valor GAT',
  `GatMesAnt` decimal(12,2) DEFAULT NULL COMMENT 'Gat mes anterior',
  `GatReal` decimal(12,2) DEFAULT NULL,
  `ClasificacionConta` char(1) DEFAULT NULL COMMENT 'Clasificacion Contable: V .-Depositos a la Vista, A .- Ahorro(Ordinario) de la tabla tiposcuentas',
  `ISRReal` decimal(12,2) DEFAULT '0.00' COMMENT 'La columna sirver paara acumular el sr Diario por socio solo cuando estee activa esta opcion en  PARAMGENERALES',
  `CobraSalProm` char(1) DEFAULT 'N' COMMENT 'Cobra Comision de Saldo Promedio',
  `ComSalProm` decimal(12,2) DEFAULT '0.00' COMMENT 'Comision de Saldo Promedio',
  `IVAComSalProm` decimal(12,2) DEFAULT '0.00' COMMENT 'IVA de la Comision de Saldo Promedio',
  `ExcentaCobSaldProm` char(1) DEFAULT 'N' COMMENT 'Excenta Cobra Comision de Saldo Promedio',
  `ComSalPromCob` decimal(12,2) DEFAULT '0.00' COMMENT 'Comision de Saldo Promedio Cobrado',
  `IVAComSalPromCob` decimal(12,2) DEFAULT '0.00' COMMENT 'IVA de la Comision de Saldo Promedio Cobrado',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Empresa',
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(15) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  KEY `index1` (`CuentaAhoID`),
  KEY `index2` (`ClienteID`),
  KEY `index3` (`TipoCuentaID`),
  KEY `index4` (`SaldoDispon`),
  PRIMARY KEY (RegistroID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla Temporal de Cuentas de Ahorro para el cierre de mes'$$
