-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPFIRASPCOMERCIAL
DELIMITER ;
DROP TABLE IF EXISTS `TMPFIRASPCOMERCIAL`;
DELIMITER $$


CREATE TABLE `TMPFIRASPCOMERCIAL` (
  `NumeroID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Numero de transaccion',
  `TransaccionID` bigint(20) DEFAULT NULL COMMENT 'Numero de transaccion',
  `Numcontrol` varchar(18) DEFAULT NULL COMMENT 'Numero de Control',
  `Idcreditofira` int(11) DEFAULT NULL COMMENT 'Id del Acreditado FIRA',
  `Idacreditadofira` int(11) DEFAULT NULL COMMENT 'Nombre del Acreditdo',
  `Nomacreditadofira` varchar(250) DEFAULT NULL COMMENT 'Número de control del crédito FIRA. Identificador en FIRA del crédito. Identificador en FIRA del acreditado. Nombre del acreditado (el que el IFNB registró en el sistema de FIRA). Columna',
  `Rfcacreditado` varchar(13) DEFAULT NULL COMMENT 'RFC del acreditado. Para los créditos con garantia FIRA: Este campo será aplicable solo en los casos de operaciones globales y deberá ser el mismo con el que se hizo la consulta del acreditado a la SIC mencionada en el anexo 1. Para los créditos sin garantia FIRA: Este campo es aplicable en todos los casos y deberá ser el mismo con el que se hizo la consulta del acreditado a la SIC mencionada en el anexo 1.',
  `Nomacreditado` varchar(250) DEFAULT NULL COMMENT 'Nombre del acreditado de acuerdo a lo registrado en los sistemas del IFNB. Para los créditos con garantia FIRA: Este campo será aplicable solo en los casos de operaciones globales. Para los créditos sin garantia FIRA: No aplica.',
  `Idacredifnb` varchar(20) DEFAULT NULL COMMENT 'Número identificador del acreditado en las bases de datos del IFNB. Para los créditos con garantia FIRA: Este campo será aplicable solo en los casos de operaciones globales. Para los créditos sin garantia FIRA: Campo aplicable en todos los casos.',
  `Subordinado` int(1) DEFAULT NULL COMMENT 'Indicar si es un crédito subordinado y en el caso de créditos sindicados indicar si contractualmente se encuentran subordinados respecto de otros acreedores en la prelación de pago: 1 = Si es subordinado. 2 = No es subordinado.',
  `Sp100` decimal(10,3) DEFAULT NULL COMMENT 'En caso de que al cierre del mes reportado el crédito ya presente atraso en el pago del monto exigible en los términos pactados originalmente con el IFNB, indicar los meses de atraso del crédito.',
  `Garantiarf` int(1) DEFAULT NULL COMMENT 'Indicar si el crédito cuenta con garantia real financiera admisible por FIRA de acuerdo a lo establecido en el inciso e) de este anexo: 1 = Cuenta con garantias reales financieras. 2 = No cuenta con garantias reales financieras.',
  `Numgrf` int(10) DEFAULT NULL COMMENT 'En caso de que la variable GARANTIARF = 1, indicar con cuantas garantias reales financieras cuenta el crédito. Nota: Este campo no es aplicable para los créditos sin garantia FIRA.',
  `Garantiarnf` int(1) DEFAULT NULL COMMENT 'Indicar si el crédito cuenta con garantia real no financiera admisible por FIRA de acuerdo a lo establecido en el inciso f) de este anexo: 1 = Cuenta con garantias reales no financieras. 2 = No cuenta con garantias reales no financieras.',
  `Numgrnf` int(10) DEFAULT NULL COMMENT 'En caso de que la variable GARANTIARNF = 1, indicar con cuantas garantias reales no financieras cuenta el crédito. Nota: Este campo no es aplicable para los créditos sin garantia FIRA.',
  `Garantiap` int(1) DEFAULT NULL COMMENT 'Indicar si el crédito cuenta con garantia personal distinta de FIRA en cualquiera de sus modalidades de acuerdo a lo establecido en el inciso g) de este anexo: 1 = Cuenta con garantias personales. 2 = No cuenta con garantias personales.',
  `Numgp` int(10) DEFAULT NULL COMMENT 'En caso de que la variable GARANTIAP = 1, indicar con cuantas garantias personales cuenta el crédito. Nota: Este campo no es aplicable para los créditos sin garantia FIRA.',
  `Saldoinsoluto` decimal(21,3) DEFAULT NULL COMMENT 'Indicar el saldo insoluto del crédito al cierre del mes reportado, el cual representa el monto de crédito efectivamente otorgado al acreditado, ajustado por los intereses devengados, menos los pagos de principal e intereses, asi como las quitas, condonaciones, bonificaciones y descuentos que se hubieren otorgado. En todo caso, dicho saldo no deberá incluir los intereses devengados no cobrados reconocidos en cuentas de orden dentro del balance, de créditos que estén en cartera vencida.',
  `Tipogrf` int(1) DEFAULT NULL COMMENT 'Indicar con qué tipo de garantia real financiera cuenta el IFNB de acuerdo a las garantias admisibles por FIRA: 1 = Dinero en efectivo. 2 = Valores o medios de pago con vencimiento menor a 7 dias a favor del IFNB. 3 = Ambas (1 y 2).',
  `Valorcontablegrf1` decimal(21,3) DEFAULT NULL COMMENT 'Valor contable de la garantia real financiera (GRF) cuando es dinero en efectivo. En pesos. En caso de ser más de una GRF, se sumará el valor contable de las garantias de este tipo en su conjunto.',
  `Valorcontablegrf2` decimal(21,3) DEFAULT NULL COMMENT 'Valor contable de las garantias reales financieras (GRF) cuando son valores o medios de pago con vencimiento menor a 7 dias a favor del IFNB. En pesos. En caso de ser más de una GRF, se sumará el valor contable de las garantias de este tipo en su conjunto.',
  `Hfxgrf1` int(1) DEFAULT NULL COMMENT 'Indicar si la moneda de las garantias reales financieras cuando es dinero en efectivo es la misma que la del saldo insoluto del crédito: 1 = Es la misma moneda. 2 = Están en monedas diferentes.',
  `Hfxgrf2` int(1) DEFAULT NULL COMMENT 'Indicar si la moneda de la garantias reales financieras cuando son valores o medios de pago con vencimiento menor a 7 dias a favor del IFNB es la misma que la del saldo insoluto del crédito: 1 = Es la misma moneda. 2 = Están en monedas diferentes.',
  `Factorajuste` int(1) DEFAULT NULL COMMENT 'Si la garantia real financiera es un valor ó medio de pago con vencimiento menor a 7 dias indicar si es Soberano o si fue emitido por Otros emisores distintos al soberano: 1 = Emisor soberano. 2 = Emisor no soberano.',
  `Tipogrnf` int(1) DEFAULT NULL COMMENT 'Indicar qué tipo de garantias reales no financieras tiene el IFNB de acuerdo a las garantias admisibles por FIRA: 1 = Solo Bienes inmuebles comerciales o residenciales. 2 = Solo Bienes muebles. 3 = Solo otras garantias previstas en el Articulo 32 del Reglamento del Registro Público de Comercio vigente. 4 = 1 y 2. 5 = 1 y 3. 6 = 2 y 3. 7 = Todas (1, 2 y 3).',
  `Garantiaart32` varchar(250) DEFAULT NULL COMMENT 'En caso de haber contestado “3”, “5”, “6” o “7” en la variable anterior (TIPOGRNF), indicar con cual garantia prevista en el Articulo 32 del Reglamento del Registro Público de Comercio vigente cuenta el crédito (nombrarla).',
  `Valorgarantiagrnf1` decimal(21,3) DEFAULT NULL COMMENT 'Valor del bien inmueble, el cual deberá corresponder a la última valuación disponible de dicha garantia. Deberá considerarse un valor que no exceda el valor razonable corriente de la garantia en los términos del anexo 24 de la CUB. En pesos. En caso de ser más de un bien inmueble, se sumará el valor de las garantias de todos los bienes en su conjunto.',
  `Valorgarantiagrnf2` decimal(21,3) DEFAULT NULL COMMENT 'Valor del bien mueble, el cual deberá corresponder a la última valuación disponible de dicha garantia. Deberá considerarse un valor que no exceda el valor razonable corriente de la garantia en los términos del anexo 24 de la CUB. En pesos. En caso de ser más de un bien mueble, se sumará el valor de las garantias de este tipo en su conjunto.',
  `Valorgarantiagrnf3` decimal(21,3) DEFAULT NULL COMMENT 'Valor de garantia prevista en el Articulo 32 del Reglamento del Registro Público de Comercio vigente, el cual deberá corresponder a la última valuación disponible de dicha garantia. Deberá considerarse un valor que no exceda el valor razonable corriente de la garantia en los términos del anexo 24 de la CUB. En pesos. En caso de ser más de una garantia del Articulo 32, se sumará el valor de las garantias de este tipo en su conjunto.',
  `Porccubgp1` decimal(10,6) DEFAULT NULL COMMENT 'Indicar el porcentaje del saldo del crédito al cierre del mes reportado, que cubre la garantia personal.',
  `Nomgarante1` varchar(250) DEFAULT NULL COMMENT 'Indicar el nombre del obligado solidario o aval.',
  `Rfcgarante1` varchar(13) DEFAULT NULL COMMENT 'RFC del obligado solidario o aval. Nota: Este campo deberá ser el mismo con el cual se hizo la consulta del garante a la SIC mencionada en el anexo 1.',
  `Tipogarante1` int(1) DEFAULT NULL COMMENT 'Indicar el tipo de garante: 1 = Estados y municipios u org. descentralizados estatales o municipales. 2 = Entidades financieras. 3 = Personas morales o fisicas con actividad empresarial con ventas netas menores a 14 mill UDIS. 4 = Personas morales o fisicas con actividad empresarial con ventas netas mayores o iguales a 14 mill UDIS. 5 = Gobierno Federal, empresas paraestatales u org. descentralizados con ventas netas anuales menores a 14 mill UDIS. 6 = Gobierno Federal, empresas paraestatales u org. descentralizados con ventas netas anuales mayores o iguales a 14 mill UDIS. 7 = Garantia de una ley federal.',
  `Monedagp1` int(1) DEFAULT NULL COMMENT 'Indicar la moneda en la que el garante hará frente a su obligación: 1 = Peso mexicano. 2 = Dólar americano. 3 = UDIs. 4 = Otro. Nota: Este campo no es aplicable para los créditos sin garantia FIRA.',
  `Porccubgp2` decimal(10,6) DEFAULT NULL COMMENT 'En caso de que hubiese un segundo garante (aval u obligado solidario), indicar el porcentaje del saldo del crédito al cierre del mes reportado, que cubre dicha garantia personal.',
  `Nomgarante2` varchar(250) DEFAULT NULL COMMENT 'Indicar el nombre del segundo obligado solidario o aval.',
  `Rfcgarante2` varchar(13) DEFAULT NULL COMMENT 'RFC del obligado solidario o aval. Nota: Este campo deberá ser el mismo con el cual se hizo la consulta del garante a la SIC mencionada en el anexo 1.',
  `Tipogarante2` int(1) DEFAULT NULL COMMENT 'Indicar el tipo de garante: 1 = Estados y municipios u org. descentralizados estatales o municipales. 2 = Entidades financieras. 3 = Personas morales o fisicas con actividad empresarial con ventas netas menores a 14 mill UDIS. 4 = Personas morales o fisicas con actividad empresarial con ventas netas mayores o iguales a 14 mill UDIS. 5 = Gobierno Federal, empresas paraestatales u org. descentralizados con ventas netas anuales menores a 14 mill UDIS. 6 = Gobierno Federal, empresas paraestatales u org. descentralizados con ventas netas anuales mayores o iguales a 14 mill UDIS. 7 = Garantia de una ley federal.',
  `Monedagp2` int(1) DEFAULT NULL COMMENT 'Indicar la moneda en la que cubre la garantia personal del segundo garante (aval u obligado solidario): 1 = Peso mexicano. 2 = Dólar americano. 3 = UDIs. 4 = Otro. Nota: Este campo no es aplicable para los créditos sin garantia FIRA.',
  `Nomgarantepm` varchar(250) DEFAULT NULL COMMENT 'Indicar el nombre del garante que ofrece la cobertura de Paso y Medida.',
  `Nomgarantesp` varchar(250) DEFAULT NULL COMMENT 'Indicar el nombre del garante que ofrece la cobertura de Segundas Pérdidas.',
  `Porccubpm` decimal(10,6) DEFAULT NULL COMMENT 'Indicar el porcentaje cubierto por la cobertura de Paso y Medida. ',
  `Porccubsp` decimal(10,6) DEFAULT NULL COMMENT 'Indicar el porcentaje cubierto por la cobertura de Segundas Pérdidas.',
  `Garante` int(1) DEFAULT NULL COMMENT 'Se indicará si la información reportada corresponde al garante o al acreditado: 1 = Corresponde al garante. 2 = Corresponde al acreditado.',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente ID en el SAFI (Campo Extra no va en el reporte)',
  `TipoGarantiaFIRAID` int(11) DEFAULT NULL COMMENT 'Corresponde al campo TipoGarantiaFIRAID de la tabla de CREDITOS',
  `TipoOperaAgro` char(2) DEFAULT NULL COMMENT 'Indica el tipo de operacion que se utilizara para los grupos de creditos AGRO: G: GLOBAL NF: NO FORMAL\nEste campo se actualiza en el reporte con el campo GRUPOSCREDITO TipoOperaAgro',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de Personalidad del Cliente M.- Persona Moral A.- Persona Fisica Con Actividad Empresarial F.- Persona Fisica Sin Actividad Empresarial\n',
  `EsFinanciera` char(1) DEFAULT 'N' COMMENT 'Define si el tipo de sociedad es una financiera. (TABLA TIPOSOCIEDAD)',
  `CreditoID` bigint(12) DEFAULT NULL COMMENT 'Numero de credito ID',
  `EsAgro` char(1) DEFAULT NULL COMMENT 'Identifica si el Credito es Agro o no S.- Agro N.- No Agro',
  `RfcGarantePM` varchar(13) DEFAULT '' COMMENT 'RFC del garante de la cobertura de Paso y Medida',
  `RfcGarantePP` varchar(13) DEFAULT '' COMMENT 'RFC del garante de la cobertura de Primeras y Perdidas',
  `IDPortafolioPP` int(11) DEFAULT NULL COMMENT 'Indicar la clave con la que el IFNB identifica el fondo que cubre las Primeras Perdidas en caso de incumplimiento',
  `MontoPortafolioPP` decimal(21,3) DEFAULT NULL COMMENT 'Indicar el saldo al cierre del mes reportado, del portafolio destinado a cubrir las Primeras Perdidas',
  `TipoGarantePM`  int(1) DEFAULT NULL COMMENT 'Tipo de garante de la cobertura de de Paso y Medida',
  `TipoGarantePP` int(1) DEFAULT NULL COMMENT 'Tipo de garante de la cobertura de Primeras Perdidas',
  `IDCreditoIFNB`  bigint(12) DEFAULT NULL COMMENT 'Identificador del credito asignado por la entidad.',
  `STCredito` char(2) DEFAULT NULL COMMENT ' Estatus del credito: VI: Vigente. VE: Vencido, Se debera cuadrar contra el estatus del reporte de saldos de cartera',
  `AplicaCont` char(1) DEFAULT NULL COMMENT 'Si toma referencia para los valores el Credito Contigente ',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `FechaActual` datetime NOT NULL COMMENT 'Auditoria',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Auditoria',
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Auditoria',
  PRIMARY KEY (`NumeroID`),
  KEY `IDX_TMPFIRASPCOMERCIAL_01` (`Idcreditofira`),
  KEY `IDX_TMPFIRASPCOMERCIAL_02` (`Idacreditadofira`),
  KEY `IDX_TMPFIRASPCOMERCIAL_03` (`Idacredifnb`),
  KEY `IDX_TMPFIRASPCOMERCIAL_04` (`ClienteID`)
) ENGINE=InnoDB AUTO_INCREMENT=196 DEFAULT CHARSET=latin1 COMMENT='Tabla que almacena la informacion Ddel reporte Formato variables SPcomercial '$$