-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPREPCIRCULO
DELIMITER ;
DROP TABLE IF EXISTS `TMPREPCIRCULO`;
DELIMITER $$


CREATE TABLE `TMPREPCIRCULO` (
  `CreditoID` bigint(12) NOT NULL COMMENT 'Numero de Credito',
  `Transaccion` bigint(20) NOT NULL COMMENT 'Numero de Transaccion',
  `ClienteID` int(11) DEFAULT NULL COMMENT 'Numero de Cliente',
  `SucursalID` int(11) DEFAULT NULL COMMENT 'Numero de Sucursal del Cliente',
  `ApellidoPaterno` varchar(30) DEFAULT NULL COMMENT 'Apelliedo Paterno',
  `ApellidoMaterno` varchar(30) DEFAULT NULL COMMENT 'Apelliedo Materno',
  `Nombre` varchar(50) DEFAULT NULL COMMENT 'Nombre',
  `FechaNacimiento` varchar(10) DEFAULT NULL COMMENT 'Fecha de Nacimiento',
  `RFC` varchar(13) DEFAULT NULL COMMENT 'RFC',
  `CURP` varchar(18) DEFAULT NULL COMMENT 'CRUP',
  `Nacionalidad` varchar(2) DEFAULT NULL COMMENT 'Nacionalidad',
  `EstadoCivil` char(1) DEFAULT NULL COMMENT 'Estado Civil\nS = Soltero, C = Casado V = Viudo, D= Divorciado, E  = Separado, U = Union Libre',
  `TipoResidencia` char(1) DEFAULT NULL COMMENT 'Tipo de Residencia \n1 .- Propietario, 2 .- Renta, 3 .- Familia. 4 .- Hipotecada',
  `Sexo` char(1) DEFAULT NULL COMMENT 'Genero\nF .- Femeninno, M .- Masculino',
  `TipoPersona` varchar(2) DEFAULT NULL COMMENT 'Tipo de Persona\nPF .- Persona Fisica tenga actividad empresarial o no',
  `CalleYNumero` varchar(80) DEFAULT NULL COMMENT 'Calle y numero del domicilio',
  `Colonia` varchar(65) DEFAULT NULL COMMENT 'Colonia del Domicilio de la Persona',
  `Municipio` varchar(65) DEFAULT NULL COMMENT 'Municipio del Domicilio de la Persona',
  `Estado` char(4) DEFAULT NULL COMMENT 'Estado del Domicilio de la Persona',
  `CodigoPostal` varchar(5) DEFAULT NULL COMMENT 'Codigo Postal del Domicilio de la Persona',
  `TelefonoDom` varchar(20) DEFAULT NULL COMMENT 'Telefono del Domicilio',
  `TipoDomicilio` char(1) DEFAULT NULL COMMENT 'Tipo de Domicilio. N .- Negocio, O.- Del Otorgante, C .- Casa, P .- Apartado Postal, E .- Empleo',
  `CentroTrabajo` varchar(99) DEFAULT NULL COMMENT 'Nombre del Centro de Trabajo',
  `CalleYNumeroTra` varchar(80) DEFAULT NULL COMMENT 'Calle y Numero del Trabajo',
  `ColoniaTra` varchar(65) DEFAULT NULL COMMENT 'Colonia del Domicilio del Trabajo',
  `MunicipioTra` varchar(65) DEFAULT NULL COMMENT 'Municipio del Trabajo',
  `EstadoTra` varchar(4) DEFAULT NULL COMMENT 'Estado del Trabajo',
  `CodigoPostalTra` varchar(5) DEFAULT NULL COMMENT 'Codigo Postal del Trabajo',
  `TelefonoTra` varchar(20) DEFAULT NULL COMMENT 'Telefono del Trabajo',
  `PuestoTra` varchar(60) DEFAULT NULL COMMENT 'Puesto del Trabajo',
  `TipoRespons` char(1) DEFAULT NULL COMMENT 'Tipo de Responsabilidad\nO .- Obligatorio Solidario\nI .- Individual (Titular)\n',
  `TipoContrato` char(2) DEFAULT NULL COMMENT 'Tipo de Contrato\nAE .- FÃÂ­sica Actividad Empresarial\nGS .- Grupo Solidario\n',
  `Moneda` char(2) DEFAULT NULL COMMENT 'Moneda del Credito\nMX .- Pesos Mexicanos\nUS .- DÃÂ³lares Americanos\nUD .- Unidades de InversiÃÂ³n\n',
  `TipoCuenta` char(1) DEFAULT NULL COMMENT 'Tipo de Cuenta\nF .- Pagos Fijos\nR .- Revolvente',
  `NumAmortizacion` int(11) DEFAULT NULL COMMENT 'Numero de Amortizaciones',
  `FrecuenciaPago` char(1) DEFAULT NULL COMMENT 'S.- Semanal,\nC.- Catorcenal\nQ.- Quincenal\nM.- Mensual\nB.-Bimestral \nT.-Trimestral \nA.-Anual\nU.- Pago Unico\nR.- Revolvente',
  `TotalCapital` decimal(14,2) DEFAULT NULL COMMENT 'Saldo Total de Capital',
  `CapitalVencido` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Capital Vencido',
  `TotalInteres` decimal(14,2) DEFAULT NULL COMMENT 'Total de Interes',
  `InteresVencido` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Interes Vencido',
  `Moratorios` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de Interes Moratorio',
  `Comisiones` decimal(14,2) DEFAULT NULL COMMENT 'Saldo de las comisiones del Credito',
  `TotalIVA` decimal(14,2) DEFAULT NULL COMMENT 'Total Pendiente de Pago de IVA',
  `TasaIVAInt` decimal(12,4) DEFAULT NULL COMMENT 'Tasa de IVA',
  `ClientePagaIVA` char(1) DEFAULT NULL COMMENT 'Indica si el Cliente Paga IVA o esta Excento (S/N)',
  `CobraIVAInt` char(1) DEFAULT NULL COMMENT 'Indica si el Producto Cobra IVA de Interes (S/N)',
  `CobraIVAMor` char(1) DEFAULT NULL COMMENT 'Indica si el Producto Cobra IVA de Moratorios (S/N)',
  `TotalDeuda` decimal(14,2) DEFAULT NULL COMMENT 'Total de la Deuda',
  `TotalVencido` decimal(14,2) DEFAULT NULL COMMENT 'Total del Adeudo Vencido',
  `MontoPagar` decimal(14,2) DEFAULT NULL COMMENT 'Monto del Pago Programado',
  `FechaInicio` date DEFAULT NULL COMMENT 'Fecha de Inicio del Credito',
  `FechaUltPago` varchar(10) DEFAULT NULL COMMENT 'Fecha del Ultimo Pago Realizado',
  `NoCuotasAtraso` int(4) DEFAULT NULL COMMENT 'Numero de Cuotas en Atraso',
  `FechaCierre` varchar(10) DEFAULT NULL COMMENT 'Fecha de Liquidacion o Cierre del Credito',
  `PagoActual` varchar(2) DEFAULT NULL COMMENT 'Pago o Situacion Actual\nV .- Vigente\n01 .- 1 Periodo de Atraso\n02 .- 2 Periodo de Atraso (Sucesivamente)',
  `NumLicenciaConducir` varchar(40) DEFAULT NULL COMMENT 'Numero de Licencia de Conducir',
  `ClaveElectorIFE` varchar(20) DEFAULT NULL COMMENT 'Clave de Elector de la IFE',
  `NumeroDependientes` int(11) DEFAULT NULL COMMENT 'Numero de Dependientes Economicos',
  `TipoAsentamiento` char(2) DEFAULT NULL COMMENT 'Clave del tipo de Asentamiento del Domiclio de la Persona',
  `TipoAsentamientoTrabajo` char(2) DEFAULT NULL COMMENT 'Clave del tipo de Asentamiento del Domiclio del Trabajo',
  `NumPagosEfectuados` int(11) DEFAULT NULL COMMENT 'Numero de Pagos Realizados',
  `HisPago` varchar(2) DEFAULT NULL COMMENT 'Pago o Situacion Actual, requerido cuando se Reporta por 1a vez\nV .- Vigente\n01 .- 1 Periodo de Atraso\n02 .- 2 Periodo de Atraso (Sucesivamente)',
  `CreditoMaximo` decimal(14,2) DEFAULT NULL COMMENT 'Maximo Credito Otorgado',
  `NumCreditoAnterior` varchar(25) DEFAULT NULL COMMENT 'Numero de CreditoAnterior, usado cuando el Credito Fue Migrado de un sistema anterior',
  `EstatusCredito` char(1) DEFAULT NULL COMMENT 'Estatus del Credito',
  `ClavePrevencion` char(2) DEFAULT NULL COMMENT 'Clave de Prevecion segun Circulo',
  `TipoPagoCapital` char(1) DEFAULT NULL COMMENT 'Tipo de pago de capital del credito',
  `ValorActivoValuacion` decimal(11,2) DEFAULT NULL COMMENT 'Valor de la garantia',
  `MontoUltimoPago` decimal(12,2) DEFAULT NULL COMMENT 'Monto del ultimo pago antes de la fecha de corte',
  `PlazoMeses` int(6) DEFAULT NULL COMMENT 'Plazo en meses del credito otorgado',
  `MontoCreditoOriginacion` decimal(10,2) DEFAULT NULL COMMENT 'Monto del credito otorgado',
  `SolicitudCreditoID` int(11) DEFAULT NULL,
  `OrigenDomicilio` varchar(2) DEFAULT NULL COMMENT 'Clave segun el pais ejemplo Pais --> Mexico  ,   clave --> MX',
  `RazonSocialDomicilio` varchar(2) DEFAULT NULL COMMENT 'Clave segun el pais ejemplo Pais --> Mexico  ,   clave --> MX',
  `FechaCarteraVencida` varchar(10) DEFAULT NULL COMMENT 'Fecha en la paso a cartera vencido',
  `FechaPrimIncumplimiento` varchar(8) DEFAULT NULL COMMENT 'Contiene la fecha en que incumplio en un pago por primera vez',
  `FormaPagoInteres` varchar(2) DEFAULT NULL COMMENT 'Forma en la que se pagan los interes',
  `DiasVencimiento` int(11) DEFAULT NULL COMMENT 'Dias que lleva el credito vencido',
  `CorreoElectronico` varchar(45) DEFAULT NULL COMMENT 'Correo electronico del cliente',
  `TieneEmpleo` char(1) DEFAULT NULL COMMENT 'Se usa para saber si el cliente tiene o no empleo',
  `FechaDefuncion`      VARCHAR(10) DEFAULT NULL    COMMENT 'Fecha en la que el cliente fallecio',
  `IndicadorDef`        CHAR(1)     DEFAULT NULL    COMMENT 'Indica si el cliente fallecio y no se conoce la fecha se asigna con el valor Y',
  `Monto` decimal(14,2) DEFAULT NULL COMMENT 'Monto capturado en pantalla',
  `FechaIngreso` date DEFAULT NULL COMMENT 'Fecha de ingreso',
  PRIMARY KEY (`CreditoID`,`Transaccion`),
  KEY `fk_TMPREPCIRCULO_1` (`CreditoID`),
  KEY `fk_TMPREPCIRCULO_2` (`ClienteID`),
  CONSTRAINT `fk_TMPREPCIRCULO_1` FOREIGN KEY (`CreditoID`) REFERENCES `CREDITOS` (`CreditoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TMPREPCIRCULO_2` FOREIGN KEY (`ClienteID`) REFERENCES `CLIENTES` (`ClienteID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla Temporal para la Obtencion del Reporte a Circulo de Cr'$$
