-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPREGR04C0451
DELIMITER ;
DROP TABLE IF EXISTS `TMPREGR04C0451`;DELIMITER $$

CREATE TABLE `TMPREGR04C0451` (
  `NumTransaccion` bigint(20) DEFAULT NULL COMMENT 'Numero de transaccion',
  `CreditoID` bigint(20) DEFAULT NULL COMMENT 'Identificador del credito',
  `ClienteID` bigint(20) DEFAULT NULL COMMENT 'Identificador del cliente',
  `DireccionID` int(11) DEFAULT NULL COMMENT 'Nuumero de Dirección ',
  `EstadoID` int(11) DEFAULT NULL COMMENT 'Identificador del estado',
  `EstadoClave` varchar(20) DEFAULT NULL COMMENT 'Clave del Estado',
  `MunicipioID` int(11) DEFAULT NULL COMMENT 'Identificador del Municipio',
  `MunicipioClave` varchar(20) DEFAULT NULL COMMENT 'Clave del Municipio',
  `ColoniaID` int(11) DEFAULT NULL COMMENT 'Identificador de la Colonia',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de persona',
  `Denominacion` varchar(200) DEFAULT NULL COMMENT 'Denominacion',
  `ApellidoPat` varchar(200) DEFAULT NULL COMMENT 'Apellido paterno del cliente',
  `ApellidoMat` varchar(200) DEFAULT NULL COMMENT 'Apellido materno del cliente',
  `RFC` varchar(13) DEFAULT NULL COMMENT 'RFC del cliente',
  `CURP` varchar(18) DEFAULT NULL COMMENT 'CURP del cliente',
  `Genero` char(1) DEFAULT NULL COMMENT 'Genero',
  `ClaveSucursal` varchar(100) DEFAULT NULL COMMENT 'Clave de la sucursal',
  `DestinoCreID` int(11) DEFAULT NULL COMMENT 'Identificador del destino del credito',
  `ClasifRegID` int(11) DEFAULT NULL COMMENT 'Numero de la Clasificación de Rep Regulatorios',
  `ClasifConta` varchar(20) DEFAULT NULL COMMENT 'Clave por Destino de Acuerdo al SITI',
  `ProductoCredito` varchar(200) DEFAULT NULL COMMENT 'Producto del credito',
  `FechaDisp` date DEFAULT NULL COMMENT 'Fecha inicio del credito',
  `FechaVencim` date DEFAULT NULL COMMENT 'Fecha de vencimiento del credito',
  `TipoAmorti` int(11) DEFAULT NULL COMMENT 'Tipo de amortizaciones',
  `MontoCredito` decimal(16,2) DEFAULT NULL COMMENT 'Monto del credito',
  `PeriodicidadCap` int(11) DEFAULT NULL COMMENT 'Periodicidad capital',
  `PeriodicidadInt` int(11) DEFAULT NULL COMMENT 'Periodicidad interes',
  `TasaInteres` decimal(12,4) DEFAULT NULL COMMENT 'Tasa de interes',
  `UltimaAmorti` int(11) DEFAULT NULL COMMENT 'Ultima amortizacion',
  `FecUltPagoCap` date DEFAULT NULL COMMENT 'Fecha ultimo pago capital',
  `FecUltPagoInt` date DEFAULT NULL COMMENT 'Fecha ultimo pago interes',
  `MonUltPagoCap` decimal(16,2) DEFAULT NULL COMMENT 'Monto ultimo pago capital',
  `MonUltPagoInt` decimal(16,2) DEFAULT NULL COMMENT 'Monto ultimo pago interes',
  `FecPrimAtraso` varchar(20) DEFAULT NULL COMMENT 'Fecha primer atraso',
  `MontoCondona` decimal(16,2) DEFAULT NULL COMMENT 'Monto condonacion',
  `FecUltCondona` varchar(20) DEFAULT NULL COMMENT 'Fecha ultima condonacion',
  `NumDiasAtraso` int(11) DEFAULT NULL COMMENT 'Numero de dias de atraso',
  `TipoCredito` char(1) DEFAULT NULL COMMENT 'Tipo de credito',
  `EstatusCredito` char(1) DEFAULT NULL COMMENT 'Estatus del credito',
  `SituacContable` char(1) DEFAULT NULL COMMENT 'Situacion contable del estatus del credito',
  `SalCapital` decimal(16,2) DEFAULT NULL COMMENT 'Saldo capital',
  `SalIntOrdin` decimal(16,2) DEFAULT NULL COMMENT 'Saldo interes ordinario',
  `SalIntMora` decimal(16,2) DEFAULT NULL COMMENT 'Saldo interes moratorio',
  `SalIntCtaOrden` decimal(16,2) DEFAULT NULL COMMENT 'Saldo interes no contabilizado',
  `SalMoraCtaOrden` decimal(16,2) DEFAULT NULL COMMENT 'Otros Saldos moratorios ',
  `IntereRefinan` decimal(16,2) DEFAULT NULL COMMENT 'Saldo del Interes refinanciado con el tratamiento al credito',
  `SaldoInsoluto` decimal(16,2) DEFAULT NULL COMMENT 'Saldo insoluto',
  `TipoRelacion` varchar(2) DEFAULT NULL COMMENT 'Tipo de Relacion',
  `TipCarCalifi` char(1) DEFAULT NULL COMMENT 'Tipo calificacion por clasificacion',
  `CalifiIndiv` char(1) DEFAULT NULL COMMENT 'Calificacion individual',
  `CalifCubierta` char(2) DEFAULT NULL COMMENT 'Calificacion cubierta',
  `CalifExpuesta` char(2) DEFAULT NULL COMMENT 'Calificacion expuerta',
  `ReservaCubierta` decimal(16,2) DEFAULT NULL COMMENT 'Reserva cubierta',
  `ReservaExpuesta` decimal(16,2) DEFAULT NULL COMMENT 'Reserva expuesta',
  `EPRCAdiCarVen` decimal(16,2) DEFAULT NULL COMMENT 'EPRC adicional cartera vencida',
  `EPRCAdiSIC` decimal(16,2) DEFAULT NULL COMMENT 'EPRC adicional SIC',
  `EPRCAdiCNVB` decimal(16,2) DEFAULT NULL COMMENT 'EPRC adicional CNVB',
  `GtiaCtaAhorro` decimal(16,2) DEFAULT NULL COMMENT 'Garantia cuenta de ahorro',
  `GtiaInversion` decimal(16,2) DEFAULT NULL COMMENT 'Garantia inversion',
  `GtiaHisInver` decimal(16,2) DEFAULT NULL COMMENT 'Garantia historico inversion',
  `TotGtiaLiquida` decimal(16,2) DEFAULT NULL COMMENT 'Total garantia liquida',
  `GtiaHipotecaria` decimal(16,2) DEFAULT NULL COMMENT 'Garantia hipotecaria',
  `FecConsultaSIC` varchar(20) DEFAULT NULL COMMENT 'Fecha consulta SIC',
  `ClaveSIC` varchar(20) DEFAULT NULL COMMENT 'clave sic',
  `UltFecVen` date DEFAULT NULL COMMENT 'Ultima Fecha Vencimiento',
  KEY `R04C0451_idx1` (`DestinoCreID`),
  KEY `R04C0451_idx2` (`ClasifRegID`),
  KEY `R04C0451_idx3` (`CreditoID`),
  KEY `R04C0451_idx4` (`ClienteID`),
  KEY `R04C0451_idx5` (`NumTransaccion`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$