-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPSALDOSGESTIONCOB
DELIMITER ;
DROP TABLE IF EXISTS `TMPSALDOSGESTIONCOB`;DELIMITER $$

CREATE TABLE `TMPSALDOSGESTIONCOB` (
  `Transaccion` bigint(20) DEFAULT NULL COMMENT 'Número de transaccion que usa como llave de todos los movimientos por consulta de reporte',
  `GrupoID` int(12) DEFAULT NULL COMMENT 'Número de grupo al que pertenece la amortizacion de credito de un credito que tiene un cliente',
  `NombreGrupo` varchar(200) DEFAULT NULL COMMENT 'Nombre del grupo si el credito es grupal ',
  `CreditoID` bigint(12) DEFAULT NULL COMMENT 'Número de crédito ',
  `SolicitudCreditoID` bigint(20) DEFAULT NULL COMMENT 'Id de la Solicitud de Credito',
  `CicloGrupo` int(12) DEFAULT NULL COMMENT 'ciclo actual de grupo',
  `ClienteID` int(12) DEFAULT NULL COMMENT 'cliente relacionado con el credito',
  `NombreCompleto` varchar(200) DEFAULT NULL COMMENT 'nombre del cliente',
  `MontoCredito` decimal(14,2) DEFAULT NULL COMMENT 'cantidad total del crédito',
  `FechaInicio` date DEFAULT NULL COMMENT 'fecha de inicio del credito',
  `FechaVencimien` date DEFAULT NULL COMMENT 'fecha vencimiento del credito',
  `FechaVencim` date DEFAULT NULL COMMENT 'fecha de vencimiento de la amortización del crédito',
  `EstatusCredito` varchar(50) DEFAULT NULL COMMENT 'estatus actual del credito',
  `Capital` decimal(14,2) DEFAULT NULL COMMENT 'cantodad de capital',
  `CapitalVencido` decimal(14,2) DEFAULT NULL COMMENT 'Saldo capital vencido del credito.',
  `Interes` decimal(14,2) DEFAULT NULL COMMENT 'cantidad generada porinteres',
  `Moratorios` decimal(14,2) DEFAULT NULL COMMENT 'cantidad de cargos moratorios',
  `Comisiones` decimal(14,2) DEFAULT NULL COMMENT 'comisiones ',
  `Cargos` decimal(14,2) DEFAULT NULL COMMENT 'cargos',
  `AmortizacionID` int(12) DEFAULT NULL COMMENT 'identificador de la amortizacion',
  `IVATotal` decimal(14,2) DEFAULT NULL COMMENT 'cargo de iva total',
  `CobraIVAMora` char(1) DEFAULT NULL COMMENT 'cobra mora "S" .- si "N".- no',
  `CobraIVAInteres` char(1) DEFAULT NULL COMMENT 'cobra interes "S" si "N" no',
  `SucursalID` int(12) DEFAULT NULL COMMENT 'Número de la sucursal',
  `NombreSucurs` varchar(50) DEFAULT NULL COMMENT 'Nombre de la sucursal',
  `ProductoCreditoID` int(12) DEFAULT NULL COMMENT 'Número del producto de credito',
  `Descripcion` varchar(100) DEFAULT NULL COMMENT 'descripcion del producto de credito',
  `PromotorActual` int(12) DEFAULT NULL COMMENT 'número de Promotor relacionado',
  `NombrePromotor` varchar(100) DEFAULT NULL COMMENT 'nombre de promotor relacionado',
  `TotalCuota` decimal(14,2) DEFAULT NULL COMMENT 'total de cuotas',
  `Pago` decimal(14,2) DEFAULT NULL COMMENT 'cantidad de pago ',
  `FechaPago` date DEFAULT NULL COMMENT 'fecha en la que hizo el pago',
  `DiasAtraso` int(12) DEFAULT NULL COMMENT 'cantidad de dias de atraso fechasistema - fechaexigible',
  `SaldoTotal` decimal(14,2) DEFAULT NULL COMMENT 'saldo total',
  `FechaEmision` date DEFAULT NULL COMMENT 'Fecha de emisión',
  `HoraEmision` time DEFAULT NULL COMMENT 'Hora de emisión',
  `Telefono` varchar(20) DEFAULT NULL COMMENT 'Telefono del cliente',
  `Celular` varchar(20) DEFAULT NULL COMMENT 'Telefono celular del cliente.',
  `CalleNumero` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio del cliente.',
  `ColoniaID` int(11) DEFAULT NULL COMMENT 'ID de la Colonia',
  `NombreColonia` varchar(200) DEFAULT NULL,
  `CP` char(5) DEFAULT NULL COMMENT 'Codigo postal del domiclio del cliente.',
  `LocalidadID` int(11) DEFAULT NULL COMMENT 'ID de la localidad del domicilio.',
  `NombreLocalidad` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad.',
  `EstadoID` int(11) DEFAULT NULL COMMENT 'ID del estado del domiclio.',
  `NombreEstado` varchar(100) DEFAULT NULL COMMENT 'Nombre del estado.',
  `NombreReferencia1` varchar(250) DEFAULT NULL COMMENT 'Nombre completo de la referencia del cliente.',
  `TelefonoRef1` varchar(20) DEFAULT NULL COMMENT 'Telefono de la referencia.',
  `CalleNumeroRef1` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio de la referencia del cliente.',
  `ColoniaIDRef1` int(11) DEFAULT NULL COMMENT 'ID de la Colonia de la referencia.',
  `NombreColoniaRef1` varchar(200) DEFAULT NULL COMMENT 'Nombre de la Colonia de la referencia.',
  `CPRef1` char(5) DEFAULT NULL COMMENT 'CP de la referencia.',
  `LocalidadIDRef1` int(11) DEFAULT NULL COMMENT 'ID de la localidad de la referencia.',
  `NombreLocalidadRef1` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad',
  `EstadoIDRef1` int(11) DEFAULT NULL COMMENT 'Id del estado de la referencia.',
  `NombreEstadoRef1` varchar(200) DEFAULT NULL COMMENT 'Nombre del estado de la referencia.',
  `NombreReferencia2` varchar(250) DEFAULT NULL COMMENT 'Nombre completo de la referencia del cliente.',
  `TelefonoRef2` varchar(20) DEFAULT NULL COMMENT 'Telefono de la referencia.',
  `CalleNumeroRef2` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio de la referencia del cliente.',
  `ColoniaIDRef2` int(11) DEFAULT NULL COMMENT 'ID de la Colonia de la referencia.',
  `NombreColoniaRef2` varchar(200) DEFAULT NULL COMMENT 'Nombre de la Colonia de la referencia.',
  `CPRef2` char(5) DEFAULT NULL COMMENT 'CP de la referencia.',
  `LocalidadIDRef2` int(11) DEFAULT NULL COMMENT 'ID de la localidad de la referencia.',
  `NombreLocalidadRef2` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad',
  `EstadoIDRef2` int(11) DEFAULT NULL COMMENT 'Id del estado de la referencia.',
  `NombreEstadoRef2` varchar(200) DEFAULT NULL COMMENT 'Nombre del estado de la referencia.',
  `NombreReferencia3` varchar(250) DEFAULT NULL COMMENT 'Nombre completo de la referencia del cliente.',
  `TelefonoRef3` varchar(20) DEFAULT NULL COMMENT 'Telefono de la referencia.',
  `CalleNumeroRef3` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio de la referencia del cliente.',
  `ColoniaIDRef3` int(11) DEFAULT NULL COMMENT 'ID de la Colonia de la referencia.',
  `NombreColoniaRef3` varchar(200) DEFAULT NULL COMMENT 'Nombre de la Colonia de la referencia.',
  `CPRef3` char(5) DEFAULT NULL COMMENT 'CP de la referencia.',
  `LocalidadIDRef3` int(11) DEFAULT NULL COMMENT 'ID de la localidad de la referencia.',
  `NombreLocalidadRef3` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad',
  `EstadoIDRef3` int(11) DEFAULT NULL COMMENT 'Id del estado de la referencia.',
  `NombreEstadoRef3` varchar(200) DEFAULT NULL COMMENT 'Nombre del estado de la referencia.',
  `NombreReferencia4` varchar(250) DEFAULT NULL COMMENT 'Nombre completo de la referencia del cliente.',
  `TelefonoRef4` varchar(20) DEFAULT NULL COMMENT 'Telefono de la referencia.',
  `CalleNumeroRef4` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio de la referencia del cliente.',
  `ColoniaIDRef4` int(11) DEFAULT NULL COMMENT 'ID de la Colonia de la referencia.',
  `NombreColoniaRef4` varchar(200) DEFAULT NULL COMMENT 'Nombre de la Colonia de la referencia.',
  `CPRef4` char(5) DEFAULT NULL COMMENT 'CP de la referencia.',
  `LocalidadIDRef4` int(11) DEFAULT NULL COMMENT 'ID de la localidad de la referencia.',
  `NombreLocalidadRef4` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad',
  `EstadoIDRef4` int(11) DEFAULT NULL COMMENT 'Id del estado de la referencia.',
  `NombreEstadoRef4` varchar(200) DEFAULT NULL COMMENT 'Nombre del estado de la referencia.',
  `NombreAval1` varchar(250) DEFAULT NULL COMMENT 'Nombre completo del aval del cliente.',
  `TelefonoAval1` varchar(20) DEFAULT NULL COMMENT 'Telefono del aval.',
  `CalleNumeroAval1` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio del aval del cliente.',
  `ColoniaIDAval1` int(11) DEFAULT NULL COMMENT 'ID de la Colonia del aval.',
  `NombreColoniaAval1` varchar(200) DEFAULT NULL COMMENT 'Nombre de la Colonia del aval.',
  `CPAval1` char(5) DEFAULT NULL COMMENT 'CP del aval.',
  `LocalidadIDAval1` int(11) DEFAULT NULL COMMENT 'ID de la localidad del aval.',
  `NombreLocalidadAval1` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad',
  `EstadoIDAval1` int(11) DEFAULT NULL COMMENT 'Id del estado del aval.',
  `NombreEstadoAval1` varchar(200) DEFAULT NULL COMMENT 'Nombre del estado del aval.',
  `NombreAval2` varchar(250) DEFAULT NULL COMMENT 'Nombre completo del aval del cliente.',
  `TelefonoAval2` varchar(20) DEFAULT NULL COMMENT 'Telefono del aval.',
  `CalleNumeroAval2` varchar(100) DEFAULT NULL COMMENT 'Calle y numero del domicilio del aval del cliente.',
  `ColoniaIDAval2` int(11) DEFAULT NULL COMMENT 'ID de la Colonia del aval.',
  `NombreColoniaAval2` varchar(200) DEFAULT NULL COMMENT 'Nombre de la Colonia del aval.',
  `CPAval2` char(5) DEFAULT NULL COMMENT 'CP del aval.',
  `LocalidadIDAval2` int(11) DEFAULT NULL COMMENT 'ID de la localidad del aval.',
  `NombreLocalidadAval2` varchar(200) DEFAULT NULL COMMENT 'Nombre de la localidad',
  `EstadoIDAval2` int(11) DEFAULT NULL COMMENT 'Id del estado del aval.',
  `NombreEstadoAval2` varchar(200) DEFAULT NULL COMMENT 'Nombre del estado del aval.',
  `MontoSeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto del seguro por cuota',
  `IVASeguroCuota` decimal(12,2) DEFAULT NULL COMMENT 'Monto de Iva para el seguro por cuota',
  KEY `INDEX_TMPSALDOSGESTIONCOB_1` (`CreditoID`),
  KEY `INDEX_TMPSALDOSGESTIONCOB_2` (`AmortizacionID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla temporal para agilizar los procesos del reporte de saldos gestion cobranza'$$