
DELIMITER ;
DROP TABLE IF EXISTS TMPSITIPLDREP;
DELIMITER $$
CREATE TABLE `TMPSITIPLDREP` (
  `RepSitiID` bigint(20) UNSIGNED AUTO_INCREMENT COMMENT 'Llave primaria de reporte.',
  `TipoReporte` int(11) NOT NULL COMMENT 'Tipo de Reporte ',
  `PeriodoReporte` varchar(10) NOT NULL COMMENT 'Periodo el cual cubre el Reporte\n',
  `Folio` varchar(6) NOT NULL COMMENT 'Folio consecutivo.',
  `ClaveOrgSupervisor` varchar(6) DEFAULT NULL COMMENT 'Clave del Organo Supervisor\n',
  `ClaveEntCasFim` varchar(6) DEFAULT NULL COMMENT 'Clave del Sujeto Obligado\n',
  `LocalidadSuc` varchar(8) DEFAULT NULL COMMENT 'Localidad de la Suc',
  `Sucursal` varchar(8) DEFAULT NULL COMMENT 'Clave de la Sucursal',
  `TipoOperacionID` varchar(2) DEFAULT NULL COMMENT 'TipoOperacionID',
  `InstrumentMonID` varchar(3) DEFAULT NULL COMMENT 'Clave del Instrumento Monetario\n',
  `CuentaAhoID` varchar(16) DEFAULT NULL COMMENT 'Numero de CuentaAhoID',
  `Monto` varchar(30) DEFAULT NULL COMMENT 'Monto de operación.',
  `ClaveMoneda` varchar(3) DEFAULT NULL COMMENT 'Clave o identificador de la moneda\n',
  `FechaOpe` varchar(8) DEFAULT NULL COMMENT 'Fecha de la Operacion\n',
  `FechaDeteccion` varchar(8) DEFAULT NULL COMMENT 'Fecha de Deteccion de la operacion\n',
  `Nacionalidad` varchar(4) DEFAULT NULL COMMENT 'Nacionalidad',
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de Persona sujeto\n',
  `RazonSocial` varchar(60) DEFAULT NULL COMMENT 'RazonSocial',
  `Nombre` varchar(60) DEFAULT NULL COMMENT 'Nombres',
  `ApellidoPat` varchar(60) DEFAULT NULL COMMENT 'Apellido Paterno',
  `ApellidoMat` varchar(60) DEFAULT NULL COMMENT 'Apellido Materno',
  `RFC` varchar(13) DEFAULT NULL COMMENT 'RFC',
  `CURP` varchar(18) DEFAULT NULL COMMENT 'CURP',
  `FechaNac` varchar(60) DEFAULT NULL COMMENT 'Fecha de nacimiento o constitución',
  `Domicilio` varchar(60) DEFAULT NULL COMMENT 'Domicilio oficial',
  `Colonia` varchar(30) DEFAULT NULL COMMENT 'Colonia',
  `Localidad` varchar(8) DEFAULT NULL COMMENT 'Localidad',
  `Telefono` varchar(40) DEFAULT NULL COMMENT 'Telefono',
  `ActEconomica` varchar(10) DEFAULT NULL COMMENT 'Actividad Economica.',
  `NomApoderado` varchar(60) DEFAULT NULL COMMENT 'Nombre del Apoderado\n',
  `ApPatApoderado` varchar(60) DEFAULT NULL COMMENT 'Apellido Paterno del Apoderado',
  `ApMatApoderado` varchar(60) DEFAULT NULL COMMENT 'Apellido Materno del Apoderado\n',
  `RFCApoderado` varchar(13) DEFAULT NULL COMMENT 'RFC del Apoderado\n',
  `CURPApoderado` varchar(18) DEFAULT NULL COMMENT 'Curp del apoderado\n',
  `CtaRelacionadoID` varchar(2) DEFAULT NULL COMMENT 'Id o Identificador de la cuenta de personas relacionadas\n',
  `CuenAhoRelacionado` varchar(16) DEFAULT NULL COMMENT 'Cuenta de Ahorro de la Persona Relacionada\n',
  `ClaveSujeto` varchar(6) DEFAULT NULL COMMENT 'Clave del Sujeto Titular\n\n',
  `NomTitular` varchar(60) DEFAULT NULL COMMENT 'nombre del Titular\n',
  `ApPatTitular` varchar(60) DEFAULT NULL COMMENT 'Apellido Paterno del Titular\n',
  `ApMatTitular` varchar(60) DEFAULT NULL COMMENT 'Apellido Materno del titular\n',
  `DesOperacion` varchar(300) DEFAULT NULL COMMENT 'Descripcion de la Operacion\n',
  `Razones` varchar(300) DEFAULT NULL COMMENT 'Razones de la Operacion',
  `ClaveCNBV` char(4) DEFAULT NULL COMMENT 'Clave proporcionada por la CNBV para identificar cada pais',
  `OperacionID` bigint(20) DEFAULT '0' COMMENT 'ID de la Operación Reportada de acuerdo al Tipo de Reporte.',
  `Fecha` date DEFAULT '1900-01-01' COMMENT 'Fecha de la operación.',
  `NumTransaccion` bigint(20) NOT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`RepSitiID`),
  KEY `INDEX_TMPSITIPLDREP_1` (`NumTransaccion`),
  KEY `INDEX_TMPSITIPLDREP_2` (`PeriodoReporte`, `TipoReporte`, `NumTransaccion`),
  KEY `INDEX_TMPSITIPLDREP_3` (`TipoReporte`,`PeriodoReporte`,`Folio`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TMP: Tabla para reporte siti.'$$