-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- USUARIOS
DELIMITER ;
DROP TABLE IF EXISTS `USUARIOS`;
DELIMITER $$

CREATE TABLE `USUARIOS` (
  `UsuarioID` int(11) NOT NULL COMMENT 'Numero de Usuario',
  `ClavePuestoID` varchar(10) DEFAULT NULL COMMENT 'ID o clave del Puesto',
  `Nombre` varchar(50) DEFAULT NULL,
  `ApPaterno` varchar(50) DEFAULT NULL,
  `ApMaterno` varchar(50) DEFAULT NULL,
  `NombreCompleto` varchar(150) NOT NULL COMMENT 'Nombre del\nUsuario',
  `Clave` varchar(45) NOT NULL COMMENT 'Clave',
  `Contrasenia` varchar(45) NOT NULL COMMENT 'Contrasenia',
  `RolID` int(11) DEFAULT NULL COMMENT 'Rol o Perfil del\nUsuario',
  `Estatus` char(1) DEFAULT NULL COMMENT 'Estatus del Usuario\nA .- Activo\nB .- Bloqueado\nC .- Cancelado o Baja\nI .- Inactivo',
  `LoginsFallidos` int(11) DEFAULT NULL COMMENT 'Numero de Logins\nFallidos a la \nAplicacion',
  `Correo` varchar(50) DEFAULT NULL COMMENT 'Correo Email\ndel Usuario',
  `SucursalUsuario` int(11) DEFAULT NULL COMMENT 'Sucursal donde\nSe encuentra\nAsignado el \nUsuario',
  `EstatusSesion` char(1) DEFAULT NULL COMMENT 'Estatus de sesion\nValores\nA=Activo\nI=Inactivo',
  `FechaAlta` date DEFAULT NULL,
  `FechUltimAcces` date DEFAULT NULL COMMENT 'Fecha de ultimo acceso\n',
  `FechUltPass` date DEFAULT NULL COMMENT 'Fecha de cambio del  password\n\n',
  `IPsesion` varchar(15) DEFAULT NULL COMMENT 'IP de la maquina donde se logea el usuario',
  `MotivoBloqueo` varchar(200) DEFAULT NULL,
  `FechaBloqueo` date DEFAULT NULL,
  `MotivoCancel` varchar(200) DEFAULT NULL,
  `FechaCancel` date DEFAULT NULL,
  `UsuarioIDCancel` int(11) DEFAULT NULL COMMENT 'Numero de Usuario realiza Cancelacion',
  `Semilla` varchar(25) NOT NULL COMMENT 'Reservado',
  `RealizaConsultasCC` char(1) DEFAULT NULL COMMENT 'Campo para verificar si un Usuario puede realizar consultas a Circulo de Crédito\\nS = SI\\nN = NO',
  `usuarioCirculo` char(12) DEFAULT NULL COMMENT 'nombre de Usuario de circulo',
  `contrasenaCirculo` char(16) DEFAULT NULL COMMENT 'contraseña de circulo de credito',
  `RealizaConsultasBC` char(1) DEFAULT '' COMMENT 'Campo para verificar si un Usuario puede realizar consultas a Circulo de Crédito \nS = SI \nN = NO',
  `UsuarioBuroCredito` char(12) DEFAULT '' COMMENT 'Nombre de Usuario de Buro de Credito',
  `ContrasenaBuroCredito` char(16) DEFAULT '' COMMENT 'Contraseña del Usuario de Buro de credito',
  `MotivoReactiva` varchar(200) DEFAULT NULL COMMENT 'Motivo de reactivar el usuario',
  `FechaReactiva` date DEFAULT NULL COMMENT 'Fecha en que se reactiva el usuario',
  `UsuarioIDReactiva` int(11) DEFAULT NULL COMMENT 'Numero de Usuario realiza la ractivacion',
  `AccesoMonitor` char(1) DEFAULT 'N' COMMENT 'Acceso al Monitor de Solicitud de Credito\nS: Acceso Total\nN: Acceso Parcial''',
  `Notificacion` char(1) DEFAULT 'N' COMMENT 'Indica si el Usuario recibe notificaciones.',
  `AccedeHuella` char(1) DEFAULT '' COMMENT 'Indica si el usuario puede acceder con Huella Dígital:  S = Si, N  = No',
  `AccederAutorizar` char(1) DEFAULT '' COMMENT 'Indica si permite ingresar la contraseña o con Huella, C = Solo Conttraseña,  H = Solo Huella, A = Ambos ',
  `RFC` varchar(13) DEFAULT '' COMMENT 'RFC del Usuario, se utiliza para vincularlo con clientes y validar la huella digital',
  `CURP` char(18) DEFAULT NULL COMMENT 'CURP del USUARIO',
  `DireccionCompleta` varchar(200) DEFAULT NULL COMMENT 'Direccion Completa del Usuario',
  `FolioIdentificacion` varchar(18) DEFAULT NULL COMMENT 'Numero de Folio de la Identificacion del Usuario',
  `FechaExpedicion` date DEFAULT NULL COMMENT 'Fecha de Expedicion de la Identificacion',
  `FechaVencimiento` date DEFAULT NULL COMMENT 'Fecha de Vencimiento de la Identificacion',
  `UsaAplicacion` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Campo para saber si usa la aplicacion movil S = SI, N = NO',
  `IMEI` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'Campo para el imei del usuario',
  `UsuarioExt` varchar(45) DEFAULT NULL COMMENT 'Eindica el usuario externo que está relacionado con SAFI',
  `EmpleadoID` bigint(20) NOT NULL DEFAULT '0' COMMENT 'ID o clave del Empleado tabla EMPLEADOS',
  `EstatusAnalisis` char(1) NOT NULL DEFAULT 'I' COMMENT 'Indica el estatus de analista de credito /A activo  /I inactivo',
  `NotificaCierre` CHAR(1) DEFAULT 'N' NOT NULL COMMENT 'Indica si se notifica al usuario el cierre automatico',
  `EmpresaID` int(11) DEFAULT NULL COMMENT 'Llave Foranea Hacia Paquete Empresa\n',
  `Usuario` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `FechaActual` datetime DEFAULT NULL COMMENT 'Campo de Auditoria',
  `DireccionIP` varchar(15) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `ProgramaID` varchar(50) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `Sucursal` int(11) DEFAULT NULL COMMENT 'Campo de Auditoria',
  `NumTransaccion` int(15) DEFAULT NULL COMMENT 'Campo de Auditoria',
  PRIMARY KEY (`UsuarioID`),
  KEY `fk_USUARIOS_rol` (`RolID`),
  KEY `fk_USUARIOS_sucursal` (`SucursalUsuario`),
  KEY `fk_USUARIOS_1` (`ClavePuestoID`),
  KEY `idx_USUARIOS_1` (`Clave`),
  CONSTRAINT `fk_USUARIOS_1` FOREIGN KEY (`ClavePuestoID`) REFERENCES `PUESTOS` (`ClavePuestoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_sucursal` FOREIGN KEY (`SucursalUsuario`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla para Manejo de Usuario del Sistema'$$