-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- USUARIOSERVICIO
DELIMITER ;
DROP TABLE IF EXISTS `USUARIOSERVICIO`;

DELIMITER $$
CREATE TABLE `USUARIOSERVICIO` (
  `UsuarioServicioID` int(11) NOT NULL,
  `TipoPersona` char(1) DEFAULT NULL COMMENT 'Tipo de Responsabilidad del Usuario \nM.- Persona Moral \nA.- Persona Fisica Con Actividad Empresarial \nF.- Persona Fisica Sin Actividad Empresarial',
  `PrimerNombre` varchar(50) DEFAULT NULL COMMENT 'Primer Nombre del Usuario de Servicios',
  `SegundoNombre` varchar(50) DEFAULT NULL COMMENT 'Segundo Nombre del Usuario de Servicios',
  `TercerNombre` varchar(50) DEFAULT NULL COMMENT 'Tercer Nombre del Usuario de Servicios',
  `ApellidoPaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Paterno del Usuario de Servicios',
  `ApellidoMaterno` varchar(50) DEFAULT NULL COMMENT 'Apellido Materno del Usuario de Servicios',
  `FechaNacimiento` date DEFAULT NULL COMMENT 'Fecha de Nacimiento del Usuario de Servicios',
  `Nacionalidad` char(1) DEFAULT NULL COMMENT 'Nacionalidad del Usuario de Servicios\n''N'' = Nacional\n''E'' = Extranjero',
  `PaisNacimiento` int(11) DEFAULT NULL COMMENT 'Pais de Nacimiento, llave foranea a PAISES',
  `EstadoNacimiento` int(11) DEFAULT NULL COMMENT 'Pais de Nacimiento, llave foranea a ESTADOSREPUB',
  `Sexo` char(1) DEFAULT NULL COMMENT 'Codigo de sexo del Usuario de Servicios\nClave Sexo:\n''M'' = Masculino\n''F''  = Femenino',
  `CURP` char(18) DEFAULT NULL COMMENT 'Clave Unica de Registro Poblacional',
  `RazonSocial` varchar(150) DEFAULT NULL COMMENT 'Razon Social, tratandose de Personas Morales',
  `TipoSociedadID` int(11) DEFAULT NULL COMMENT 'Tipo de Sociedad, tiene llave foranea a la tabla  TIPOSOCIEDAD, para personas Morales',
  `RFC` char(13) DEFAULT NULL COMMENT 'Registro Federal de Contribuyentes del Usuario de Servicios',
  `RFCpm` char(13) DEFAULT NULL COMMENT 'Registro Federal de Contribuyentes del Usuario de Servicios, cuando esta sea Persona Moral',
  `RFCOficial` char(13) DEFAULT NULL COMMENT 'RFC del cliente ya sea RFC que es asignado como persona fisica o el RFC como persona moral',
  `FEA` varchar(250) DEFAULT NULL COMMENT 'Firma Electrónica Avanzada, en caso de contar con ella.',
  `FechaConstitucion` date DEFAULT NULL COMMENT 'Fecha de Constitucion ante el Registro Federal de Contribuyentes.',
  `PaisRFC` int(11) DEFAULT NULL COMMENT 'Pais que Asigna el Registro Federal de Contribuyentes.',
  `OcupacionID` int(5) DEFAULT NULL COMMENT 'Profesión del cliente,Llave Foranea Hacia tabla OCUPACIONES',
  `Correo` varchar(50) DEFAULT NULL COMMENT 'Correo Electronico del Usuario de Servicios',
  `TelefonoCelular` varchar(20) DEFAULT NULL COMMENT 'Telefono Celular del Usuario de Servicios',
  `Telefono` varchar(20) DEFAULT NULL COMMENT 'Telefono del Usuario de Servicios',
  `ExtTelefonoPart` varchar(7) DEFAULT NULL COMMENT 'Contiene en número de extensión del teléfono',
  `NombreCompleto` varchar(200) DEFAULT NULL COMMENT 'Este campo no se captura, se forma en base a los nombres y apellidos',
  `SucursalOrigen` int(11) DEFAULT NULL COMMENT 'No de Sucursal en la que se da de Alta el Usuario, Llave Foranea Hacia Tabla SUCURSALES',
  `PaisResidencia` int(11) DEFAULT NULL COMMENT 'Pais de Residencia, Llave Foranea Hacia tabla PAISES',
  `TipoDireccionID` int(11) DEFAULT NULL COMMENT 'ID de el tipo de Dirección del Usuario de Servicios,Llave Foranea de TIPOSDIRECCION',
  `EstadoID` int(11) DEFAULT NULL COMMENT 'Hace referencia al ID del Estado del Usuario de Servicios',
  `MunicipioID` int(11) DEFAULT NULL COMMENT 'Hace referencia al ID del muncipio del Usuario de Servicios',
  `LocalidadID` int(11) DEFAULT NULL COMMENT 'Numero de Localidad del Usuario de Servicios, llave foranea de LOCALIDADREPUB',
  `ColoniaID` int(11) DEFAULT NULL COMMENT 'Numero de Colonia del Usuario de Servicios, llave foranea de COLONIASREPUB',
  `Calle` varchar(50) DEFAULT NULL COMMENT 'Nombre de la calle del domicilio',
  `NumExterior` varchar(10) DEFAULT NULL COMMENT 'Numero Exterior del domicilio',
  `NumInterior` varchar(10) DEFAULT NULL COMMENT 'Numero Interior del domicilio',
  `CP` char(5) DEFAULT NULL COMMENT 'Codigo Postal del domicilio',
  `Piso` varchar(50) DEFAULT NULL COMMENT 'Número de piso.',
  `Manzana` varchar(50) DEFAULT NULL COMMENT 'Nombre de la Manzana',
  `Lote` varchar(50) DEFAULT NULL COMMENT 'Lote',
  `DirCompleta` varchar(500) DEFAULT NULL COMMENT 'Dirección Completa',
  `TipoIdentiID` int(11) DEFAULT NULL COMMENT 'ID de el tipo de identificacion del Usuario de Servicios,Llave Foranea de TIPOSIDENTI',
  `NumIdenti` varchar(30) DEFAULT NULL COMMENT 'Numero de identificacion del documento de identifiación del Usuario de Servicios',
  `FecExIden` date DEFAULT NULL COMMENT 'Fecha de Expedición de la Identificación',
  `FecVenIden` date DEFAULT NULL COMMENT 'Fecha de Vencimiento de la Identificación',
  `DocEstanciaLegal` varchar(3) DEFAULT NULL COMMENT 'Documento de Estancial Legal',
  `DocExisLegal` varchar(30) DEFAULT NULL COMMENT 'Documento de Existencia Legal',
  `FechaVenEst` date DEFAULT NULL COMMENT 'Fecha de Vencimiento de la Estancia',
  `UsuarioUnificadoID` INT(11) NOT NULL DEFAULT '0' COMMENT 'Numero de Usuario Unificado',
  `NivelRiesgo` CHAR(1) NOT NULL DEFAULT '' COMMENT 'Nivel de Riesgo del Usuario de Servicio\nB.- Bajo\nM.- Medio\nA.- Alto',
  `Estatus` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Estatus del Usuario de Servicio\nA.- Activo\nI.- Inactivo',
  `SoloNombres` varchar(500) DEFAULT '' COMMENT 'Primer Nombre, Segundo Nombre y Tercer Nombre.',
  `SoloApellidos` varchar(500) DEFAULT '' COMMENT 'Apellido Paterno y Apellido Materno.',
  `RazonSocialPLD` varchar(200) DEFAULT '' COMMENT 'Razón Social limpio de caracteres especiales.',
  `EmpresaID` int(11) DEFAULT NULL,
  `Usuario` int(11) DEFAULT NULL,
  `FechaActual` datetime DEFAULT NULL,
  `DireccionIP` varchar(45) DEFAULT NULL,
  `ProgramaID` varchar(50) DEFAULT NULL,
  `Sucursal` int(11) DEFAULT NULL,
  `NumTransaccion` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`UsuarioServicioID`),
  KEY `fk_USUARIOSERVICIO_1` (`PaisNacimiento`),
  KEY `fk_USUARIOSERVICIO_2` (`EstadoNacimiento`),
  KEY `fk_USUARIOSERVICIO_3` (`TipoDireccionID`),
  KEY `fk_USUARIOSERVICIO_6` (`SucursalOrigen`),
  KEY `fk_USUARIOSERVICIO_7` (`PaisResidencia`),
  KEY `fk_USUARIOSERVICIO_8` (`EstadoID`),
  KEY `fk_USUARIOSERVICIO_9` (`MunicipioID`),
  KEY `fk_USUARIOSERVICIO_10` (`LocalidadID`),
  KEY `fk_USUARIOSERVICIO_11` (`ColoniaID`),
  KEY `fk_USUARIOSERVICIO_12` (`TipoIdentiID`),
  CONSTRAINT `fk_USUARIOSERVICIO_1` FOREIGN KEY (`PaisNacimiento`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_10` FOREIGN KEY (`LocalidadID`) REFERENCES `LOCALIDADREPUB` (`LocalidadID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_11` FOREIGN KEY (`ColoniaID`) REFERENCES `COLONIASREPUB` (`ColoniaID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_12` FOREIGN KEY (`TipoIdentiID`) REFERENCES `TIPOSIDENTI` (`TipoIdentiID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_2` FOREIGN KEY (`EstadoNacimiento`) REFERENCES `ESTADOSREPUB` (`EstadoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_3` FOREIGN KEY (`TipoDireccionID`) REFERENCES `TIPOSDIRECCION` (`TipoDireccionID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_6` FOREIGN KEY (`SucursalOrigen`) REFERENCES `SUCURSALES` (`SucursalID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_7` FOREIGN KEY (`PaisResidencia`) REFERENCES `PAISES` (`PaisID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_8` FOREIGN KEY (`EstadoID`) REFERENCES `ESTADOSREPUB` (`EstadoID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOSERVICIO_9` FOREIGN KEY (`MunicipioID`) REFERENCES `MUNICIPIOSREPUB` (`MunicipioID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla para almacenar los datos de los Usuarios(No Clientes) de los servicios que brinda la sociedad.'$$