//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 04:08:01 PM CST 
//


package contabilidad.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ctas"
})
@XmlRootElement(name = "BCE:Balanza", namespace = "http://www.sat.gob.mx/balanza")
public class BalanzaBean {

    @XmlElement(name = "BCE:Ctas", namespace = "http://www.sat.gob.mx/balanza", required = true)
	public List<BalanzaBean.Ctas> ctas;
    @XmlAttribute(name = "Ano", required = true)
    protected int ano;
    @XmlAttribute(name = "Mes", required = true)
    protected String mes;
    @XmlAttribute(name = "TotalCtas", required = true)
    protected int totalCtas;
    @XmlAttribute(name = "RFC", required = true)
    protected String rfc;
    @XmlAttribute(name = "Version", required = true)
    protected String version;




  
    public List<BalanzaBean.Ctas> getCtas() {
        if (ctas == null) {
            ctas = new ArrayList<BalanzaBean.Ctas>();
        }
        return this.ctas;
    }

    
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    
    public void setVersion(String value) {
        this.version = value;
    }

   
    public String getRFC() {
        return rfc;
    }

    
    public void setRFC(String value) {
        this.rfc = value;
    }

   
    public int getTotalCtas() {
        return totalCtas;
    }

   
    public void setTotalCtas(int value) {
        this.totalCtas = value;
    }

    
    public String getMes() {
        return mes;
    }

    
    public void setMes(String value) {
        this.mes = value;
    }

    
    public int getAno() {
        return ano;
    }

    
    public void setAno(int value) {
        this.ano = value;
    }


   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Ctas {
        @XmlAttribute(name = "SaldoFin", required = true)
        protected BigDecimal saldoFin;
        @XmlAttribute(name = "Haber", required = true)
        protected BigDecimal haber;
        @XmlAttribute(name = "Debe", required = true)
        protected BigDecimal debe;
        @XmlAttribute(name = "SaldoIni", required = true)
        protected BigDecimal saldoIni;
        @XmlAttribute(name = "NumCta", required = true)
        protected String numCta;




        public String getNumCta() {
            return numCta;
        }

        
        public void setNumCta(String value) {
            this.numCta = value;
        }

       
        public BigDecimal getSaldoIni() {
            return saldoIni;
        }

       
        public void setSaldoIni(BigDecimal value) {
            this.saldoIni = value;
        }

       
        public BigDecimal getDebe() {
            return debe;
        }

        
        public void setDebe(BigDecimal value) {
            this.debe = value;
        }

       
        public BigDecimal getHaber() {
            return haber;
        }

        
        public void setHaber(BigDecimal value) {
            this.haber = value;
        }

        
        public BigDecimal getSaldoFin() {
            return saldoFin;
        }

        
        public void setSaldoFin(BigDecimal value) {
            this.saldoFin = value;
        }

    }

}
