-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPINSERTMONEDAS
DELIMITER ;
DROP PROCEDURE IF EXISTS `TMPINSERTMONEDAS`;DELIMITER $$

CREATE PROCEDURE `TMPINSERTMONEDAS`(	)
TerminaStore: BEGIN

INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (5,1,'CENTENARIO-MÉXICO','CENTE','.',0,0,0,0,1,0,0,21976.42,'20','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (6,1,'AZTECA-MÉXICO','AZT','.',0,0,0,0,1,0,0,0,'21','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (7,1,'HIDALGO-MÉXICO','HID','.',0,0,0,0,1,0,0,0,'22','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (8,1,'1/2 HIDALGO-MÉXICO','HID','.',0,0,0,0,1,0,0,0,'23','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (9,1,'1/4 HIDALGO-MÉXICO','HID','.',0,0,0,0,1,0,0,0,'24','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (10,1,'1/5 HIDALGO-MÉXICO','HID','.',0,0,0,0,1,0,0,0,'25','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (11,1,'1 OZ LIBERTAD-MÉXICO','LIB','.',0,0,0,0,1,0,0,394.51,'26','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (12,1,'1/2 OZ LIBERTAD-MÉXICO','LIB','.',0,0,0,0,1,0,0,0,'27','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (13,1,'1/4 OZ LIBERTAD-MÉXICO','LIB','.',0,0,0,0,1,0,0,0,'28','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (14,1,'1/10 OZ LIBERTAD-MÉXICO','LIB','.',0,0,0,0,1,0,0,0,'29','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (15,1,'1/20 OZ LIBERTAD-MÉXICO','LIB','.',0,0,0,0,1,0,0,0,'30','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (16,1,'UDIS GUBERNAMENTALES-MÉXICO','UDG','.',0,0,0,0,1,0,0,0,'8','UD',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (17,1,'DIRHAM-EMIRATOS ARABES UNIDOS','AED','.',0,0,0,0,2,0,0,3.61651,'AED','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (18,1,'LEK-ALBANIA','ALL','.',0,0,0,0,2,0,0,0,'ALL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (19,1,'FLORIN-ANTILLAS HOLANDESAS','ANG','.',0,0,0,0,2,0,0,0,'ANG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (20,1,'PESO-ARGENTINA','ARP','.',0,0,0,0,2,0,0,2.89948,'ARP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (21,1,'CHELIN-AUSTRIA','ATS','.',0,0,0,0,2,0,0,0,'ATS','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (22,1,'DOLAR-AUSTRALIA','AUD','.',0,0,0,0,2,0,0,13.95809,'AUD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );

INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (23,1,'DOLAR-BARBADOS','BBD','.',0,0,0,0,2,0,0,6.64165,'BBD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (24,1,'FRANCO-LUXEMBURGO','BEC','.',0,0,0,0,2,0,0,0,'BEC','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (25,1,'FRANCO-BELGICA','BEF','.',0,0,0,0,2,0,0,0,'BEF','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (26,1,'LEV-BULGARIA','BGL','.',0,0,0,0,2,0,0,0,'BGL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (27,1,'DINAR-BAHRAIN','BHD','.',0,0,0,0,2,0,0,0,'BHD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (28,1,'DOLAR-BERMUDA','BMD','.',0,0,0,0,2,0,0,13.2833,'BMD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (29,1,'BOLIVIANO-BOLIVIA','BOP','.',0,0,0,0,2,0,0,1.89765,'BOP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (30,1,'REAL-BRASIL','BRC','.',0,0,0,0,2,0,0,6.48026,'BRC','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (31,1,'DOLAR-BAHAMAS','BSD','.',0,0,0,0,2,0,0,13.2833,'BSD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (32,1,'DOLAR-BELICE','BZD','.',0,0,0,0,2,0,0,7.0096,'BZD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (33,1,'DOLAR-CANADA','CAD','.',12.86249,13.72402,0,0,2,0,0,13.24226,'CAD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (34,1,'FRANCO-SUIZA','CHF','.',0,0,0,0,2,0,0,13.58908,'CHF','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (35,1,'PESO-CHILE','CLP','.',0,0,0,0,2,0,0,0.02763,'CLP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (36,1,'YUAN-CHINA','CNY','.',0,0,0,0,2,0,0,2.08800,'CNY','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (37,1,'PESO-COLOMBIA','COP','.',0,0,0,0,2,0,0,7.4162,'COP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (38,1,'COLON-COSTA RICA','CRC','.',0,0,0,0,2,0,0,0.02657,'CRC','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (39,1,'CORONA-REP. CHECA','CSK','.',0,0,0,0,2,0,0,0.64637,'CSK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (40,1,'PESO-CUBA','CUP','.',0,0,0,0,2,0,0,13.28330,'CUP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (41,1,'MARCO-ALEMANIA','DEM','.',0,0,0,0,2,0,0,0,'DEM','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (42,1,'CORONA-DINAMARCA','DKK','.',0,0,0,0,2,0,0,2.19719,'DKK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (43,1,'PESO-REP. DOMINICANA','DOP','.',0,0,0,0,2,0,0,0.33979,'DOP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (44,1,'DINAR-ARGELIA','DZD','.',0,0,0,0,2,0,0,0.16192,'DZD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (45,1,'SUCRE-ECUADOR','ECS','.',0,0,0,0,2,0,0,13.28330,'ECS','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (46,1,'CORONA-ESTONIA','EEK','.',0,0,0,0,2,0,0,0,'EEK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (47,1,'LIBRA-EGIPTO','EGP','.',0,0,0,0,2,0,0,2.18577,'EGP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (48,1,'PESETA-ESPAÑA','ESP','.',0,0,0,0,2,0,0,0,'ESP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (49,1,'BIRR-ETIOPIA','ETB','.',0,0,0,0,2,0,0,0,'ETB','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (50,1,'MARCO-FINLANDIA','FIM','.',0,0,0,0,2,0,0,0,'FIM','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (51,1,'DOLAR-FIDJI','FJD','.',0,0,0,0,2,0,0,7.45193,'FJD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (52,1,'FRANCO-FRANCIA','FRF','.',0,0,0,0,2,0,0,0,'FRF','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (53,1,'CEDI-GHANA','GHC','.',0,0,0,0,2,0,0,0,'GHC','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (54,1,'DRAKMA-GRECIA','GRD','.',0,0,0,0,2,0,0,0,'GRD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (55,1,'QUETZAL-GUATEMALA','GTO','.',0,0,0,0,2,0,0,1.69508,'GTO','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );

INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (56,1,'DOLAR-GUYANA','GYD','.',0,0,0,0,2,0,0,0.06575,'GYD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (57,1,'DOLAR-HONG KONG','HKD','.',0,0,0,0,2,0,0,1.71315,'HKD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (58,1,'LEMPIRA-HONDURAS','HNL','.',0,0,0,0,2,0,0,0.69711,'HNL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (59,1,'GOURDE-HAITI','HTG','.',0,0,0,0,2,0,0,0,'HTG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (60,1,'FORINT-HUNGRIA','HUF','.',0,0,0,0,2,0,0,0.05831,'HUF','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (61,1,'RUPIA-INDONESIA','IDR','.',0,0,0,0,2,0,0,1.40312,'IDR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (62,1,'PUNT-IRLANDA','IEP','.',0,0,0,0,2,0,0,0,'IEP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (63,1,'SHEKEL-ISRAEL','ILS','.',0,0,0,0,2,0,0,3.33318,'ILS','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (64,1,'RUPIA-INDIA','INR','.',0,0,0,0,2,0,0,0.23870,'INR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (65,1,'DINAR-IRAK','IQD','.',0,0,0,0,2,0,0,0.01142,'IQD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (66,1,'RIYAL-IRAN','IRR','.',0,0,0,0,2,0,0,0,'IRR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (67,1,'CORONA-ISLANDIA','ISK','.',0,0,0,0,2,0,0,0,'ISK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (68,1,'LIRA-ITALIA','ITL','.',0,0,0,0,2,0,0,0,'ITL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );

INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (69,1,'DOLAR-JAMAICA','JMD','.',0,0,0,0,2,0,0,0.14798,'JMD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (70,1,'DINAR-JORDANIA','JOD','.',0,0,0,0,2,0,0,0,'JOD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );

INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (71,1,'YEN-JAPON','JPY','.',0.15471,0.17808,0,0,2,0,0,0.16976,'JPY','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );

INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (72,1,'CHELIN-KENYA','KES','.',0,0,0,0,2,0,0,0.15754,'KES','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (73,1,'WON-COREA DEL NORTE','KPW','.',0,0,0,0,2,0,0,0,'KPW','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (74,1,'WON-COREA DEL SUR','KRW','.',0,0,0,0,2,0,0,11.74948,'KRW','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (75,1,'DINAR-KUWAIT','KWD','.',0,0,0,0,2,0,0,47.12397,'KWD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (76,1,'LIBRA-LIBANO','LBP','.',0,0,0,0,2,0,0,0,'LBP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (77,1,'RUPIA-SRI-LANKA','LKR','.',0,0,0,0,2,0,0,0,'LKR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (78,1,'LITAS-LITUANIA','LTT','.',0,0,0,0,2,0,0,0,'LTT','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (79,1,'DINAR-LIBIA','LYD','.',0,0,0,0,2,0,0,0,'LYD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (80,1,'DIRHAM-MARRUECOS','MAD','.',0,0,0,0,2,0,0,1.48348,'MAD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (81,1,'ONZA TROY DE PLATA-MÉXICO','MAG','.',0,0,0,0,2,0,0,0,'MAG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (82,1,'ONZA TROY DE ORO-MÉXICO','MAU','.',0,0,0,0,2,0,0,0,'MAU','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (83,1,'LIRA-MALTA','MTL','.',0,0,0,0,2,0,0,0,'MTL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (84,1,'RINGGIT-MALASIA','MYR','.',0,0,0,0,2,0,0,4.24322,'MYR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (85,1,'NAIRA-NIGERIA (FED)','NGN','.',0,0,0,0,2,0,0,0.08262,'NGN','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (86,1,'CORDOBA-NICARAGUA','NIC','.',0,0,0,0,2,0,0,0.56242,'NIC','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (87,1,'FLORIN-HOLANDA','NLG','.',0,0,0,0,2,0,0,0,'NLG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (88,1,'CORONA-NORUEGA','NOK','.',0,0,0,0,2,0,0,2.20011,'NOK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (89,1,'DOLAR-NUEVA ZELANDA','NZD','.',0,0,0,0,2,0,0,10.74885,'NZD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (90,1,'BALBOA-PANAMA','PAB','.',0,0,0,0,2,0,0,13.28330,'PAB','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (91,1,'N. SOL-PERU','PES','.',0,0,0,0,2,0,0,5.05283,'PES','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (92,1,'PESO-FILIPINAS','PHP','.',0,0,0,0,2,0,0,0.31814,'PHP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (93,1,'RUPIA-PAKISTAN','PKR','.',0,0,0,0,2,0,0,0,'PKR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (94,1,'ZLOTY-POLONIA','PLZ','.',0,0,0,0,2,0,0,3.97503,'PLZ','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (95,1,'ESCUDO-PORTUGAL','PTE','.',0,0,0,0,2,0,0,0,'PTE','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (96,1,'GUARANI-PARAGUAY','PYG','.',0,0,0,0,2,0,0,3.00521,'PYG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (97,1,'LEU-RUMANIA','ROL','.',0,0,0,0,2,0,0,3.56657,'ROL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (98,1,'RUBLO-FEDERACIÓN RUSA','RUR','.',0,0,0,0,2,0,0,0.41258,'RUR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (99,1,'RIYAL-ARABIA SAUDITA','SAR','.',0,0,0,0,2,0,0,3.54199,'SAR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (100,1,'CORONA-SUECIA','SEK','.',0,0,0,0,2,0,0,1.95397,'SEK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (101,1,'DOLAR-SINGAPUR','SGD','.',0,0,0,0,2,0,0,10.68309,'SGD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (102,1,'CORONA-ESLOVAQUIA','SKK','.',0,0,0,0,2,0,0,0,'SKK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (103,1,'FLORIN-SURINAM','SRG','.',0,0,0,0,2,0,0,0,'SRG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (104,1,'LIBRA-GRAN BRETAÑA','STG','.',20.10907,21.39866,0,0,2,0,0,20.77375,'STG','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (105,1,'COLON-EL SALVADOR','SVC','.',0,0,0,0,2,0,0,1.51855,'SVC','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (106,1,'LIBRA-SIRIA','SYP','.',0,0,0,0,2,0,0,0,'SYP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (107,1,'BAHT-TAILANDIA','THB','.',0,0,0,0,2,0,0,0.42188,'THB','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (108,1,'LIRA-TURQUIA','TRL','.',0,0,0,0,2,0,0,7.41421,'TRL','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (109,1,'DOLAR-TRINIDAD Y TOBAGO','TTD','.',0,0,0,0,2,0,0,2.09185,'TTD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (110,1,'DOLAR-TAIWAN','TWD','.',0,0,0,0,2,0,0,0.44313,'TWD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (111,1,'CHELIN-TANZANIA','TZS','.',0,0,0,0,2,0,0,0,'TZS','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (112,1,'HRYVNA-UCRANIA','UAK','.',0,0,0,0,2,0,0,1.64049,'UAK','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (113,1,'UNIDAD DE CUENTA (NAFIN-BANXICO)-MÉXICO','UNB','.',0,0,0,0,1,0,0,0,'UNB','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (114,1,'PESO-URUGUAY','UYP','.',0,0,0,0,2,0,0,0.61927,'UYP','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (115,1,'BOLIVAR-VENEZUELA','VEB','.',0,0,0,0,2,0,0,3.09302,'VEB','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (116,1,'DONG-VIETNAM','VND','.',0,0,0,0,2,0,0,0.63654,'VND','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (117,1,'DEG-DERECHOS ESPECIALES DE GI','XDR','.',0,0,0,0,2,0,0,20.03560,'XDR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (118,1,'FRANCO-AFRICA CENTRAL','XOF','.',0,0,0,0,2,0,0,0,'XOF','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (119,1,'RIAL-YEMEN (DEM.POP.)','YDD','.',0,0,0,0,2,0,0,0,'YDD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (120,1,'DINAR-YUGOSLAVIA','YUD','.',0,0,0,0,2,0,0,0,'YUD','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (121,1,'RAND-UNION SUDAFRICANA','ZAR','.',0,0,0,0,2,0,0,1.61830,'ZAR','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );
INSERT INTO `microfin`.`MONEDAS`(`MonedaId`,`EmpresaID`,`Descripcion`,`DescriCorta`,`Simbolo`, `TipCamComVen`,`TipCamVenVen`,`TipCamComInt`,`TipCamVenInt`,`TipoMoneda`,`TipCamFixCom`,`TipCamFixVen`,`TipCamDof`,`EqCNBVUIF`,`EqBuroCred`,`Usuario`,`FechaActual`,`DireccionIP`,`ProgramaID`,`Sucursal`,`NumTransaccion`) VALUES (122,1,'ZAIRE-ZAIRE','ZRZ','.',0,0,0,0,2,0,0,0,'ZRZ','',15,'2012-08-06 10:42:54','0:0:0:0:0:0:0:1','',3,1 );


END TerminaStore$$