-- ---------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- ---------------------------------------------------------------------------------
-- TMPUPDATEPAISES
DELIMITER ;
DROP PROCEDURE IF EXISTS `TMPUPDATEPAISES`;DELIMITER $$

CREATE PROCEDURE `TMPUPDATEPAISES`(	)
TerminaStore: BEGIN

Update PAISES set Nombre='ANGOLA', EqBuroCred='AO' where PaisID=101;
Update PAISES set Nombre='ARGELIA', EqBuroCred='DZ' where PaisID=102;
Update PAISES set Nombre='ISLA DE LA ASCENSION', EqBuroCred='AS' where PaisID=103;
Update PAISES set Nombre='BENIN', EqBuroCred='BJ' where PaisID=104;
Update PAISES set Nombre='BOTSWANA', EqBuroCred='BW' where PaisID=105;
Update PAISES set Nombre='BURKINA FASO', EqBuroCred='BF' where PaisID=106;
Update PAISES set Nombre='BURUNDI', EqBuroCred='BI' where PaisID=107;
Update PAISES set Nombre='ISLAS CABO VERDE', EqBuroCred='CV' where PaisID=108;
Update PAISES set Nombre='CAMERUN', EqBuroCred='CM' where PaisID=109;
Update PAISES set Nombre='ISLAS CANARIAS', EqBuroCred='ES' where PaisID=110;
Update PAISES set Nombre='CEUTA', EqBuroCred='ES' where PaisID=111;
Update PAISES set Nombre='ISLAS COMORAS', EqBuroCred='CJ' where PaisID=112;
Update PAISES set Nombre='CONGO', EqBuroCred='CG' where PaisID=113;
Update PAISES set Nombre='COSTA DE MARFIL', EqBuroCred='IC' where PaisID=114;
Update PAISES set Nombre='CHAD', EqBuroCred='CD' where PaisID=115;
Update PAISES set Nombre='DJIBOUTI', EqBuroCred='DJ' where PaisID=116;
Update PAISES set Nombre='EGIPTO', EqBuroCred='EG' where PaisID=117;
Update PAISES set Nombre='ERITREA', EqBuroCred='' where PaisID=118;
Update PAISES set Nombre='ETIOPIA', EqBuroCred='ET' where PaisID=119;
Update PAISES set Nombre='GABON', EqBuroCred='GB' where PaisID=120;
Update PAISES set Nombre='GAMBIA', EqBuroCred='GM' where PaisID=121;
Update PAISES set Nombre='GHANA', EqBuroCred='GH' where PaisID=122;
Update PAISES set Nombre='GUINEA', EqBuroCred='GN' where PaisID=123;
Update PAISES set Nombre='GUINEA BISSAU', EqBuroCred='GW' where PaisID=124;
Update PAISES set Nombre='GUINEA ECUATORIAL', EqBuroCred='GQ' where PaisID=125;
Update PAISES set Nombre='KENYA', EqBuroCred='KE' where PaisID=126;
Update PAISES set Nombre='LESOHOTO', EqBuroCred='LS' where PaisID=127;
Update PAISES set Nombre='LIBERIA', EqBuroCred='LR' where PaisID=128;
Update PAISES set Nombre='LIBIA', EqBuroCred='LV' where PaisID=129;
Update PAISES set Nombre='MADAGASCAR', EqBuroCred='MG' where PaisID=130;
Update PAISES set Nombre='ISLA DE MADEIRA', EqBuroCred='MD' where PaisID=131;
Update PAISES set Nombre='MAHORE', EqBuroCred='CJ' where PaisID=132;
Update PAISES set Nombre='MALAVI', EqBuroCred='MW' where PaisID=133;
Update PAISES set Nombre='MALI', EqBuroCred='ML' where PaisID=134;
Update PAISES set Nombre='MARRUECOS', EqBuroCred='RC' where PaisID=135;
Update PAISES set Nombre='ISLA MAURICIO', EqBuroCred='MU' where PaisID=136;
Update PAISES set Nombre='MAURITANIA', EqBuroCred='MR' where PaisID=137;
Update PAISES set Nombre='MELILLA', EqBuroCred='ES' where PaisID=138;
Update PAISES set Nombre='MOZAMBIQUE', EqBuroCred='MZ' where PaisID=139;
Update PAISES set Nombre='NAMIBIA', EqBuroCred='' where PaisID=140;
Update PAISES set Nombre='NIGER', EqBuroCred='' where PaisID=141;
Update PAISES set Nombre='NIGERIA', EqBuroCred='NR' where PaisID=142;
Update PAISES set Nombre='REPUBLICA CENTROAFRICANA', EqBuroCred='CF' where PaisID=143;
Update PAISES set Nombre='ISLA REUNION', EqBuroCred='RE' where PaisID=144;
Update PAISES set Nombre='RUANDA', EqBuroCred='RW' where PaisID=145;
Update PAISES set Nombre='SAHARA OCCIDENTAL', EqBuroCred='' where PaisID=146;
Update PAISES set Nombre='ISLA SANTA ELENA', EqBuroCred='SH' where PaisID=147;
Update PAISES set Nombre='SANTO TOME Y PRINCIPE', EqBuroCred='MP' where PaisID=148;
Update PAISES set Nombre='SENEGAL', EqBuroCred='SN' where PaisID=149;
Update PAISES set Nombre='ISLAS SEYCHELLES', EqBuroCred='' where PaisID=150;
Update PAISES set Nombre='SIERRA LEONA', EqBuroCred='' where PaisID=151;
Update PAISES set Nombre='ISLA SOCOTORA', EqBuroCred='YS' where PaisID=152;
Update PAISES set Nombre='SOMALIA', EqBuroCred='SO' where PaisID=153;
Update PAISES set Nombre='SUDAFRICA', EqBuroCred='ZA' where PaisID=154;
Update PAISES set Nombre='BOPHUTHATSWANA', EqBuroCred='ZA' where PaisID=155;
Update PAISES set Nombre='CISKEI', EqBuroCred='ZA' where PaisID=156;
Update PAISES set Nombre='TRANSKEI', EqBuroCred='ZA' where PaisID=157;
Update PAISES set Nombre='VENDA', EqBuroCred='' where PaisID=158;
Update PAISES set Nombre='SUDAN', EqBuroCred='SB' where PaisID=159;
Update PAISES set Nombre='SUAZILANDIA', EqBuroCred='SZ' where PaisID=160;
Update PAISES set Nombre='TANZANIA', EqBuroCred='TZ' where PaisID=161;
Update PAISES set Nombre='TOGO', EqBuroCred='TG' where PaisID=162;
Update PAISES set Nombre='TRISTAN DA CUNHA', EqBuroCred='TD' where PaisID=163;
Update PAISES set Nombre='TUNEZ', EqBuroCred='TU' where PaisID=164;
Update PAISES set Nombre='UGANDA', EqBuroCred='UG' where PaisID=165;
Update PAISES set Nombre='ZAIRE', EqBuroCred='ZR' where PaisID=166;
Update PAISES set Nombre='ZAMBIA', EqBuroCred='ZM' where PaisID=167;
Update PAISES set Nombre='ZIMBABWE', EqBuroCred='ZW' where PaisID=168;
Update PAISES set Nombre='ANGUILA', EqBuroCred='AI' where PaisID=201;
Update PAISES set Nombre='ANTIGUA Y BARBUDA', EqBuroCred='AG' where PaisID=202;
Update PAISES set Nombre='ANTILLAS NEERLANDESAS (HOLANDESAS)', EqBuroCred='NN' where PaisID=203;
Update PAISES set Nombre='ARGENTINA', EqBuroCred='AT' where PaisID=204;
Update PAISES set Nombre='ARUBA', EqBuroCred='AW' where PaisID=205;
Update PAISES set Nombre='ISLAS BAHAMAS', EqBuroCred='BS' where PaisID=206;
Update PAISES set Nombre='ISLAS BARBADOS', EqBuroCred='BB' where PaisID=207;
Update PAISES set Nombre='BELICE', EqBuroCred='BZ' where PaisID=208;
Update PAISES set Nombre='ISLAS BERMUDAS', EqBuroCred='BU' where PaisID=209;
Update PAISES set Nombre='BOLIVIA', EqBuroCred='BO' where PaisID=210;
Update PAISES set Nombre='BRASIL', EqBuroCred='BR' where PaisID=211;
Update PAISES set Nombre='ISLAS CAIMAN', EqBuroCred='CI' where PaisID=212;
Update PAISES set Nombre='CANADA', EqBuroCred='CN' where PaisID=213;
Update PAISES set Nombre='COLOMBIA', EqBuroCred='CB' where PaisID=214;
Update PAISES set Nombre='COSTA RICA', EqBuroCred='' where PaisID=215;
Update PAISES set Nombre='CUBA', EqBuroCred='HR' where PaisID=216;
Update PAISES set Nombre='CHILE', EqBuroCred='CL' where PaisID=217;
Update PAISES set Nombre='ISLA DOMINICA', EqBuroCred='DM' where PaisID=218;
Update PAISES set Nombre='ECUADOR', EqBuroCred='EC' where PaisID=219;
Update PAISES set Nombre='EL SALVADOR', EqBuroCred='SV' where PaisID=220;
Update PAISES set Nombre='ESTADOS UNIDOS DE AMERICA', EqBuroCred='US' where PaisID=221;
Update PAISES set Nombre='ISLA GRANADA', EqBuroCred='GD' where PaisID=222;
Update PAISES set Nombre='GROENLANDIA', EqBuroCred='GE' where PaisID=223;
Update PAISES set Nombre='ISLAS GUADALUPE', EqBuroCred='GP' where PaisID=224;
Update PAISES set Nombre='GUATEMALA', EqBuroCred='GT' where PaisID=225;
Update PAISES set Nombre='GUYANA INGLESA', EqBuroCred='GY' where PaisID=226;
Update PAISES set Nombre='GUAYANA FRANCESA', EqBuroCred='GF' where PaisID=227;
Update PAISES set Nombre='HAITI', EqBuroCred='HA' where PaisID=228;
Update PAISES set Nombre='HONDURAS', EqBuroCred='HN' where PaisID=229;
Update PAISES set Nombre='ISLA DE JAMAICA', EqBuroCred='JM' where PaisID=230;
Update PAISES set Nombre='MALVINAS', EqBuroCred='FA' where PaisID=231;
Update PAISES set Nombre='ISLA DE MARTINICA', EqBuroCred='MQ' where PaisID=232;
Update PAISES set Nombre='ISLA MONTSERRAT', EqBuroCred='MK' where PaisID=233;
Update PAISES set Nombre='NICARAGUA', EqBuroCred='NI' where PaisID=234;
Update PAISES set Nombre='PANAMA', EqBuroCred='PM' where PaisID=235;
Update PAISES set Nombre='PARAGUAY', EqBuroCred='PY' where PaisID=236;
Update PAISES set Nombre='PERU', EqBuroCred='PU' where PaisID=237;
Update PAISES set Nombre='PUERTO RICO', EqBuroCred='' where PaisID=238;
Update PAISES set Nombre='REPUBLICA DOMINICANA', EqBuroCred='DO' where PaisID=239;
Update PAISES set Nombre='ISLAS SAN CRISTOBAL Y NEVIS', EqBuroCred='KN' where PaisID=240;
Update PAISES set Nombre='ISLAS SAN PEDRO Y MIGUELON', EqBuroCred='SP' where PaisID=241;
Update PAISES set Nombre='ISLAS SAN VICENTE Y LAS GRANADINAS', EqBuroCred='SF' where PaisID=242;
Update PAISES set Nombre='ISLA SANTA LUCIA', EqBuroCred='LC' where PaisID=243;
Update PAISES set Nombre='SURINAM', EqBuroCred='SR' where PaisID=244;
Update PAISES set Nombre='TRINIDAD Y TOBAGO', EqBuroCred='TT' where PaisID=245;
Update PAISES set Nombre='ISLAS TURCAS Y CAICOS', EqBuroCred='TC' where PaisID=246;
Update PAISES set Nombre='URUGUAY', EqBuroCred='UY' where PaisID=247;
Update PAISES set Nombre='ISLAS VIRGENES (ESTADOUNIDENSES)', EqBuroCred='' where PaisID=248;
Update PAISES set Nombre='ISLAS VIRGENES BRITANICAS', EqBuroCred='VG' where PaisID=249;
Update PAISES set Nombre='VENEZUELA', EqBuroCred='VE' where PaisID=250;
Update PAISES set Nombre='AFGANISTAN', EqBuroCred='AF' where PaisID=301;
Update PAISES set Nombre='ARABIA SAUDITA', EqBuroCred='SA' where PaisID=302;
Update PAISES set Nombre='ARMENIA', EqBuroCred='' where PaisID=303;
Update PAISES set Nombre='AZERBAIYAN', EqBuroCred='' where PaisID=304;
Update PAISES set Nombre='BAHREIN', EqBuroCred='BH' where PaisID=305;
Update PAISES set Nombre='BANGLADESH', EqBuroCred='BD' where PaisID=306;
Update PAISES set Nombre='BHUTAN', EqBuroCred='' where PaisID=307;
Update PAISES set Nombre='BRUNEI', EqBuroCred='BN' where PaisID=308;
Update PAISES set Nombre='CAMBOYA', EqBuroCred='' where PaisID=309;
Update PAISES set Nombre='ISLAS DE COCOS O KEELING', EqBuroCred='AU' where PaisID=310;
Update PAISES set Nombre='COREA', EqBuroCred='' where PaisID=311;
Update PAISES set Nombre='COREA DEL NORTE', EqBuroCred='KX' where PaisID=312;
Update PAISES set Nombre='COREA DEL SUR', EqBuroCred='KR' where PaisID=313;
Update PAISES set Nombre='CHINA', EqBuroCred='CP' where PaisID=314;
Update PAISES set Nombre='HONG KONG', EqBuroCred='HK' where PaisID=315;
Update PAISES set Nombre='CHINA NACIONALISTA', EqBuroCred='CP' where PaisID=316;
Update PAISES set Nombre='CHIPRE', EqBuroCred='CY' where PaisID=317;
Update PAISES set Nombre='REPUBLICA DE CHIPRE', EqBuroCred='' where PaisID=318;
Update PAISES set Nombre='CHIPRE SEPTENTRIONAL', EqBuroCred='' where PaisID=319;
Update PAISES set Nombre='ISLA DE CHRISTMAS', EqBuroCred='' where PaisID=320;
Update PAISES set Nombre='EMIRATOS DE ARABIA', EqBuroCred='UM' where PaisID=321;
Update PAISES set Nombre='FILIPINAS', EqBuroCred='PH' where PaisID=322;
Update PAISES set Nombre='GEORGIA', EqBuroCred='GX' where PaisID=323;
Update PAISES set Nombre='INDIA', EqBuroCred='IB' where PaisID=325;
Update PAISES set Nombre='INDONESIA', EqBuroCred='IF' where PaisID=326;
Update PAISES set Nombre='IRAN', EqBuroCred='IR' where PaisID=327;
Update PAISES set Nombre='IRAQ', EqBuroCred='IQ' where PaisID=328;
Update PAISES set Nombre='ISRAEL', EqBuroCred='IG' where PaisID=329;
Update PAISES set Nombre='JAPON', EqBuroCred='JP' where PaisID=330;
Update PAISES set Nombre='JORDANIA', EqBuroCred='JO' where PaisID=331;
Update PAISES set Nombre='KAZAJSTAN', EqBuroCred='' where PaisID=332;
Update PAISES set Nombre='KIRGUISTAN', EqBuroCred='' where PaisID=333;
Update PAISES set Nombre='KUWAIT', EqBuroCred='KW' where PaisID=334;
Update PAISES set Nombre='LIBANO', EqBuroCred='LB' where PaisID=335;
Update PAISES set Nombre='MACAO', EqBuroCred='MJ' where PaisID=336;
Update PAISES set Nombre='MALASIA', EqBuroCred='MY' where PaisID=337;
Update PAISES set Nombre='ISLAS MALDIVAS', EqBuroCred='MV' where PaisID=338;
Update PAISES set Nombre='MONGOLIA', EqBuroCred='MC' where PaisID=339;
Update PAISES set Nombre='MYANMAR', EqBuroCred='' where PaisID=340;
Update PAISES set Nombre='NEPAL', EqBuroCred='NP' where PaisID=341;
Update PAISES set Nombre='OMAN', EqBuroCred='OM' where PaisID=342;
Update PAISES set Nombre='PAKISTAN', EqBuroCred='PK' where PaisID=343;
Update PAISES set Nombre='QATAR', EqBuroCred='QA' where PaisID=344;
Update PAISES set Nombre='LAOS', EqBuroCred='LO' where PaisID=345;
Update PAISES set Nombre='SINGAPUR', EqBuroCred='' where PaisID=346;
Update PAISES set Nombre='SIRIA', EqBuroCred='SY' where PaisID=347;
Update PAISES set Nombre='SRI LANKA', EqBuroCred='LK' where PaisID=348;
Update PAISES set Nombre='TAILANDIA', EqBuroCred='TH' where PaisID=349;
Update PAISES set Nombre='TAYIKISTAN', EqBuroCred='' where PaisID=350;
Update PAISES set Nombre='TURKMENISTAN', EqBuroCred='' where PaisID=351;
Update PAISES set Nombre='TURQUIA', EqBuroCred='TR' where PaisID=352;
Update PAISES set Nombre='UZBEKISTAN', EqBuroCred='' where PaisID=353;
Update PAISES set Nombre='VIET NAM', EqBuroCred='VN' where PaisID=354;
Update PAISES set Nombre='YEMEN', EqBuroCred='YS' where PaisID=355;
Update PAISES set Nombre='ALBANIA', EqBuroCred='AN' where PaisID=401;
Update PAISES set Nombre='ALEMANIA', EqBuroCred='DW' where PaisID=402;
Update PAISES set Nombre='ANDORRA', EqBuroCred='AD' where PaisID=403;
Update PAISES set Nombre='ISLAS ANGLONORMANDAS', EqBuroCred='' where PaisID=404;
Update PAISES set Nombre='AUSTRIA', EqBuroCred='DF' where PaisID=405;
Update PAISES set Nombre='ISLAS AZORES', EqBuroCred='AX' where PaisID=406;
Update PAISES set Nombre='BELARUS', EqBuroCred='' where PaisID=407;
Update PAISES set Nombre='BELGICA', EqBuroCred='BE' where PaisID=408;
Update PAISES set Nombre='BOSNIA Y HERZEGOVINA', EqBuroCred='BX' where PaisID=409;
Update PAISES set Nombre='BULGARIA', EqBuroCred='BG' where PaisID=410;
Update PAISES set Nombre='CROACIA', EqBuroCred='HX' where PaisID=411;
Update PAISES set Nombre='DINAMARCA', EqBuroCred='DK' where PaisID=412;
Update PAISES set Nombre='ESLOVAQUIA', EqBuroCred='CS' where PaisID=413;
Update PAISES set Nombre='ESLOVENIA', EqBuroCred='XN' where PaisID=414;
Update PAISES set Nombre='ESPAÑA', EqBuroCred='ES' where PaisID=415;
Update PAISES set Nombre='ESTONIA', EqBuroCred='SU' where PaisID=416;
Update PAISES set Nombre='FEROE', EqBuroCred='' where PaisID=417;
Update PAISES set Nombre='FINLANDIA', EqBuroCred='FI' where PaisID=418;
Update PAISES set Nombre='FRANCIA', EqBuroCred='FR' where PaisID=419;
Update PAISES set Nombre='GIBRALTAR', EqBuroCred='GI' where PaisID=420;
Update PAISES set Nombre='GRECIA', EqBuroCred='GR' where PaisID=421;
Update PAISES set Nombre='HUNGRIA', EqBuroCred='HU' where PaisID=422;
Update PAISES set Nombre='IRLANDA', EqBuroCred='IE' where PaisID=423;
Update PAISES set Nombre='ISLANDIA', EqBuroCred='IS' where PaisID=424;
Update PAISES set Nombre='ITALIA', EqBuroCred='IT' where PaisID=425;
Update PAISES set Nombre='LETONIA', EqBuroCred='LX' where PaisID=426;
Update PAISES set Nombre='LIECHTENSTEIN', EqBuroCred='CH' where PaisID=427;
Update PAISES set Nombre='LITUANIA', EqBuroCred='LT' where PaisID=428;
Update PAISES set Nombre='LUXEMBURGO', EqBuroCred='LU' where PaisID=429;
Update PAISES set Nombre='MACEDONIA', EqBuroCred='MH' where PaisID=430;
Update PAISES set Nombre='ISLAS MALTA Y GOZO', EqBuroCred='MT' where PaisID=431;
Update PAISES set Nombre='ISLA DE MAN', EqBuroCred='' where PaisID=432;
Update PAISES set Nombre='MOLDOVA', EqBuroCred='' where PaisID=433;
Update PAISES set Nombre='MONACO', EqBuroCred='' where PaisID=434;
Update PAISES set Nombre='NORUEGA', EqBuroCred='NO' where PaisID=435;
Update PAISES set Nombre='HOLANDA', EqBuroCred='NL' where PaisID=436;
Update PAISES set Nombre='POLONIA', EqBuroCred='PL' where PaisID=437;
Update PAISES set Nombre='PORTUGAL', EqBuroCred='PT' where PaisID=438;
Update PAISES set Nombre='INGLATERRA', EqBuroCred='UK' where PaisID=439;
Update PAISES set Nombre='REPUBLICA CHECA', EqBuroCred='CS' where PaisID=440;
Update PAISES set Nombre='RUMANIA', EqBuroCred='RO' where PaisID=441;
Update PAISES set Nombre='RUSIA', EqBuroCred='RU' where PaisID=442;
Update PAISES set Nombre='SAN MARINO', EqBuroCred='' where PaisID=443;
Update PAISES set Nombre='VATICANO', EqBuroCred='VC' where PaisID=444;
Update PAISES set Nombre='SUECIA', EqBuroCred='SE' where PaisID=445;
Update PAISES set Nombre='SUIZA', EqBuroCred='SW' where PaisID=446;
Update PAISES set Nombre='UCRANIA', EqBuroCred='UA' where PaisID=447;
Update PAISES set Nombre='YUGOSLAVIA', EqBuroCred='' where PaisID=448;
Update PAISES set Nombre='AUSTRALIA', EqBuroCred='AU' where PaisID=501;
Update PAISES set Nombre='BAKER', EqBuroCred='' where PaisID=502;
Update PAISES set Nombre='ISLAS COOK', EqBuroCred='' where PaisID=503;
Update PAISES set Nombre='ISLAS FIJI', EqBuroCred='FJ' where PaisID=504;
Update PAISES set Nombre='ISLA GUAM', EqBuroCred='' where PaisID=505;
Update PAISES set Nombre='KINGMAN REEF', EqBuroCred='' where PaisID=506;
Update PAISES set Nombre='KIRIBATI', EqBuroCred='KI' where PaisID=507;
Update PAISES set Nombre='HOWLAND', EqBuroCred='' where PaisID=508;
Update PAISES set Nombre='JARVIS', EqBuroCred='' where PaisID=509;
Update PAISES set Nombre='JOHNSTON', EqBuroCred='' where PaisID=510;
Update PAISES set Nombre='ISLAS MACQUARIE', EqBuroCred='' where PaisID=511;
Update PAISES set Nombre='ISLAS MARIANAS DEL NORTE', EqBuroCred='' where PaisID=512;
Update PAISES set Nombre='ISLAS MARSHALL', EqBuroCred='' where PaisID=513;
Update PAISES set Nombre='MICRONESIA', EqBuroCred='' where PaisID=514;
Update PAISES set Nombre='MIDWAY', EqBuroCred='' where PaisID=515;
Update PAISES set Nombre='ISLA NAURU', EqBuroCred='NA' where PaisID=516;
Update PAISES set Nombre='ISLA NIUE', EqBuroCred='' where PaisID=517;
Update PAISES set Nombre='ISLA DE NORFOLK', EqBuroCred='' where PaisID=518;
Update PAISES set Nombre='ISLA NUEVA CALEDONIA', EqBuroCred='NW' where PaisID=519;
Update PAISES set Nombre='NUEVA ZELANDIA', EqBuroCred='NZ' where PaisID=520;
Update PAISES set Nombre='PALAU', EqBuroCred='' where PaisID=521;
Update PAISES set Nombre='PALMYRA', EqBuroCred='' where PaisID=522;
Update PAISES set Nombre='NUEVA GUINEA', EqBuroCred='PG' where PaisID=523;
Update PAISES set Nombre='PITCAIRN', EqBuroCred='PS' where PaisID=524;
Update PAISES set Nombre='POLINESIA FRANCESA', EqBuroCred='FP' where PaisID=525;
Update PAISES set Nombre='ISLAS SALMON', EqBuroCred='SI' where PaisID=526;
Update PAISES set Nombre='SAMOA ORIENTAL', EqBuroCred='' where PaisID=527;
Update PAISES set Nombre='SAMOA OCCIDENTAL', EqBuroCred='WS' where PaisID=528;
Update PAISES set Nombre='TERRITORIO DE LAS ISLAS DEL MAR DEL CORAL', EqBuroCred='' where PaisID=529;
Update PAISES set Nombre='TOKELALU', EqBuroCred='' where PaisID=530;
Update PAISES set Nombre='TONGA', EqBuroCred='TA' where PaisID=531;
Update PAISES set Nombre='TUVALU', EqBuroCred='TV' where PaisID=532;
Update PAISES set Nombre='VANUATU', EqBuroCred='VU' where PaisID=533;
Update PAISES set Nombre='ISLA WAKE', EqBuroCred='' where PaisID=534;
Update PAISES set Nombre='ISLAS WALLIS Y FUTUNA', EqBuroCred='WT' where PaisID=535;
Update PAISES set Nombre='EXTRANJERO, OTRO PAIS', EqBuroCred='' where PaisID=600;
Update PAISES set Nombre='MEXICO (PAIS)', EqBuroCred='MX' where PaisID=700;
Update PAISES set Nombre='INSUFICIENTEMENTE ESPECIFICADO', EqBuroCred='' where PaisID=999;


END TerminaStore$$