//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 05:42:45 PM CST 
//


package contabilidad.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ctas"
})
@XmlRootElement(name = "catalogocuentas:Catalogo", namespace = "http://www.sat.gob.mx/catalogo")
public class CatalogoBean {

    @XmlElement(name = "catalogocuentas:Ctas", namespace = "http://www.sat.gob.mx/catalogo", required = true)
	public List<CatalogoBean.Ctas> ctas;
    @XmlAttribute(name = "Ano", required = true)
    protected int ano;
    @XmlAttribute(name = "Mes", required = true)
    protected String mes;
    @XmlAttribute(name = "TotalCtas", required = true)
    protected int totalCtas;
    @XmlAttribute(name = "RFC", required = true)
    protected String rfc;
    @XmlAttribute(name = "Version", required = true)
    protected String version;



   

    
    public List<CatalogoBean.Ctas> getCtas() {
        if (ctas == null) {
            ctas = new ArrayList<CatalogoBean.Ctas>();
        }
        return this.ctas;
    }

    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

   
    public void setVersion(String value) {
        this.version = value;
    }

    
    public String getRFC() {
        return rfc;
    }

    
    public void setRFC(String value) {
        this.rfc = value;
    }

  
    public int getTotalCtas() {
        return totalCtas;
    }

    
    public void setTotalCtas(int value) {
        this.totalCtas = value;
    }

    public String getMes() {
        return mes;
    }

    
    public void setMes(String value) {
        this.mes = value;
    }

    
    public int getAno() {
        return ano;
    }

   
    public void setAno(int value) {
        this.ano = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Ctas {
        @XmlAttribute(name = "Natur", required = true)
        protected String natur;
        @XmlAttribute(name = "Nivel", required = true)
        protected int nivel;
        @XmlAttribute(name = "SubCtaDe")
        protected String subCtaDe;
        @XmlAttribute(name = "Desc", required = true)
        protected String desc;
        @XmlAttribute(name = "NumCta", required = true)
        protected String numCta;
        @XmlAttribute(name = "CodAgrup", required = true)
        protected String codAgrup;






       
        public String getCodAgrup() {
            return codAgrup;
        }

      
        public void setCodAgrup(String value) {
            this.codAgrup = value;
        }

       
        public String getNumCta() {
            return numCta;
        }

        
        public void setNumCta(String value) {
            this.numCta = value;
        }

       
        public String getDesc() {
            return desc;
        }

        
        public void setDesc(String value) {
            this.desc = value;
        }

        
        public String getSubCtaDe() {
            return subCtaDe;
        }

       
        public void setSubCtaDe(String value) {
            this.subCtaDe = value;
        }

       
        public int getNivel() {
            return nivel;
        }

        
        public void setNivel(int value) {
            this.nivel = value;
        }

        public String getNatur() {
            return natur;
        }

        
        public void setNatur(String value) {
            this.natur = value;
        }

    }

}
